### ISSUE TITLE
No ipython-notebook package for Stretch

### ISSUE THREAD

**Issue by 8ballin** [Cyb3rWard0g/HELK#10]
The latest package for ipython-notebook in Debian appears to be in Jessie.  Do you want to pull it from that old repo or somewhere else?

**Comment by Cyb3rWard0g** [comment]
Hey @8ballin . I removed the IPython-notebook and ipython packages part since it is already done by "pip install jupyter". ipython-notebook is also deprecated. Let me know if the bash script works for you by using pip to install jupyter. I updated the bash script and Dockerfile.

**Comment by Cyb3rWard0g** [comment]
@8ballin are you still having the same issue? let me know. Thank you for sharing your findings. This makes this beta version a better one. 👍

**Comment by 8ballin** [comment]
I'm about to test shortly, just got home from work.  I promise to follow up.

**Comment by 8ballin** [comment]
Install successful using option 3 on Debian Stretch.  Thank you.

**Comment by Cyb3rWard0g** [comment]
Thank you @8ballin ! 👍
