### ISSUE TITLE
Request Entity too large

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/HELK#100]
**Describe the problem**
Visualizing data being ingested throws that error message

**What steps did you take trying to fix the issue?**
googled it and asked @neu5ron ;) He always has the answers!!! :) 👍 Thank you man!

**How could we replicate the issue?**
Building HELK, ingesting data and going through the HELK visualizations

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**

**What OS are you using to host the HELK?**

**Any additional context?**
other log files, pictures, etc.
![image](https://user-images.githubusercontent.com/9653181/45329894-f4021600-b562-11e8-8036-17f17961a693.png)

**Comment by neu5ron** [comment]
we have fixed temporarily in NGINX. but future we need to have the .kibana index auto shorten URLs. because as mentioned, browsers will eventually fail next :)

**Comment by neu5ron** [comment]
pr coming soon, closing.
