### ISSUE TITLE
Error during installation of HELK

### ISSUE THREAD

**Issue by wasilewski** [Cyb3rWard0g/HELK#11]
Hi,

I've created a new Ubuntu based VM Machine and I am trying to Install HELK however, I am experiencing a few errors. Do I need to install anything else prior to the installation process? README file doesn't specify that. Please take a look:

sudo ./helk_install.sh

**********************************************
**           HELK - M E N U                 **
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: 0.9 (BETA)           **
** HELK ELK version: 6.x                    **
** License: BSD 3-Clause                    **
**********************************************

1. Pull the latest HELK image from DockerHub
2. Build the HELK image from local Dockerfile
3. Install the HELK from local bash script
4. Exit

[HELK-INSTALLATION-INFO] Enter choice [ 1 - 4] 1
[HELK-DOCKER-INSTALLATION-INFO] Installing docker first
[HELK-DOCKER-INSTALLATION-INFO] This is a debian-based system..
[HELK-DOCKER-INSTALLATION-INFO] Installing Docker..
[HELK-DOCKER-INSTALLATION-INFO] Installing updates..
[HELK-DOCKER-INSTALLATION-INFO] Adding the GPG key for the official Docker repository to the system..
[HELK-DOCKER-INSTALLATION-INFO] Installing updates..
[HELK-DOCKER-INSTALLATION-INFO] Adding the docker repository to APT sources..
 ***** ERROR: Could not add the docker repository to APT sources.. (Error Code: 127).****
[HELK-DOCKER-INSTALLATION-INFO] Updating the package database with the Docker packages from the newly added repo..
[HELK-DOCKER-INSTALLATION-INFO] Making sure that Docker is being installed from the Docker repo and not the default Ubuntu 16.04 repo..
[HELK-DOCKER-INSTALLATION-INFO] Installing Docker..
 *** ERROR: Could not install Docker.. (Error Code: 100).**
[HELK-DOCKER-INSTALLATION-INFO] Docker has been successfully installed..
[HELK-DOCKER-INSTALLATION-INFO] Docker Version:
**scripts/helk_linux_deb_docker_install.sh: line 93: docker: command not found**
[HELK-DOCKER-INSTALLATION-INFO] Checking local vm.max_map_count variable
[HELK-DOCKER-INSTALLATION-INFO] Building the HELK container from source..
**./helk_install.sh: line 48: docker: command not found**
[HELK-DOCKER-INSTALLATION-INFO] Running the HELK container in the background..
**./helk_install.sh: line 50: docker: command not found**
[HELK-DOCKER-INSTALLATION-INFO] Waiting for Jupyter Server to start..
**./helk_install.sh: line 54: curl: command not found**
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
./helk_install.sh: line 54: curl: command not found
^C

**Comment by wasilewski** [comment]
nvm, option number 3 seems to be working so far, thanks!

**Comment by Cyb3rWard0g** [comment]
Hello @wasilewski . it seems that the main issue is the docker package not being pulled properly. Can you provide the version of your Ubuntu system? So far it works with Xenial 16.04 (LTS). I have to adjust the script to take other versions of Ubuntu. Also, could you copy and paste the logs from /var/log/helk-docker-install.log?? That should give you more details of what exactly happened wile installing Docker. thank you Charlie!

**Comment by Cyb3rWard0g** [comment]
@wasilewski I integrated the official docker install script (edge version) from Docker. Known as the convenience script, it is capable to detect your specific distribution and version and install Docker the right way. Let me know if that works. I just added that with this last commit. https://github.com/Cyb3rWard0g/HELK/commit/4f2bbfbc2186840954e110257b9350742263cd29

**Comment by wasilewski** [comment]
@Cyb3rWard0g Option 1 still doesn't work. I went back to my fresh installation Ubuntu snapshot and tried again. Looks like an error with CURL installation:

[HELK-INSTALLATION-INFO] Enter choice [ 1 - 4] 1
[HELK-DOCKER-INSTALLATION-INFO] HELK identified Linux as the system kernel
[HELK-DOCKER-INSTALLATION-INFO] Checking distribution list and version
[HELK-DOCKER-INSTALLATION-INFO] You're using ubuntu version xenial
[HELK-DOCKER-INSTALLATION-INFO] Docker is not installed
[HELK-DOCKER-INSTALLATION-INFO] Checking if curl is installed first
[HELK-DOCKER-INSTALLATION-INFO] curl is not installed
[HELK-DOCKER-INSTALLATION-INFO] Installing curl before installing docker..
 * ERROR: Could not install curl (Error Code: 100).
[HELK-DOCKER-INSTALLATION-INFO] Installing docker via convenience script..
 * ERROR: Could not install docker via convenience script (Error Code: 127).
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 262144
[HELK-DOCKER-INSTALLATION-INFO] Building the HELK container from source..
[HELK-DOCKER-INSTALLATION-INFO] Running the HELK container in the background..
[HELK-DOCKER-INSTALLATION-INFO] Waiting for Jupyter Server to start..
./helk_install.sh: line 33: curl: command not found
./helk_install.sh: line 33: curl: command not found
./helk_install.sh: line 33: curl: command not found
./helk_install.sh: line 33: curl: command not found
^C

I am running VMware Workstation with Ubuntu:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

**Comment by Cyb3rWard0g** [comment]
oops. sorry. I didnt set the curl installation properly. try it again. I fixed the install syntax with this commit https://github.com/Cyb3rWard0g/HELK/commit/13995a4d66494ad066045e9aab65f260ffedbd2f

**Comment by Cyb3rWard0g** [comment]
@wasilewski let me know if that fixed the issue. The option 1 and 2 are affected by the docker installation so I hope the new docker install script fixes all the that. 👍

**Comment by wasilewski** [comment]
@Cyb3rWard0g All good this time! 

[HELK-INSTALLATION-INFO] Enter choice [ 1 - 4] 1
[HELK-DOCKER-INSTALLATION-INFO] HELK identified Linux as the system kernel
[HELK-DOCKER-INSTALLATION-INFO] Checking distribution list and version
[HELK-DOCKER-INSTALLATION-INFO] You're using ubuntu version xenial
[HELK-DOCKER-INSTALLATION-INFO] Docker is not installed
[HELK-DOCKER-INSTALLATION-INFO] Checking if curl is installed first
[HELK-DOCKER-INSTALLATION-INFO] curl is not installed
[HELK-DOCKER-INSTALLATION-INFO] Installing curl before installing docker..
[HELK-DOCKER-INSTALLATION-INFO] Installing docker via convenience script..
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 262144
[HELK-DOCKER-INSTALLATION-INFO] Building the HELK container from source..
[HELK-DOCKER-INSTALLATION-INFO] Running the HELK container in the background..
[HELK-DOCKER-INSTALLATION-INFO] Waiting for Jupyter Server to start..
[HELK-INSTALLATION-INFO] Obtaining current host IP..

***********************************************************************************
** [HELK-INSTALLATION-INFO] YOUR HELK IS READY                                   **
** [HELK-INSTALLATION-INFO] USE THE FOLLOWING SETTINGS TO INTERACT WITH THE HELK **
***********************************************************************************
xxxxx

BTW. This project is great. Thank you and keep up a good work!

**Comment by Cyb3rWard0g** [comment]
Awesome!!!! Yaayy! Thank you very much for your feedback and for sharing the issues you were having with it. That helps the project to get better. 👍  I will be sharing a blog post soon and a wiki to provide more details about how everything is built and how it can be customized to make it scale even more. 👍  . I will close this issue, but if you have any other issues, feel free to open another one. Have a great weekend! Thank you
