### ISSUE TITLE
spark initial job job has not accepted any resources

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#111]
Hi

i can get the initial steps of the notebook to run ok, untill i hit this step

![image](https://user-images.githubusercontent.com/9341788/47652209-a29afe00-db85-11e8-8585-98048fa219f9.png)

I initially thought was because  I had too much sysmon data for the test instance of the helk to handle so i limited it do one day, by giving it a specific index instead of the wildcard index

![image](https://user-images.githubusercontent.com/9341788/47652293-d37b3300-db85-11e8-9417-1e15aa108c1a.png)

however i still can't get past the following step in the notebook

![image](https://user-images.githubusercontent.com/9341788/47652351-f574b580-db85-11e8-8a23-8cfaf242154e.png)

this is the one that shows the relationship table from what i can tell. do i need to limit the sysmon data set further?

the logs shows the following

18/10/29 13:14:36 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[D 2018-10-29 13:14:49.077 JupyterHub proxy:670] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
13:14:49.082 - info: [ConfigProxy] 200 GET /api/routes
[I 2018-10-29 13:14:49.110 JupyterHub proxy:301] Checking routes
18/10/29 13:14:51 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[Stage 0:>                                                          (0 + 0) / 1]18/10/29 13:15:06 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cl                uster UI to ensure that workers are registered and have sufficient resources
18/10/29 13:15:21 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
18/10/29 13:15:36 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
18/10/29 13:15:51 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[Stage 0:>                                                          (0 + 0) / 1]18/10/29 13:16:06 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cl                uster UI to ensure that workers are registered and have sufficient resources
18/10/29 13:16:21 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
18/10/29 13:16:36 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
18/10/29 13:16:51 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources

im a total newbie to the jupyter part of the HELK, but from your presentation it seems this is where the magic is.

**Comment by Cyb3rWard0g** [comment]
Hey @ssi0202 , what version of HELK are you using?? I ask that because the latest version does not create derby.log files in Jupyter.

**Comment by ssi0202** [comment]
arhh not the latest, i'll update and see what happens ;)

**Comment by Cyb3rWard0g** [comment]
Let me know if you still have issues with this. It still works as expected with the latest version. I will open the issue if you still have the same problems. Thank you!
