### ISSUE TITLE
droping sysmon events based on as_org

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#113]
hey trying to get this filter to work

# MS drop filter
filter {
  if [log_name] == "Microsoft-Windows-Sysmon/Operational" and "[meta_dst_ip_geo][as_org]" == "[insert name here]" {
  drop { }
}
}
what am i missing i've tried several iterations, basically i want to get rid of noisy network traffic before 
it get to elasticsearch as this is a huge amount of events once is scale to hundreds of machines.

the only way i've gotten it to work is via a cidr filter with ip's but that will be death to maintain

**Comment by Cyb3rWard0g** [comment]
HEy @ssi0202 , it looks good to me. the only thing would be where that filter is being applied. In what order.  
![image](https://user-images.githubusercontent.com/9653181/48270371-e6a0c500-e407-11e8-9bc3-4ef2ffbc0cee.png)

I would assume that it needs to be done after the 8115 config. I was wondering if thats the issue or if your string search is case sensitive or just not the right string?? Can you try with other strings rather than [meta_dst_ip_geo][as_org] and see if you have hits?

**Comment by ssi0202** [comment]
hi again,

i got the filter in the right place and if i do this

# MS drop filter
filter {
  if [log_name] == "Microsoft-Windows-Sysmon/Operational" and [process_name] == "firefox.exe" {
  drop { }
}
}

it seems to work ok

however if i do

# MS drop filter
filter {
  if [log_name] == "Microsoft-Windows-Sysmon/Operational" and [meta_dst_ip_geo][as_org] == "Microsoft Corporation" {
  drop { }
}
}

it does not work

it seems to be related to the "." in the   meta_dst_ip_geo.as_org part of the filter.

i tried doing "%[as_org]" as well. since there is a space in between Microsoft and Corporation should this be bracketed also?

im sure it can be done

the examples i can find with elastic do not cover having a "." in the  

i guess it would have to be one of the ones below

**Comment by Cyb3rWard0g** [comment]
mmm @ssi0202 , I will have to replication it on my end too. I will let you know if I get the same. It all looks good to me.

**Comment by ssi0202** [comment]
hey 

this filter works as intended now

filter {
  if [log_name] == "Microsoft-Windows-Sysmon/Operational" and [meta_dst_ip_geo][as_org] == "Microsoft Corporation" {
  drop { }
}
}

I don't know why it did not work the first time, the id is 8116 in the pipeline i may have put it in the wrong place.

please close the issue.

**Comment by Cyb3rWard0g** [comment]
sounds thank you for the update @ssi0202 👍

**Comment by neu5ron** [comment]
@ssi0202 nice! I was going to say, it looked good to me but just check order to make sure after 8112
