### ISSUE TITLE
Can't call helk ip 

### ISSUE THREAD

**Issue by weev3** [Cyb3rWard0g/HELK#114]
Hi, after restarting HELK docker only elastic docker container was stopped running and can't start again. All docker container are running except elastic search. I also can't call to HELK IP after restarting docker container. How I can start again ?

**Comment by Cyb3rWard0g** [comment]
HEY @weev3 , could you share some logs from the initial installation. they should be in your host /var/log/helk-install.log . Also, did you use the helk_install.sh script to start everything?? Thank you!

**Comment by weev3** [comment]
Hello @Cyb3rWard0g , How can I connect elasticsearch http(port 9200) from other IP Address? 
This is not an issue but i can't find any answers in google that fit for me. 
I want to gather data from sysmon view. So, i changed " network.host: localhost" in elasticsearch.yml but shows 500 server error :(. Help me

**Comment by weev3** [comment]
Hello @Cyb3rWard0g  thanks again for your reply, yes i found lab setup in your [website](https://cyberwardog.blogspot.com/2017/02/setting-up-pentesting-i-mean-threat_87.html)

Let me show some config file, I want to add  

> Microsoft-Windows-TerminalServices-LocalSessionManager/Operational 

 to kibana index pattern, so i add 2 .conf file (filter and output). 

**Output conf file** 

```
# HELK winevent-security output conf file
# HELK build Stage: Alpha
# Author: Roberto Rodriguez (@Cyb3rWard0g)
# License: GPL-3.0

output {
  if [log_name] == "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational"{
    elasticsearch {
      hosts => ["helk-elasticsearch:9200"]
      index => "logs-endpoint-winevent-terminalservices-%{+YYYY.MM.dd}"
      document_id => "%{[@metadata][log_hash]}"
      #document_type => "_doc"
    }
    kafka {
      bootstrap_servers => "helk-kafka-broker:9092"
      codec => "json"
      topic_id => "securitytransformed"
    }
  }
}
```
**Filter conf file**

```
filter {
   if "winlogbeat" in [tags] and [log_name] == "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" and [event_id] == 21 {  
  mutate {
    add_field => { "EventDescription" => "Session logon succeeded" }
  }
}
}

filter {
   if "winlogbeat" in [tags] and [log_name] == "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" and [event_id] == 24 {  
  mutate {
    add_field => { "EventDescription" => "Session has been disconnected" }
  }
}
}

filter {
   if "winlogbeat" in [tags] and [log_name] == "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" and [event_id] == 25 {  
  mutate {
    add_field => { "EventDescription" => "Session reconnection succeeded" }
  }
}
}
```

After this i can't see index pattern in kibana. What am i missed ? @Cyb3rWard0g , thanks very much for your help

**Comment by Cyb3rWard0g** [comment]
thats not the docker version. I meant the one from this repo: 
```
git clone https://github.com/Cyb3rWard0g/HELK
cd HELK/docker
sudo ./helk_install.sh
```
If you want to add a new config to the logstash pipeline, add it to the pipeline folder locally on your host and then you can restart the logstash docker container
```
sudo docker restart helk-logstash
```
I adjusted the two configs below:

filter:
```
filter {
   if "winlogbeat" in [tags] and [log_name] == "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" and [event_id] == 21 {  
    mutate {
      add_field => { "EventDescription" => "Session logon succeeded" }
    }
  }
   if "winlogbeat" in [tags] and [log_name] == "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" and [event_id] == 24 {  
    mutate {
      add_field => { "EventDescription" => "Session has been disconnected" }
    }
  }
   if "winlogbeat" in [tags] and [log_name] == "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" and [event_id] == 25 {  
    mutate {
      add_field => { "EventDescription" => "Session reconnection succeeded" }
    }
  }
}
```
output
```
output {
  if [log_name] == "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational"{
    elasticsearch {
      hosts => ["helk-elasticsearch:9200"]
      index => "logs-endpoint-winevent-terminalservices-%{+YYYY.MM.dd}"
      document_id => "%{[@metadata][log_hash]}"
    }
  }
}
```

**Comment by Cyb3rWard0g** [comment]
Hey @weev3 , let me know if this is still an issue. Thank you! 👍

**Comment by Cyb3rWard0g** [comment]
HEy @weev3 , closing this issue. Please let me know if you have any additional questions so we can reopen it.
