### ISSUE TITLE
adding character count for  process_command_line in sysmon logstash filter

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#118]

**Comment by ssi0202** [comment]
hi 
not a bug as such but more a enhancement

i want to count the number of characters in the process command line filed, as really really long command lines are indication of a script being run, and no a end user typing stuff in. We resently had a pentest and with sysmon im able to see these very long command lines being run and i want to be able to alert on this

below is the "vanila" logstash helk filter for sysmon event id 1


    if [event_id] == 1 {
      mutate {
        add_field => { "action" => "processcreate" }
        rename => {
          "CommandLine" => "process_command_line"
          "CurrentDirectory" => "process_current_directory"
          "ParentImage" => "process_parent_path"
          "ParentCommandLine" => "process_parent_command_line"
          "IntegrityLevel" => "process_integrity_level"
          "LogonGuid" => "user_logon_guid"
          "ParentProcessGuid" => "process_parent_guid"
          "ParentProcessId" => "process_parent_id"
          "TerminalSessionId" => "user_session_id"
          "FileVersion" => "file_version"
          "Description" => "file_description"
          "Product" => "file_product"
          "Company" => "file_company"
        }
        gsub => [ "process_parent_guid", "[{}]", "" ]
      }

######## IOC section #######  OFFICE SUITE ####   
if [process_parent_name] =~ /(?i)(cmd.exe)/ and [process_name] =~ /(?i)(cmd.exe)/ {
  ruby {
     code =>"
             event['processcreate']  = event['process_command_line'].length > 250
	}
        mutate {
               add_field => { "IOC" => "Browser Launched From Outlook" }
               add_tag => [ "Browser Launched From office" ]
    }
  }
### below works fine
if [process_parent_name] =~ /(?i)(OUTLOOK.EXE)/ and [process_name]  =~ /(?i)(psexec.exe|powershell.exe|wscript.exe|cmd.exe|taskeng.exe|cab.exe|java.exe|py.exe|.exe)/ 
       {
       mutate { 
              add_field => { "IOC" => "Powershell & Exes Launched From Outlook" }
              add_tag => [ "Powershell & Exes Launched From outlook" ] 

    }
  }

there could be more ways of doing this, but the above is what i could fine from searching the elastic forums. 

see my post here

https://discuss.elastic.co/t/count-length-of-field-number-of-characters-in-a-field-and-add-the-result-into-a-new-field/157705

**Comment by Cyb3rWard0g** [comment]
Nice @ssi0202 ! yeah that would be the way to do it in my opinion. I will test it out and add it to the next update 👍

**Comment by ssi0202** [comment]
hey 

its not working correctly at the moment i keep getting an error from logstash guess i need more logstash-fu with ruby on top. i can even tell if im close but i think you get the idea. 

ps i also caught the pentester with the helk doin a whoami.exe, i made an IOC of that before they started ;o)

i have a whole week of pentester activity to  learn from now as i recorded everything with sysmon etc to wec and send all the data to the helk. I had them map their work to ATT&CK so hopefully i will be able to contribute what techniques look like at later date. Once again thank you so much for buliding and sharing this

**Comment by neu5ron** [comment]
@ssi0202 you could do:
```
if [process_parent_name] =~ /(?i)(cmd.exe)/ and [process_name] =~ /(?i)(cmd.exe)/ {
    ruby {
        code => "
            process_command_line_length  = event.get('process_command_line').length
            if process_command_line_length >= 250
                event.set('IOC', 'Command line exceeds 250 characters')
                event.tag('Command line exceeds 250 characters')
            end
        "
    }
}
```
