### ISSUE TITLE
Plans to support ES 6.5?

### ISSUE THREAD

**Issue by ltfi** [Cyb3rWard0g/HELK#119]
What plans are there to support the latest version (6.5.1 right now) of Elasticsearch?

**Comment by neu5ron** [comment]
soon :) We were waiting for 6.5.1 actually.

**Comment by Cyb3rWard0g** [comment]
good morning @ltfi , 6.5.1 is available. I am pushing an update soon.  I would say over the weekend. 👍

**Comment by ltfi** [comment]
Thats a very good new 👏🏽 will this release support Zeppelin?

**Comment by Cyb3rWard0g** [comment]
@ltfi Zeppelin is the next notebook. Finishing Elastalert with SIGM and KSQL integrations. Also, updating the containers size and updating Spark, Kafka and ELK stack.. Zeppelin is next. 👍

**Comment by Cyb3rWard0g** [comment]
Hey @ltfi ! Logstash plugins are not part of the new release. That is next. I updated the build to 6.5.3 . Closing this issue since there is nothing to fix here. You suggestions are part of the next updates 👍
