### ISSUE TITLE
Log file location

### ISSUE THREAD

**Issue by weev3** [Cyb3rWard0g/HELK#120]
Hi @Cyb3rWard0g , it is possible to change logs storage location in new mount folder?.
I think default HELK log files are in /var/lib/docker/overlay2. 
In my case, new mount folder in /mnt/nfs_share, how to change log storage location to that folder?.
Can you help me?.
 I followed HELK docker installation instruction for enterprise usage. Our company has 300-400 computers, so log files need to stored in that location.

**Comment by Cyb3rWard0g** [comment]
Hey @weev3 ! sorry for the late response. I have been a little busy lately. Regarding the logs storage location in a new mount folder, I have not dealt with it yet. I will have to do some research on how it can be done.

**Comment by weev3** [comment]
@cyb3rWard0g Thank you. I tried too many answers on Google but all didn't fits for me.
I used 24GB of RAM and 100GB storage for production use, our company can't provide more than 100GB for physical storage so I need to find a way to store only logs file to /mnt/share folder. 
Thanks for creating this HELK. Attackers can't hide when they doing Lateral movement.

**Comment by neu5ron** [comment]
You can [create a snapshot](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) of the ELK indexes and then restore them into your new desired location. 

You can then change the path of where your indexes are in the elasticsearch.yml (the configuration file for elasticsearch) by altering:
the `path.data:` line.
probably better option is to edit the docker compose file and the definitions under the "volumes" line:
https://github.com/Cyb3rWard0g/HELK/blob/5f303c83ae09707ba3d0bc987fe81d874e570e76/docker/helk-kibana-analysis-basic.yml#L10
and the re-run through the docker compose after modifying.

**Comment by neu5ron** [comment]
@weev3 fixed, wonder so we can close

**Comment by Cyb3rWard0g** [comment]
Closing the issue. Happy to reopen it if this is something that can be done from a HELK's perspective. Unfortunately, I cannot control the environment provided for HELK that is not recommended for the current version of the project. If this is fixed, please let me know how and I can add that as an option for the project.
