### ISSUE TITLE
IP Configuration

### ISSUE THREAD

**Issue by tesslamx** [Cyb3rWard0g/HELK#127]
I'm a newcome on HELK, I installed HELK by script and I'd like to change de IP configuration the script asked for at the installation execution. I mean, I'd need to change the new IP on every service (docker machine) or when exactly to keep running HELK without problems.

Thanks for you time and attention, greetings!

**Comment by Cyb3rWard0g** [comment]
@tesslamx , feel free to reopen this issue if my response above did not help. I tested what I recommended and it works. Thank you
