### ISSUE TITLE
CSV Support

### ISSUE THREAD

**Issue by ltfi** [Cyb3rWard0g/HELK#128]
How can I analyze "csv" logs in "HELK"?

**Comment by Cyb3rWard0g** [comment]
Hey @ltfi , good question. I have a basic example with the ATT&CK integration:
1- https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/0003-attack-input.conf
2- https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/1216-attack-filter.conf
3- https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9956-attack-output.conf

You will just have to adjust some values such as the location of the file, the tag and index. Let me know if this helps

**Comment by ltfi** [comment]
Wow, thanks for quick response.

**Comment by ltfi** [comment]
How can i build whole project? I can use it with docker but cannot build :)
