### ISSUE TITLE
No indices match pattern "powershell-*" and wmiprvse.exe

### ISSUE THREAD

**Issue by WasKa001** [Cyb3rWard0g/HELK#13]
Hi,

I have a two questions:

1. All of the below are working fine and are discoverable apart from **powershell-***

powershell-*
sysmon-*
winevent-application*
winevent-security-*
winevent-system-*

No matching indices found: No indices match pattern "powershell-*"
Screnshoot with error message: https://imgur.com/Ox7ePL1

2. I've noticed **wmiprvse.exe** is generating lots of data. I just installed Win 7 on my VM endpoint, configured sysmon and winlog beat using your blog post about hunting lab. Is this normal? Looks like it generated almost 500.000 entries within an hour. 

Screenshoot - https://imgur.com/1T5zOMJ

Thanks!

**Comment by Cyb3rWard0g** [comment]
@WasKa001 thank you for the details. Regarding the powershell-* index. Did you set your endpoint to send PowerShell logs over to the HELK?? For example, this is the Winlogbeat config that I use in my lab: https://github.com/Cyb3rWard0g/HELK/blob/master/winlogbeat/winlogbeat.yml . Let me know if you are doing that already. if you are already doing that, can you just refresh your Kibana interface in your browser by typing the IP of your HELK and refreshing the page?? Sometimes there might be a delay for the logs to get to the HELK but the browser caches kibana results (i.e the warning message). Also, regarding wmiprvse.exe yes that could be normal. The Sysmon config provided in my blog post (https://gist.github.com/Cyb3rWard0g/136481552d8845e52962534d1a4b8664) is just a basic one to allow others to customize the way it is needed or wanted. Let me know if this is helpful and if I was able to help or answer your questions.

**Comment by Cyb3rWard0g** [comment]
Hey @WasKa001 I hope you had a good weekend. Let me know if you were able to take a look at the suggestions I shared. let me know if this could be closed or if you still need help. Thank you!

**Comment by WasKa001** [comment]
@Cyb3rWard0g hi, sorry I didn't have a chance to check it yet. I am using .yml config file from your blog. I guess it's the same as the one you've posted above. I'll check once again later on today in the evening and will get back to you soon, thanks!

**Comment by Cyb3rWard0g** [comment]
@WasKa001 sounds good. no rush. The YML file is a good start but needs to be customized for your own need and use cases. Let me know if you were able to install the HELK without any issues 👍  Whenever you have a chance. Thank you

**Comment by WasKa001** [comment]
@Cyb3rWard0g HELK installation is not the issue, I've installed it and everything is working properly apart from powershell-* section - "No indices match pattern "powershell-*"

Do I need to modify your YML to get this working? I used YML from your blog post about threat hunting lab. Thanks!

**Comment by Cyb3rWard0g** [comment]
ok so HELK installation is not the issue. Can you provide the link to the YML file? The one that I used for the threat hunting lab is not set up to pull PowerShell logs. The YML that you should use is this one: https://github.com/Cyb3rWard0g/HELK/blob/master/winlogbeat/winlogbeat.yml. Also, make sure you have enhanced PowerShell logging enabled: https://cyberwardog.blogspot.com/2017/06/enabling-enhanced-ps-logging-shipping.html . Let me know if this makes sense.

**Comment by WasKa001** [comment]
@Cyb3rWard0g ok thank you, I will have a chance to test it out over the weekend. I will replace my config file with the above YML and will let you now. I also don't have currently Enhanced PowerShell logging enabled so I guess this is why I am getting the error related to powershell-* indices pattern match

**Comment by Cyb3rWard0g** [comment]
Sounds good @WasKa001. I will close this issue since it is a configuration happening at the client side and not in HELK. Feel free to reopen it or create a new one if the HELK fails at install or if any index does not work at all after you have all the data you need being sent to it. Thank you
