### ISSUE TITLE
HELK without Docker Environment

### ISSUE THREAD

**Issue by ltfi** [Cyb3rWard0g/HELK#130]
How can i build HELK to run without docker environment?

**Comment by Cyb3rWard0g** [comment]
Hey @ltfi ! Sorry for the late response. For the moment, I am focusing on making the docker-compose deployment more robust and stable. I have plans on pushing packer images and make it easy to deploy it in other environments besides docker 👍

**Comment by Cyb3rWard0g** [comment]
I will leave this issue open until there is another way to deploy HELK besides Docker. Do you have any other any environment in mind @ltfi ??

**Comment by griffo138** [comment]
I've been trying to build it out into an openstack project. I don't know how you'd make that as automated as your docker deployment but it would be useful.

**Comment by ltfi** [comment]
thnx for response @Cyb3rWard0g

**Comment by ltfi** [comment]
@neu5ron I wanna build source code to make some further customization for my own case.

**Comment by ltfi** [comment]
I want to build the source code, I don't want to use the docker, how can I do?

**Comment by Cyb3rWard0g** [comment]
Hey @ltfi , you can take each Dockerfile for each component of HELK and turn it into a bash script. I will be creating Packer scripts soon for the project. I will link those new files to this issue when they are done. In the meantime, let me know how it goes on your end when trying to build your own bash scripts. Thank you!
