### ISSUE TITLE
SSL certificate, add user, change password

### ISSUE THREAD

**Issue by jespersj** [Cyb3rWard0g/HELK#131]
Hi there

Bare with me, first time github and HELK user here...

I have just finished installing HELK and is now able to log into Kibana with the default username/password/certificate. I would like to change the default username/password and if possible update the SSL certificate to a signed/trusted certificat, is that possible?

HELK looks like a epic tool and I'm really looking forward to use it.

**Comment by neu5ron** [comment]
no problem. Glad you are interested.

# replace cert
generate a cert and replace line 19 and 20 in the nginx config with the location of your cert key and cert pem/crt.
the nginx config location should be:
/etc/nginx/sites-available/default
you will need to upload the certs into the NGINX docker instance, u can get into that docker instance via something such as:
sudo docker exec -ti helk-nginx bash

# add user/pass:
add usernames/passwords by logging into the docker instance and running:
sh -c "echo -n '$USER_NAME:' >> /etc/nginx/htpasswd.users"
sh -c "openssl passwd -apr1 >> /etc/nginx/htpasswd.users"

**Comment by MakoWish** [comment]
Unfortunately, attempting to add a user with the above method errors with "Read-only file system". Is there another method to add users?

`root@5a32c0c54f70:~# sh -c "echo -n 'eadmin:' >> /etc/nginx/htpasswd.users"
sh: 1: cannot create /etc/nginx/htpasswd.users: Read-only file system
root@5a32c0c54f70:~#
`

**Comment by Cyb3rWard0g** [comment]
Hey @MakoWish , can you do the change locally and then do `sudo docker restart helk-nginx` for the build to pick up the changes?

**Comment by MakoWish** [comment]
Not sure what you mean by "do the change locally". I was in the container with `sudo docker exec -ti helk-nginx bash`, and I get the above "Read-only file system" error when attempting to write to the file. Even with `sudo vi /etc/nginx/htpasswd.users`, vi says the file is read-only.
