### ISSUE TITLE
typo in new helk_install.sh

### ISSUE THREAD

**Issue by griffo138** [Cyb3rWard0g/HELK#133]
**Describe the problem**
In the section Docker Compose Build Choices
Option 2 Reads 
" HELK_BUILD='helk-kibana-notebook-analysis-';break;;"

I believe it should not have the final hyphen 

**What version of HELK are you using?**
latest pull
**What OS are you using to host the HELK?**
Ubuntu 16.04

**Comment by griffo138** [comment]
Great to see the new release guys - been really looking forward to the update to 6.5

**Comment by Cyb3rWard0g** [comment]
Thank you very much @griffo138 for the heads up 👍 Please let me know if you find any other issues with the scripts.
