### ISSUE TITLE
ERROR: yaml.parser.ParserError - helk-kibana-notebook-analysis-basic.yml

### ISSUE THREAD

**Issue by griffo138** [Cyb3rWard0g/HELK#134]
**Describe the problem**
Invalid yml in helk-kibana-notebook-analysis-basic.yml

When 
Building & running HELK from helk-kibana-notebook-analysis-basic.yml file
I get
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./helk-kibana-notebook-analysis-basic.yml", line 4, column 2
expected <block end>, but found '<block mapping start>'
  in "./helk-kibana-notebook-analysis-basic.yml", line 30, column 3

**What steps did you take trying to fix the issue?**
added an extra space in the yml

  helk-elasticsearch:
^
here

**What version of HELK are you using?**
latest pull
**What OS are you using to host the HELK?**
Ubuntu 16.04

**Comment by Cyb3rWard0g** [comment]
Thank you @griffo138 👍 I appreciate the help
