### ISSUE TITLE
ee outlier and flare

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#137]
hi

not an issue but did you see these two projects for detecting behavior ee-outlier just got open sourced

https://github.com/NVISO-BE/ee-outliers

https://github.com/austin-taylor/flare

**Comment by Cyb3rWard0g** [comment]
I have seen those two projects and they are great! Once the Spark & Jupyter integration gets more robust, I think it would be good to go over those again. Thank you for sharing. The project is still a work in progress and I will take those two in consideration for when the time comes. Thank you again @ssi0202 . I really appreciate your suggestions 👍
