### ISSUE TITLE
sigma rules placement

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#138]
where do i put the sigma rules 

like the ones from here ex

https://github.com/Neo23x0/sigma/tree/master/rules/windows/sysmon

**Comment by Cyb3rWard0g** [comment]
All the rules with the latest integration are in `/etc/elastalert/rules` . Does that answer your question? Sorry for the late response @ssi0202

**Comment by Cyb3rWard0g** [comment]
@ssi0202 , feel free to reopen this issue if I didnt answer your question. Thank you 👍
