### ISSUE TITLE
Sysmon Configuration 

### ISSUE THREAD

**Issue by hoboscientist** [Cyb3rWard0g/HELK#141]
Hey, I love the work you have done with HELK. I see all the ETL but can you share your sysmon configuration that you are using. Preferably one integrated with ATT&CK. Thanks in advance.
Much Love,
Hobo

**Comment by Cyb3rWard0g** [comment]
Hey @hoboscientist , sorry for the late response. I do not have a final config that is mapped to ATT&CK yet. One that I have seen with ATT&Ck references is this one https://github.com/ion-storm/sysmon-config/blob/develop/sysmonconfig-export.xml .

**Comment by hoboscientist** [comment]
Hey, I just have a short query. I have found Olafharong's configuration too. Between olafhartong's and ion-storm, which one do you recommend? Albeit, I see that ion-storms is more granular, and I have been testing olaf's config which, in my case, is producing a lot of false positives. Thanks for your time. Cheers.
