### ISSUE TITLE
Periodically remove old data

### ISSUE THREAD

**Issue by chinguunhr** [Cyb3rWard0g/HELK#143]
Hello,

Is there any way to remove old data(older than 30 day)  periodically ?

**Comment by griffo138** [comment]
I use Curator by elastic  https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html
you should be able to find templates online, I created a template for the different indexes based on what retention periods I wanted and then a bash script added to cron. 
If you need further assistance let me know and I'll share what I have.

**Comment by chinguunhr** [comment]
@Cyb3rWard0g  Thanks. :)

**Comment by ssi0202** [comment]
hey griffo please share what you have

**Comment by griffo138** [comment]
so once curator is installed and you've configured the base curator.xml file (/usr/local/bin/curator.yml) with your elasticsearch settings 

i have something like this - the prefix is what you might want to change - this will do all the indices starting with logs. You could have logs-endpoint-winevent-system for example. I have one for each with retention periods from 1 week to 6 months.

> ---

actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 30 days (based on index name), for logs-*
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logs-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30
      exclude:
>  

I save that as /root/delete_log_indices_time_base.yml 
then have a bash script /root/delete_log_indices_time_base.sh containing 

> /usr/local/bin/curator /root/delete_log_indices_time_base.yml --config /usr/local/bin/curator.yml

chmod +x /root/delete_log_indices_time_base.sh

then add it to cron to run daily. 

there is probably a better way, if someone else has advice. I'm just a windows admin playing on linux

**Comment by neu5ron** [comment]
well we held off long enough that this is now in the kibana management tab for 6.6! Which 6.6 will be around the corner in HELK.
Going to close this, @chinguunhr if you have any questions comments -- feel free to respond. However, I believe this is a much better solution (ie: inside of Kibana) than what we could provide.
![selection_504](https://user-images.githubusercontent.com/6351842/51957153-6d1ddf00-2418-11e9-866c-63d72f139c83.png)
