### ISSUE TITLE
error in visualization - dashboard

### ISSUE THREAD

**Issue by hakavod** [Cyb3rWard0g/HELK#144]
![helk](https://user-images.githubusercontent.com/45045004/50609701-7c078500-0e9e-11e9-863a-ea09edb3f4c7.png)

good afternoon with everyone, had a similar problem and have solved it?

**Comment by Cyb3rWard0g** [comment]
Good morning @hakavod , what dashboard and visualization is that?

**Comment by hakavod** [comment]
Hi, thanks for answering ... I share a screen today. The events in the panel are shown, but what I appreciate is that the alerts or "errors" are more constant when I reduce the interval refresh to 5 seconds.

![helk_2](https://user-images.githubusercontent.com/45045004/50646953-65683900-0f45-11e9-94f0-8516f9875f53.jpg)

**Comment by neu5ron** [comment]
Thanks for the info @hakavod . This definitely appears to be an elasticsearch/database-backend issue.
can you provide the logs from that?

Also, any specific reason you can share on the necessity to have the refresh interval for 5 seconds? This may help me provide some alternatives.

**Comment by hakavod** [comment]
> Gracias por la info @hakavod . Esto definitivamente parece ser un problema de elasticsearch / database-backend. 
> puede proporcionar los registros de eso?
> 
> Además, ¿alguna razón específica que pueda compartir sobre la necesidad de tener el intervalo de actualización durante 5 segundos? Esto me puede ayudar a proporcionar algunas alternativas.

hello excuse the delay in answering. In principle the chosen interval I choose to have almost in real time what happens in the servers, sometimes by specific requirements for other areas that want to be controlled that no one else may be accessing. As for the records you want some log? If you tell me the route where I can get it, I'll gladly share it with you.

**Comment by neu5ron** [comment]
Instead of using dashboard for similar function of alert, have you thought about using what @Cyb3rWard0g added to HELK recently with ElastaAlert for this instant alert functionality or using Elastic X-Pack watcher/alerting?

Anyways, can you send specs on your server? Also can you share some of the last 100 lines of elastisearch.log during time of error? please remove any IP addresses / hostnames from the log before posting...

**Comment by hakavod** [comment]
Thank you all for your response, install the latest version and all ok.

**Comment by Cyb3rWard0g** [comment]
Thank you for the update @hakavod 👍
