### ISSUE TITLE
Can't show logs from kibana

### ISSUE THREAD

**Issue by buldruu** [Cyb3rWard0g/HELK#147]
Winlogbeat is sending fine logs to kafka. But kibana not displaying any logs. Winlogbeat configuration is your recommended yml file. Installation is completed without any error.
![image](https://user-images.githubusercontent.com/45187522/50684349-2ffc4200-1050-11e9-9a6f-e3375c201784.png)
![image](https://user-images.githubusercontent.com/45187522/50684384-4dc9a700-1050-11e9-9b50-6523af38f7a2.png)

**Comment by hakavod** [comment]
hello you can share the screen that shows you when you are in the management option

**Comment by zganchu** [comment]
Hi @hakavod,  are you talking about index patterns? Indexes are HELK defaults.

**Comment by neu5ron** [comment]
@buldruu did u change the output of the winlog beat config to match accordingly to the IP of your HELK instance?

**Comment by Cyb3rWard0g** [comment]
@buldruu can you share your Winlogbeat config??

**Comment by buldruu** [comment]
@buldruu Of course, @Cyb3rWard0g. Changed OS version 16.4.5 to 16.4.1 but issue persistent. 
[winlogbeat.yml.txt](https://github.com/Cyb3rWard0g/HELK/files/2734933/winlogbeat.yml.txt)

**Comment by hakavod** [comment]
En mi humilde opinión haría lo siguiente, en una consola de powershell en el agente realizaria lo siguiente y luego prueba si ya puedes recibir logs.

1. .\install-service-winlogbeat.ps1
2. .\winlogbeat.exe test config -c .\winlogbeat.yml -e.
3. Get-WinEvent -Listlog * | Format-List -Property Logname
4. Start-Service winlogbeat

**Comment by hakavod** [comment]
In my humble opinion I would do the following, in a powershell console the agent would do the following and then test if you can already receive logs.

1. .\install-service-winlogbeat.ps1
2. .\winlogbeat.exe test config -c .\winlogbeat.yml -e.
3. Get-WinEvent -Listlog * | Format-List -Property Logname
4. Start-Service winlogbeat

**Comment by Cyb3rWard0g** [comment]
@buldruu , can you try again by refreshing your page on the Discovery option and checking if you get messages or not. Also, can you provide information about the build? Are you using Option 1 or 2? Are you using the basic or trial version?

**Comment by buldruu** [comment]
@hakavod Winlogbeat is working fine. 
@Cyb3rWard0g  I'm using option 1 and basic version. Can I show logstash pipeline logs? I think may logstash not send to elasticsearch.

**Comment by Cyb3rWard0g** [comment]
@buldruu can you run the following command? `sudo docker logs --follow helk-logstash` ? and share the results? Also what happens when you do `sudo docker ps`?

**Comment by buldruu** [comment]
When looking for logs I found it. It was internet connection issue. I configured docker proxy, http, https proxy but logstash was can't install "**logstash-filter-prune**" plug-in. So permitted direct internet access and it installs successfully.
@Cyb3rWard0g you can close it.

**Comment by Cyb3rWard0g** [comment]
makes sense 👍 Thank you @buldruu . I hope the `sudo docker logs --follow` command helps with future issues. Thank you
