### ISSUE TITLE
Elastalert - IP Reputation 

### ISSUE THREAD

**Issue by griffo138** [Cyb3rWard0g/HELK#150]
Feature Request.
and blacklist or reputation lists from sources like http://iplists.firehol.org/ into elastalert rules.

similar to some security providers where communication to or from these IPs is flagged.

**Comment by neu5ron** [comment]
I definitely agree that firehol is a great list.. However, loading millions of IPs into a database as an alert without strict formal vetting for use-case on the end-user side (in this case end-user would be the HELK user).

For example, thousands of the IPs are scanning IPs. We would not want to have millions of alerts for scans. If we then try to perform whitelist that is much of a burden for an opensource "hunting" platform.

I am open to suggestions and as I said before I don't disagree that firehol has many great use cases.

I will differ to @Cyb3rWard0g on this, but I do not think we want to get into IP reputation IOC for HELK.
If people want to add these things in themselves that is great and good idea. But we do not want to overload HELK with false positives/alerts.

**Comment by griffo138** [comment]
I see your point, My thought process was probably quite narrow-minded. I'm currently looking to use firehols lists to flag on the rule sigma_win_susp_rundll32_activity1.yml type rules. In a shared hosting environment, I'm hoping it would prove quite useful. Even then I think I'll only include IP's from certain categories in the firehol lists.

**Comment by Cyb3rWard0g** [comment]
I agree with @neu5ron . Thank you for the suggestion @griffo138 . I will let users configure their own enrichments when it comes down to intel feeds.
