### ISSUE TITLE
Path to docker-composer missing 

### ISSUE THREAD

**Issue by jespersj** [Cyb3rWard0g/HELK#154]
**Describe the problem**
On a fresh clone I'm getting this when installing:

[everything earlier works fine, omitted here]
[HELK-INSTALLATION-INFO] Building & running HELK from helk-kibana-analysis-basic.yml file..
 * ERROR: Could not run HELK via docker-compose file helk-kibana-analysis-basic.yml (Error Code: 1).

The logfile /var/log/helk-install.log shows the following:
sudo: docker-compose: command not found

**What steps did you take trying to fix the issue?**
Hardcoded the path to docker-compose
sed -i 's/sudo -E docker-compose/sudo -E \\/usr\\/local\\/bin\\/docker-compose/' ./helk_install.sh

For some unknown reason it's not in the PATH, but a "which docker-compose" does show it, so I don't know what is going on.

I haven't tried to run the helk_update.sh yet, but it looks like it's going to have the same issue.

**How could we replicate the issue?**
Fresh clone, on Centos.

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
HELK build version: v0.1.6-alpha12132018

**What OS are you using to host the HELK?**
Centos 7

**Comment by jespersj** [comment]
helk_update.sh works like it should, no problems at all.

It looks like the env isn't correctly set up when doing the "sudo -E" part. So a fix could also be to just remove it.
sed -i 's/sudo -E docker-compose/docker-compose/' ./helk_install.sh

Ps. github removed the backslash "\" I had in the post above. I hope it still makes sense. Sed will fail because of this.

**Comment by Cyb3rWard0g** [comment]
Hey @jespersj , can you run the following?
`docker-compose --version`

Also, did you let the script install docker-compose or you installed it manually?.

**Comment by Cyb3rWard0g** [comment]
Hey @jespersj , so are you still having issues with docker-compose not found? Also, the -E is needed for the docker-compose env variable `ADVERTISED_LISTENER`. it is set during the execution of the steps inside of the `helk_install.sh` script. I remember running it without `sudo -E` and not picking up the `export ADVERTISED_LISTENER` that happens in inside of the execution of the script. Have you tested it without `sudo -E`? Let me know please, and I can update it. I have limited access at the moment.

**Comment by jespersj** [comment]
@Cyb3rWard0g with 
`/usr/local/bin/docker-compose -f $COMPOSE_CONFIG up --build -d >> $LOGFILE 2>&1`
it installs just fine, but I'm uncertain what the ADVERTISED_LISTENER is used for and if something isn't working correctly afterwards? How can I verify it?

**Comment by Cyb3rWard0g** [comment]
@jespersj , I have some details about ADVERTISED_LISTENER in the wiki section `Kafka` under `Kafka Broker`: https://github.com/Cyb3rWard0g/HELK/wiki/Kafka#kafka-broker . 

Kafka needs to advertise its IP address for producers (endpoints or log shippers) to send data. Kafka is a docker container therefore it has two interfaces. One to communicate with the internal docker containers and another one to listen to connections from external systems (outside of docker containers). ADVERTISED_LISTENER is the ip to be reached out by, once again, log producers outside of the docker environment.

You can check if logs are being received by Kafka broker  by following this how-to from the HELk wiki: https://github.com/Cyb3rWard0g/HELK/wiki/Check-Kafka-topic-ingestion .

If you are using winlogbeat to send logs to kafka you can use this how-to from the HELK wiki: https://github.com/Cyb3rWard0g/HELK/wiki/Check-Winlogbeat-shipping

Or if you want to read the contents of the Kafka broker server config file where the IP address is set, you can do it this way:

```
sudo docker exec -ti helk-kafka-broker cat /opt/helk/kafka/config/server.properties | grep 10.0.10.102 
```
you change 10.0.10.102 with your own Ip address. You should get something like this:

![image](https://user-images.githubusercontent.com/9653181/51735583-c8855100-2055-11e9-94ae-733ac00cd172.png)

If you see the ip of your system hosting HELK there, then the environment variable worked and there was no need to run `sudo -E` then.

**Comment by jespersj** [comment]
Excellent, thank you.

Yea, it has the correct ip. So yes, I agree no need for "sudo -E"

**Comment by Cyb3rWard0g** [comment]
@jespersj , I fixed it with this hot-fix https://github.com/Cyb3rWard0g/HELK/releases/tag/v0.1.6-alpha01312019 . Thank you very much
