### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by jermdw** [Cyb3rWard0g/HELK#16]
Create FAQ for wiki. Some users may not know how to restart the HELK server if it stops, modify variables etc... A FAQ page in the wiki would help answer some of these questions.

**Comment by Cyb3rWard0g** [comment]
Hey @jermdw Thank you for the suggestion. Yes I am slowly creating one. I have a few things that I have to create some images to explain a little better. I am planning on getting that done by next week.

**Comment by jermdw** [comment]
Awesome sounds good let me know if I can be of help! 😄 @Cyb3rWard0g
