### ISSUE TITLE
UTC!

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#160]
**Describe the problem**
time sync.
**What steps did you take trying to fix the issue?**
depends on host configuration.
**How could we replicate the issue?**
not having UTC
**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
latest
**What OS are you using to host the HELK?**
ubuntu
**Any additional context?**
other log files, pictures, etc.

We need to make sure set host to UTC -- also to set Kibana to default time picking zone to UTC

reference #155 -- next release will include fix

**Comment by neu5ron** [comment]
thinking about this a lot more (probably than I should ;)

## problems I see with setting someone's timezone and enabling NTP
1. they may have a specific timezone set for a specific reason.
1. they may not have network/access to be able to reach out to x,y,z NTP - we then don't want to have to write scripts to test network connectivity and then if/else statements to try each specific NTP and set accordingly :(
1. windows logs (specifically) are not "usually" set to UTC because it is preconfigured to use "local" timezone and not GMT/UTC. Also, most don't configure the host (after setup) to UTC either.. because they forget or more likely they don't want UTC to be displayed to the end user in their "clock" -- not knowing that the end user clock can be different than the system clock :) except in the case of sysmon.

## problems I see with setting the kibana default to UTC
- many of the reasons mentioned above
- specifically reason in that lets say windows logs are coming in as EST -- people will have to go back 4 hours to see the latest windows logs :)

# Solution
I say we set mention some of the above in  best suggestion and one-off's above mentioned above into the FAQ/best-practices section. Then a note in the install script about it.

**Comment by Cyb3rWard0g** [comment]
agreed ^^ with `Solution` statement

**Comment by kjecyb** [comment]
https://discuss.elastic.co/t/storing-dates-in-elastic-best-practices/57496/2
