### ISSUE TITLE
Error on nginx

### ISSUE THREAD

**Issue by borbelyau** [Cyb3rWard0g/HELK#164]
Hey guys,

I install helk today

For some reason I can not see anything, when access to url, error 502 appears, I did not change anything from the original, I just put the ip in the installation.

The error on log:
172.30.82.154 - helk [05/Feb/2019:13:50:28 +0000] "GET / HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
172.30.82.154 - helk [05/Feb/2019:13:50:28 +0000] "GET /favicon.ico HTTP/1.1" 502 568 "https://192.168.0.45/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

==> /var/log/nginx/error.log <==
2019/02/05 13:50:28 [error] 108#108: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.82.154, server: , request: "GET / HTTP/1.1", upstream: "http://172.19.0.3:5601/", host: "192.168.0.45"
2019/02/05 13:50:28 [error] 108#108: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.82.154, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.3:5601/favicon.ico", host: "192.168.0.45", referrer: "https://192.168.0.45/"

Tks

**Comment by Cyb3rWard0g** [comment]
Hey @borbelyau , can you show the helk-install log file?? it is in `/var/log/helk_install.log`. Also, can you show your main console output when you were installing HELK. That will help me also to see what option you chose and the license version. Also, can you do me a favor and run the following commands:
`sudo docker logs helk-kibana`
`sudo docker logs helk-nginx`

**Comment by neu5ron** [comment]
@borbelyau as @Cyb3rWard0g mentioned -- please send those logs.
it does appear that this would be kibana has not started or other error with kibana -- which we can help once we get the logs.
thanks for asking!

**Comment by borbelyau** [comment]
hey guys, 
I discovery that selinux is the problem...
Tks

**Comment by neu5ron** [comment]
no problem! glad to see you are using centos/rhel -- no reason HELK should work on those platforms, and glad to know you are testing the waters.

Let me know if you need any selinux help, have ran ELK stuff on it before - so I may be able to help
