### ISSUE TITLE
Integrating mysql with helk <Question>

### ISSUE THREAD

**Issue by borbelyau** [Cyb3rWard0g/HELK#167]
**Describe the problem**
How I integrate mysql with helk ?

Mysql is installed in same server that HELK, 
How I send the log or how I capture information inside mysql?

Tks Bro

**Comment by neu5ron** [comment]
there should be some metricbeats for mysql https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-mysql.html

also you could use filebeat and point at the directory/location of the mysql logs

let me know if either of these help, then can explain the logstash config after
