### ISSUE TITLE
Forwarded events (WEF) get the same document_id

### ISSUE THREAD

**Issue by ker0z** [Cyb3rWard0g/HELK#169]
**Describe the problem**
All events received from the WEF/WEC (winlogbeat installed on a collector) get the same document_id ("_id: "%{[@metadate][log_hash]}"). Since the document_id is the key of indexing, all events received that way get overwritten. Events from WEC host (not a forward event) get a numerical document_id and are correctly indexed.

**What steps did you take trying to fix the issue?**
I compared events from WEF and locally. The only different to the naked eye is an event from WEF didn't go thru pipeline 0098 and 0099... and I don't know why. Since pipeline 0099 add value to [@metadate][loghash], the value is empty when sent to elastic.

**What version of HELK are you using?**
Latest

**What OS are you using to host the HELK?**
Ubuntu 18.04.1 LTS

**Comment by neu5ron** [comment]
@ker0z is winlogbeat going to Kafka or directly to beats(via logstash beats input)?

**Comment by ker0z** [comment]
We're following the HELK architecture. winlogbeat to Kafka. Kafka to Logstash. We tried to output from Kafka to Logstash without any pipeline. Not all events has the [message] tag in it. That may explain why the 0098 and 0099 are not triggered. But I didn't find the cause of this difference. On the WEC server, events look fine, with a message.

**Comment by neu5ron** [comment]
Do you perhaps have an EventID or better the entire log (removing any PII/attributable info) that you can share?

I have noticed that sometimes winlogbeat has this issue -- but I am not certain if this is related in anyway.

**Comment by ker0z** [comment]
I found where the problem is. The WEC/WEF was configure in a way that winlogbeat don't to do much processing.

It's well explianed in this blogpost.

http://blog.davidvassallo.me/2017/11/18/lessons-learned-winlogbeat-forwarded-events-no-event-description/

Thank you for your time!
