### ISSUE TITLE
catch all if not hash then generate one

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#171]
ref #169

**Comment by Cyb3rWard0g** [comment]
I was experimenting with an else statement before and ran into the `concatenate_all_fields` fingerprint configuration option: https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html#plugins-filters-fingerprint-concatenate_all_fields

Initially I thought I could do something like this:

```
filter {
  if [message] {
    mutate { add_field => { "z_logstash_pipeline" => "0099" } }
    fingerprint {
      source => "message"
      target => "[@metadata][log_hash]"
      method => "MURMUR3"
      key => "Logstash"
    }
  }
  else {
    mutate { add_field => { "z_logstash_pipeline" => "0099" } }
    fingerprint {
      concatenate_all_fields => true
      target => "[@metadata][log_hash]"
      method => "MURMUR3"
      key => "Logstash"
    }
  }
}
```
However, I dont know why it wouldnt work according to these:
* https://discuss.elastic.co/t/logstash-fingerprint-plugin-how-to-exclude-timestamp/112498/8
* https://github.com/logstash-plugins/logstash-filter-fingerprint/issues/43

Why do I need to exclude the @timestamp field??

**Comment by Cyb3rWard0g** [comment]
oh ok so this is the statement:
```
 I got into a situation where the content of my message does not change but since @timestamp is integral part of the message it creates a UUID and kind of defeats the purpose of the UUID.
```
Welp, in security event logs, there could be events where the values of all the fields are the same because an action could be repeated several times but with seconds or milliseconds between each action. it is a valid use cases, and I believe it is useful to have those "repeated" events be sent to HELK Elasticsearch. I believe this should be enough then:

```
filter {
  if [message] {
    mutate { add_field => { "z_logstash_pipeline" => "0099" } }
    fingerprint {
      source => "message"
      target => "[@metadata][log_hash]"
      method => "MURMUR3"
      key => "Logstash"
    }
  }
  else {
    mutate { add_field => { "z_logstash_pipeline" => "0099" } }
    fingerprint {
      concatenate_all_fields => true
      target => "[@metadata][log_hash]"
      method => "MURMUR3"
      key => "Logstash"
    }
  }
}
```

**Comment by neu5ron** [comment]
yep, so this is exactly what I was thinking, however with the concat-all I there will be two many fields that wouldn't make it unique, such as certain timestamps, any tags, z_logstash_pipeline, etc. What I used to do for any other logs, is an else statement, then hash usually two things -- the UID that the log/vendor contains with the hostname. We could perform the same, and in this example use windows fields:
- EventRecordID
- EventID
- Channel
- Hostname
- ProcessID
- ThreadID


this should give use a unique enough scenario, especially if only an "else" statement

**Comment by neu5ron** [comment]
I will work on this @Cyb3rWard0g, unless you have different suggestion than above -- let me know

but this is my bad.. because I have never seen an even via nxlog have this issue -- so I had no idea winlogbeat would have this

**Comment by Cyb3rWard0g** [comment]
I dont get it, so if we have the following event:
```
<System>
    <Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385F-C22A-43E0-BF4C-06F5698FFBD9}" /> 
    <EventID>1</EventID> 
    <Version>5</Version> 
    <Level>4</Level> 
    <Task>1</Task> 
    <Opcode>0</Opcode> 
    <Keywords>0x8000000000000000</Keywords> 
    <TimeCreated SystemTime="2018-04-11T05:25:02.959125700Z" /> 
    <EventRecordID>11748095</EventRecordID> 
    <Correlation /> 
    <Execution ProcessID="2152" ThreadID="3392" /> 
    <Channel>Microsoft-Windows-Sysmon/Operational</Channel> 
    <Computer>DESKTOP-WARDOG</Computer> 
    <Security UserID="S-1-5-18" /> 
  </System>
  <EventData>
    <Data Name="UtcTime">2018-04-11 05:25:02.955</Data> 
    <Data Name="ProcessGuid">{A98268C1-9C2E-5ACD-0000-0010396CAB00}</Data> 
    <Data Name="ProcessId">4756</Data> 
    <Data Name="Image">C:\Windows\System32\conhost.exe</Data> 
    <Data Name="FileVersion">10.0.16299.15 (WinBuild.160101.0800)</Data> 
    <Data Name="Description">Console Window Host</Data> 
    <Data Name="Product">Microsoft® Windows® Operating System</Data> 
    <Data Name="Company">Microsoft Corporation</Data> 
    <Data Name="CommandLine">\??\C:\WINDOWS\system32\conhost.exe 0xffffffff -ForceV1</Data> 
    <Data Name="CurrentDirectory">C:\WINDOWS</Data> 
    <Data Name="User">DESKTOP-WARDOG\wardog</Data> 
    <Data Name="LogonGuid">{A98268C1-95F2-5ACD-0000-002019620F00}</Data> 
    <Data Name="LogonId">0xf6219</Data> 
    <Data Name="TerminalSessionId">1</Data> 
    <Data Name="IntegrityLevel">Medium</Data> 
    <Data Name="Hashes">SHA1=B0BF5AC2E81BBF597FAD5F349FEEB32CAC449FA2,MD5=6A255BEBF3DBCD13585538ED47DBAFD7,SHA256=4668BB2223FFB983A5F1273B9E3D9FA2C5CE4A0F1FB18CA5C1B285762020073C,IMPHASH=2505BD03D7BD285E50CE89CEC02B333B</Data> 
    <Data Name="ParentProcessGuid">{A98268C1-9C2E-5ACD-0000-00100266AB00}</Data> 
    <Data Name="ParentProcessId">240</Data> 
    <Data Name="ParentImage">C:\Windows\System32\cmd.exe</Data> 
    <Data Name="ParentCommandLine">"C:\WINDOWS\system32\cmd.exe"</Data> 
  </EventData>
```
and we only hash:
```
<EventID>1</EventID>
<Channel>Microsoft-Windows-Sysmon/Operational</Channel> 
<Computer>DESKTOP-WARDOG</Computer> 
<Data Name="ProcessId">4756</Data>
```
then that would make it a unique message?? what if we get the same message as above but with:
```
 <TimeCreated SystemTime="2018-01-11T05:25:02.959125700Z" />
<Data Name="UtcTime">2018-01-11 05:25:02.955</Data>
```
then the message will still be considered a repeated message based on the hash right? So wouldnt that hurt data availability? because we are dropping the message when it could be just a process doing something several times?

**Comment by Cyb3rWard0g** [comment]
I believe in general the pipe should have the `message` if statement and then an `else` statement that would hash messages without the initial `if statement argument`. I ran into that problem when I was re-ingesting data already parsed by the HELK logstash pipeline for tests in new HELK deployments.

**Comment by neu5ron** [comment]
we would be adding EventRecordID and PID and ThreadID to what u mentioned as well.
we can add timecreated too

the concat all, notice this line:
9402111699000829998593
so "@timestamp" would be the time the event is receiving at this point if this early in the pipeline that we concat them. also other "@metadata"  -- that make sense?
sorry, trying to type while watching a 3 year -- i'm probably talking like one right now

**Comment by neu5ron** [comment]
some of these fields do not exist in all windows logs.. ie: process id, thread id..
going to use random UUID for hash/id -- however, this is rare and also implementing tag to be able to find this sort of thing if it happens -- can then go back through and find.
