### ISSUE TITLE
Installing on Ubuntu pip==1.5.4 distribution was not found...

### ISSUE THREAD

**Issue by frankangiolelli** [Cyb3rWard0g/HELK#18]
@Cyb3rWard0g 
Error message shows up in /var/log/helk-install.log
**Error: The 'pip==1.5.4' distribution was not found and is required by...**

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Fix:** 
sudo easy_install pip==1.5.4

After that, the installation went through fine and I got happy message:
**IT IS HUNTING SEASON!!!!!**

May want to consider  dropping that into the installation script. Cheers and thanks for the great work!

**Comment by Cyb3rWard0g** [comment]
Thank you @frankangiolelli ! Yes I was actually doing some testing earlier and ran into the same issue. I replaced it with Python-Pip and it install PIP 9.01. I will have an update for it today. Thank you for sharing and letting me know. I will close this when I update the script. 👍

**Comment by Cyb3rWard0g** [comment]
Fixed with https://github.com/Cyb3rWard0g/HELK/commit/25d4aa59963880762cf7dd2c0bdd8f64a32fb01c Thank you for pointing that out @frankangiolelli  👍
