### ISSUE TITLE
docker compose 1.23.2

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#185]
add latest version of docker to
https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_install.sh
and
https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_docker_install.sh

**Comment by Cyb3rWard0g** [comment]
fixed with https://github.com/Cyb3rWard0g/HELK/pull/193
