### ISSUE TITLE
tracking latest docker compose

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#186]
add to-do list to make sure each update/release (or find better way like just URL that points to latest)

**Comment by Cyb3rWard0g** [comment]
The latest comment in thread should work to get the latest version:
Latest comment: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c#gistcomment-2839301

I tested it and it works. I think this could be an easy fix and no need to wait until 6.7.

**Comment by neu5ron** [comment]
just tested, will add next release
