### ISSUE TITLE
no matching indices found

### ISSUE THREAD

**Issue by bsisco** [Cyb3rWard0g/HELK#19]
Getting this error for all indices on a fresh pull. I have a feeling it may be due to the Sysmon version on the monitored systems...I'm using the newest version (7.01) with the SwiftOnSecurity config with the mimikatz addition from ion...any thoughts would be apprecieated

**Comment by Cyb3rWard0g** [comment]
Hey @bsisco !! Are you using beats (Winlogbeat)?? if so, make sure that your config is pointing to Kafka output and the 3 Kafka brokers. the config should look like the one I have in the repo also as a template: https://github.com/Cyb3rWard0g/HELK/blob/master/winlogbeat/winlogbeat.yml . If you are already doing that. Go to your computer sending logs and run: winlogbeat.exe -e . That should show you if logs are making it to the HELK. Let me know what you get after going through those two verification steps. thank you!

**Comment by bsisco** [comment]
this is what i get with winlogbeat.exe -e
`2018/02/01 16:53:24.734037 beat.go:276: INFO winlogbeat start running.
2018/02/01 16:53:26.336034 log.go:36: INFO kafka message: [Initializing new client]
2018/02/01 16:53:26.338034 log.go:36: INFO client/metadata fetching metadata for all topics from broker [[10.0.0.5:9094]]
2018/02/01 16:53:27.397045 log.go:36: INFO Failed to connect to broker [[10.0.0.5:9094 dial tcp 10.0.0.5:9094: connectex: No connection could be made because the target machine actively refused it.]]: %!s(MISSING)
2018/02/01 16:53:27.404043 log.go:36: INFO kafka message: [client/metadata got error from broker while fetching metadata: dial tcp 10.0.0.5:9094: connectex: No connection could be made because the target machine actively refused it.]
2018/02/01 16:53:27.405047 log.go:36: INFO client/metadata fetching metadata for all topics from broker [[10.0.0.5:9093]]
2018/02/01 16:53:28.405500 log.go:36: INFO Failed to connect to broker [[10.0.0.5:9093 dial tcp 10.0.0.5:9093: connectex: No connection could be made because the target machine actively refused it.]]: %!s(MISSING)
2018/02/01 16:53:28.407501 log.go:36: INFO kafka message: [client/metadata got error from broker while fetching metadata: dial tcp 10.0.0.5:9093: connectex: No connection could be made because the target machine actively refused it.]
2018/02/01 16:53:28.409493 log.go:36: INFO client/metadata fetching metadata for all topics from broker [[10.0.0.5:9092]]
2018/02/01 16:53:29.416118 log.go:36: INFO Failed to connect to broker [[10.0.0.5:9092 dial tcp 10.0.0.5:9092: connectex: No connection could be made because the target machine actively refused it.]]: %!s(MISSING)
2018/02/01 16:53:29.418084 log.go:36: INFO kafka message: [client/metadata got error from broker while fetching metadata: dial tcp 10.0.0.5:9092: connectex: No connection could be made because the target machine actively refused it.]
2018/02/01 16:53:29.422082 log.go:36: INFO kafka message: [client/metadata no available broker to send metadata request to]
2018/02/01 16:53:29.423085 log.go:36: INFO client/brokers resurrecting [[3]] dead seed brokers`

**Comment by Cyb3rWard0g** [comment]
Ok so you have the config pointing to your HELK and your HELK IP is 10.0.0.5. 

A few things:
- Can you ping 10.0.0.5 from your box?
- What options did you use for your HELK? docker or straight bash script?
- Go to your HELK and check you have brokers connected to Zookeeper:
--- sudo /opt/helk/kafka/kafka_2.11-1.0.0/bin/zookeeper-shell.sh
------ ls /brokers/ids
------ CTR-C to exit
- Check your brokers properties and see if they got an IP assigned to the "advertised.listeners" section:
--- cat /opt/helk/kafka/kafka_2.11-1.0.0/config/server.properties
--- cat /opt/helk/kafka/kafka_2.11-1.0.0/config/server-1.properties
--- cat /opt/helk/kafka/kafka_2.11-1.0.0/config/server-2.properties

I hope that helps to see where the issue might be happening. Let me know thank you

**Comment by bsisco** [comment]
- Yes, i can ping from all boxes
- Docker install
- ` ls /brokers/ids [0, 1, 2]`

`cat config/server.properties  | grep advertised.listeners`
`#advertised.listeners=OUTSIDE://HELKIP:9093,INSIDE://:9092`
`advertised.listeners=PLAINTEXT://10.0.0.5:9092`
`cat config/server-1.properties  | grep advertised.listeners`
`#advertised.listeners=OUTSIDE://HELKIP:9095,INSIDE://:9094`
`advertised.listeners=PLAINTEXT://10.0.0.5:9093`
`cat config/server-2.properties  | grep advertised.listeners`
`#advertised.listeners=OUTSIDE://HELKIP:9097,INSIDE://:9096`
`advertised.listeners=PLAINTEXT://10.0.0.5:9094`

**Comment by Cyb3rWard0g** [comment]
Ok all looks good to me so far. Can you share your Winlogbeat configuration?

**Comment by bsisco** [comment]
[winlogbeat.txt](https://github.com/Cyb3rWard0g/HELK/files/1686608/winlogbeat.txt)

**Comment by Cyb3rWard0g** [comment]
Can you share your /var/log/helk-install.log from your docker install. Also can you run:
- sudo docker helk logs

Thank you

**Comment by Cyb3rWard0g** [comment]
I am also testing the dockerfile and Image pull on my end with fresh Ubuntu image.

**Comment by Cyb3rWard0g** [comment]
@bsisco I found the issue. I didnt expose the ports for option one when running the image. The imag e is built correctly but I forgot to expose those ports. Thank you for sharing this! I will adjust the main shell script and add the ports there. Give me 5 minutes. 👍

**Comment by bsisco** [comment]
Rock on! Thanks for the responses and updates...cheers!

**Comment by Cyb3rWard0g** [comment]
Thank you very much @bsisco !! I updated the main config and tested it. It works now. let me know if you have any other issues. Fixed this issue with the following commit https://github.com/Cyb3rWard0g/HELK/commit/3b17da481a1cc65c374da02a2550c8b91d7de48f

**Comment by Cyb3rWard0g** [comment]
I will close it when you have yours up and running well 👍

**Comment by bsisco** [comment]
We're up and running...thanks for the fix!

**Comment by Cyb3rWard0g** [comment]
Awesome thank you @bsisco ! 👍
