### ISSUE TITLE
elastalert using deprecated setting 

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#192]
right now elastalert is using a setting that will be removed in 7.0 -- right now it is not breaking anything in HELK 6.6.X testing - however it is outputting an insane amount of logs such as:
`[2019-02-21T05:51:18,050][WARN ][o.e.d.s.f.s.FetchSourceContext] [helk-1] Deprecated parameter [_source_include] used, expected [_source_includes] instead`

I think we should push forward with planned release, however will want to either note -- or find a way to suppress the error for now

https://www.elastic.co/guide/en/elasticsearch/reference/6.6/breaking-changes-6.6.html#_deprecate_literal__source_exclude_literal_and_literal__source_include_literal_url_parameters

**Comment by Cyb3rWard0g** [comment]
https://github.com/Yelp/elastalert/issues/2202

**Comment by Cyb3rWard0g** [comment]
https://github.com/Yelp/elastalert/commit/b942cb0e4cccda7905b649d9464bca40650bdc7e

**Comment by neu5ron** [comment]
this is good, going to close
