### ISSUE TITLE
Zeppelin Docker Container

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/HELK#199]
Create Dockerfile
Create Docker Image
Push Docker Image to Dockerhub

**Comment by OliverMorenoGonzalez** [comment]
Hello, have you thought about integrate Anaconda ? Anaconda integrate Jupyter and Zeppelin among other things.
Right now I am testing Anaconda package with docker if you agree I could translate the knowledge to this repo, when I finish my tests.

**Comment by Cyb3rWard0g** [comment]
Hey @OliverMorenoGonzalez ! Thank you for getting interested in this part of the project. Thats awesome I am new to Anaconda so I would really appreciate it! I rebuilt the basic Jupyter install last night with Anaconda and I dont know if I did it right lol, but I was able to get a Jupyter notebook just fine. I am translating the Lab and Hub extension that I already have via PIP to it tonight 👍 . I will share updates hopefully tomorrow at the end of the day. Any help is really appreciated . Thank you again!

**Comment by OliverMorenoGonzalez** [comment]
I am more or less new to Anaconda too, my approach ( I am just starting ) is install Anaconda image with docker compose and later launch some docker exec commands over Anaconda container.
I will stay watching in case there is an oportunity to improve or just help.

**Comment by Cyb3rWard0g** [comment]
Very nice @OliverMorenoGonzalez ! I have been testing with basic Anaconda installation first via Dockerfile using my own helk-spark-base image (only apache spark downloaded) and then adding packages and making sure I have the right url channels and all that to pull more packages 👍

**Comment by OliverMorenoGonzalez** [comment]
I found Miniconda is Anaconda with less packages It is also usefull in case you want more control over install only packages you need.

This is the command to run it.

`docker run -i -t -p 8888:8888 continuumio/miniconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip=0.0.0.0 --port=8888 --no-browser --allow-root"`

**Comment by Cyb3rWard0g** [comment]
thank you very much @OliverMorenoGonzalez for the information. I finally finished installing everything with miniconda3 and it all looks good. I am figuring out the `hub` option to have a login page for single-user since I am running my container with non-root account.

**Comment by OliverMorenoGonzalez** [comment]
I think the solution to this is create an environment with conda, next activate It, and later install what It is needed.
Tomorrow I can test it.
