### ISSUE TITLE
elastalert index for silenece

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#211]
**Describe the problem**
If user doesn't specify any elastalert silence configurations, then errors will be displayed in the elastalert error.
**What steps did you take trying to fix the issue?**
Rebuild
**How could we replicate the issue?**
Run HELK with elastalert
**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**
N/A
**What version of HELK are you using?**
latest as of 2019-02-24
**What OS are you using to host the HELK?**
Ubuntu 16
**Any additional context?**
other log files, pictures, etc.
![selection_001](https://user-images.githubusercontent.com/6351842/53306162-a733a280-3857-11e9-9866-52cbfc6b3c86.png)

The fix is just to create the index ahead of time (even if empty) during build process.

**Comment by Cyb3rWard0g** [comment]
mmmmm the index is created by default though. does that happen at the beginning?

![image](https://user-images.githubusercontent.com/9653181/53362151-862a8a80-3907-11e9-8ef5-b7c8df11c95f.png)

**Comment by neu5ron** [comment]
right so I see the index get created... 
and yup it does happen at the beginning -- haven't gotten an error since 2019-02-24 00:51:26 (UTC).
it happened 2,000,000+ times I just figured it was going to keep happening.

**Comment by neu5ron** [comment]
this isn't occuring anymore
