### ISSUE TITLE
is the elastalert server / container config usable with the elastalert kibana plugin 

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#214]
so an issue more of a question

i like the kibana elastalert plugin interface can i just throw that on there and it will work?

https://github.com/bitsensor/elastalert-kibana-plugin/releases

the sigmarules are comming ;) by the way

**Comment by Cyb3rWard0g** [comment]
hey @ssi0202 , I would think so. I have not tried that yet. That might add another dependency that could slow down updates that happen all the time from ELK, but it would be great to explore and see how stable it is. Do you have experience working with it?

**Comment by Cyb3rWard0g** [comment]
Closing this since there is nothing to fix.
