### ISSUE TITLE
Fail shipping to kafka with winlogbeat

### ISSUE THREAD

**Issue by Nicoflo22** [Cyb3rWard0g/HELK#216]
**Describe the problem**

I played with your docker images of HELK and everything went fine. Now i'm trying to recreate the same lab but I install and configure every component so that I can fully understand how it works. 

I can't send the logs to my kafka cluster. I also manually created a topic and tried to connect to logstash but I have an error. (explained below)

**What steps did you take trying to fix the issue?**

Checked the version compatibility but it seems ok (kafka_2.12-0.10.2.2), latest version of winlogbeat and ELK
Checked the config files but did not see any mistake
Looked on the internet but found nothing helpful

**What OS are you using to host the HELK?**

Debian 9.2.1 for my ELK but my cluster of 3 kafka brokers is composed of 3 nodes on 3 Debian 9.2.1 VMs. I also have a cluster of 3 zookeepers for HA also on Debian 9.2.1

**Any additional context?**

Here is my winlogbeat output config on my endpoint

![winlogbeat_to_kafka](https://user-images.githubusercontent.com/48251700/53815186-6e837f80-3f61-11e9-9d99-1953511bea7c.PNG)

Here are my winlogbeat logs when I try to send to kafka (it seems to connect and then disconnect forever, I show your 3 screenshots but then it kind of repeats forever)

![winlogbeat_logs](https://user-images.githubusercontent.com/48251700/53815045-2a907a80-3f61-11e9-9be2-a770075030ad.PNG)
![winlogbeat_logs2](https://user-images.githubusercontent.com/48251700/53815047-2a907a80-3f61-11e9-9892-a5362ed5b8ea.PNG)
![winlogbeatlogs3](https://user-images.githubusercontent.com/48251700/53815048-2a907a80-3f61-11e9-9125-3487dc9d56ea.PNG)

The topic was created as you can see 

![kafka_topic_winlogbeat](https://user-images.githubusercontent.com/48251700/53815208-80652280-3f61-11e9-94e6-8ecb71fd4024.PNG)

But when I try to read the data with kafka-console-consumer there is nothing.

Here are kafka logs:

![log_kakfa_erreur](https://user-images.githubusercontent.com/48251700/53815328-c1f5cd80-3f61-11e9-8e0c-b0ebbb427321.PNG)

And from my logstash side when I try to get data from the topic first_topic in which I manually added some data I get this error

![logstash_error](https://user-images.githubusercontent.com/48251700/53815550-231da100-3f62-11e9-968a-5bb8709c43bd.PNG)

Thank you for your help

**Comment by Cyb3rWard0g** [comment]
Hey @Nicoflo22 ! Can you share one of your Kafka brokers `server.properties` file? Also, I see your winlogbeat trying to send logs to kafka1, kafka2, kafka3? Instead of the IP addresses?

**Comment by Nicoflo22** [comment]
Thank you very much for you reply ! 

Here is the **_server.properties_** file from broker 3 (other brokers have their own **_broker.id_** and **_advertised.listeners_**)

![config_kafka_3](https://user-images.githubusercontent.com/48251700/53868923-6544f200-3ff7-11e9-9a01-4a8eb8363d71.PNG)

Yes actually on my machines I added this in /etc/hosts (i can ping kafka1, kafka2, ... from every machine)

![hosts](https://user-images.githubusercontent.com/48251700/53869033-ab01ba80-3ff7-11e9-9911-73eee1952f2c.PNG)

I also did this on my windows endpoints in _C:\Windows\System32\Drivers\etc\hosts._

**Comment by Nicoflo22** [comment]
For the option advertised listeners I tried to change kafka3 to 172.23.128.123 but it doesn't change anything (I mean now in winlogbeat logs it says 172.23.128.123 instead of kafka3 but it still says connection established and then it disconnects immediately and it loops that way)

**Comment by Cyb3rWard0g** [comment]
The errors that you are getting in Kafka side is because they cannot bind to the host IP address. You are using docker on each system right? you mentioned 3 Debian nodes with Kafka in each one of them.  Is the kafka application run via docker? (thats what it looks like to me based on your images). If so, I believe that 1) they are not binding to the host IP and 2) they cannot communicated with each other. I think that when you do docker in separate VMs you need something like docker swarm.

**Comment by Nicoflo22** [comment]
No I don't use docker I have one service running per VMs in a cloud environment.

I just built a new cluster of 3 kafka brokers, this time in a newer version (2.12-2.1.0)
As you can see now it looks like it's struggling in the beginning, and then it seems that the logs are being shipped.

![new_winlogbeat_logs](https://user-images.githubusercontent.com/48251700/53886348-20818100-4020-11e9-90f6-6d828ddf1694.PNG)
![new_winlogbeat_logs2](https://user-images.githubusercontent.com/48251700/53886349-211a1780-4020-11e9-913a-2b4283e0c419.PNG)
![new_winlogbeat_logs3](https://user-images.githubusercontent.com/48251700/53886350-211a1780-4020-11e9-9b54-98dca214f4d4.PNG)

 But when I launch the consumer.sh I get 0 messages


![new_winlogbeat_logs4](https://user-images.githubusercontent.com/48251700/53886541-8837cc00-4020-11e9-8f24-f6045191621a.PNG)


Thank you for these quick replies





By the way, forget about the logstash problem, I had given a wrong IP in the .conf

**Comment by Nicoflo22** [comment]
UPDATE: 

When i use

kafka-console-consumer --bootstrap-server localhost:9095 --from-beginning --topic SUJET_WINLOGBEAT **_--partition 0_**

instead of 

kafka-console-consumer --bootstrap-server localhost:9095 --from-beginning --topic SUJET_WINLOGBEAT 

I get the messages ! I don't know why the first command doesn't work though... If anyone knows the answer ?

I'll try now to make them go through logstash. Thank you very much for your help

**Comment by Cyb3rWard0g** [comment]
Closing this issue because you were able to get the logs to Kafka correct? @Nicoflo22
