### ISSUE TITLE
ERROR DURING INSTALLATION OF HELK

### ISSUE THREAD

**Issue by ehsanshaikh77** [Cyb3rWard0g/HELK#218]
![image](https://user-images.githubusercontent.com/26488637/54190608-f9222c80-44d5-11e9-97cb-d0be911469b1.png)

Can anyone help me in solving this error?

**Comment by ehsanshaikh77** [comment]
Please see the error in snap. @Cyb3rWard0g

**Comment by patricioparga** [comment]
Is that the output of /var/log/helk-install.log? If not, posting that might be more helpful

**Comment by Cyb3rWard0g** [comment]
yeah @ehsanshaikh77 , can you do `cat /var/log/helk-install.log` and send it over? Thank you @patricioparga

**Comment by ehsanshaikh77** [comment]
I had deleted virtual machine coz I was frustrated when HELK was not installing, but I have helk-install.log errror in my mind which was something that:----Pulling HELK-elasticsearch elasticsearch/elasticsearch dial tcp: lookup  on 192.168.65.1:53: read udp 192.168.65.1:53: i/o timeout

Sent from Yahoo Mail on Android 
 
  On Sat, 16 Mar 2019 at 1:49 AM, Roberto Rodriguez<notifications@github.com> wrote:   
yeah @ehsanshaikh77 , can you do cat /var/log/helk-install.log and send it over? Thank you @patricioparga

**Comment by Cyb3rWard0g** [comment]
timeout and elasticsearch being pulled from their docker registry. I wonder if their registry is down or some network issue?

**Comment by ehsanshaikh77** [comment]
What is the solution? 

Sent from Yahoo Mail on Android 
 
  On Sat, 16 Mar 2019 at 2:28 AM, Roberto Rodriguez<notifications@github.com> wrote:   
timeout and elasticsearch being pulled from their docker registry. I wonder if their registry is down or some network issue?

**Comment by Cyb3rWard0g** [comment]
I tested latest and it worked. I had to abort it because I disconnected from wi-fi by accident but it worked fine:

![image](https://user-images.githubusercontent.com/9653181/54465991-33006680-4754-11e9-9b1a-9b4f2addba03.png)

I believe the issue is in your network. Can you please try again the latest version and provide your helk-install.logs??? Thank you @ehsanshaikh77

**Comment by Cyb3rWard0g** [comment]
I also see that you might be running an old version since the messages in your screenshot look a little different.

**Comment by Cyb3rWard0g** [comment]
Let me know if it works for you @ehsanshaikh77 . Thank you!

**Comment by ehsanshaikh77** [comment]
![error](https://user-images.githubusercontent.com/26488637/54671348-1344b600-4b39-11e9-9c3a-092967c8b273.png)
Please check this @Cyb3rWard0g , I'm facing this error

**Comment by ehsanshaikh77** [comment]
again and again I'm trying, I'm facing this error.

**Comment by ehsanshaikh77** [comment]
please see the helk-install.log @Cyb3rWard0g 
![error](https://user-images.githubusercontent.com/26488637/54671609-95cd7580-4b39-11e9-8148-41a250e70a98.png)

**Comment by Cyb3rWard0g** [comment]
Please refer to https://github.com/Cyb3rWard0g/HELK/issues/224
