### ISSUE TITLE
Issue when install HELK on Centos/RHEL 6 & 7

### ISSUE THREAD

**Issue by bjames301** [Cyb3rWard0g/HELK#220]
During the yum install of httpd-tools the parameter -y is not passed.  This forces the system to hang and wait on user input for the install of the RPM. I have resolved this error by adding the -y value to the helk_install.sh script.

**Comment by Cyb3rWard0g** [comment]
Thank you @bjames301 . I am adding it to the next Hot-fix 👍 I appreciate it!

**Comment by bjames301** [comment]
Absolutely sir! This is a great project and Id love to get more involved.

**Comment by Cyb3rWard0g** [comment]
It is already in the script https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_install.sh#L160
