### ISSUE TITLE
Issue with helk_install.sh install on Centos/RHEL 6&7 docker related

### ISSUE THREAD

**Issue by bjames301** [Cyb3rWard0g/HELK#221]
The helk_install script does not enable docker via systemd (systemctl enable docker). Also it does not start the docker service (systemctl start docker). All docker commands fail because the service is not running. Resolved once the service is started.

**Comment by Cyb3rWard0g** [comment]
@bjames301 . I assume it needs `sudo systemctl start docker`? I have Ubuntu as the preferred platform, so I have not done much testing to get docker install in Centos. Can you provide some information in what worked for you? I can add it to the next release. Thank you! 👍

**Comment by bjames301** [comment]
sudo systemctl enable docker then sudo systemctl start docker.

Also I would love to be your tester for centos and rhel. I can aide in setting up jenkins build jobs to vet things!

**Comment by neu5ron** [comment]
@bjames301 
great info, thanks! You want to take a stab on making a pull request to the install script for rhel/centos?
adding this fix and also here are few more can add:
https://github.com/Cyb3rWard0g/HELK/issues/220
https://github.com/Cyb3rWard0g/HELK/issues/174

**Comment by bjames301** [comment]
Absolutely I’ll get something completed tonight!

**Comment by neu5ron** [comment]
no rush at all, take ur time. but we appreciate it!

**Comment by mspotlight** [comment]
@bjames301 Has there been any movement on this one? Thanks!
