### ISSUE TITLE
switch to java 11

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#225]
Java 11 is fully supported by elastic now - this will increase performance and also enables G1GC by default

**Comment by Cyb3rWard0g** [comment]
isn't that defined in the official images? Docker Images I mean.

**Comment by neu5ron** [comment]
im not %100 sure, its possible - but i think last time I checked it’s using
the hosts java image.
just note, for us to double check

**Comment by neu5ron** [comment]
looks like the docker images starting in 7 will have it. this is nice!
from 
https://www.elastic.co/blog/this-week-in-elasticsearch-and-apache-lucene-2019-04-12
“””
Starting with Elasticsearch 7, our default download includes a bundled JDK; if you’re using the bundled JDK or our official Docker image you will no longer need to worry about the JDK version.
“”
