### ISSUE TITLE
Existing ELK stack

### ISSUE THREAD

**Issue by camaro23** [Cyb3rWard0g/HELK#229]
Hey Team,

I already have a prebuilt ELK stack in my environment. Is there a base install option which enables me to skip the docker installs of the ELK stack and point filebeat to my prebuilt ELK cluster?

Thanks

**Comment by Cyb3rWard0g** [comment]
Hey @camaro23 ! HELk does not have those configs yet to use plain bash scripts. That is part of the cloud integration. I will have those ready for packer images.

**Comment by Cyb3rWard0g** [comment]
HELK comes with:
- ELK
- Kafka
- Nginx
- Jupyter
- Spark
If you already have the stack part, you will just have to adjust HELK properties to point to your elk stack. Remember HELK is ran as docker container for now so you will have to make sure the HELK parts can connect to your own elk stack.

**Comment by Cyb3rWard0g** [comment]
Closing this issue since there is nothing to fix and it is a custom build where user will have to adapt the project to its own custom stack.
