### ISSUE TITLE
Kibana, change elasticsearch.url setting

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#230]
This line needs changed to "elasticsearch.hosts" for 7.x release:
https://github.com/Cyb3rWard0g/HELK/blob/181c851a9ee1fd1f471120f03205048b4a3212f6/docker/helk-kibana/config/kibana.yml#L21

reference:
https://www.elastic.co/guide/en/kibana/7.x/breaking-changes-7.0.html#_literal_elasticsearch_url_literal_is_no_longer_valid

**Comment by Cyb3rWard0g** [comment]
Line in config does not need to be changed. It is not even used via the config file. HELK handles it via ENV Variable ;) https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-kibana/scripts/kibana-entrypoint.sh#L12 

Working on it...
