### ISSUE TITLE
murmur3 generated document_id has high collision probability

### ISSUE THREAD

**Issue by itsnotapt** [Cyb3rWard0g/HELK#231]
**Describe the problem**
The 32-bit implementation of murmur3 used for generating the document_id will create collisions, roughly 1 every ~100k events.

https://github.com/Cyb3rWard0g/HELK/blob/2ef0bd0bed1d6789b8fa834ac44f898a28868a1f/docker/helk-logstash/pipeline/0099-all-fingerprint-hash-filter.conf#L21-L22

https://github.com/Cyb3rWard0g/HELK/blob/2ef0bd0bed1d6789b8fa834ac44f898a28868a1f/docker/helk-logstash/pipeline/9950-winevent-sysmon-output.conf#L11

**Suggested Fix**
There is currently a PR for the murmur3 128bit, which would resolved this issue: https://github.com/logstash-plugins/logstash-filter-fingerprint/pull/42

I feel like this should be replaced with SHA1 for now, until murmur3 128bit has been implemented.

```
    target => "[@metadata][log_hash]"
    method => "SHA1",
    key => "Log analytics",
    base64encode => true
```

**Reproduction**
As a test, I changed the `target => "[@metadata][log_hash]"` to `target => "fingerprint"` and used the SHA1 fingerprint to generate the document `_id` as described above.

It took ~60k for the first collision to occur:
![image](https://user-images.githubusercontent.com/3096198/55831386-e3227e80-5b0a-11e9-901e-d4fbaedc5bf1.png)

**Comment by neu5ron** [comment]
nice find!
I had been thinking about this a lot before this was brought up, I think switching to sha1 is a good idea.
I would not base64encode the hash though.
I will update config later tonight

**Comment by itsnotapt** [comment]
Good point on the base64encode, I think my brain assumed this function existed because it was SHA1 binary instead of hex.

**Comment by itsnotapt** [comment]
Actually, now I think about it, there is value in using base64encode as it's technically more space efficient than hexdigest. Drop in the bucket, but explains why example code generally use it.

**Comment by Cyb3rWard0g** [comment]
Thats awesome @neu5ron @itsnotapt !

**Comment by neu5ron** [comment]
thanks again for pushing me to do this!
