### ISSUE TITLE
Support for an IP to domain resolution enrichment

### ISSUE THREAD

**Issue by itsnotapt** [Cyb3rWard0g/HELK#232]
Currently sysmon does not provide good domain resolutions for IP addresses. One solution would be to use the `Microsoft-Windows-DNS-Client` logs to capture all seen domain resolutions (type `A`/`AAAA`) and store them in a lookup cache.

See https://www.elastic.co/guide/en/logstash/current/plugins-filters-memcached.html

This solution is based on the work seen at https://github.com/0xrawsec/whids
See the blog https://rawsec.lu/blog/posts/2018/Jun/17/overcoming-domain-name-resolution-issue-in-sysmon/

Looks like @Cyb3rWard0g added this log recently to be indexed.
https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9961-winevent-dns-client-output.conf

Work todo:
- [ ] Parsing of the `Microsoft-Windows-DNS-Client` logs, which is would a good addition to HELK regardless
- [ ] Setup new docker container for memcache
- [ ] Add storing of domain resolutions to memcache in pipeline
- [ ] Add lookup for domain resolutions from memcache for IPs seen in pipeline

I'd like to volunteer to do the work, if no one else has started or have better solution.

**Comment by Cyb3rWard0g** [comment]
I like that @itsnotapt . Looks pretty straight forward based on the blog post you shared. Looking forward to seeing what you come up with. No one is working on that at the moment so I really appreciate your willingness to collaborate and improve the project

**Comment by itsnotapt** [comment]
Given that sysmon is adding natively next release, I don't see a need for this enhancement anymore.

https://twitter.com/markrussinovich/status/1137466538322042880?s=20

Welcome to close unless anyone has another use-case for it?

**Comment by neu5ron** [comment]
@itsnotapt yeah I would agree can close this,short of having to do enrichment on millions of documents for IP to domain resolution - as you have said, one could simply pivot between log sources.
