### ISSUE TITLE
ERROR: Could not run HELK via docker-compose file helk-kibana-analysis-basic.yml (Error Code: 1)

### ISSUE THREAD

**Issue by mspotlight** [Cyb3rWard0g/HELK#233]
**Describe the problem**
Getting the referenced error when running helk_install.sh. I have the proxy settings configured properly and I can get to all of the URLs via a browser but I get unauthorized authentication required error.
![Screenshot2](https://user-images.githubusercontent.com/30303880/55989222-9efebd80-5c73-11e9-9b11-ce807aba68db.jpg)

**What steps did you take trying to fix the issue?**
Checked all areas for proxy settings that I could think of

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
Current version on Github

**What OS are you using to host the HELK?**
Ubuntu 16.04.6 LTS
![Screenshot1](https://user-images.githubusercontent.com/30303880/55989051-652db700-5c73-11e9-9923-b3aa840fb952.jpg)

**Any additional context?**
other log files, pictures, etc.

**Comment by mspotlight** [comment]
Any thoughts??

**Comment by neu5ron** [comment]
can you try again? elastic did some major reform of their docker stuff over last week / few days+ with the whole 7.x release.

**Comment by neu5ron** [comment]
also, you mention all the proxy settings configured correctly -- does that mean you are running a proxy?

**Comment by mspotlight** [comment]
> also, you mention all the proxy settings configured correctly -- does that mean you are running a proxy?

Yes, we are running a proxy and as I indicated I have that proxy listed everywhere I can possible think of and as you can see I can get to the URL via a web browser. Anyway I will see about running the install again as suggested above as it seems elastic was doing some reforms.

**Comment by beardedcat** [comment]
I'm having similar issues with no proxy on Ubuntu 18.04 using both the Basic and Trial Versions
![image](https://user-images.githubusercontent.com/49662086/56172317-ccae7400-5f9d-11e9-8c29-e8e87b478f10.png)

**Comment by Cyb3rWard0g** [comment]
Hey @beardedcat @mspotlight do you guys still have the same issues with the latest updates? Please let me know whenever you have a chance. thank you!

**Comment by Cyb3rWard0g** [comment]
closing due to no responses.
