### ISSUE TITLE
No logs in Kibana

### ISSUE THREAD

**Issue by vivami** [Cyb3rWard0g/HELK#234]
Hi Roberto,

Trying out your awesome project, but running into the following problem:
`Discover: Could not locate that index-pattern-field (id: @timestamp)`. 
<img width="1073" alt="Screenshot 2019-04-12 at 13 50 18" src="https://user-images.githubusercontent.com/1519457/56035474-8dc4b800-5d2a-11e9-9e9f-495f921a19bd.png">

According to your docs this means I should wait a bit for incoming events to show up in Kibana. I've waited for some time now, but still the same error. 
```
vincent@helk:~/HELK/docker$ sudo ./helk_install.sh 
 
**********************************************
**          HELK - THE HUNTING ELK          **
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: v0.1.7-alpha04062019 **
** HELK ELK version: 6.6.1                  **
** License: GPL-3.0                         **
**********************************************
 
[HELK-INSTALLATION-INFO] HELK being hosted on a Linux box
[HELK-INSTALLATION-INFO] Available Memory: 7608 MBs
[HELK-INSTALLATION-INFO] You're using ubuntu version bionic
 
*****************************************************
*      HELK - Docker Compose Build Choices          *
*****************************************************
 
1. KAFKA + KSQL + ELK + NGNIX + ELASTALERT
2. KAFKA + KSQL + ELK + NGNIX + ELASTALERT + SPARK + JUPYTER
 
Enter build choice [ 1 - 2]: 1
[HELK-INSTALLATION-INFO] HELK build set to 1
[HELK-INSTALLATION-INFO] Set HELK elastic subscription (basic or trial): basic
[HELK-INSTALLATION-INFO] Set HELK IP. Default value is your current IP: 10.0.42.63
[HELK-INSTALLATION-INFO] Set HELK Kibana UI Password: hunting
[HELK-INSTALLATION-INFO] Verify HELK Kibana UI Password: hunting
[HELK-INSTALLATION-INFO] Installing htpasswd..
[HELK-INSTALLATION-INFO] Installing docker via convenience script..
[HELK-INSTALLATION-INFO] Installing docker-compose..
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 4120294
[HELK-INSTALLATION-INFO] Building & running HELK from helk-kibana-analysis-basic.yml file..
[HELK-INSTALLATION-INFO] Waiting for some services to be up .....
 
 
***********************************************************************************
** [HELK-INSTALLATION-INFO] HELK WAS INSTALLED SUCCESSFULLY                      **
** [HELK-INSTALLATION-INFO] USE THE FOLLOWING SETTINGS TO INTERACT WITH THE HELK **
***********************************************************************************
 
HELK KIBANA URL: https://10.0.42.63
HELK KIBANA USER: helk
HELK KIBANA PASSWORD: hunting
HELK ZOOKEEPER: 10.0.42.63:2181
HELK KSQL SERVER: 10.0.42.63:8088
 
IT IS HUNTING SEASON!!!!!
```

Can't see any errors in `/var/log/helk-install.log` and everything shows up 'done' in green.

Winlogbeat should be correctly configured:
<img width="989" alt="Screenshot 2019-04-12 at 13 56 34" src="https://user-images.githubusercontent.com/1519457/56035551-d11f2680-5d2a-11e9-8156-fd992018afdd.png">

Running `sudo docker exec -ti helk-kafka-broker /opt/helk/kafka/bin/kafka-console-consumer.sh --bootstrap-server helk-kafka-broker:9092 --topic winlogbeat --from-beginning` I can see the logs in Kafka:
```
{"@timestamp":"2019-04-12T11:41:29.346Z","@metadata":{"beat":"winlogbeat","type":"_doc","version":"7.0.0","topic":"winlogbeat"},"message":"The Computer Browser service entered the running state.","winlog":{"keywords":["Classic"],"task":"","computer_name":"WIN-B08Q0BG4R7A","provider_name":"Service Control Manager","event_data":{"param2":"running","Binary":"420072006F0077007300650072002F0034000000","param1":"Computer Browser"},"provider_guid":"{555908d1-a6d7-4695-8e1e-26931d2012f4}","channel":"System","event_id":7036,"api":"wineventlog","record_id":12614,"process":{"pid":496,"thread":{"id":3928}}},"event":{"kind":"event","code":7036,"created":"2019-04-12T11:41:29.631Z"},"log":{"level":"information"},"ecs":{"version":"1.0.0"},"host":{"name":"WIN-B08Q0BG4R7A"},"agent":{"id":"b222ee3b-2538-4679-bb6f-3af5ec9b77f3","version":"7.0.0","type":"winlogbeat","ephemeral_id":"b0bfcb9c-7e37-493e-891c-03e01f7a0c95","hostname":"WIN-B08Q0BG4R7A"}}
{"@timestamp":"2019-04-12T11:41:35.403Z","@metadata":{"beat":"winlogbeat","type":"_doc","version":"7.0.0","topic":"winlogbeat"},"message":"The Computer Browser service entered the stopped state.","host":{"name":"WIN-B08Q0BG4R7A"},"agent":{"hostname":"WIN-B08Q0BG4R7A","id":"b222ee3b-2538-4679-bb6f-3af5ec9b77f3","version":"7.0.0","type":"winlogbeat","ephemeral_id":"b0bfcb9c-7e37-493e-891c-03e01f7a0c95"},"ecs":{"version":"1.0.0"},"winlog":{"event_id":7036,"process":{"pid":496,"thread":{"id":3352}},"event_data":{"param1":"Computer Browser","param2":"stopped","Binary":"420072006F0077007300650072002F0031000000"},"record_id":12615,"task":"","provider_guid":"{555908d1-a6d7-4695-8e1e-26931d2012f4}","provider_name":"Service Control Manager","computer_name":"WIN-B08Q0BG4R7A","channel":"System","api":"wineventlog","keywords":["Classic"]},"event":{"kind":"event","code":7036,"created":"2019-04-12T11:41:35.637Z"},"log":{"level":"information"}}
```

I've ran some malicious actions on the host and I can see Logstash and ElasticSearch filling up:
<img width="890" alt="Screenshot 2019-04-12 at 13 50 43" src="https://user-images.githubusercontent.com/1519457/56035507-aa60f000-5d2a-11e9-88ea-a679fbc68a06.png">

I've restarted the Kibana contianer as well, but does not help. Any ideas I can try to resolve this issue?

Thanks a bunch in advance!

**Comment by GandhiWasHere** [comment]
Hey, same problem. glad to get some help +1

**Comment by lostInSpaceSomewhere** [comment]
same here as well...
data is going from sysmon to kafka, but can see where its failing from there
Anyone know where to test the path in the pipline of kafka --> logstash?

**Comment by conorjohnston** [comment]
Just to add to this, I am seeing the same behaviour too...

Everthing seems fine from winlogbeat > kafka > logstash >elasticsearch, but after hours still "No matching indices found:" in kibana

Any help much appreciated

**Comment by neu5ron** [comment]
thanks for posting this issue all.

Is everyone using winlogbeat version 7?

I verified with winlogbeat < 7 and it worked, then installed winlogbeat 7 and got the same issue as you all..

reference, its about time, that we have a catch all:
https://github.com/Cyb3rWard0g/HELK/issues/182#issuecomment-466721304

**Comment by neu5ron** [comment]
All, thank you for this submission - @Cyb3rWard0g and I are tracking the [field name changes in Winlogbeat 7](https://www.elastic.co/guide/en/beats/libbeat/current/breaking-changes-7.0.html#id-1.8.5.6.8) 
Until we upgrade HELK to support Elastic 7.x (which was released 2019-04-10) please use winlogbeat >= 6.x.
This is the latest version of winlogbeat (that is not version 7):
https://www.elastic.co/downloads/past-releases/winlogbeat-6-7-1

In the mean time, we also updated the Wiki.

**Comment by vivami** [comment]
Thanks Nate! I can confirm that this resolves my issue.

**Comment by Cyb3rWard0g** [comment]
Nice! Thank you for confirming @vivami 👍 Thank you for sharing your testing about Winlogbeat 7 @neu5ron

**Comment by conorjohnston** [comment]
Hi all, can confirm winlogbeat 7 was my issue too.

Everything working perfectly now

**Comment by Cyb3rWard0g** [comment]
Thank you @conorjohnston !

**Comment by lostInSpaceSomewhere** [comment]
Confirmed here as well
using 6.x works immediately

**Comment by baadie** [comment]
Same issue here. 6.7.1 latest version that works.

**Comment by Cyb3rWard0g** [comment]
Thank you @lostInSpaceSomewhere @baadie for testing it and confirming the Winlogbeat 7.0.0 issue. I hope I can get an updated Logstash config next week 👍 For now 6.7.1 is working fine 💯

**Comment by neu5ron** [comment]
this should be fixed in latest release. please reopen if that is not the case/scenario.
winlogbeat 6 and 7
