### ISSUE TITLE
Integrating Wazuh and HELK

### ISSUE THREAD

**Issue by dimaz1** [Cyb3rWard0g/HELK#235]
Hello

I wanna integrate wazuh and helk but I have problem with logstash and kafka config for this purpose. ( I install wazuh manager on other server and install wazuh-kibana-app on HELK server ) . 
can you provide solution for this ?

Thanks

**Comment by Cyb3rWard0g** [comment]
Hey @dimaz1 , unfortunately that is an integration that I do not support and it is not in the roadmap to support. If you get to work on the logstash and kafka integration with Wazuh, let me know and I can do some testing on my end. If it becomes a stable integration, that could be part of a custom branch (maybe). However, I do not see it as part of the master build. Wazuh has its own dependencies that will not be supported or tracked by me when I upgrade HELK to future versions. It is hard to maintain dependencies of HELK and dependencies created by other projects that are considered custom builds of the ELK piece of this project (from a HELK perspective). I hope you understand.

**Comment by reya9000** [comment]
Yeah Thanks
