### ISSUE TITLE
Feature Request: Jupyter - Powershell and R kernels

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [Cyb3rWard0g/HELK#236]
**Describe the problem**
- *heavy powershell user for IR/Hunting*.  Would really like to include powershell scripting in jupyter.  I know there may be limitations due to using Powershell core.
- Would also like to have R analytics language kernel.

**What version of HELK are you using?**
Latest

**What OS are you using to host the HELK?**

**Any additional context?**
Please :)

**Comment by Cyb3rWard0g** [comment]
Hey @lostInSpaceSomewhere !! Thank you for the suggestions. Im in the process of adding Scala for the next release. I will try to squeeze R in there. Regarding PowerShell, there is an early prototype https://github.com/vors/jupyter-powershell for it. I will add that too in the upcoming release ( I hope this weekend) 👍 That was in the to-do list for Kernels and I am happy to see others also interested in this part of the project 🎊

**Comment by Cyb3rWard0g** [comment]
Regarding Limitations of PowerShell Core, yeah that might not provide all the capabilities after reading. Can you provide some examples of the things that you would do and I will test those before installing those dependencies? Thank you @lostInSpaceSomewhere !

**Comment by Cyb3rWard0g** [comment]
@lostInSpaceSomewhere R kernel ready 😉 
![image](https://user-images.githubusercontent.com/9653181/56262418-ea0c4b00-6121-11e9-9f88-2d8ed2771dbb.png)

**Comment by lostInSpaceSomewhere** [comment]
@Cyb3rWard0g 
***awesome and thanks!***

I really envision leveraging this one platform to execute attack simulations (mitre att&ck, atomic red team, and beyond) from jupyter and watching the results.  Jupyter gives that ability to step through actions and executions, which eases learning for others and enables collaboration. 
beyond attack sim, there is additional hunting that can be executed from the notebooks leveraging pshell to endpoints.  Entering pssessions and executing actions, pulling data, etc. as well as IR stuff - email remediation, search, etc from pshell.

does that help?

**Comment by Cyb3rWard0g** [comment]
Ahh @lostInSpaceSomewhere then you will like the project I am releasing hopefully this weekend which will be a repo to support notebook technologies. Starting with Jupyter & Zeppelin. I was thinking on releasing one use case for Jupyter related to manipulate open source projects like empire and Caldera ;)

**Comment by lostInSpaceSomewhere** [comment]
@Cyb3rWard0g - sounds awesome. Look forward to it.

**Comment by lostInSpaceSomewhere** [comment]
@Cyb3rWard0g 
whats the best way to upgrade?  Usually there is a docker-compose down, and then run docker-compose up if the compose file pulls ":latest" versions of images

**Comment by Cyb3rWard0g** [comment]
@devdua was working on a script to perform an easy update. He is still working on the latest features he wanted to implement to handle environment variables and all that. 

What I usually do to is the following:
export ADVERTISED_LISTENER=<your helk IP>
then:
`sudo -E docker-compose -f <helk YML file> up --buil -d`

**Comment by Cyb3rWard0g** [comment]
Moving PowerShell Kernel request to project https://github.com/hunters-forge/notebooks-forge
