### ISSUE TITLE
HELK ELK Query Slow logs 

### ISSUE THREAD

**Issue by feedblade** [Cyb3rWard0g/HELK#238]
MY HELK have a little problems that slow query logs 
My VM resource have follow as, 
CPU = 4 core. 
HDD = 500 Gb. 
Memory = 64Gb . 
But I am facing query slow logs last 30 days and my logs have 3 days per days.

**Comment by neu5ron** [comment]
you probably need few more cores.

a single node doing ingest and search with that limited resources is probably the cause. or whether your storage is ssd or 10k or 15k SAS makes a big difference as well.

if not increasing, I would reach out for a contracted support/consulting.
