### ISSUE TITLE
How to change HELK container readonly to read/wrtie 

### ISSUE THREAD

**Issue by feedblade** [Cyb3rWard0g/HELK#239]
I would like to change some config file in HELK container but I cannot edit some config file in HELK container . May I know how to do it

**Comment by Cyb3rWard0g** [comment]
hey @feedblade , what configs are you trying to update?

**Comment by feedblade** [comment]
Example: i want to update the elasticsearch.yml in elasticsearch container.

**Comment by Cyb3rWard0g** [comment]
Can you update it locally outside of the container? in HELK/docker/helk-elasticsearch/ config/elasticsearch.yml ? https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-elasticsearch/config/elasticsearch.yml . Any change applied to it will be pushed to the Elasticsearch container. Does this answer your question?

**Comment by feedblade** [comment]
Thank you for your information and I appreciate for your support .

**Comment by Cyb3rWard0g** [comment]
Thank you @feedblade . Closing this issue then. Let me know if you have any other questions.
