### ISSUE TITLE
HELK on one node regular elasticstack on the other?

### ISSUE THREAD

**Issue by mathurin68** [Cyb3rWard0g/HELK#242]
Probably a stupid question... 

One cluster 2 nodes, test environment, playing with production data

There's no way I'm going to be able to get sysmon on all the boxes BUT I still want to play with HELK on our production data in a test environment. 

Is there any issues with having Helk on one node and just the regular elasticsearch on the other?  

Thank you!

**Comment by Cyb3rWard0g** [comment]
Hey @mathurin68 , so you would still use HELK elasticsearch and then have another ES instance right? And you want to use both ES as part of your cluster. Is this correct? If so, you will just have to make sure that your ES docker container can talk to your external ES node.

**Comment by mathurin68** [comment]
Perfect all I needed to know!!!
