### ISSUE TITLE
Kibana Dashboard Reporting 

### ISSUE THREAD

**Issue by feedblade** [Cyb3rWard0g/HELK#243]
May know which opensource plugin is the best for Kibana dashboard reporting

**Comment by Cyb3rWard0g** [comment]
Hey @feedblade , can you provide some more details on what you are trying to do?

**Comment by feedblade** [comment]
Kinbana Reporting plugin is paid version  so , I am trying to integrate with search-guard plugin . Recommend search-guard alternative plugin for Kibana. I want to use Role base access for ELK and Reporting feature

**Comment by Cyb3rWard0g** [comment]
Hey @feedblade , yeah search-guard would be a good for your free use cases. I do not support that plugin because it does not keep up with latest versions fast enough. I dont like to have the dependency there. Would love to hear how it would work for you. Thank you for the question!
