### ISSUE TITLE
Problem in restarting kibana service 

### ISSUE THREAD

**Issue by reya9000** [Cyb3rWard0g/HELK#244]
Hi

I want to restart kibana service in helk-kibana container with "systemctl restart kibana" but after executing this command I get below error : 

`Failed to get D-Bus connection: Operation no permitted`

How can I restart kibana service ?

**Comment by Cyb3rWard0g** [comment]
Hey @reya9000 ! Can you just `sudo docker restart helk-kibana` ?

**Comment by reya9000** [comment]
Thanks
