### ISSUE TITLE
Collect linux events

### ISSUE THREAD

**Issue by hakavod** [Cyb3rWard0g/HELK#248]
Good morning, some of you know that event collector I can install in Linux (Ubuntu) so I can send it to Kibana and visualize it in the DashBoard ?. If you had the link or how to do it, please share it.

**Comment by hakavod** [comment]
Good morning, some of you know that event collector I can install in Linux (Ubuntu) so I can send it to Kibana and visualize it in the DashBoard ?. If you had the link or how to do it, please share it.

**Comment by Cyb3rWard0g** [comment]
Hey @hakavod , You have a few options:
* https://www.elastic.co/products/beats/auditbeat
* https://github.com/richiercyrus/Venator and https://www.elastic.co/products/beats/filebeat
* https://jordanpotti.com/2018/02/16/elk-osquery-kolide-fleet-love/

Let me know if that helps. Sorry for the delay.

**Comment by hakavod** [comment]
Perfect, thank you very much dear.

**Comment by hakavod** [comment]
> Hey @hakavod , You have a few options:
> 
> * https://www.elastic.co/products/beats/auditbeat
> * https://github.com/richiercyrus/Venator and https://www.elastic.co/products/beats/filebeat
> * https://jordanpotti.com/2018/02/16/elk-osquery-kolide-fleet-love/
> 
> Let me know if that helps. Sorry for the delay.

Perfect, thank you very much dear.

**Comment by Cyb3rWard0g** [comment]
Np. Happy to help!

**Comment by 7manks** [comment]
Hi , i would like to add linux logs to helk , what i have done is use filebeat to transfer all logs to elasticsearch. is that OK?but not seem working . i am new to elk .  any suggestions?
