### ISSUE TITLE
HELK Installation Error: helk-nginx

### ISSUE THREAD

**Issue by DimitrisPr** [Cyb3rWard0g/HELK#255]
I am attempting to install HELK via `helk_install.sh` and the following error appears

`ERROR: for helk-nginx  Cannot start service helk-nginx: driver failed programming external connectivity on endpoint helk-nginx (4d6fdffaa03557d0fa9e2c5b77d026e59f9f97e915a77a4a6825167de6b66dc0): Error staCreating helk-logstash `

` Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
`

Do you have an idea why?
I stopped any nginx instances before the installation.

**Comment by Cyb3rWard0g** [comment]
Hey @DimitrisPr , are you running anything else besides HELK in your box?

**Comment by DimitrisPr** [comment]
Hi there!
No, I actually even removed docker before the installation.

**Comment by Cyb3rWard0g** [comment]
can you try the latest version that was pushed an hour ago?

**Comment by DimitrisPr** [comment]
I was just trying to install it again actually.
I just noticed the following error on the logs

`Get https://registry-1.docker.io/v2/cyb3rward0g/helk-nginx/manifests/0.0.7: Get https://auth.docker.io/token?scope=repository%3Acyb3rward0g%2Fhelk-nginx%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`

**Comment by DimitrisPr** [comment]
oh, excuse me, it was the old version Be right back.

**Comment by DimitrisPr** [comment]
@Cyb3rWard0g Installed successfully. Thank you!

**Comment by lokmanshrestha** [comment]
after reboot, when i try to  open helk same error occur how can we solve this problem
