### ISSUE TITLE
[Question] offline evtx file to HELK  

### ISSUE THREAD

**Issue by sidomir7** [Cyb3rWard0g/HELK#262]
Hi, I have question is there way how to send offline evtx files to HELK ? Use case is send and analyze logs from computer which is not sending logs with winlogbeat. 
I found only one solution, convert evtx files to json format and then send them with kafkacat. 
It is only solution for now, or I am missing something?

**Comment by neu5ron** [comment]
blog will be posted soon on this

**Comment by neu5ron** [comment]
Great timing! We just added support for this.
Instructions here, pretty simple - only 3 steps :)
https://www.perched.io/blog/2019/6/3/importing-evtx-files-into-helk-or-elastic

**Comment by beachcondo** [comment]
> Great timing! We just added support for this.
> Instructions here, pretty simple - only 3 steps :)
> https://www.perched.io/blog/2019/6/3/importing-evtx-files-into-helk-or-elastic

Link is dead, does anyone have these instructions?

**Comment by neu5ron** [comment]
@beachcondo93 https://svch0st.medium.com/replaying-windows-event-logs-against-elastalert-and-sigma-rules-using-helk-6db6edde6760
let me know if this helps
