### ISSUE TITLE
'Hello World' App with HELK

### ISSUE THREAD

**Issue by DimitrisPr** [Cyb3rWard0g/HELK#263]
Hi.
**This is a question, not an issue**

I am trying to get started with HELK. Basically what I want to do is to ship my first data from Kafka to Apache Spark (and then execute some classification algorithms on them). 

But I have no idea how to create this first 'Hello World' process.

Could you please give me some guidance?

Thanks in advance,
Dimitris

**Comment by Cyb3rWard0g** [comment]
Hey @DimitrisPr , I havent provided an example for it yet. However, you can use this post https://posts.specterops.io/threat-hunting-with-jupyter-notebooks-part-4-sql-join-via-apache-sparksql-6630928c931e and when you get to initialize the `READER`, instead of setting Elasticsearch in it, you have to initialize a Kafka streaming reader. Let me know if this makes sense. I have the Kafka JAR files in it so it should work.

**Comment by DimitrisPr** [comment]
@Cyb3rWard0g thank you so much. 
Once I figure out how the system works, I'll contribute to the project as much as I possibly can.

Thank you for this great tool.

P.S: If you don't mind, leave this issue open for future discussions.

Cheers

**Comment by DimitrisPr** [comment]
@Cyb3rWard0g As I understand, HELK is currently designed to read and process Windows Logs.

I am trying to create a phishing email real-time detection system. With that being said, I would like to read emails (in real time from an SMTP Server, save them on elasticsearch and then process them on Spark.

But here is the question. How do I import my data to HELK (so that they end up in elastic search?)

**Comment by angry-tony** [comment]
@Cyb3rWard0g you are so awesome!!
I was impressed to read your five-part series in specterops.io.
I am waiting for your last post....
When will you post your last it??
(Threat Hunting with Jupyter Notebooks Part 5: Documenting, Sharing and Running Threat Hunter Playbooks!)

**Comment by Cyb3rWard0g** [comment]
Hey @angry-tony , sorry for the late response. It will be released hopefully in two weeks. Thank you for the feedback
