### ISSUE TITLE
 Does someone help me with this?

### ISSUE THREAD

**Issue by hakavod** [Cyb3rWard0g/HELK#269]
Utilizo la última versión de Kibana 7.1.0
![Error_Kibana](https://user-images.githubusercontent.com/45045004/59064311-9986b380-886f-11e9-8e64-6f32fa6dc76d.png)

**Comment by Cyb3rWard0g** [comment]
Good evening @hakavod . Can you provide more details please? When did this happen? Can you provide output of the following commands:
```
sudo docker ps
```
```
sudo docker logs --follow helk-elasticsearch
sudo docker logs --follow helk-kibana
```
what option are you using? Basic license? Trial? What ELK + Spark + Jupyter + Elastalert?

**Comment by hakavod** [comment]
> Good evening @hakavod . Can you provide more details please? When did this happen? Can you provide output of the following commands:
> 
> ```
> sudo docker ps
> ```
> 
> ```
> sudo docker logs --follow helk-elasticsearch
> sudo docker logs --follow helk-kibana
> ```
> 
> what option are you using? Basic license? Trial? What ELK + Spark + Jupyter + Elastalert?

**Comment by hakavod** [comment]
> Good evening @hakavod . Can you provide more details please? When did this happen? Can you provide output of the following commands:
> 
> ```
> sudo docker ps
> ```
> 
> ```
> sudo docker logs --follow helk-elasticsearch
> sudo docker logs --follow helk-kibana
> ```
> 
> what option are you using? Basic license? Trial? What ELK + Spark + Jupyter + Elastalert?

In the dashboard, I use the basic version. I use option 2 of the installation process. Attached Logs.
![logs_kibana](https://user-images.githubusercontent.com/45045004/59081749-65ce7c80-88b5-11e9-8b6a-906d52ed9912.png)
![Logs_Elasticksearch](https://user-images.githubusercontent.com/45045004/59081750-65ce7c80-88b5-11e9-9758-8789826b1919.png)
![Error_Kibana](https://user-images.githubusercontent.com/45045004/59081751-65ce7c80-88b5-11e9-99db-f926abed0f33.png)

**Comment by Cyb3rWard0g** [comment]
Hey @hakavod . Can you try the latest HELK build? I pushed a few updates and a bug fix for ES memory. Let me know please. thank you!

**Comment by hakavod** [comment]
> Hola @hakavod . ¿Puedes probar la última versión de HELK? Presioné algunas actualizaciones y una corrección de errores para la memoria ES. Por favor házmelo saber. ¡gracias!


Thank you @Cyb3rWard0g 
![resultado](https://user-images.githubusercontent.com/45045004/59300997-2f4a8600-8c56-11e9-9bde-8b0836cadc7d.png)
, update and all agree. Thanks for the reply.

**Comment by Cyb3rWard0g** [comment]
Awesome thank you for the update @hakavod
