### ISSUE TITLE
process_granted_access (event_id 10) should likely be an Integer like process_id

### ISSUE THREAD

**Issue by itsnotapt** [Cyb3rWard0g/HELK#271]
This would allow bitstream calculations downstream e.g. `process_granted_access & 0x1000 != 0`

**Comment by Cyb3rWard0g** [comment]
I like this. I will have to do some additional testing for this.

**Comment by Cyb3rWard0g** [comment]
Once again thank you very much for the recommendations and updates :) I appreciate it!

**Comment by neu5ron** [comment]
I will add this in next release in the file
https://github.com/Cyb3rWard0g/HELK/blob/cfb9b98894f2c96ae4f0cb1fd2d0291f6dcea3fd/docker/helk-logstash/pipeline/1542-winevent-process-ids-conversions.conf
