### ISSUE TITLE
process_target_* (event_id 10) is inconsistent with OSSEM

### ISSUE THREAD

**Issue by itsnotapt** [Cyb3rWard0g/HELK#272]
OSSEM has listed them as `target_process_*`
I don't have any preference either way, both makes sense.

**Comment by Cyb3rWard0g** [comment]
Hey @itsnotapt Thank you so much for the help! I really appreciate your help on going over the Sysmon data and mapping schemas to OSSEM. Regarding this specific use case. I am still debating the naming convention for `target` fields. I will go over that this week and provide some definitions and reasons why we choose one syntax over the other. I will keep it as `process_target_` for now.
