### ISSUE TITLE
Elastic Docker not publishing port 9200

### ISSUE THREAD

**Issue by tee2015** [Cyb3rWard0g/HELK#281]
**Describe the problem**
Elastic Docker not publishing port 9200

is this not configured by default ?

**Comment by Cyb3rWard0g** [comment]
Hey @tee2015 , port 9200 is not exposed by default to anything outside of the Docker Containers network. It is exposed to all the HELK components but not to the physical network. For example, if you want to access ES from another container inside of HELK, you can do the following:
```
sudo docker exec -ti helk-kibana bash
```
to interact with the Kibana contaienr and then you can simply use regular ES APIs to send a POST or GET request to `helk-elasticsearch:9200`

**Comment by Cyb3rWard0g** [comment]
This is not a problem. It is done like that by design to not allow anyone interact with the ES database directly besides the HELK containers.

**Comment by Cyb3rWard0g** [comment]
Does this answer your question @tee2015 ?

**Comment by tee2015** [comment]
Hi Roberto, thank you for replying, Right yes that does make sense because I can see the port configured which made me have doubts about what's going on , and I suggest u to make a gitter channel or telegram for quick assistance and I heard this suggestion from multiple person, and I am happy to maintain it and assist in that. Also I am very impressed by this project and working on how to contribute in any aspects of it,and also keen to make it work on my end too and load data into it. Facing currently some issues also from winbeat. can we discuss the winbeat here ? or I open a new question? 

Regards.

**Comment by Cyb3rWard0g** [comment]
Thank you for the update @tee2015 ! Thank you very much for the feedback. Regarding Winlogbeat, yeas it would be good to open a new issue and I can help :) Also, regarding a channel, I have a slack channel I host and I would like to send an invite to you. What is your twitter handle? I can send you a private message and then you can provide the email address you would like me to send the invite to.

**Comment by tee2015** [comment]
@tarek_chalan_au

Thanks Roberto.
