### ISSUE TITLE
There are no logs in kibana

### ISSUE THREAD

**Issue by hakavod** [Cyb3rWard0g/HELK#287]
![Error](https://user-images.githubusercontent.com/45045004/59620759-44f6fa00-90f3-11e9-9998-1dbadeceb924.png)

Good morning, please your support. No logs are displayed in kibana. I installed HELK about a week ago

**Comment by neu5ron** [comment]
more than likely your hard drive is full.

can you verify?

**Comment by Cyb3rWard0g** [comment]
oh yeah I remember that message before and it was because I could not ingest any more logs. can you please check how much space you have left in ES?

**Comment by Cyb3rWard0g** [comment]
Hey @hakavod , let me know if you were able to check how much space you have left in Elasticsearch. Thank you!

**Comment by neu5ron** [comment]
going to close. reopen if you have any more information @hakavod 
thanks!
