### ISSUE TITLE
Elastalert not working

### ISSUE THREAD

**Issue by sidomir7** [Cyb3rWard0g/HELK#289]
Hi today I reinstall HELK during the installation I select option 2 for elastalert  docker. 
Everything is ok, but I can not see any logs in kibana (discover elastalert.... ).
Other views and dashboards are OK I can search and see all logs. 

On windows machine I crated few users, use powershell to making noice for sigma rules, even I ran **atomic red** framework and still 0 hits in this view (at least sticky key UAC bypass should be triggered ). 
I can see some data only in elasalert_status_status, but there I can see only all rules are hit 0 times. 
Can you help me ?

**Comment by oripka** [comment]
Hi, I just did a fresh install with the same option (2) and am running into the same issue.

**Comment by lsoumille** [comment]
This may be linked to Elastalert version. Only the beta release is compatible with ElasticSearch 7.0

**Comment by neu5ron** [comment]
all, thanks for the notes!

We did test elastalert with Elastic 7.x, and we ran into some issues that we thought we solved. However, this may not be the case indicated by the comments.

Before we can determine, are you able to output the logs from ElastAlert and Elasticsearch when you think the alerts are not showing but you recently ran an event/log that should happen.
@sidomir7 & @oripka can you send the output from the following commands
```
#### Get ElastAlert Logs
docker logs --tail 25 helk-elastalert

#### Get ElasticSearch Logs
docker logs --tail 25 helk-elasticsearch
```

**Comment by sidomir7** [comment]
Sorry for late respond. 


Elastic search logs: 

`"at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:394) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:378) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:394) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:381) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:293) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:305) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:292) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.search.SearchService.parseSource(SearchService.java:755) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.search.SearchService.createContext(SearchService.java:608) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:583) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:386) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.search.SearchService.access$100(SearchService.java:124) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:358) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:354) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1069) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]",
"at java.lang.Thread.run(Thread.java:835) ~[?:?]"] }
`

ElastAlert Logs: 
`WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
ERROR:root:Error running query: [u'Failed to parse query [(event_id:1 AND process_parent_name:"services.exe" AND NOT (process_path:"\\windows\\system32" OR process_path:"\\program files\\windows defender\\mpcmdrun.exe" OR "\\program files (x86)\\google\\update\\googleupdate.exe" OR "c:\\windows\\servicing"))]']
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
ERROR:root:Error running query: [u'Failed to parse query [(event_id:1 AND process_parent_name:"services.exe" AND NOT (process_path:"\\windows\\system32" OR process_path:"\\program files\\windows defender\\mpcmdrun.exe" OR "\\program files (x86)\\google\\update\\googleupdate.exe" OR "c:\\windows\\servicing"))]']
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
ERROR:root:Error running query: [u'Failed to parse query [(event_id:1 AND process_parent_name:"services.exe" AND NOT (process_path:"\\windows\\system32" OR process_path:"\\program files\\windows defender\\mpcmdrun.exe" OR "\\program files (x86)\\google\\update\\googleupdate.exe" OR "c:\\windows\\servicing"))]']
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
WARNING:root:doc_type has been deprecated since elasticsearch version 6 and will be completely removed in 8
ERROR:root:Error running query: [u'Failed to parse query [(event_id:1 AND process_parent_name:"services.exe" AND NOT (process_path:"\\windows\\system32" OR process_path:"\\program files\\windows defender\\mpcmdrun.exe" OR "\\program files (x86)\\google\\update\\googleupdate.exe" OR "c:\\windows\\servicing"))]']
`

**Comment by neu5ron** [comment]
@neu5ron note to self, this will be closed in upcoming implementation

**Comment by neu5ron** [comment]
@sidomir7 also in the  interim this should be fixed as well , I also apologize for late response -- somehow missed this completely...

**Comment by webhead404** [comment]
@neu5ron any updates on this?

**Comment by neu5ron** [comment]
this should all be fixed, sorry didn’t communicate fix when in a few weeks
ago.
let me know if this doesnt work

**Comment by webhead404** [comment]
@neu5ron after testing with a fresh install Elastalert is working.

**Comment by neu5ron** [comment]
awesome, thanks for the patience @webhead404 - again apologizes for delay/forgetting.
reach out if you have any suggestions or other questions.

Cheers
