### ISSUE TITLE
question windows firewall logs

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#291]
hi

i just got through the SANS SEC599 and there is alot on the build in windows firewall in the course, specifically using it to block AND alert on client to client traffic in general. To this end i have made som block rules with the firewall and now want to collect these in order to alert on any blocks/drops of packages by the client firewall. But before I get any further i would like to hear if you think this functionality is already covered with the current state of the HELK, without deploying sysmon to endpoints

i can see that this file is being logged that concern changes in the firewall rules, and rules that are blocking traffic 
Microsoft-Windows-Windows Firewall With Advanced Security/Firewall

the logfile i want to parse into HELK is the pfirewall.log file that i my view is needfull as it holds infor about what is being blocked or am i missing something obvious, in relation to this data already being covered by the HELK's capabilities.

**Comment by Cyb3rWard0g** [comment]
mmmm @ssi0202 , I have not the pfirewall.log before. Do you have any docs on it to read about it?
