### ISSUE TITLE
Question Auditbeat

### ISSUE THREAD

**Issue by SawWinnNaung** [Cyb3rWard0g/HELK#294]
Hi, I'm currently working as an infosec engineer in Myanmar. Do you have the plan to put Linux logs in further release feature?

**Comment by Cyb3rWard0g** [comment]
Hey @SawWinnNaung , yes that is something that I am planning on implement soon. I do not have an ETA, but it is a datasource that can be easily imported. Have you tried to do it yourself yet? or it is something that you would wait for? . If you get to it, please let me know how it was done and I can add it to the project. Thank you for the question.

**Comment by Cyb3rWard0g** [comment]
Closing this issue since there is nothing to fix here. Thank you for the question @SawWinnNaung
