### ISSUE TITLE
Kibana does not raise and it is because of the disk spac

### ISSUE THREAD

**Issue by hakavod** [Cyb3rWard0g/HELK#302]
Help, Kibana does not raise and it is because of the disk space. Is there a way to remove the indexes by console and not directly from the web? In which route do I find the logs to eliminate it?

**Comment by Cyb3rWard0g** [comment]
Hey @hakavod ! You can do it via the API. Here is the API docs. Let me know if that helps or not. Thank you @hakavod ! https://www.elastic.co/guide/en/elasticsearch/reference/current/indices.html

**Comment by hakavod** [comment]
![image](https://user-images.githubusercontent.com/45045004/61644883-2bede580-ac6b-11e9-8f24-99b6fa87a237.png)

thanks for answering. Through the web interface I can not make the change, since it does not load because there is no space left on the disk. You could indicate the route and / or the command that I can use to perform from a console connection.

**Comment by Cyb3rWard0g** [comment]
First lets identify all the indices and their size. Access the Elasticsearch docker container:

` sudo docker exec -ti helk-elasticsearch bash`

Then you can run the following:

`curl -XGET "http://localhost:9200/_cat/shards?v"`

**Comment by Cyb3rWard0g** [comment]
Once you identify the indices you want to delete, run the following:
`curl -XDELETE http://localhost:9200/myindex-1,myindex-2,myindex-3,myindex-4`

Can you share the output of the first command? (list indices and size)

**Comment by hakavod** [comment]
The result of executing the commands is as follows

![image](https://user-images.githubusercontent.com/45045004/61652678-1fbf5380-ac7e-11e9-8e6a-bde667a8716a.png)

![image](https://user-images.githubusercontent.com/45045004/61652730-3e254f00-ac7e-11e9-84a5-37d55415f108.png)

![image](https://user-images.githubusercontent.com/45045004/61652842-847aae00-ac7e-11e9-8806-1f4cf432de69.png)

**Comment by Cyb3rWard0g** [comment]
try `helk-elasticsearch:9200` instead of `localhost:9200`

**Comment by Cyb3rWard0g** [comment]
oh wait @hakavod , you need to do `sudo` when you do `docker exec -ti helk-elasticsearch bash`

**Comment by Cyb3rWard0g** [comment]
ohh @hakavod your `helk-elasticsearch` is restarting and it is not up. Can you do instead: `sudo docker ps`?

**Comment by hakavod** [comment]
when executing sudo docker ps, the following appears. Try to stop and restart, but still in the same state.

![image](https://user-images.githubusercontent.com/45045004/61657960-e55bb380-ac89-11e9-89ac-9edcf6f4fe96.png)

**Comment by Cyb3rWard0g** [comment]
can you share Elasticsearch logs? `sudo docker logs helk-elasticsearch` . Also, how do you know the issue is disk size again that your containers are not up?

**Comment by hakavod** [comment]
> can you share Elasticsearch logs? `sudo docker logs helk-elasticsearch` . Also, how do you know the issue is disk size again that your containers are not up?

I apologize dear Cyb3rWard0g for just responding, what they chose was to reinstall HELK again.
