### ISSUE TITLE
Discover: Could not locate that index-pattern-field (id: @timestamp)

### ISSUE THREAD

**Issue by Trolldemorted** [Cyb3rWard0g/HELK#303]
**Describe the problem**
After a clean start (option 4, basic), Kibana shows some issues:
![grafik](https://user-images.githubusercontent.com/10261186/61521331-45472580-aa10-11e9-8546-83b180085eb4.png)

I assume those are not intended?

**How could we replicate the issue?**
- acquire a fresh ubuntu18 vm
- run helk_install.sh, select 4 + basic
- open kibana

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
d10231195d2fbf65a31548088ad09c4906538dff

**What OS are you using to host the HELK?**
ubuntu18 server LTS

**Comment by Cyb3rWard0g** [comment]
Hey @Trolldemorted ! Do you have any data being sent to HELK? Those two error messages show when you have no data in your HELK. Usually after you do a fresh install and go to `Discover`, you will get that if there is nothing in Elasticsearch. Let me know. Thank you!

**Comment by Trolldemorted** [comment]
I just piped one winlogbeat into it, so I assume it doesn't use the winmon index. Thanks for the quick response and sorry for bothering you!
