### ISSUE TITLE
Error Installing HELK on CentOS 7

### ISSUE THREAD

**Issue by francescouk** [Cyb3rWard0g/HELK#307]
[HELK-INSTALLATION-INFO] Building & running HELK from helk-kibana-notebook-analysis-alert-basic.yml file..
 * ERROR: Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error Code: 1).

**Comment by Cyb3rWard0g** [comment]
would you mind checking what version of docker-compose you have? I have seen that issue when docker-compose is already installed and it is an old version or it was installed via SNAP.

**Comment by francescouk** [comment]
[root@localhost /]# docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by Cyb3rWard0g** [comment]
aha yeah thats old. Would you mind doing `locate docker-compose`? I wonder if it was installed with snap.

**Comment by Cyb3rWard0g** [comment]
wait mmmm the version is not that old. Can you check the `helk-install.log` file in /var/log/helk_install.log? and provide the output? Please

**Comment by francescouk** [comment]
`Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.unicamp.br
 * extras: ftp.unicamp.br
 * updates: ftp.unicamp.br
Resolving Dependencies
--> Running transaction check
---> Package httpd-tools.x86_64 0:2.4.6-89.el7.centos.1 will be installed
--> Processing Dependency: libaprutil-1.so.0()(64bit) for package: httpd-tools-2.4.6-89.el7.centos.1.x86_64
--> Processing Dependency: libapr-1.so.0()(64bit) for package: httpd-tools-2.4.6-89.el7.centos.1.x86_64
--> Running transaction check
---> Package apr.x86_64 0:1.4.8-3.el7_4.1 will be installed
---> Package apr-util.x86_64 0:1.5.2-6.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package           Arch         Version                     Repository     Size
================================================================================
Installing:
 httpd-tools       x86_64       2.4.6-89.el7.centos.1       updates        91 k
Installing for dependencies:
 apr               x86_64       1.4.8-3.el7_4.1             base          103 k
 apr-util          x86_64       1.5.2-6.el7                 base           92 k

Transaction Summary
================================================================================
Install  1 Package (+2 Dependent packages)

Total download size: 286 k
Installed size: 584 k
Downloading packages:
--------------------------------------------------------------------------------
Total                                               47 kB/s | 286 kB  00:06     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : apr-1.4.8-3.el7_4.1.x86_64                                   1/3 
  Installing : apr-util-1.5.2-6.el7.x86_64                                  2/3 
  Installing : httpd-tools-2.4.6-89.el7.centos.1.x86_64                     3/3 
  Verifying  : httpd-tools-2.4.6-89.el7.centos.1.x86_64                     1/3 
  Verifying  : apr-util-1.5.2-6.el7.x86_64                                  2/3 
  Verifying  : apr-1.4.8-3.el7_4.1.x86_64                                   3/3 

Installed:
  httpd-tools.x86_64 0:2.4.6-89.el7.centos.1                                    

Dependency Installed:
  apr.x86_64 0:1.4.8-3.el7_4.1           apr-util.x86_64 0:1.5.2-6.el7          

Complete!
Adding password for user helk
# Executing docker install script, commit: 6bf300318ebaab958c4adc341a8c7bb9f3a54a1a
+ sh -c 'yum install -y -q yum-utils'
+ sh -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sh -c 'yum makecache'
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.unicamp.br
 * extras: ftp.unicamp.br
 * updates: ftp.unicamp.br
Metadata Cache Created
+ '[' -n '' ']'
+ sh -c 'yum install -y -q docker-ce'
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/docker-ce-stable/packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
Public key for containerd.io-1.2.6-3.3.el7.x86_64.rpm is not installed
Importing GPG key 0x621E9F35:
 Userid     : "Docker Release (CE rpm) <docker@docker.com>"
 Fingerprint: 060a 61c5 1b55 8a7f 742b 77aa c52f eb6b 621e 9f35
 From       : https://download.docker.com/linux/centos/gpg
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
100   617    0   617    0     0     97      0 --:--:--  0:00:06 --:--:--   185

  2 11.2M    2  253k    0     0  35075      0  0:05:34  0:00:07  0:05:27 35075
 19 11.2M   19 2277k    0     0   271k      0  0:00:42  0:00:08  0:00:34 2019k
 37 11.2M   37 4317k    0     0   461k      0  0:00:24  0:00:09  0:00:15 2075k
 54 11.2M   54 6204k    0     0   601k      0  0:00:19  0:00:10  0:00:09 2037k
 70 11.2M   70 8142k    0     0   719k      0  0:00:15  0:00:11  0:00:04 2011k
 88 11.2M   88  9.9M    0     0   824k      0  0:00:13  0:00:12  0:00:01 2009k
100 11.2M  100 11.2M    0     0   884k      0  0:00:12  0:00:12 --:--:-- 2014k
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
`

**Comment by francescouk** [comment]
Dunno if this is a solution, but I´ve used this command:
sudo service docker stop then
sudo service docker start
and then tested again with success.

**Comment by Cyb3rWard0g** [comment]
So did you install docker again?

**Comment by francescouk** [comment]
No, I didnt! Has been installed by the Helk package. The only thing I´ve done was stop the docker service and then started again after the errors reproduced.
After that, the helk install finished without errors.

**Comment by Cyb3rWard0g** [comment]
ahhh interesting. I wonder if Docker Service was not then enabled? Would you mind providing the /var/log/helk_install.log file please?/

**Comment by francescouk** [comment]
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.unicamp.br
 * extras: ftp.unicamp.br
 * updates: ftp.unicamp.br
Resolving Dependencies
--> Running transaction check
---> Package httpd-tools.x86_64 0:2.4.6-89.el7.centos.1 will be installed
--> Processing Dependency: libaprutil-1.so.0()(64bit) for package: httpd-tools-2.4.6-89.el7.centos.1.x86_64
--> Processing Dependency: libapr-1.so.0()(64bit) for package: httpd-tools-2.4.6-89.el7.centos.1.x86_64
--> Running transaction check
---> Package apr.x86_64 0:1.4.8-3.el7_4.1 will be installed
---> Package apr-util.x86_64 0:1.5.2-6.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package           Arch         Version                     Repository     Size
================================================================================
Installing:
 httpd-tools       x86_64       2.4.6-89.el7.centos.1       updates        91 k
Installing for dependencies:
 apr               x86_64       1.4.8-3.el7_4.1             base          103 k
 apr-util          x86_64       1.5.2-6.el7                 base           92 k

Transaction Summary
================================================================================
Install  1 Package (+2 Dependent packages)

Total download size: 286 k
Installed size: 584 k
Downloading packages:
--------------------------------------------------------------------------------
Total                                               47 kB/s | 286 kB  00:06     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : apr-1.4.8-3.el7_4.1.x86_64                                   1/3 
  Installing : apr-util-1.5.2-6.el7.x86_64                                  2/3 
  Installing : httpd-tools-2.4.6-89.el7.centos.1.x86_64                     3/3 
  Verifying  : httpd-tools-2.4.6-89.el7.centos.1.x86_64                     1/3 
  Verifying  : apr-util-1.5.2-6.el7.x86_64                                  2/3 
  Verifying  : apr-1.4.8-3.el7_4.1.x86_64                                   3/3 

Installed:
  httpd-tools.x86_64 0:2.4.6-89.el7.centos.1                                    

Dependency Installed:
  apr.x86_64 0:1.4.8-3.el7_4.1           apr-util.x86_64 0:1.5.2-6.el7          

Complete!
Adding password for user helk
# Executing docker install script, commit: 6bf300318ebaab958c4adc341a8c7bb9f3a54a1a
+ sh -c 'yum install -y -q yum-utils'
+ sh -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
Loaded plugins: fastestmirror
adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sh -c 'yum makecache'
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.unicamp.br
 * extras: ftp.unicamp.br
 * updates: ftp.unicamp.br
Metadata Cache Created
+ '[' -n '' ']'
+ sh -c 'yum install -y -q docker-ce'
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/docker-ce-stable/packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
Public key for containerd.io-1.2.6-3.3.el7.x86_64.rpm is not installed
Importing GPG key 0x621E9F35:
 Userid     : "Docker Release (CE rpm) <docker@docker.com>"
 Fingerprint: 060a 61c5 1b55 8a7f 742b 77aa c52f eb6b 621e 9f35
 From       : https://download.docker.com/linux/centos/gpg
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
100   617    0   617    0     0     97      0 --:--:--  0:00:06 --:--:--   185

  2 11.2M    2  253k    0     0  35075      0  0:05:34  0:00:07  0:05:27 35075
 19 11.2M   19 2277k    0     0   271k      0  0:00:42  0:00:08  0:00:34 2019k
 37 11.2M   37 4317k    0     0   461k      0  0:00:24  0:00:09  0:00:15 2075k
 54 11.2M   54 6204k    0     0   601k      0  0:00:19  0:00:10  0:00:09 2037k
 70 11.2M   70 8142k    0     0   719k      0  0:00:15  0:00:11  0:00:04 2011k
 88 11.2M   88  9.9M    0     0   824k      0  0:00:13  0:00:12  0:00:01 2009k
100 11.2M  100 11.2M    0     0   884k      0  0:00:12  0:00:12 --:--:-- 2014k
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Adding password for user helk
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Adding password for user helk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100   617    0   617    0     0     99      0 --:--:--  0:00:06 --:--:--   147

  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  4 11.2M    4  492k    0     0  68258      0  0:02:52  0:00:07  0:02:45  472k
 22 11.2M   22 2532k    0     0   302k      0  0:00:37  0:00:08  0:00:29 1253k
 39 11.2M   39 4572k    0     0   486k      0  0:00:23  0:00:09  0:00:14 1494k
 57 11.2M   57 6612k    0     0   634k      0  0:00:18  0:00:10  0:00:08 1625k
 75 11.2M   75 8635k    0     0   760k      0  0:00:15  0:00:11  0:00:04 1725k
 92 11.2M   92 10.3M    0     0   857k      0  0:00:13  0:00:12  0:00:01 2037k
100 11.2M  100 11.2M    0     0   894k      0  0:00:12  0:00:12 --:--:-- 2007k
./helk_install.sh: line 322: docker-compose: command not found
Adding password for user helk
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Adding password for user helk
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Adding password for user helk
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Adding password for user helk
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Adding password for user helk
Creating network "docker_helk" with driver "bridge"
Creating volume "docker_esdata" with local driver
Pulling helk-elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:7.1.0)...
7.1.0: Pulling from elasticsearch/elasticsearch
Pulling helk-kibana (docker.elastic.co/kibana/kibana:7.1.0)...
7.1.0: Pulling from kibana/kibana
Pulling helk-logstash (docker.elastic.co/logstash/logstash:7.1.0)...
7.1.0: Pulling from logstash/logstash
Pulling helk-nginx (cyb3rward0g/helk-nginx:0.0.7)...
0.0.7: Pulling from cyb3rward0g/helk-nginx
Pulling helk-zookeeper (cyb3rward0g/helk-zookeeper:2.2.0)...
2.2.0: Pulling from cyb3rward0g/helk-zookeeper
Pulling helk-kafka-broker (cyb3rward0g/helk-kafka-broker:2.2.0)...
2.2.0: Pulling from cyb3rward0g/helk-kafka-broker
Pulling helk-ksql-server (confluentinc/cp-ksql-server:5.1.3)...
5.1.3: Pulling from confluentinc/cp-ksql-server
Pulling helk-ksql-cli (confluentinc/cp-ksql-cli:5.1.3)...
5.1.3: Pulling from confluentinc/cp-ksql-cli
Pulling helk-elastalert (cyb3rward0g/helk-elastalert:0.2.4)...
0.2.4: Pulling from cyb3rward0g/helk-elastalert
Creating helk-elasticsearch ... 
[1A[2K
Creating helk-elasticsearch ... [32mdone[0m
[1BCreating helk-kibana        ... 
[1A[2K
Creating helk-kibana        ... [32mdone[0m
[1BCreating helk-nginx         ... 
Creating helk-logstash      ... 
[2A[2K
Creating helk-nginx         ... [32mdone[0m
[2B[1A[2K
Creating helk-logstash      ... [32mdone[0m
[1BCreating helk-elastalert    ... 
Creating helk-zookeeper     ... 
[2A[2K
Creating helk-elastalert    ... [32mdone[0m
[2B[1A[2K
Creating helk-zookeeper     ... [32mdone[0m
[1BCreating helk-kafka-broker  ... 
[1A[2K
Creating helk-kafka-broker  ... [32mdone[0m
[1BCreating helk-ksql-server   ... 
[1A[2K
Creating helk-ksql-server   ... [32mdone[0m
[1BCreating helk-ksql-cli      ... 
[1A[2K
Creating helk-ksql-cli      ... [32mdone[0m
[1B
