### ISSUE TITLE
Standardize process_id name and (SubjectLogonId(4742) with user_logon_id(4662)) in HELK

### ISSUE THREAD

**Issue by jsecurity101** [Cyb3rWard0g/HELK#310]
Standardize Names:
 process_id 

SubjectLogonId(4742) with user_logon_id(4662)

**Comment by neu5ron** [comment]
nice!

if I may ask, what isn't labeled process_id correctly?

**Comment by neu5ron** [comment]
note for self / @Cyb3rWard0g / @Cyb3rPanda 
probably need to add to OSSEM, ontop of the fix mentioned.
here are following fields not mapped:

1. SubjectDomainName
1. SubjectLogonId
1. SubjectUserName
1. SubjectUserSid
1. TargetDomainName
1. TargetSid
1. TargetUserName
1. PasswordLastSet (probably not a big deal not to map, but just putting in here for reference/documentation)

maybe a bigger thing would be to map these things that have clearly defined Subject/Target in a catch all (after the more specific EventID transforms)?

**Comment by jsecurity101** [comment]
I believe process_id is a `winlogbeat(ism)`. 
Today when I was working on some JOIN functions with Jupyter Notebooks & Apache Spark, and couldn't use the `process_id` to join them. 

Also the fields you mentioned above, are not standardized across the board. (Just did a PR to OSSEM to fix this issue. At least for events 4662 and 4742: https://github.com/Cyb3rWard0g/OSSEM/pull/40)

**Comment by jsecurity101** [comment]
Update for this - This should actually be `LogonId` to fit the actual data inside of the event.

**Comment by neu5ron** [comment]
as we discussed offline, 4624 and 4662 were already done. Thanks for the OSSEM PR and I am going to work on 4742 now.
### 4624:
"SubjectLogonId" => "reporter_logon_id"
https://github.com/Cyb3rWard0g/HELK/blob/9a2812fa43f3ad01bc58badddaed4d8deeaa0863/docker/helk-logstash/pipeline/1532-winevent-security-filter.conf#L41

### 4662:
"SubjectLogonId" => "user_logon_id"
https://github.com/Cyb3rWard0g/HELK/blob/9a2812fa43f3ad01bc58badddaed4d8deeaa0863/docker/helk-logstash/pipeline/1532-winevent-security-filter.conf#L238

**Comment by neu5ron** [comment]
https://github.com/Cyb3rWard0g/HELK/commit/5c88da5baa59b3db44fbd3cae711f2adee67b7dd
