### ISSUE TITLE
Event ID 5145 - SubjectLogonID data standardization

### ISSUE THREAD

**Issue by jsecurity101** [Cyb3rWard0g/HELK#311]
PR to OSSEM for EventID 5145: https://github.com/Cyb3rWard0g/OSSEM/pull/40

HELK needs to have `SubjectLogonID` to be standardized. Similar to 4624 Events.

**Comment by jsecurity101** [comment]
Might be good to check data is being standardized for 4624 in terms of user_logon_id, as well. I am not seeing SubjectLogonID for 4624 event's as well.

**Comment by jsecurity101** [comment]
Update for this - This should actually be `LogonId` to fit the actual data inside of the event.

**Comment by neu5ron** [comment]
as we discussed offline, 4624 and 5145  were already done. Thanks for the OSSEM PR for 5145.
Going to close this, feel free to reopen if you need. 
### 4624:
"SubjectLogonId" => "reporter_logon_id"
https://github.com/Cyb3rWard0g/HELK/blob/9a2812fa43f3ad01bc58badddaed4d8deeaa0863/docker/helk-logstash/pipeline/1532-winevent-security-filter.conf#L41

### 5145:
"SubjectUserSid" => "user_sid"
https://github.com/Cyb3rWard0g/HELK/blob/9a2812fa43f3ad01bc58badddaed4d8deeaa0863/docker/helk-logstash/pipeline/1532-winevent-security-filter.conf#L726
