### ISSUE TITLE
Please consider adding a method to stop containers.

### ISSUE THREAD

**Issue by s3curetty** [Cyb3rWard0g/HELK#313]
This is a feature addition request.
When you use helk_install.sh for container deployment, the docker compose file is set to restart always.
To get the containers to stop you have to read the bash file, make sense of which docker-compose file has been used to create the containers and use a similar command to stop the containers.
`docker-compose -f *your-choice-trial/basic down*`
This might get tricky for users not used to docker/docker-compose.
For me the containers kept spawning after PC restarts, which wasn't what I expected.
Then I ran the `helk_remove_containers.sh` script, just to find my images missing.
Would suggest an easier way to stop the docker-compose stack while not removing the images.

**Comment by tee2015** [comment]
Hi U should be able to stop the containers without using the remove script.the remove is to totally uninstall the helk, There are some open source frameworks to control containers U can use them with a GUI interface.

**Comment by s3curetty** [comment]
That is a good idea too. But I would recommend a simple way to put down the containers that we start.
For eg we can add this to the output after creation of containers
`docker-compose stop your-yamlfile-here.yml`

**Comment by Cyb3rWard0g** [comment]
Thank you @s3curetty for the suggestion !

**Comment by s3curetty** [comment]
Thanks for implementing it :dancer:
