### ISSUE TITLE
No visuals on kibana

### ISSUE THREAD

**Issue by zexedex** [Cyb3rWard0g/HELK#318]
Hello,
I'm having troubles seeing any visuals on kibana :
1- I installed HELK just like it's in the description 
2- I changed the IP@ to 127.0.0.1 since i don't have a fixed one, for that i followed the "update kafka broker" section in the wiki => works fine apparently, no problems.
3- i installed filebeat and gave it the following configuration : 
#==== Filebeat inputs ====
filebeat.inputs:
-type: log
  enabled: true
  paths:
     - /var/log/*.log
output.logstash:
  hosts: ["127.0.0.1:5044"]

That's it, i didn't change anything in the logstash, elasticseach config files ! 
The filebeat seems to work fine, but i can't seem to see any data on kibana ! 

Nothing to see on docker helk-logstash nor helk-elasticseach or kibana !

**Comment by neu5ron** [comment]
logstash wouldn't be listening on localhost, its in a docker and you would need to have filebeat send to the routable (non-loopback IP). Let me know if that helps

**Comment by neu5ron** [comment]
@zexedex going to close this. Please update if something else occurs or you have any new information.

cheers
