### ISSUE TITLE
ElastAlert rule "helk_sysmon_cmdline_file_creation" does not work as intended

### ISSUE THREAD

**Issue by Trolldemorted** [Cyb3rWard0g/HELK#320]
**Describe the problem**
Said rule uses the following filter:
```yaml
filter:
- query:
    query_string:
      query: (event_id:11 AND file_name:*.cmdline)
```
However this query does not match filenames like `c:\foo\bar.cmdline`, I guess because dots are special characters. Omitting the dot (`file_name:*cmdline`) works, but that would create false positives because it is less precise.

**What steps did you take trying to fix the issue?**
I tried to find out what dots do and how to espace them, but was unsuccessful.

**How could we replicate the issue?**
Start HELK with elastalert, set up sysmon&winlogbeat, create a .cmdline file, observe `elastalert_status` or manually execute the query.

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
d10231195d2fbf65a31548088ad09c4906538dff

**What OS are you using to host the HELK?**
Ubuntu 18

**Comment by neu5ron** [comment]
@Trolldemorted can you try `file_name.keyword`

this will give you the raw/unparsed field.

**Comment by neu5ron** [comment]
@Trolldemorted let me know if the following does not suffice, and (not being sarcastic) thanks for bringing this up.. It's rare people ask these questions.

Use the "file_name.keyword" for the time being as a new release of HELK is being published soon. Therefore, I just tested this rule on the pending release just to make sure. Seems between the temporary fix (if there is an actual break) and the pending release - we should be OK.
![Selection_001-4](https://user-images.githubusercontent.com/6351842/64155831-97e27280-ce01-11e9-8376-d619426653ca.jpg)

**Comment by neu5ron** [comment]
feel free to re-open if you see fit.
