### ISSUE TITLE
Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error code:1))

### ISSUE THREAD

**Issue by Ol1ver26** [Cyb3rWard0g/HELK#324]
**Describe the problem**
got error code 1 while install HELK option 4

**What steps did you take trying to fix the issue?**
i did stop option 4 installation and try to install option2 instead and options 2 was install successfully.

**What version of HELK are you using?**
newest one i think, just clone the HELK

**What OS are you using to host the HELK?**
Ubuntu 18.04 in VM

**Any additional context?**
other log files, pictures, etc.
![image](https://user-images.githubusercontent.com/36188251/64346843-3bb46400-d036-11e9-82ee-07623ce7fc44.png)

**Comment by marcin-github** [comment]
Run docker-compose with mentioned file as parameter manually and check error returned by dcoker-compse.

**Comment by Cyb3rWard0g** [comment]
Hey @Ol1ver26 , can you provide the contents of /var/log/helk-install.log? That should tell you why it failed. Thank you!

**Comment by Ol1ver26** [comment]
> Hey @Ol1ver26 , can you provide the contents of /var/log/helk-install.log? That should tell you why it failed. Thank you!

it doesn't seem to work, cuz i havent install option4 properly.

![image](https://user-images.githubusercontent.com/36188251/64398890-d26e3880-d0a9-11e9-9619-a986a59bf403.png)

**Comment by Ol1ver26** [comment]
> docker-compose with mentioned file

Could you explain in more detail about this? i am new to the field. thank you

**Comment by marcin-github** [comment]
I'm also newbie with HELK. if you run instalator using `bash -x` you will see debug log from bash. And you will see:
```
[HELK-INSTALLATION-INFO] Building & running HELK from helk-kibana-notebook-analysis-alert-basic.yml file..
+ docker-compose -f helk-kibana-notebook-analysis-alert-basic.yml up --build -d
+ ERROR=1
+ '[' 1 -ne 0 ']'
+ echoerror 'Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error Code: 1).'
+ printf ' * ERROR: Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error Code: 1).\n'
 * ERROR: Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error Code: 1).
+ exit 1
```
As you can see docker-compose quit with error so run manually:
```
docker-compose -f helk-kibana-notebook-analysis-alert-basic.yml up --build -d
```

In my case it looks like this:
```
# docker-compose -f helk-kibana-notebook-analysis-alert-basic.yml up --build -d
WARNING: The ADVERTISED_LISTENER variable is not set. Defaulting to a blank string.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

In my case, after installing docker from installer, docker wasn't started.

**Comment by Ol1ver26** [comment]
> I'm also newbie with HELK. if you run instalator using `bash -x` you will see debug log from bash. And you will see:
> 
> ```
> [HELK-INSTALLATION-INFO] Building & running HELK from helk-kibana-notebook-analysis-alert-basic.yml file..
> + docker-compose -f helk-kibana-notebook-analysis-alert-basic.yml up --build -d
> + ERROR=1
> + '[' 1 -ne 0 ']'
> + echoerror 'Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error Code: 1).'
> + printf ' * ERROR: Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error Code: 1).\n'
>  * ERROR: Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error Code: 1).
> + exit 1
> ```
> 
> As you can see docker-compose quit with error so run manually:
> 
> ```
> docker-compose -f helk-kibana-notebook-analysis-alert-basic.yml up --build -d
> ```
> 
> In my case it looks like this:
> 
> ```
> # docker-compose -f helk-kibana-notebook-analysis-alert-basic.yml up --build -d
> WARNING: The ADVERTISED_LISTENER variable is not set. Defaulting to a blank string.
> ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
> 
> If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
> ```
> 
> In my case, after installing docker from installer, docker wasn't started.

Just saw this, i have a try tomorrow see if its work,thanks

**Comment by neu5ron** [comment]
@Ol1ver26 please reopen if this is still an issue. thanks!

**Comment by Ol1ver26** [comment]
Thanks for the help, but I am using option 2 instead of 4 and didn’t come with the same issue, and option 2 meets my need as well.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
发件人: Nate Guagenti <notifications@github.com>
发送时间: Monday, October 7, 2019 5:56:16 AM
收件人: Cyb3rWard0g/HELK <HELK@noreply.github.com>
抄送: Litian Chen <l95.chen@connect.qut.edu.au>; Mention <mention@noreply.github.com>
主题: Re: [Cyb3rWard0g/HELK] Could not run HELK via docker-compose file helk-kibana-notebook-analysis-alert-basic.yml (Error code:1)) (#324)


@Ol1ver26<https://github.com/Ol1ver26> please reopen if this is still an issue. thanks!

―

**Comment by mojomasterchris** [comment]
I had this problem, it turned out docker service "auplink" was crashing.  

I uninstalled docker 

`sudo apt-get purge -y docker-engine docker-ce`
`sudo apt-get autoremove -y --purge docker-engine docker-ce`

`sudo rm -rf /var/lib/docker /etc/docker`
`sudo rm /etc/apparmor.d/docker`
` sudo groupdel docker`
`sudo rm -rf /var/run/docker.sock`

then ran helk_install.sh and everything worked.

**Comment by wasya2020** [comment]
Hi all. 
Make sure you install HELK on a clean Ubuntu machine. 
In my case I had some binding ports busy from other services installed and it was blocking the installation.
Cheers.
