### ISSUE TITLE
Firewalld Command Failed to create NAT CentOS 7

### ISSUE THREAD

**Issue by francescouk** [Cyb3rWard0g/HELK#326]
**firewalld[18408]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.4 -d**

**systemctl stop firewalld**

**systemctl status firewalld**

**last version**

**CentOS 7**

**Comment by Cyb3rWard0g** [comment]
We ask for ports to be open and accessible according to the docker-compose templates being used. Troubleshooting network setups is outside of the scope of the development of HELK at the moment.
