### ISSUE TITLE
If docker is installed but docker-compose is not then the install will fail

### ISSUE THREAD

**Issue by BasicInfoSec** [Cyb3rWard0g/HELK#33]
If docker is installed but docker compose is not then the install will fail. I have submitted pull request #32 with a possible fix for you to consider, if it finds docker it will check foir docker compose and if it is not found it will be installed.

**Comment by Cyb3rWard0g** [comment]
@BasicInfoSec sorry for the delay. I fixed the docker & docker-compose installation steps with the latest commit https://github.com/Cyb3rWard0g/HELK/commit/c43eaa08e30f01a886023e8b772562d72f1bb81c

Thank you for pointing that out!! 👍
