### ISSUE TITLE
Index Pattern update for Elastalert Status

### ISSUE THREAD

**Issue by nopsecurity** [Cyb3rWard0g/HELK#332]
First of all - loving HELK - great work!

Is there a way to pull in all of the fields from the elastalerts_status index to be able to make dashboards? When a rule is matched, and i open the log in the elastalerts_status index, the fields display properly (match_body.type, match_body.host_name) but they have the error that they dont exist in the index pattern.

Usually i would refresh the index pattern and they would be ok, but refreshing doesn't populate these fields in the index which prevents creating dashboards etc with the match_body data. 

Thank you!

**Comment by Cyb3rWard0g** [comment]
Hey @nopsecurity , thank you very much for the feedback! I believe the mapping is provided by Elastalert directly: https://github.com/Yelp/elastalert/blob/b65b9718075677b313e42561eab2eb524534ea01/elastalert/es_mappings/6/elastalert_status.json . However, I believe that should be taken care of now by this template that @neu5ron just pushed: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/output_templates/01-elastalert-status.json. Whenever you have a chance @neu5ron , could you confirm this? Thank you in advance!

**Comment by neu5ron** [comment]
@nopsecurity is this an upgraded cluster/HELK instance? like from elastic 5.x > 6.x or 6.x > 7.x?

**Comment by nopsecurity** [comment]
Hey guys, thanks for the response

This wasnt an upgrade - installed last week (thursday) using the latest repo

**Comment by neu5ron** [comment]
cool, ok couple quick questions that will help me figure out which solution (ideas) to use for best course of action  

1) do you need to keep your existing elastalert? or is this just a test environment? I am not referring to the data in the logs-* index (just elastalert_status is all).
2) which install option did you use? (1,2,3,4)
3) are you using basic or trail license?

**Comment by nopsecurity** [comment]
1. no need to keep the logs
2. option 4
3. trial

**Comment by neu5ron** [comment]
awesome, this "should" be easy then.
1. `docker stop helk-elastalert`
2.  go to kibana > dev tools > and run `DELETE /elastalert*`
3. follow the below in order
```
cd HELK
# get latest elastalert things and the elasticsearch template for elastalert
sudo git pull https://github.com/Cyb3rWard0g/HELK

# Make sure to change these variables to match your environment :)
export ADVERTISED_LISTENER="$ReplaceWithHELKIP"
export ELASTIC_PASSWORD="$ReplaceWithPreviousElasticPasswordYouUsed"
export KIBANA_UI_PASSWORD="$ReplaceWithPreviousKibanaPasswordYouUsed"

# this will rebuild elastalert
docker-compose -f helk-kibana-notebook-analysis-alert-trial.yml up --build -d

```

**Comment by nopsecurity** [comment]
Good news is the above process went without issue (had to run docker-compose with sudo -E)
Bad news - no longer ingesting logs

**Comment by nopsecurity** [comment]
Working great now - thanks!

**Comment by neu5ron** [comment]
awesome!

glad I got those fixes in this morning

also thanks for the kind words in the first message. let us know if you
have any feedback or anything else.
cheers
