### ISSUE TITLE
error in docker/helk-logstash/Dockerfile in Centos 7

### ISSUE THREAD

**Issue by Fedora-Man** [Cyb3rWard0g/HELK#333]
I this the last line is of the file (docker/helk-logstash/Dockerfile) has an error:

COPY --chown=logstash:logstash config/logstash.yml /usr/share/logstash/config/logstash.yml

It should be:
COPY config/logstash.yml /usr/share/logstash/config/logstash.yml

**Comment by Cyb3rWard0g** [comment]
Hey @fedoracoffee , if I take the `--chown` command, Logstash cannot read my files somehow. I tested it before and thats why I added it there. However, have you tried to run it without `--chown`? if so, was Logstash able to read the logstash config? I havent looked into that in a while. Thank you in advance!

**Comment by fedoracoffee** [comment]
This the error I got while installing if chown is there:

Step 5/5 : COPY --chown=logstash:logstash config/logstash.yml /usr/share/logstash/config/logstash.yml
Service 'helk-logstash' failed to build: Unknown flag: chown

**Comment by fedoracoffee** [comment]
My mistake I installed docker before running the installation  and it was older version. The installation script installed the right version but then I got:

./helk_install.sh: line 323: docker-compose: command not found

I will install docker-compose and try again

**Comment by Cyb3rWard0g** [comment]
Ok . Docker-compose is also installed by the script but I wonder why it didnt go through. can you check the /var/log/helk-install.log? https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_install.sh#L208-L218

**Comment by fedoracoffee** [comment]
I think it is installed by the script but because /usr/local/bin (where it is installed) not in the execution path in Centos it is not found.

The PATH variable in Centos 7 is "/sbin:/bin:/usr/sbin:/usr/bin"

**Comment by Cyb3rWard0g** [comment]
ahhh got it good call. I will add that to the script then. Thank you very much for providing the details needed for it to be fixed in the next commit. I will keep it open until the commit is pushed.

**Comment by neu5ron** [comment]
this should be a non-issue with the new updates. please re-open if there is still an issue
