### ISSUE TITLE
helk update script needs love at some point

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#335]
for one it has old build options... 
probably some other things in there too

**Comment by Cyb3rWard0g** [comment]
Yup, It was built by @devdua , but I believe he is not supporting it anymore, so it is something that will be updated later. Not for this release. thank you man! I will keep it open to track progress.

**Comment by devdua** [comment]
I apologise, I've been really busy with my new job and settling down in a new city that I couldn't complete the new version of the script. I definitely haven't abandoned it and will submit a PR very soon. Please excuse the delay!
________________________________

**Comment by Cyb3rWard0g** [comment]
Updated 5 months ago. https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_update.sh . Can be re-opened for further modifications or updates to it.
