### ISSUE TITLE
Elastalert additional fields

### ISSUE THREAD

**Issue by nopsecurity** [Cyb3rWard0g/HELK#336]
Is it possible to to create 2 extra fields in the elastalert_status section? One for mitre_technique_id and one for mitre_technique_name?

If this is possible, we could add technique names and IDs to the sigma rules which can be visualized in a mitre dashboard. Im currently doing this with sysmon through rule names, but being able to do it through sigma/elastalerts would be much more versatile.

 I am looking at modifying the elastalert.py script to pull in additional data, but have not been successful so far. 

Thanks!

**Comment by neu5ron** [comment]
@nopsecurity yeah definetly interested in seeing what you come up with / works.Thanks for being open to do that!

**Comment by Cyb3rWard0g** [comment]
Hey @nopsecurity , I will close this issue for now. Thank you for the initiative. Let me know if you end up working on this via scripted fields as you mentioned before. We will review the PR if it is something you would like to contribute to the project. Thank you in advance!

**Comment by nopsecurity** [comment]
Hi Roberto

My apologies for not replying sooner. I'm not sure what is the best way to
contact you, but I ended up modifying all of the sigma rules within helk to
include mitre tactic, technique and description. I created a custom alerter
which worked better than scripted fields that pulls in all of the MITRE
information on alert. I have a MITRE dashboard I created that im using as
my primary dashboard that kind of gives me a high level view of threats
coming in. When time permits, I will make a PR so you can take a look.

Keep up the great work, your project has been fantastic.
