### ISSUE TITLE
Feature Request: Expose elasticsearch to allow plug and play dashboard setup 

### ISSUE THREAD

**Issue by smit1759** [Cyb3rWard0g/HELK#337]
Are you able to modify the dockerfile to allow the exposure of port 9200 of the elasticsearch instance? This will allow the "plug and play" features in the "Add Data to Kibana" page.

**Comment by neu5ron** [comment]
this should be possible in next release, later this month or so.
For now you can use Kibana or bash/cli into the helk-elasticsearch container
