### ISSUE TITLE
Catch-All: Suggestion to remove helk_parsed from logic

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/HELK#342]
**Describe the problem**
I was sending ETW events via Winlogbeat, and they got the tag "helk_parsed" via this config https://github.com/Cyb3rWard0g/HELK/blob/540c79b6624fd179625e0a6c38c659f15bf66794/docker/helk-logstash/pipeline/9998-catch_all-output.conf. However, I had not defined the Output file yet. I was expecting it to go to catch all. I dont know if it is necessary or not lol Please @neu5ron let me know if it makes sense or if I should not be lazy and set up my output config if I want to ingest new data LOL

**Comment by Cyb3rWard0g** [comment]
I meant this config: https://github.com/Cyb3rWard0g/HELK/blob/540c79b6624fd179625e0a6c38c659f15bf66794/docker/helk-logstash/pipeline/1010-winevent-winlogbeats-filter.conf

**Comment by neu5ron** [comment]
I think you are right, I had a enhancement/fix for this upcoming release.
However, let me double check tonight and if so I will push to the master
branch

**Comment by Cyb3rWard0g** [comment]
Nicee thank you man!

**Comment by Cyb3rWard0g** [comment]
Updated in https://github.com/Cyb3rWard0g/HELK/pull/343
