### ISSUE TITLE
CORS / elasticsearch.yml mounted read-only

### ISSUE THREAD

**Issue by torrycrass** [Cyb3rWard0g/HELK#344]
**Describe the problem**
I am attempting to allow CORS to use a 3rd party interface with elasticsearch. This requires CORS to be enabled (based on instructions and tool error)

```
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Attempting to modify the `elasticsearch.yml` file inside the docker doesn't work.

```
[root@8455145a29bb config]# tail -n 7 elasticsearch.yml.backup  >> elasticsearch.yml
bash: elasticsearch.yml: Read-only file system
```

Checking `cat /proc/mounts` indicates the file itself is read-only (see below). How can I update this configuration file to add the necessary lines?

```
/dev/sda1 /usr/share/elasticsearch/config/elasticsearch.yml ext4 ro,relatime,errors=remount-ro,data=ordered 0 0
```

**What steps did you take trying to fix the issue?**
After various attempts to manipulate the file (all failing of course). I attempted to remount the file as read-write like you would with file systems. This failed as well.

```
[root@8455145a29bb config]# mount -o remount,rw /dev/sda1 /usr/share/elasticsearch/config/elasticsearch.yml
mount: mount point /usr/share/elasticsearch/config/elasticsearch.yml is not a directory
```

**How could we replicate the issue?**
Attempt to edit the elasticsearch.yml file inside the docker.

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**
N/A

**What version of HELK are you using?**
Latest via git repo

**What OS are you using to host the HELK?**
Ubuntu 16.04 LTS

**Any additional context?**
other log files, pictures, etc.

**Comment by torrycrass** [comment]
While the read-only issue still exists (I'm guessing on purpose). There are just simply no instructions on how to do these simple things, *probably why I'm struggling so badly* =) So I've added them here and am closing this issue.

The way to address this is to update the `elasticsearch.yml` file located in your user directory HELK folder structure:

`/HELK/docker/helk-elasticsearch/config/elasticsearch.yml`

Once the lines are appropriately added restart the docker container to get them to take effect.

`docker restart CONTAINERID`

Then you can check that they took effect by:

1. Log into container bash: `docker exec -u 0 -it CONTAINERID /bin/bash`
2. Show the last of your config if you added it to the bottom of the file: `tail config/elasticsearch.yml`
3. In my case it output the following which indicated the settings were used:

```
[root@8455145a29bb elasticsearch]# tail config/elasticsearch.yml
#https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-settings.html
xpack.monitoring.collection.enabled: true

# ---------------------------------- CORS -----------------------------------

http.cors.allow-origin: '*'
http.cors.enabled: true
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: true
```
4. exit the docker container `exit`

**Comment by neu5ron** [comment]
thanks for the notes @torrycrass 
sorry you had to figure out the hard way.. yeah anytime elasticsearch.yml is edited (in any elastic install), requires a restart of the service/container/process/etc..
