### ISSUE TITLE
ElastAlert HELK rule is causing false positives

### ISSUE THREAD

**Issue by webhead404** [Cyb3rWard0g/HELK#345]
**Describe the problem**
The ElastAlert rule for Windows-wevtutil-clear-logs_0 doesn't work as intended. It fires when 
`c:\windows\system32\wevtutil.exe sl microsoft-windows-sysmon/operational` is ran. 

**What steps did you take trying to fix the issue?**
Rewriting the query to just reference the "cl" and not "set-log" or sl. 

**How could we replicate the issue?**

Use wevutil.exe with the sl argument on any log.

**What version of HELK are you using?**
Latest

**What OS are you using to host the HELK?**
Ubuntu

![image](https://user-images.githubusercontent.com/8658818/65696019-254e6680-e03e-11e9-8b72-5eb653ba102e.png)

**Comment by Cyb3rWard0g** [comment]
Hey @webhead404 , thank you for opening this issue. How did you re-write the query ? The query is `event_id:1 AND process_command_line:wevtutil AND process_command_line:cl` right? that picks the other events too?

**Comment by webhead404** [comment]
@webhead404 yes sir! As you can see in the screenshot. The query returns sl as well as cl. It triggers on sl more often that cl. I haven't got the query fixed yet.

**Comment by Cyb3rWard0g** [comment]
mmm. can you try .keyword? and the wildcards around?

**Comment by webhead404** [comment]
Like this? It works!

<img width="622" alt="Screen Shot 2019-09-30 at 10 56 41 PM" src="https://user-images.githubusercontent.com/8658818/65933057-ace8fc00-e3d5-11e9-8191-741dc747e643.png">

**Comment by neu5ron** [comment]
@Cyb3rWard0g you OK with removing this rule? this is actually covered in more specific in SIGMA rule https://github.com/Neo23x0/sigma/blob/d14f5c34368410612652e1c69a6d6de908b0cfac/rules/windows/process_creation/win_etw_trace_evasion.yml

**Comment by Cyb3rWard0g** [comment]
Yes that works for me @neu5ron . Yeah @webhead404 , would you mind confirming that it triggered on the other ones please?

**Comment by webhead404** [comment]
@Cyb3rWard0g @neu5ron it triggers on the second one but not the first.

**Comment by webhead404** [comment]
This returned zero results. `(process_command_line.keyword:"* cl *\/Trace*") OR (process_command_line.keyword:"* clear\-log *\/Trace*") OR (process_command_line.keyword:"* sl* \/e\:false*") OR (process_command_line.keyword:"* set\-log* \/e\:false*")`

**Comment by Cyb3rWard0g** [comment]
sounds good. It makes sense. Ok I will remove the custom one from HELK.

**Comment by Cyb3rWard0g** [comment]
Thank you very much @webhead404 !

**Comment by webhead404** [comment]
Thank you sir for clarifying! Happy to help.
