### ISSUE TITLE
src_ip_addr and dst_ip_addr not indexed as keyword

### ISSUE THREAD

**Issue by nopsecurity** [Cyb3rWard0g/HELK#348]
src_ip_addr and dst_ip_addr are only indexed as ip and not keyword in the current build. This becomes an issue in some of the network based sysmon rules where there are wildcards to filter out specific ip ranges.

As a workaround i updated rules to include subnet ranges (127.0.0.0/8 instead of 127.*)

**Comment by neu5ron** [comment]
hmmm... interesting conclusion! thanks for sharing this too!

I would really dislike to store IPs as both keyword and IP (thats are large dupicate...) 
where is the fix you implemented? Is it online?

**Comment by nopsecurity** [comment]
Yup fair enough. Im currently going through the ruleset and manually testing/making changes. When im done i can post the full ruleset if that would be benificial. Some rules in the sigmac conversion are using uppercase in .keyword search fields (which are normalized to lower case) so they dont work. The majority of rules are good though - big fan of the HELK project!

**Comment by nopsecurity** [comment]
sigma_sysmon_malware_backconnect_ports.yml
sigma_sysmon_rdp_reverse_tunnel.yml
sigma_sysmon_rundll32_net_connections.yml

For reference, these three rules are effected by the opened issue though

**Comment by neu5ron** [comment]
fixed in upcoming release
