### ISSUE TITLE
circuit_breaking_exception, Data too large

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#349]
The fix is already in the master/main branch. However, opening this encase anybody else runs across it.
The fix is reverting back to CMS java GC (from G1GC). This is because G1GC has a known bug/issue in 7.x.
Also, upgrading latest elastalert

**Describe the problem**
Circuit breakers are frequently hit/occur. Most of this occurs when elastalert is run, however that has no true caustion - it is just because that is doing the searches.. this is a garbage collection issue.

**What steps did you take trying to fix the issue?**
see above

**How could we replicate the issue?**
run (bunch) of searches and or elastalert.

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
the one with elastic 7.0.1

**What OS are you using to host the HELK?**
ubuntu 18

**Any additional context?**
other log files, pictures, etc.

cross posting issue in Elastalert repo, I noticed this while performing my weekly sweep of GitHub repo's I watch that are related to HELK (sigma, elastalert, etc...) . https://github.com/Yelp/elastalert/issues/2485

**Comment by neu5ron** [comment]
cc @Trolldemorted
I am %100 positive upgrades this is fixed via by me using temp workarounds and other upgrades to fix the upstream (this isn't a HELK issue) known bug with the java garbage collection that is currently enabled on the HELK version you are using
Then I can help you troubleshoot once you respond to this thread.

**Comment by Trolldemorted** [comment]
So https://github.com/Cyb3rWard0g/HELK/commit/3ded2f6673d684815514084fafc965f775431bce should solve this issue?

**Comment by neu5ron** [comment]
yes that will solve the issue. since thats update the entrypoint (start script), all you have to do is restart the elasticsearch docker container after you update the script.

 also upgrading/rebuilding the elastalert docker container is a good idea if you can

**Comment by neu5ron** [comment]
@Trolldemorted please reopen if this is still an issue, and add any new information.
