### ISSUE TITLE
winlogbeat events are not shown in kibana

### ISSUE THREAD

**Issue by Fedora-Man** [Cyb3rWard0g/HELK#353]
I am unable to get winlogbeat events in Kibana!

I am using CentOS Linux release 7.6.1810 and latest HELK.

Attached is the logs:
[helk-kafka-broker.log](https://github.com/Cyb3rWard0g/HELK/files/3685185/helk-kafka-broker.log)
[helk-logstash.log](https://github.com/Cyb3rWard0g/HELK/files/3685186/helk-logstash.log)

Anything is wrong?

**Comment by Fedora-Man** [comment]
Also I am using VMWare to host HELK and the IP address is 172.16.1.26 but I see the following IPs assigned (172.17.0.1 and 172.18.0.1):

br-5beca4e7e9cb: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fe80::42:e4ff:fe56:c4c2  prefixlen 64  scopeid 0x20<link>
        ether 02:42:e4:56:c4:c2  txqueuelen 0  (Ethernet)
        RX packets 2558  bytes 7242265 (6.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2820  bytes 7229472 (6.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:b4ff:fee1:f2e8  prefixlen 64  scopeid 0x20<link>
        ether 02:42:b4:e1:f2:e8  txqueuelen 0  (Ethernet)
        RX packets 29687  bytes 1838558 (1.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 41993  bytes 166602292 (158.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.1.26  netmask 255.255.255.0  broadcast 172.16.1.255
        inet6 fe80::92d5:3e55:180d:af39  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:98:51:89  txqueuelen 1000  (Ethernet)
        RX packets 433574  bytes 610355982 (582.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 62497  bytes 26099592 (24.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Are these created by HELK?

**Comment by neu5ron** [comment]
OK I think what is happening is your hard drive may be full..
can you run `df -h` and send the output of that?

also your logs may actually already be in there, just you need to change your time picker in the top right of Kibana to say something like the last year or few months.
does this show any logs when you do this?

yes those IPs are created by docker.



also, it seems (if your hard drive is not full), that zookeeper has died.
try:
`docker restart helk-zookeeper  && docker restart helk-kafka-broker`

**Comment by Cyb3rWard0g** [comment]
I just built latest HELK with this environment: (shire) https://github.com/hunters-forge/Blacksmith/tree/master/aws/mordor
 I cannot replicate. Check if your hard drive is full per @neu5ron recommendations.

**Comment by neu5ron** [comment]
@Fedora-Man closing this issue, please reopen with any new information and after you followed the questions/suggestions above.thanks!

**Comment by Fedora-Man** [comment]
I check the disk and it is not full:
[root@elk ~]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   50G   24G   27G  48% /
devtmpfs                 7.8G     0  7.8G   0% /dev
tmpfs                    7.8G     0  7.8G   0% /dev/shm
tmpfs                    7.8G   98M  7.7G   2% /run
tmpfs                    7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/sda1               1014M  232M  783M  23% /boot
/dev/mapper/centos-home   92G  6.6G   85G   8% /home
tmpfs                    1.6G   12K  1.6G   1% /run/user/42
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/705bad314c2cbf0afbe8d62bb63022df58870132d2a43f791ac41b4686e02a57/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/5c8502b8361e899ff51770d78f402df91f7f228e30fbc755f3c3b9d557101f77/mounts/shm
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/a6c94c85a59ab55667df2e056b3f874193eabace69d0b50036d2c942ce1233df/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/dc2dc070ce98de6f4913900456fe8fdf5e5079ff3046f02c8b412f0d7a43c36d/mounts/shm
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/95529363beb153642e944dd8d63037b2239415a900f9243368189fb4be3d43cd/merged
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/1682742fec9fb757ded500978a20142036d681cba96f4dc95321fd11e0de0f59/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/8c33b46a3784b876ac4214cb718d8eedc30cb6d2bdb00d779427135d7ec6b62c/mounts/shm
shm                       64M     0   64M   0% /var/lib/docker/containers/749b76e9d1abc2edb59c4f7614e87ebbdf5bd7ac7d5adeb2964e10a093d375de/mounts/shm
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/9a91960e039beb06b1a7adcebd015a1afca6570e1ad6e843ee89296f749337ad/merged
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/e88b56b1e197cfebd162c51b8539c55b8072d23d59cac74cf764b2d7bf14d5c2/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/96959437a8f8cfa5d921101067297e7e17625f313d52a71f147de2a714556dc5/mounts/shm
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/f8d31086ca0cc937b9741a507c9e503431d7bcb97e065d5dc986e8fd9516b589/merged
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/99965237176afb39b9d8e22ee81bdec3e0318c17d526990516f0b1f69e4d81ff/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/c7df89ee35b4657f8b1686395eecdf409ce06f49c71a7fcb6ea821a92bd72ea4/mounts/shm
tmpfs                    1.6G     0  1.6G   0% /run/user/0
overlay                   50G   24G   27G  48% /var/lib/docker/overlay2/513ba5e0b42c6441a77721fad99be68bdced29eafa6f7cf3ed2a997c707eaf84/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/4474b034112b197a40b59f9c5bbd8f7aaadc0a42215b58f5bf9d6752b007db1a/mounts/shm
shm                       64M     0   64M   0% /var/lib/docker/containers/61236d23f2a8c226fc3b9d1e8ff739ebfe61d833db7cfafc849b976dd270ef0b/mounts/shm
shm                       64M     0   64M   0% /var/lib/docker/containers/9deda69314a5d5e6c5b7b753278e8cff5f10f19c1570a816bb7360c841834e0d/mounts/shm

and I tried restarting zookeeper with the command:

docker restart helk-zookeeper && docker restart helk-kafka-broker

But still the same problem.
