### ISSUE TITLE
question:  Load Local Docker Images 

### ISSUE THREAD

**Issue by mojomasterchris** [Cyb3rWard0g/HELK#355]
I'm still pretty new to Docker, I've followed the instructions in "Load Local Docker Images" but now I'm having a hard time starting containers from the images.

Is there something I missing besides 

> docker create . . .

**Comment by Cyb3rWard0g** [comment]
can you provide all the steps that you took and where you are having issues with?

**Comment by Cyb3rWard0g** [comment]
These two wiki documents have the `docker create` commands

1) https://github.com/Cyb3rWard0g/HELK/wiki/Export-Docker-Images-locally
2) https://github.com/Cyb3rWard0g/HELK/wiki/Load-Local-Docker-Images

Could you please follow those two how-tos and let me know when you are ready to simply run the helk_install script. it will first check if the images exist locally, and if you followed the two documents above it will pick the local images and do its thing. Let me know how it goes!

**Comment by mojomasterchris** [comment]
Will do, thanks for the help and I'll let you know how it goes

**Comment by Cyb3rWard0g** [comment]
Let us know if you have any issues with it @mojomasterchris . Closing this for now. We can open another issue if you face any issues with it. That process of exporting your docker images and loading them is pretty straight forward and it works just as if you were downloading the images once the docker-compose file is run. Thank you!
