### ISSUE TITLE
Not an issue in Helk - Some difficulties while adding a new filebeat pipeline

### ISSUE THREAD

**Issue by tee2015** [Cyb3rWard0g/HELK#358]
Scenario : File beat on a client send json data to Helk
1- install file beat and configure it 👍 
on Filebeat:
Input:
 - document type and path
output.kafka:
- 
  hosts: ["hostIP:9092"]
  topic: "filebeat"
  codec.json:
   pretty: false
logs shows connected successfully no issues:
![image](https://user-images.githubusercontent.com/14360476/66286176-f8dafa00-e91b-11e9-9568-1cc875699eda.png)

On Helk:
<img width="261" alt="pic2" src="https://user-images.githubusercontent.com/14360476/66286764-9a634b00-e91e-11e9-8f9c-13b0829e5c0e.PNG">

I can see no incoming messages to Kafka 
<img width="499" alt="pict3" src="https://user-images.githubusercontent.com/14360476/66286911-2f664400-e91f-11e9-88e9-f84a8d0db80f.PNG">

What I am missing !! Any Ideas thanks :)

**Comment by Cyb3rWard0g** [comment]
Hey @tee2015 can you provide more logs from WInlogbeat? Connecting to the broker does not mean that you have logs been published. I would like to see if logs were actually published.

Also, you need an output and not a filter to push data to an index. Like this: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9958-osquery-output.conf

The commands to test kafka broker look good to me. I wonder if you can just use localhost:9092 if you are doing it on your own helk-kafka-broker container. Where are you running the commands from?

Also, I like to use kafkacat to troubleshoot events being published to Kafka. I would recommend to download kafkacat on your HELK server and run :

`kafkacat -b localhost:9092 -t filbeat -C`

**Comment by tee2015** [comment]
Thanks @Cyb3rWard0g , I am using filebeat instead of winbeat in my case, and I agree using kafkacat will help in check the published messages thank you for the commad will use it.

For the localhost:9092 didnt work in my case thats why I am using the docker name.

My confusion is on filebeat part, if I define my json log as a document_type (test) and on HELK server pipline I set the document_type then it must filter the incoming messages and maybe yes I must add additionaly the output (I use it before then I remove it to a seprate pipeline config but I can put them all togehter in one file) ?

**Comment by tee2015** [comment]
My Filebeat config on the broadcaster host : 
----- input ---
filebeat.inputs:

-type: log
  paths:
     - /var/log/file.json
  document_type: file

------------ output -------------
output.kafka:
 hosts: ["$IP:9092"]
 topic: "filebeat"
 codec.json:
   pretty.flase

**Comment by neu5ron** [comment]
@tee2015 does running the following give you any more information?
`sudo /usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -e`



also, is this a file type that could be better suited using a module? ie; apache, zeek, etc..
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-modules.html#enable-modules-d-configs

**Comment by Cyb3rWard0g** [comment]
yeah lets run @neu5ron command to see if you are even making it to Kafka the right way.

**Comment by tee2015** [comment]
Hi @neu5ron  and @Cyb3rWard0g 
![image](https://user-images.githubusercontent.com/14360476/66494776-eae7cd80-eb03-11e9-8175-eb504725b084.png)

**Comment by neu5ron** [comment]
yeah most of the "errors" can be ignored, they are just informational such as `Not loading modules. Module directory not found: /usr/share/filebeat/bin/module`

but just to make sure.. There are logs actively being written to this file? if not, when was the last log written to this file you are trying to consume?

**Comment by tee2015** [comment]
I can echo to the file and I am receiving these logs on filebeat

![image](https://user-images.githubusercontent.com/14360476/66496213-4c10a080-eb06-11e9-9331-d2e48b1e1309.png)


while on kafka side still the same as above not receiving any
![image](https://user-images.githubusercontent.com/14360476/66496304-74000400-eb06-11e9-9591-41e915f8c9c5.png)

**Comment by Cyb3rWard0g** [comment]
I do not see any logs being published to the kafka broker unless I am not looking at it closely enough. Can you share all the logs that were produced instead of just a portion of it. For example with winlogbeat I get:

- published 140 events or logs to kafka
- published 200 events or logs to kafka

something like that. i do not see that on yours. Unless filebeat behaves differently. I can see it connecting to the broker but not signs of it sending logs to it.

**Comment by tee2015** [comment]
Hi @Cyb3rWard0g these are the whole logs received its just repeated no 200 or 140 logs unfortuatelly:
---------------- LOGS -------------------------------
2019-10-09T22:19:31.815-0400    INFO    kafka/log.go:53 producer/broker/1 state change to [closing] because read tcp 10.80.2.10:49698->10.80.1.136:9092: i/o timeout

2019-10-09T22:19:31.815-0400    INFO    kafka/log.go:53 Closed connection to broker 10.80.1.136:9092

2019-10-09T22:19:31.815-0400    INFO    kafka/log.go:53 producer/leader/filebeat/0 state change to [retrying-2]

2019-10-09T22:19:31.815-0400    INFO    kafka/log.go:53 producer/leader/filebeat/0 abandoning broker 1

2019-10-09T22:19:31.815-0400    INFO    kafka/log.go:53 producer/broker/1 shut down

2019-10-09T22:19:31.915-0400    INFO    kafka/log.go:53 client/metadata fetching metadata for [filebeat] from broker 10.80.1.136:9092

2019-10-09T22:19:31.969-0400    INFO    kafka/log.go:53 producer/broker/1 starting up

2019-10-09T22:19:31.970-0400    INFO    kafka/log.go:53 producer/broker/1 state change to [open] on filebeat/0

2019-10-09T22:19:31.970-0400    INFO    kafka/log.go:53 producer/leader/filebeat/0 selected broker 1

2019-10-09T22:19:31.970-0400    INFO    kafka/log.go:53 producer/leader/filebeat/0 state change to [flushing-2]

2019-10-09T22:19:31.970-0400    INFO    kafka/log.go:53 producer/leader/filebeat/0 state change to [normal]

2019-10-09T22:19:32.022-0400    INFO    kafka/log.go:53 Connected to broker at 10.80.1.136:9092 (registered as #1)

2019-10-09T22:19:33.404-0400    INFO    log/harvester.go:251    Harvester started for file: /var/log/file.json
2019-10-09T22:19:53.386-0400    INFO    [monitoring]    log/log.go:145  Non-zero metrics in the last 30s        {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":130,"time":{"ms":4}},"total":{"ticks":390,"time":{"ms":12},"value":390},"user":{"ticks":260,"time":{"ms":8}}},"handles":{"limit":{"hard":1000000,"soft":1000000},"open":8},"info":{"ephemeral_id":"1e576bf0-1302-4373-b916-da71582fd82a","uptime":{"ms":660077}},"memstats":{"gc_next":10327200,"memory_alloc":6707752,"memory_total":37088776},"runtime":{"goroutines":37}},"filebeat":{"events":{"active":2,"added":2},"harvester":{"open_files":1,"running":1,"started":1}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"active":1,"batches":1,"total":1}},"outputs":{"kafka":{"bytes_read":118,"bytes_write":1672}},"pipeline":{"clients":1,"events":{"active":9,"filtered":1,"published":1,"total":2}}},"registrar":{"states":{"current":1}},"system":{"load":{"1":3.81,"15":2.18,"5":2.49,"norm":{"1":0.9525,"15":0.545,"5":0.6225}}}}}}

**Comment by Cyb3rWard0g** [comment]
how many logs are you expecting? It said it published 1? can you share a sample of the logs you are trying to send?

**Comment by tee2015** [comment]
I sent just 1 and received 1

echo '("test_filed":"test_value1"}' >>file.json

on kafkacat:
![image](https://user-images.githubusercontent.com/14360476/66534695-beaf6980-eb62-11e9-8466-e37f2fc240ee.png)

**Comment by neu5ron** [comment]
see helk slack

**Comment by tee2015** [comment]
@neu5ron 
![image](https://user-images.githubusercontent.com/14360476/66534912-7e042000-eb63-11e9-8d87-acc2e3b6182d.png)

Yup its landing safely :P

**Comment by Cyb3rWard0g** [comment]
ok so it worked then @tee2015 . I can see the file was consumed by kafkacat. Now your output config needs to be updated to grab the nested field log.file.path. I can see it is not just simply `source` . You are using Winlogbeat 7.4 and they nested some fields. Let me know if that makes sense.

**Comment by Cyb3rWard0g** [comment]
oh nice can you share your output and filter configs please?

**Comment by tee2015** [comment]
yes sure one minute @Cyb3rWard0g  :)

**Comment by tee2015** [comment]
broadcaster server : Filebeat configs : 

#==================== Filebeat inputs =============================

filebeat.inputs:

# Each - is an input. Most options can be set at the input level, so
# you can use different inputs for various configurations.
# Below are the input specific configurations.

- type: log

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/log/file.json
    #- c:\programdata\elasticsearch\logs\*
  document_type: file

#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["10.80.1.136:9092"]

  # message topic selection + partitioning
 # topic: '%{[fields.log_filebeat]}'
  topic: "filebeat"
  codec.json:
   pretty: false
  #partition.round_robin:
 #   reachable_only: false

 # required_acks: 1
#  compression: gzip
  #max_retries:2
  #max_message_bytes: 1000000

# -------------- -- End of Filebeat --------------------------



Helk Logstash -  pipline config file 
![image](https://user-images.githubusercontent.com/14360476/66535776-6e3a0b00-eb66-11e9-8149-72e20cc2151d.png)

**Comment by Cyb3rWard0g** [comment]
Ok thank you! I am surprised the `if[source]` worked since that path was an embedded field value unless I did not see the `source` field in your kafka screenshot. I believe we can close this issue then since you were able to get logs over to HELK. correct @tee2015 ?

**Comment by tee2015** [comment]
Yes I will close it thanks @Cyb3rWard0g

**Comment by tee2015** [comment]
Hi @Cyb3rWard0g  yes you are right , no effictivness to that line :
if [source ] = ...
as per my understanding that if this file.json is on helk server then it will be beneficial to have it.

What I left on the output is just the elasticseach { configs} part 
what is happening the data is indexed under no the specified index that I want and its coming under (indexme-*)
Not sure how to control the index part tbh any ideas ? Thank you :)

**Comment by tee2015** [comment]
Solved using the default output 0098 filter and have my data separate :)
