### ISSUE TITLE
Elasticsearch password

### ISSUE THREAD

**Issue by orange-tsai** [Cyb3rWard0g/HELK#359]
**Describe the problem**
Steps:
- `git clone git@github.com:Cyb3rWard0g/HELK.git`
- `cd ./HELK/docker`
- `./helk_install.sh`
- Pick any option
- Log into kabana
- Go to add a new log, any log, ... but where is the elastic password stored? 
  - tried `docker secrets ls`
  - tried same password from the helk_install.sh script. 

```
By default, the bootstrap password is derived from a randomized keystore.seed setting, which
is added to the keystore during installation. You do not need to know or change this bootstrap
password. If you have defined a bootstrap.password setting in the keystore, however, that
value is used instead. For more information about interacting with the keystore, see Secure
Settings.
```
It is difficult to setup the `elastic` user and a <password> when how to get the password is unclear. 

**What version of HELK are you using?**
2cf253e5de967f75b4661a2c584edb7733d15031

**What OS are you using to host the HELK?**
tried ubuntu, raspbian, debian, and centos

**Comment by webhead404** [comment]
Which option did you choose? Basic or Trial? If you are using Basic there is no password set for the user I don't think.

**Comment by Cyb3rWard0g** [comment]
@orange-tsai can you please provide the information about the options that you chose to install HELK?

**Comment by orange-tsai** [comment]
I chose basic, my understanding is then to leave username and password empty?

**Comment by Cyb3rWard0g** [comment]
Can you please do a fresh install and provide more information about the installation? this is the installation wiki https://github.com/Cyb3rWard0g/HELK/wiki/Installation#helk-install

**Comment by orange-tsai** [comment]
@Cyb3rWard0g I did, same result. 

```
**********************************************
**          HELK - THE HUNTING ELK          **
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: v0.1.8-alpha05292019 **
** HELK ELK version: 7.1.0                  **
** License: GPL-3.0                         **
**********************************************

[HELK-INSTALLATION-INFO] HELK being hosted on a Linux box
[HELK-INSTALLATION-INFO] Available Memory: 9630 MBs
[HELK-INSTALLATION-INFO] You're using ubuntu version xenial
...
Enter build choice [ 1 - 4]: 4
[HELK-INSTALLATION-INFO] Set HELK elastic subscription (basic or trial): basic
...
HELK KIBANA URL: https://redacted
HELK KIBANA USER: helk
HELK KIBANA PASSWORD: hunting
HELK SPARK MASTER UI: http://redacted:8080
HELK JUPYTER SERVER URL: http://redacted/jupyter
HELK JUPYTER CURRENT TOKEN: redacted
HELK ZOOKEEPER: redacted:2181
HELK KSQL SERVER: redacted:8088
```

docker.elastic.co/elasticsearch/elasticsearch:7.1.0   "/usr/share/elastics…"   34 minutes ago      Up 34 minutes       9200/tcp, 9300/tcp

port 9200 is not accessible. I install filebeat, steps..., check with Module status and nothing is ever ingested. 
![button](https://user-images.githubusercontent.com/12297371/66540209-19ac7680-eaf9-11e9-83c6-97926726729d.png)

**Comment by Cyb3rWard0g** [comment]
port 9200 should not be accessible from outside of the containers environment. That is by default. What do you mean with "which seems wrong?"  If you are looking for filebeat ingestion, take a look at this other issue where a user needed some help with it https://github.com/Cyb3rWard0g/HELK/issues/358 . Installation looks good to me. I just installed it again and I get logs from endpoints and all that. If you are using filebeat, that would be a custom pipe question. Once again, this issue might be helpful: https://github.com/Cyb3rWard0g/HELK/issues/358 . Please let me know! Thank you!

**Comment by neu5ron** [comment]
@orange-tsai please reopen if you have any updates or other questions/comments/suggestions.

thanks!

**Comment by barvhaim** [comment]
@Cyb3rWard0g I am currently encounter this issue as well for consuming Elasticsearch data using its API, I would have to be able to access by "curl -u elastic:password <ip>:9200", first thing I did is to expose the 9200/9300 ports, but the issue now is how do I find the elastic user password? I use `KAFKA + KSQL + ELK + NGNIX` option

**Comment by Cyb3rWard0g** [comment]
There is no password for ES as far as I know. We do not use the license or mode that requires it.
