### ISSUE TITLE
winlogbeat events are not shown in kibana

### ISSUE THREAD

**Issue by Fedora-Man** [Cyb3rWard0g/HELK#362]
Related to Issue #353 
I check the disk and it is not full:

```
[root@elk ~]# df -h
Filesystem Size Used Avail Use% Mounted on
/dev/mapper/centos-root 50G 28G 23G 55% /
devtmpfs 7.8G 0 7.8G 0% /dev
tmpfs 7.8G 0 7.8G 0% /dev/shm
tmpfs 7.8G 114M 7.7G 2% /run
tmpfs 7.8G 0 7.8G 0% /sys/fs/cgroup
/dev/sda1 1014M 232M 783M 23% /boot
/dev/mapper/centos-home 92G 6.6G 85G 8% /home
tmpfs 1.6G 12K 1.6G 1% /run/user/42
tmpfs 1.6G 0 1.6G 0% /run/user/1000
```

and I tried restarting zookeeper with the command:

`docker restart helk-zookeeper && docker restart helk-kafka-broker`

But still the same problem.

Also I dont see anything indexed in Kibana and I continously getting the following in helk-logstash logs:
`[2019-10-03T09:40:16,722][WARN ][org.apache.kafka.clients.NetworkClient] [Consumer clientId=logstash-0, groupId=helk_logstash] Error while fetching metadata with correlation id 49619 : {winlogbeat=UNKNOWN_TOPIC_OR_PARTITION, SYSMON_JOIN=UNKNOWN_TOPIC_OR_PARTITION, filebeat=UNKNOWN_TOPIC_OR_PARTITION}`

**Comment by neu5ron** [comment]
can you send your winlogbeat config (remove any IP addresses or hostnames from the config please)

**Comment by Fedora-Man** [comment]
I am using the config file provided by helk. see attached.

[winlogbeat.txt](https://github.com/Cyb3rWard0g/HELK/files/3740396/winlogbeat.txt)

**Comment by Fedora-Man** [comment]
I have installed the helk on Amazon Linux and it is working fine! The only other difference with the Centos installation is docker version. 

In Amazon Linux docker:
Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136

In Centos 7 (installed by HELK):
Docker version 19.03.3, build a872fc2f86

Does this make any difference?

**Comment by Cyb3rWard0g** [comment]
you say that you have HELK on AWS. Are your security groups set up to allow traffic to HELK?

**Comment by Fedora-Man** [comment]
I said I have another HELK on AWS and it is working fine but the one on premises is installed on Centos 7 and is the one having problem!

**Comment by Fedora-Man** [comment]
I found the problem was the firewall in Centos 7 was blocking the traffic and when I stopped it everything works ok!

Any suggestion for the firewall configuration because I don't want to keep everything open and want to protect the server from attacks!

Thanks

**Comment by neu5ron** [comment]
glad to hear you figured it out!  
I would only inbound for the logstash/kafka ports from the servers that are forwarding your logs (ie: WEF server or devices with filebeat/winlogbeat/etc...
you could also password/TLS protect log forwarding - we haven't made this automatic in the configurations, but its an option.
