### ISSUE TITLE
Packetbeat configuration question

### ISSUE THREAD

**Issue by Ol1ver26** [Cyb3rWard0g/HELK#363]
**Describe the problem**
My HELK is in the school's VM and has Internet access, and also assigned the lab's intranet ip.
I want to use packetbeat to send network traffic data to VM from one computer in the lab.  I follow the instructions of ELK. (https://www.elastic.co/guide/en/beats/packetbeat/6.2/packetbeat-getting-started.html) At step 4, when i tring to config the kibana dashboard (packetbeat setup --dashboards), i receive this, 
![IMG_20191014_111936](https://user-images.githubusercontent.com/36188251/66796981-b71a0700-ef4c-11e9-82c8-4825b0e6a185.jpg)

**What steps did you take trying to fix the issue?**
I reread instructions and modeify the packetbeat.yml file.

**What version of HELK are you using?**
I install option 2 HELK at end of the July

**What OS are you using to host the HELK?**
Ubuntu 18.04.3

**Any additional context?**
other log files, pictures, etc.
This is whats inside the packesbeat.4

2019-10-08T13:57:41.895+1000	INFO	instance/beat.go:607	Home path: [C:\Program Files\Packetbeat] Config path: [C:\Program Files\Packetbeat] Data path: [C:\Program Files\Packetbeat\data] Logs path: [C:\Program Files\Packetbeat\logs]
2019-10-08T13:57:41.906+1000	INFO	instance/beat.go:615	Beat ID: 29871316-ba8a-438d-b416-5c858a0c7a25
2019-10-08T13:57:41.926+1000	INFO	[beat]	instance/beat.go:903	Beat info	{"system_info": {"beat": {"path": {"config": "C:\\Program Files\\Packetbeat", "data": "C:\\Program Files\\Packetbeat\\data", "home": "C:\\Program Files\\Packetbeat", "logs": "C:\\Program Files\\Packetbeat\\logs"}, "type": "packetbeat", "uuid": "29871316-ba8a-438d-b416-5c858a0c7a25"}}}
2019-10-08T13:57:41.927+1000	INFO	[beat]	instance/beat.go:912	Build info	{"system_info": {"build": {"commit": "5b046c5a97fe1e312f22d40a1f05365621aad621", "libbeat": "7.3.2", "time": "2019-09-06T13:40:36.000Z", "version": "7.3.2"}}}
2019-10-08T13:57:41.927+1000	INFO	[beat]	instance/beat.go:915	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":8,"version":"go1.12.4"}}}
2019-10-08T13:57:41.942+1000	INFO	[beat]	instance/beat.go:919	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2019-10-08T12:38:48.53+10:00","name":"SEF-PA00133539","ip":["fe80::953f:1de:f85d:303d/64","10.10.10.80/24","fe80::c9b6:7c7f:2ce3:562a/64","X.X.X.X/24","fe80::4ce:5232:18c8:3704/64","192.168.56.1/24","::1/128","127.0.0.1/8","fe80::5efe:a0a:a50/128","2002:83b5:21dd::83b5:21dd/128","fe80::200:5efe:83b5:21dd/128","fe80::5efe:c0a8:3801/128"],"kernel_version":"6.1.7601.24520 (win7sp1_ldr_escrow.190828-1732)","mac":["68:05:ca:80:38:79","54:bf:64:66:65:77","0a:00:27:00:00:12","00:00:00:00:00:00:00:e0","00:00:00:00:00:00:00:e0","00:00:00:00:00:00:00:e0","00:00:00:00:00:00:00:e0"],"os":{"family":"windows","platform":"windows","name":"Windows 7 Enterprise","version":"6.1","major":1,"minor":0,"patch":0,"build":"7601.24519"},"timezone":"AEST","timezone_offset_sec":36000,"id":"31fc267c-0f6a-4493-ba1c-469d46bebb40"}}}
2019-10-08T13:57:41.942+1000	INFO	[beat]	instance/beat.go:948	Process info	{"system_info": {"process": {"cwd": "C:\\Program Files\\Packetbeat", "exe": "C:\\Program Files\\Packetbeat\\packetbeat.exe", "name": "packetbeat.exe", "pid": 8724, "ppid": 6680, "start_time": "2019-10-08T13:57:41.745+1000"}}}
2019-10-08T13:57:41.942+1000	INFO	instance/beat.go:292	Setup Beat: packetbeat; Version: 7.3.2
2019-10-08T13:57:41.942+1000	INFO	[index-management]	idxmgmt/std.go:178	Set output.elasticsearch.index to 'packetbeat-7.3.2' as ILM is enabled.
2019-10-08T13:57:41.943+1000	INFO	elasticsearch/client.go:170	Elasticsearch url: http://X.X.97.15:9200
2019-10-08T13:57:41.943+1000	INFO	[publisher]	pipeline/module.go:97	Beat name: SEF-PA00133539
2019-10-08T13:57:41.943+1000	INFO	procs/procs.go:105	Process watcher disabled
2019-10-08T13:57:42.004+1000	INFO	sniffer/device.go:92	Resolved device index 0 to device: \Device\NPF_{8BF4A25B-DD3A-4307-BA6D-3A3DEF3F22FB}
2019-10-08T13:57:42.004+1000	INFO	kibana/client.go:117	Kibana url: http://X.X.97.15:5601
2019-10-08T13:57:44.926+1000	INFO	add_cloud_metadata/add_cloud_metadata.go:347	add_cloud_metadata: hosting provider type not detected.
2019-10-08T13:58:03.028+1000	ERROR	instance/beat.go:878	Exiting: error connecting to Kibana: fail to get the Kibana version: HTTP GET request to http://X.X.97.15:5601/api/status fails: fail to execute the HTTP GET request: Get http://X.X.97.15:5601/api/status: dial tcp X.X.97.15:5601: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Response: .

**Comment by Cyb3rWard0g** [comment]
Kibana is not exposed on port 5601 since it has nginx on the front. Can you share hour packetbeat config please?

**Comment by Ol1ver26** [comment]
May be difficult to read
this is my packetbeat.yml
#################### Packetbeat Configuration Example #########################

# This file is an example configuration file highlighting only the most common
# options. The packetbeat.reference.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/packetbeat/index.html

#============================== Network device ================================

# Select the network interface to sniff the data. On Linux, you can use the
# "any" keyword to sniff on all connected interfaces.
packetbeat.interfaces.device: 1

#================================== Flows =====================================

# Set `enabled: false` or comment out all options to disable flows reporting.
packetbeat.flows:
  # Set network flow timeout. Flow is killed if no packet is received before being
  # timed out.
  timeout: 30s

  # Configure reporting period. If set to -1, only killed flows will be reported
  period: 10s

#========================== Transaction protocols =============================

packetbeat.protocols:
- type: icmp
  # Enable ICMPv4 and ICMPv6 monitoring. Default: false
  enabled: true

- type: amqp
  # Configure the ports where to listen for AMQP traffic. You can disable
  # the AMQP protocol by commenting out the list of ports.
  ports: [5672]

- type: cassandra
  #Cassandra port for traffic monitoring.
  ports: [9042]

- type: dhcpv4
  # Configure the DHCP for IPv4 ports.
  ports: [67, 68]

- type: dns
  # Configure the ports where to listen for DNS traffic. You can disable
  # the DNS protocol by commenting out the list of ports.
  ports: [53]

- type: http
  # Configure the ports where to listen for HTTP traffic. You can disable
  # the HTTP protocol by commenting out the list of ports.
  ports: [80, 8080, 8000, 5000, 8002]

- type: memcache
  # Configure the ports where to listen for memcache traffic. You can disable
  # the Memcache protocol by commenting out the list of ports.
  ports: [11211]

- type: mysql
  # Configure the ports where to listen for MySQL traffic. You can disable
  # the MySQL protocol by commenting out the list of ports.
  ports: [3306,3307]

- type: pgsql
  # Configure the ports where to listen for Pgsql traffic. You can disable
  # the Pgsql protocol by commenting out the list of ports.
  ports: [5432]

- type: redis
  # Configure the ports where to listen for Redis traffic. You can disable
  # the Redis protocol by commenting out the list of ports.
  ports: [6379]

- type: thrift
  # Configure the ports where to listen for Thrift-RPC traffic. You can disable
  # the Thrift-RPC protocol by commenting out the list of ports.
  ports: [9090]

- type: mongodb
  # Configure the ports where to listen for MongoDB traffic. You can disable
  # the MongoDB protocol by commenting out the list of ports.
  ports: [27017]

- type: nfs
  # Configure the ports where to listen for NFS traffic. You can disable
  # the NFS protocol by commenting out the list of ports.
  ports: [2049]

- type: tls
  # Configure the ports where to listen for TLS traffic. You can disable
  # the TLS protocol by commenting out the list of ports.
  ports:
    - 443   # HTTPS
    - 993   # IMAPS
    - 995   # POP3S
    - 5223  # XMPP over SSL
    - 8443
    - 8883  # Secure MQTT
    - 9243  # Elasticsearch

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging


#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here or by using the `setup` command.
setup.dashboards.enabled: true

# The URL from where to download the dashboards archive. By default this URL
# has a value which is computed based on the Beat name and version. For released
# versions, this URL points to the dashboard archive on the artifacts.elastic.co
# website.
#setup.dashboards.url:

#============================== Kibana =====================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:

  # Kibana Host
  # Scheme and port can be left out and will be set to the default (http and 5601)
  # In case you specify and additional path, the scheme is required: http://localhost:5601/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  host: "https://131.181.97.15:80"
  

  # Kibana Space ID
  # ID of the Kibana Space into which the dashboards should be loaded. By default,
  # the Default Space will be used.
  #space.id:

  username: "username"
  password: "password"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

#============================= Elastic Cloud ==================================

# These settings simplify using Packetbeat with the Elastic Cloud (https://cloud.elastic.co/).

# The cloud.id setting overwrites the `output.elasticsearch.hosts` and
# `setup.kibana.host` options.
# You can find the `cloud.id` in the Elastic Cloud web UI.
#cloud.id:

# The cloud.auth setting overwrites the `output.elasticsearch.username` and
# `output.elasticsearch.password` settings. The format is `<user>:<pass>`.
#cloud.auth:

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["https://131.181.97.15:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]

#============================== Xpack Monitoring ===============================
# packetbeat can export internal metrics to a central Elasticsearch monitoring
# cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
# reporting is disabled by default.

# Set to true to enable the monitoring reporter.
#monitoring.enabled: false

# Sets the UUID of the Elasticsearch cluster under which monitoring data for this
# Packetbeat instance will appear in the Stack Monitoring UI. If output.elasticsearch
# is enabled, the UUID is derived from the Elasticsearch cluster referenced by output.elasticsearch.
#monitoring.cluster_uuid:

# Uncomment to send the metrics to Elasticsearch. Most settings from the
# Elasticsearch output are accepted here as well.
# Note that the settings should point to your Elasticsearch *monitoring* cluster.
# Any setting that is not set is automatically inherited from the Elasticsearch
# output configuration, so if you have the Elasticsearch output configured such
# that it is pointing to your Elasticsearch monitoring cluster, you can simply
# uncomment the following line.
#monitoring.elasticsearch:

#================================= Migration ==================================

# This allows to enable 6.7 migration aliases
#migration.6_to_7.enabled: true

**Comment by Ol1ver26** [comment]
May be difficult to read
this is my packetbeat.yml
#################### Packetbeat Configuration Example #########################

#This file is an example configuration file highlighting only the most common
#options. The packetbeat.reference.yml file from the same directory contains all the
#supported options with more comments. You can use it as a reference.
#
#You can find the full configuration reference here:
#https://www.elastic.co/guide/en/beats/packetbeat/index.html

#============================== Network device ================================

#Select the network interface to sniff the data. On Linux, you can use the
#"any" keyword to sniff on all connected interfaces.
packetbeat.interfaces.device: 1

#================================== Flows =====================================

#Set `enabled: false` or comment out all options to disable flows reporting.
packetbeat.flows:
  #Set network flow timeout. Flow is killed if no packet is received before being
  #timed out.
  timeout: 30s

  #Configure reporting period. If set to -1, only killed flows will be reported
  period: 10s

#========================== Transaction protocols =============================

packetbeat.protocols:
- type: icmp
  #Enable ICMPv4 and ICMPv6 monitoring. Default: false
  enabled: true

- type: amqp
  #Configure the ports where to listen for AMQP traffic. You can disable
  #the AMQP protocol by commenting out the list of ports.
  ports: [5672]

- type: cassandra
  #Cassandra port for traffic monitoring.
  ports: [9042]

- type: dhcpv4
  #Configure the DHCP for IPv4 ports.
  ports: [67, 68]

- type: dns
  #Configure the ports where to listen for DNS traffic. You can disable
  #the DNS protocol by commenting out the list of ports.
  ports: [53]

- type: http
  #Configure the ports where to listen for HTTP traffic. You can disable
  #the HTTP protocol by commenting out the list of ports.
  ports: [80, 8080, 8000, 5000, 8002]

- type: memcache
  #Configure the ports where to listen for memcache traffic. You can disable
  #the Memcache protocol by commenting out the list of ports.
  ports: [11211]

- type: mysql
  #Configure the ports where to listen for MySQL traffic. You can disable
  #the MySQL protocol by commenting out the list of ports.
  ports: [3306,3307]

- type: pgsql
  #Configure the ports where to listen for Pgsql traffic. You can disable
  #the Pgsql protocol by commenting out the list of ports.
  ports: [5432]

- type: redis
  #Configure the ports where to listen for Redis traffic. You can disable
  #the Redis protocol by commenting out the list of ports.
  ports: [6379]

- type: thrift
  #Configure the ports where to listen for Thrift-RPC traffic. You can disable
  #the Thrift-RPC protocol by commenting out the list of ports.
  ports: [9090]

- type: mongodb
  #Configure the ports where to listen for MongoDB traffic. You can disable
  #the MongoDB protocol by commenting out the list of ports.
  ports: [27017]

- type: nfs
  #Configure the ports where to listen for NFS traffic. You can disable
  #the NFS protocol by commenting out the list of ports.
  ports: [2049]

- type: tls
  #Configure the ports where to listen for TLS traffic. You can disable
  #the TLS protocol by commenting out the list of ports.
  ports:
    - 443   # HTTPS
    - 993   # IMAPS
    - 995   # POP3S
    - 5223  # XMPP over SSL
    - 8443
    - 8883  # Secure MQTT
    - 9243  # Elasticsearch

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

#================================ General =====================================

#The name of the shipper that publishes the network data. It can be used to group
#all the transactions sent by a single shipper in the web interface.
#name:

#The tags of the shipper are included in their own field with each
#transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging


#============================== Dashboards =====================================
#These settings control loading the sample dashboards to the Kibana index. Loading
#the dashboards is disabled by default and can be enabled either by setting the
#options here or by using the `setup` command.
setup.dashboards.enabled: true

#The URL from where to download the dashboards archive. By default this URL
#has a value which is computed based on the Beat name and version. For released
#versions, this URL points to the dashboard archive on the artifacts.elastic.co
#website.
#setup.dashboards.url:

#============================== Kibana =====================================

#Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
#This requires a Kibana endpoint configuration.
setup.kibana:

  #Kibana Host
  #Scheme and port can be left out and will be set to the default (http and 5601)
  #In case you specify and additional path, the scheme is required: http://localhost:5601/path
  #IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  host: "https://131.181.97.15:5601"
  

  #Kibana Space ID
  #ID of the Kibana Space into which the dashboards should be loaded. By default,
  #the Default Space will be used.
  #space.id:

  username: "username"
  password: "password"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

#============================= Elastic Cloud ==================================

#These settings simplify using Packetbeat with the Elastic Cloud (https://cloud.elastic.co/).

#The cloud.id setting overwrites the `output.elasticsearch.hosts` and
#`setup.kibana.host` options.
#You can find the `cloud.id` in the Elastic Cloud web UI.
#cloud.id:

#The cloud.auth setting overwrites the `output.elasticsearch.username` and
#`output.elasticsearch.password` settings. The format is `<user>:<pass>`.
#cloud.auth:

#================================ Outputs =====================================

#Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  #Array of hosts to connect to.
  hosts: ["https://131.181.97.15:9200"]

  #Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  #The Logstash hosts
  #hosts: ["localhost:5044"]

  #Optional SSL. By default is off.
  #List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  #Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  #Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Processors =====================================

#Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

#================================ Logging =====================================

#Sets log level. The default log level is info.
#Available log levels are: error, warning, info, debug
#logging.level: debug

#At debug level, you can selectively enable logging only for some components.
#To enable all selectors use ["*"]. Examples of other selectors are "beat",
#"publish", "service".
#logging.selectors: ["*"]

#============================== Xpack Monitoring ===============================
#packetbeat can export internal metrics to a central Elasticsearch monitoring
#cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
#reporting is disabled by default.

#Set to true to enable the monitoring reporter.
#monitoring.enabled: false

#Sets the UUID of the Elasticsearch cluster under which monitoring data for this
#Packetbeat instance will appear in the Stack Monitoring UI. If output.elasticsearch
#is enabled, the UUID is derived from the Elasticsearch cluster referenced by output.elasticsearch.
#monitoring.cluster_uuid:

#Uncomment to send the metrics to Elasticsearch. Most settings from the
#Elasticsearch output are accepted here as well.
#Note that the settings should point to your Elasticsearch *monitoring* cluster.
#Any setting that is not set is automatically inherited from the Elasticsearch
#output configuration, so if you have the Elasticsearch output configured such
#that it is pointing to your Elasticsearch monitoring cluster, you can simply
#uncomment the following line.
#monitoring.elasticsearch:

#================================= Migration ==================================

#This allows to enable 6.7 migration aliases
#migration.6_to_7.enabled: true

**Comment by Ol1ver26** [comment]
May be difficult to read
this is my packetbeat.yml
#################### Packetbeat Configuration Example #########################

#This file is an example configuration file highlighting only the most common
#options. The packetbeat.reference.yml file from the same directory contains all the
#supported options with more comments. You can use it as a reference.
#
#You can find the full configuration reference here:
#https://www.elastic.co/guide/en/beats/packetbeat/index.html

#============================== Network device ================================

#Select the network interface to sniff the data. On Linux, you can use the
#"any" keyword to sniff on all connected interfaces.
packetbeat.interfaces.device: 1

#================================== Flows =====================================

#Set `enabled: false` or comment out all options to disable flows reporting.
packetbeat.flows:
  #Set network flow timeout. Flow is killed if no packet is received before being
  #timed out.
  timeout: 30s

  #Configure reporting period. If set to -1, only killed flows will be reported
  period: 10s

#========================== Transaction protocols =============================

packetbeat.protocols:
- type: icmp
  #Enable ICMPv4 and ICMPv6 monitoring. Default: false
  enabled: true

- type: amqp
  #Configure the ports where to listen for AMQP traffic. You can disable
  #the AMQP protocol by commenting out the list of ports.
  ports: [5672]

- type: cassandra
  #Cassandra port for traffic monitoring.
  ports: [9042]

- type: dhcpv4
  #Configure the DHCP for IPv4 ports.
  ports: [67, 68]

- type: dns
  #Configure the ports where to listen for DNS traffic. You can disable
  #the DNS protocol by commenting out the list of ports.
  ports: [53]

- type: http
  #Configure the ports where to listen for HTTP traffic. You can disable
  #the HTTP protocol by commenting out the list of ports.
  ports: [80, 8080, 8000, 5000, 8002]

- type: memcache
  #Configure the ports where to listen for memcache traffic. You can disable
  #the Memcache protocol by commenting out the list of ports.
  ports: [11211]

- type: mysql
  #Configure the ports where to listen for MySQL traffic. You can disable
  #the MySQL protocol by commenting out the list of ports.
  ports: [3306,3307]

- type: pgsql
  #Configure the ports where to listen for Pgsql traffic. You can disable
  #the Pgsql protocol by commenting out the list of ports.
  ports: [5432]

- type: redis
  #Configure the ports where to listen for Redis traffic. You can disable
  #the Redis protocol by commenting out the list of ports.
  ports: [6379]

- type: thrift
  #Configure the ports where to listen for Thrift-RPC traffic. You can disable
  #the Thrift-RPC protocol by commenting out the list of ports.
  ports: [9090]

- type: mongodb
  #Configure the ports where to listen for MongoDB traffic. You can disable
  #the MongoDB protocol by commenting out the list of ports.
  ports: [27017]

- type: nfs
  #Configure the ports where to listen for NFS traffic. You can disable
  #the NFS protocol by commenting out the list of ports.
  ports: [2049]

- type: tls
  #Configure the ports where to listen for TLS traffic. You can disable
  #the TLS protocol by commenting out the list of ports.
  ports:
    - 443   # HTTPS
    - 993   # IMAPS
    - 995   # POP3S
    - 5223  # XMPP over SSL
    - 8443
    - 8883  # Secure MQTT
    - 9243  # Elasticsearch

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

#================================ General =====================================

#The name of the shipper that publishes the network data. It can be used to group
#all the transactions sent by a single shipper in the web interface.
#name:

#The tags of the shipper are included in their own field with each
#transaction published.
#tags: ["service-X", "web-tier"]

#Optional fields that you can specify to add additional information to the
#output.
#fields:
#env: staging


#============================== Dashboards =====================================
#These settings control loading the sample dashboards to the Kibana index. Loading
#the dashboards is disabled by default and can be enabled either by setting the
#options here or by using the `setup` command.
setup.dashboards.enabled: true

#The URL from where to download the dashboards archive. By default this URL
#has a value which is computed based on the Beat name and version. For released
#versions, this URL points to the dashboard archive on the artifacts.elastic.co
#website.
#setup.dashboards.url:

#============================== Kibana =====================================

#Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
#This requires a Kibana endpoint configuration.
setup.kibana:

  #Kibana Host
  #Scheme and port can be left out and will be set to the default (http and 5601)
  #In case you specify and additional path, the scheme is required: http://localhost:5601/path
  #IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  host: "https://131.181.97.15:5601"
  

  #Kibana Space ID
  #ID of the Kibana Space into which the dashboards should be loaded. By default,
  #the Default Space will be used.
  #space.id:

  username: "username"
  password: "password"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

#============================= Elastic Cloud ==================================

#These settings simplify using Packetbeat with the Elastic Cloud (https://cloud.elastic.co/).

#The cloud.id setting overwrites the `output.elasticsearch.hosts` and
#`setup.kibana.host` options.
#You can find the `cloud.id` in the Elastic Cloud web UI.
#cloud.id:

#The cloud.auth setting overwrites the `output.elasticsearch.username` and
#`output.elasticsearch.password` settings. The format is `<user>:<pass>`.
#cloud.auth:

#================================ Outputs =====================================

#Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  #Array of hosts to connect to.
  hosts: ["https://131.181.97.15:9200"]

  #Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  #The Logstash hosts
  #hosts: ["localhost:5044"]

  #Optional SSL. By default is off.
  #List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  #Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  #Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Processors =====================================

#Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

#================================ Logging =====================================

#Sets log level. The default log level is info.
#Available log levels are: error, warning, info, debug
#logging.level: debug

#At debug level, you can selectively enable logging only for some components.
#To enable all selectors use ["*"]. Examples of other selectors are "beat",
#"publish", "service".
#logging.selectors: ["*"]

#============================== Xpack Monitoring ===============================
#packetbeat can export internal metrics to a central Elasticsearch monitoring
#cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
#reporting is disabled by default.

#Set to true to enable the monitoring reporter.
#monitoring.enabled: false

#Sets the UUID of the Elasticsearch cluster under which monitoring data for this
#Packetbeat instance will appear in the Stack Monitoring UI. If output.elasticsearch
#is enabled, the UUID is derived from the Elasticsearch cluster referenced by output.elasticsearch.
#monitoring.cluster_uuid:

#Uncomment to send the metrics to Elasticsearch. Most settings from the
#Elasticsearch output are accepted here as well.
#Note that the settings should point to your Elasticsearch *monitoring* cluster.
#Any setting that is not set is automatically inherited from the Elasticsearch
#output configuration, so if you have the Elasticsearch output configured such
#that it is pointing to your Elasticsearch monitoring cluster, you can simply
#uncomment the following line.
#monitoring.elasticsearch:

#================================= Migration ==================================

#This allows to enable 6.7 migration aliases
#migration.6_to_7.enabled: true

**Comment by Cyb3rWard0g** [comment]
```
#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
#Array of hosts to connect to.
hosts: ["https://131.181.97.15:9200"]

#Optional protocol and basic auth credentials.
#protocol: "https"
#username: "elastic"
#password: "changeme"
```
Elasticsearch's port 9200 is not exposed by default.

All the traffic can go either to Logstash or Kafka.

Also I would recommend to keep the config very simple and clean to start. You also have kibana pointing to port 5601, and it is not exposed in HELK

```
#Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
#This requires a Kibana endpoint configuration.
setup.kibana:

#Kibana Host
#Scheme and port can be left out and will be set to the default (http and 5601)
#In case you specify and additional path, the scheme is required: http://localhost:5601/path
#IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
host: "https://131.181.97.15:5601"
```
I would start setting the output to Kafka and point to your HELK's IP and port 9092. See if the data gets trapped by https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9990-winevent-catchall-output.conf

**Comment by Ol1ver26** [comment]
i didnt enable logstash in packetbeats.yml, I thought this would make the whole process easier. 
But my project do need logstash in the end, so is there any way i can send date to logstash first then logstash send those filtered date to elasticsearch?Or you recommend me use Kafka first?

And how should i expose port 9200 and port 5601 in HELK?

**Comment by Cyb3rWard0g** [comment]
You do not need to expose Elasticsearch if you want to send data to it with HELK. HELK uses Kafka or Logstash. So I would comment out the elasticsearch output and use something like this: 

```
#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  # Place your HELK IP(s) here (keep the port).
  # If you only have one Kafka instance (default for HELK) then remove the 2nd IP that has port 9093
  hosts: ["<HELK-IP>:9092","<HELK-IP>:9093"]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  max_retries: 2
  max_message_bytes: 1000000
```
Another reference: https://www.elastic.co/guide/en/beats/packetbeat/current/kafka-output.html

Make sure you comment out any other output that you have in your config.

Regarding dashboards, I wonder if you can just point it to the HELK IP and port 80. Traffic is redirected by Ngnix to the internal Docker container: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-nginx/config/basic-elk#L78

**Comment by Ol1ver26** [comment]
Thank you for your detailed explanation. 
I will go back to the school lab next Monday and have a try.
There may be new questions that will ask you.

**Comment by Cyb3rWard0g** [comment]
Sounds good @Ol1ver26 ! Keep me posted. happy to help! Enjoy the rest of your weekend.

**Comment by Ol1ver26** [comment]
Our uni's VM all shut down today due to overloaded, but i will have a try as soon as it fixed.

**Comment by Ol1ver26** [comment]
@Cyb3rWard0g Sorry didnt do much recently, the school's VM has been bad performance (intermittently loogin problem), making it impossible to work. I will continue as soon as the VM is repaired.
