### ISSUE TITLE
winlogbeat7.4  Not working properly HELK

### ISSUE THREAD

**Issue by letmejustdoit** [Cyb3rWard0g/HELK#364]
**Describe the problem**
I'm the docker on the new system to complete the test, but I can't run as well as anyone else.

Discover: Could not locate that index-pattern-field (id: @timestamp)
Error: Could not locate that index-pattern-field (id: @timestamp)
    at FieldParamType.deserialize (https://127.0.0.1:8088/bundles/commons.bundle.js:3:1442890)
    at https://127.0.0.1:8088/bundles/commons.bundle.js:3:250976
    at Array.forEach (<anonymous>)
    at AggConfig.setParams (https://127.0.0.1:8088/bundles/commons.bundle.js:3:250496)
    at AggConfig.set (https://127.0.0.1:8088/bundles/commons.bundle.js:3:256216)
    at new AggConfig (https://127.0.0.1:8088/bundles/commons.bundle.js:3:250273)
    at AggConfigs.createAggConfig (https://127.0.0.1:8088/bundles/commons.bundle.js:3:245702)
    at https://127.0.0.1:8088/bundles/commons.bundle.js:3:243863
    at Array.forEach (<anonymous>)
    at new AggConfigs (https://127.0.0.1:8088/bundles/commons.bundle.js:3:243825)

No matching indices found: No indices match pattern "logs-endpoint-winevent-sysmon-*"

**What steps did you take trying to fix the issue?**
Upgrade winlogbeat 7.3 to 7.4.It's still impossible to solve the problem.
**How could we replicate the issue?**

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

Successfully built e927996a6b6c
Successfully tagged docker_helk-elastalert:latest
Creating helk-elasticsearch ... done
Creating helk-kibana        ... done
Creating helk-logstash      ... done
Creating helk-nginx         ... done
Creating helk-zookeeper     ... done
Creating helk-elastalert    ... done
Creating helk-kafka-broker  ... done
Creating helk-ksql-server   ... done
Creating helk-ksql-cli      ... done

**What version of HELK are you using?**

**What OS are you using to host the HELK?**
Centos7.4
**Any additional context?**
other log files, pictures, etc.

**Comment by Cyb3rWard0g** [comment]
Can you please share your Winlogbeat config?

**Comment by Cyb3rWard0g** [comment]
can you check that your windows box can reach the IP address of your HELK?

**Comment by letmejustdoit** [comment]
[root@8f2232e8a36d elasticsearch]# curl 127.0.0.1:9200/_cat/indices?v 
health status index                                        uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   elastalert_status                            lWyErjbeSiGSHp2lEGwvNA   1   1          0            0       283b           283b
yellow open   elastalert_status_silence                    JxgyYSLqSS2XeUA43ACAJw   1   1          0            0       283b           283b
yellow open   elastalert_status_past                       zoPE7T9ZQ3eg81L-sjrAdw   1   1          0            0       283b           283b
green  open   .monitoring-logstash-7-2019.10.25            fJA_gwQ0SKymXOBReYzrHw   1   0     101318            0     27.9mb         27.9mb
green  open   .kibana_task_manager                         CP1H7jgMQXas5OO2rp1XCQ   1   0          2            0     45.6kb         45.6kb
green  open   .monitoring-kibana-7-2019.10.25              _1uW9P_7RQmQ2eu18Q8Lzw   1   0        329            0    168.9kb        168.9kb
green  open   .monitoring-es-7-2019.10.25                  uJwLkmRHTeejzvMwfu1mPQ   1   0       5476         5751      3.6mb          3.6mb
green  open   logs-endpoint-winevent-additional-2019.10.25 WpKGKol8SE2HjLthT-8G_Q   1   0       8624            0     29.7mb         29.7mb
yellow open   elastalert_status_error                      w6eb5jI1QL6w7iDGzYKixg   1   1          0            0       283b           283b
green  open   .kibana_1                                    p_HMhw6MQ1yLbb8Icmv20Q   1   0        270            4    162.4kb        162.4kb
yellow open   elastalert_status_status                     mSNr4r27TeygYXOWYaCMtg   1   1      27462            0      3.9mb          3.9mb
yellow open   mitre-attack-2019.10.25                      Y7ZbDFZ9SDmSJifFSZofvA   1   1       8624            0       34mb           34mb

-----------------------------------------------
A lot of machines have been installed. Still, no index, no timestamp. Is it necessary to use js in winlogbeat to process fields?

No matching indices found: No indices match pattern "logs-endpoint-winevent-sysmon-*"
No matching indices found: No indices match pattern "logs-endpoint-winevent-sysmon-*"

No matching indices found: No indices match pattern "logs-endpoint-winevent-application-*"

Discover: Could not locate that index-pattern-field (id: @timestamp)

No matching indices found: No indices match pattern "logs-endpoint-winevent-etw-*"

No matching indices found: No indices match pattern "logs-endpoint-winevent-powershell-*"

No matching indices found: No indices match pattern "sysmon-join-*"
----------------------------
config:
#======================= Winlogbeat specific options ==========================
winlogbeat.event_logs:
  - name: Application
    ignore_older: 30m
  - name: Security
    ignore_older: 30m
  - name: System
    ignore_older: 30m
  - name: Microsoft-windows-sysmon/operational
    ignore_older: 30m
  - name: Microsoft-windows-PowerShell/Operational
    ignore_older: 30m
    event_id: 4103, 4104
  - name: Windows PowerShell
    event_id: 400,600
    ignore_older: 30m
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861

#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  # Place your HELK IP(s) here (keep the port).
  # If you only have one Kafka instance (default for HELK) then remove the 2nd IP that has port 9093
  hosts: ["10.112.32.41:9092"]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  max_retries: 2
  max_message_bytes: 1000000

**Comment by neu5ron** [comment]
sorry for dropping the ball on this, can you send the output of the following:

Get operating system and version
for linux (except Mac) use:  
`cat /etc/os-release`  
for Mac/OSX use:  
`sw_vers`  
Get disk space, memory, processor cores, and docker storage  
`echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN`  
Get output of the HELK docker containers:  
`docker ps --filter "name=helk"`

```
Place all output, from the above commands, here
```
