### ISSUE TITLE
Recommended Method of Ingesting Data from Third-party Tool

### ISSUE THREAD

**Issue by ameily** [Cyb3rWard0g/HELK#365]
I have a tool that runs outside of HELK. I'm curious what's the recommended / best method of ingesting the data from the tool into HELK. Playing around with HELK and reviewing the architecture, it looks like the only external ingest point is Kafka, which is fine. However, since I'm exporting data HELK doesn't have builtin support for, it looks like I need to:

- Create a new Kafka topic for my data (modify `KAFKA_CREATE_TOPICS` variable)
- Modify Logstash to listen for the new Kafka topic
- Modify Logstash filters to properly insert the data into its own collection
- Modify Logstash templates to include the Elastic mappings for the data

All of that makes sense if I'm standing up a new HELK instance. I'm wondering how I would provide someone a "patch" to an existing HELK install to add support for ingesting the tool's data.

Any guidance here would be greatly appreciated! And if there's a better way, please let me know.

**Comment by neu5ron** [comment]
there is a beats input available in logstash. send to port 5044 on the HELK IP

**Comment by Cyb3rWard0g** [comment]
Let us know if you still have any questions about this @ameily .

**Comment by ameily** [comment]
Thanks for the help, I'm working on developing a Beat for my tool now.
