### ISSUE TITLE
Anyone have issues with Kafka logs showing up in Kibana?

### ISSUE THREAD

**Issue by boris-Clover** [Cyb3rWard0g/HELK#370]
**Describe the problem**
Kafka is receiving the logs from filebeat however not seeing the logs in Kibana. Updated the Kafka Broker listener

**What steps did you take trying to fix the issue?**

**How could we replicate the issue?**

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**

**What OS are you using to host the HELK?**

**Any additional context?**
other log files, pictures, etc.

**Comment by Cyb3rWard0g** [comment]
Can you provide some information about how you verify that you are receiving logs? and can you provide a sample of the data that is being sent to Kafka?

**Comment by boris-Clover** [comment]
Thanks for responding... Using Kafkacat... Also tried updating the ip in the logstash pipeline but that didn't work either. It's not showing in the index at all

boris@ip-10-102-1-100:~$ kafkacat -b 10.102.1.100:9092 -t filebeat -C | more
{"@timestamp":"2019-10-25T20:09:47.293Z","@metadata":{"beat":"filebeat","type":"_doc","version":"7.4.1","topic":"filebeat"},"ecs":{"version":"1.1.0"},"host":{"name":"Blah","hostname":"Blah","architecture
":"x86_64","os":{"kernel":"18.2.0","build":"18D109","platform":"darwin","version":"10.14.3","family":"darwin","name":"Mac OS X"},"id":"BA20CFAC-3D89-52C2-AAC7-6F68151C64A9"},"agent":{"ephemeral_id":"c3b4487d-a48b-43dc-b0eb-2a
5b162d4c0a","hostname":"Blah","id":"56688021-3409-46ab-b870-d418686a6d01","version":"7.4.1","type":"filebeat"},"log":{"offset":0,"file":{"path":"/var/log/system.log"}},"json":{},"message":"Oct 25 01:42:52 ch-C02XF5
XGJG5H syslogd[43]: ASL Sender Statistics","input":{"type":"log"}}
{"@timestamp":"2019-10-25T20:09:50.288Z","@metadata":{"beat":"filebeat","type":"_doc","version":"7.4.1","topic":"filebeat"},"log":{"offset":67,"file":{"path":"/var/log/system.log"}},"json":{},"message":"Oct 25 03:43:07 ch-C02
XF5XGJG5H syslogd[43]: ASL Sender Statistics","input":{"type":"log"},"ecs":{"version":"1.1.0"},"host":{"hostname":"Blah","architecture":"x86_64","name":"Blah","os":{"name":"Mac OS X","kernel":"18.2.0","b
uild":"18D109","platform":"darwin","version":"10.14.3","family":"darwin"},"id":"BA20CFAC-3D89-52C2-AAC7-6F68151C64A9"},"agent":{"version":"7.4.1","type":"filebeat","ephemeral_id":"c3b4487d-a48b-43dc-b0eb-2a5b162d4c0a","hostna
me":"Blah","id":"56688021-3409-46ab-b870-d418686a6d01"}}
{"@timestamp":"2019-10-25T20:09:50.288Z","@metadata":{"beat":"filebeat","type":"_doc","version":"7.4.1","topic":"filebeat"},"json":{},"message":"Oct 25 03:43:08 Blah com.apple.xpc.launchd[1] (com.apple.bsd.dirhelpe
r[85334]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.bsd.dirhelper","log":{"offset":134,"file":{"path":"/var/log/system.log"}},"input":{"type":"log"},"a
gent":{"type":"filebeat","ephemeral_id":"c3b4487d-a48b-43dc-b0eb-2a5b162d4c0a","hostname":"Blah","id":"56688021-3409-46ab-b870-d418686a6d01","version":"7.4.1"},"ecs":{"version":"1.1.0"},"host":{"id":"BA20CFAC-3D89-
52C2-AAC7-6F68151C64A9","hostname":"Blah","name":"Blah","architecture":"x86_64","os":{"name":"Mac OS X","kernel":"18.2.0","build":"18D109","platform":"darwin","version":"10.14.3","family":"darwin"}}}
{"@timestamp":"2019-10-25T20:09:50.289Z","@metadata":{"beat":"filebeat","type":"_doc","version":"7.4.1","topic":"filebeat"},"log":{"offset":354,"file":{"path":"/var/log/system.log"}},"json":{},"message":"Oct 25 03:43:08 ch-C0
2XF5XGJG5H timed[89]: settimeofday({0x5db2a78c,0x35dae}) == 0","input":{"type":"log"},"host":{"name":"Blah","os":{"family":"darwin","name":"Mac OS X","kernel":"18.2.0","build":"18D109","platform":"darwin","version"
:"10.14.3"},"id":"BA20CFAC-3D89-52C2-AAC7-6F68151C64A9","hostname":"Blah","architecture":"x86_64"},"agent":{"ephemeral_id":"c3b4487d-a48b-43dc-b0eb-2a5b162d4c0a","hostname":"Blah","id":"56688021-3409-46a
b-b870-d418686a6d01","version":"7.4.1","type":"filebeat"},"ecs":{"version":"1.1.0"}}

**Comment by Cyb3rWard0g** [comment]
Do you have a logstash config to handel the filebeat logs? Otherwise it will just be sent to: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9998-catch_all-output.conf . In Kibana, those catch_all indicex patterns are no created by default. however, you can create them via the Kibana console.

Management -> Kibana -> Index Patterns

![image](https://user-images.githubusercontent.com/9653181/67630871-8a2af580-f864-11e9-95ef-e3795ba55d14.png)

Then you will be able to select the indices that you want to create an index pattern for:

**Comment by boris-Clover** [comment]
So I didn't create a logstash config because the logstash.yml points to the pipeline configs. Should I just add that to the Kafka-input.conf?

HELK Kafka input conf file
# HELK build Stage: Alpha
# Author: Roberto Rodriguez (@Cyb3rWard0g)
# License: GPL-3.0

input {
  kafka {
    bootstrap_servers => "10.102.1.100:9092"
    topics => ["winlogbeat", "SYSMON_JOIN","filebeat"]
    decorate_events => true
    codec => "json"
    auto_offset_reset => "latest"
    ############################# HELK Optimizing Throughput & Latency #############################
    fetch_min_bytes => "1"
    request_timeout_ms => "40000"
    ############################# HELK Optimizing Durability #############################
    enable_auto_commit => "false"
    ############################# HELK Optimizing Availability #############################
    connections_max_idle_ms => "540000"
    session_timeout_ms => "30000"
    max_poll_interval_ms => "300000"
    #############################
    max_poll_records => "500"
    # If you have multiple logstash instances, this is your ID so that each instance consumes a slice of the Kafka pie.
    # No need to change this unless you know what your doing and for some reason have the need
    group_id => "helk_logstash"
    # Change to number of Kafka partitions, only change/set if scaling on large environment & customized your Kafka paritions
    #consumer_threads => 1
  }
}

**Comment by Cyb3rWard0g** [comment]
let me know if my previous message makes sense to troubleshoot if all you need to do is add an output logstash config like the ones I showed above. Please and thank you !

**Comment by boris-Clover** [comment]
Dammit!!! THANK YOU!!! Worked perfectly!!!  You saved me a few more hours of staring at the abyss looking at config files.. THANKS!!!

**Comment by Cyb3rWard0g** [comment]
Awesome happy to hear that! np!
