### ISSUE TITLE
No matching indices found: No indices match pattern "logs-endpoint-winevent-sysmon-*"

### ISSUE THREAD

**Issue by squ1ddy** [Cyb3rWard0g/HELK#372]
Hi,

First of all thanks for all the great work on this project. I've installed on Ubuntu 18.04 from a fresh git clone today.

I'm using the winlogbeat file from here:
https://github.com/Cyb3rWard0g/HELK/blob/master/winlogbeat/winlogbeat.yml

Which is working well to send event's etc:
![image](https://user-images.githubusercontent.com/57396486/68203192-5fd1f880-0019-11ea-8d9d-ead32641697e.png)

And the logs appear to be arriving in HELK:
![image](https://user-images.githubusercontent.com/57396486/68203536-1e8e1880-001a-11ea-8337-3081c40b516e.png)

![image](https://user-images.githubusercontent.com/57396486/68203782-affd8a80-001a-11ea-913d-72531f16789a.png)

But they do not seem to be creating indices in the correct place (apologies for the clumsy language I'm a complete novice with ELK)

![image](https://user-images.githubusercontent.com/57396486/68203848-dde2cf00-001a-11ea-8fdb-1b6da09a9b10.png)

I have tried to find people having similar issues which I did but the only material suggestion I could find was downgrading winlogbeat (which was actually fixed by Cyb3rWard0g some time ago) but I wanted to try for good measure - it made no difference.

Any help pointing me in the right direction would be very much appreciated.

Thank you.

**Comment by OmarSalimAhmed** [comment]
Facing the same issue, kafka is working well, but no indices being created

###################### Winlogbeat Configuration Example ########################

#======================= Winlogbeat specific options ===========================

# event_logs specifies a list of event logs to monitor as well as any
# accompanying options. The YAML data type of event_logs is a list of
# dictionaries.
#
# The supported keys are name (required), tags, fields, fields_under_root,
# forwarded, ignore_older, level, event_id, provider, and include_xml. Please
# visit the documentation for the complete details of each option.
# https://go.es.io/WinlogbeatConfig
#winlogbeat.event_logs:
 # - name: SilkService-Log
 #   ignore_older: 72h
winlogbeat.event_logs:
  - name: ForwardedEvents
    ignore_older: 30m

#-------------------------- Kafka output ------------------------------
#----------------------------- Kafka output --------------------------------
output.kafka:
  hosts: ["192..168.x.x:9092"]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  #max_retries: 2
  #max_message_bytes: 1000000

**Comment by OmarSalimAhmed** [comment]
Changed to winlogbeat 6.7.0 using the below config without success:
#======================= Winlogbeat specific options ==========================
winlogbeat.event_logs:
  - name: Application
    ignore_older: 30m
  - name: Security
    ignore_older: 30m
  - name: System
    ignore_older: 30m
  - name: Microsoft-windows-sysmon/operational
    ignore_older: 30m
  - name: Microsoft-windows-PowerShell/Operational
    ignore_older: 30m
    event_id: 4103, 4104
  - name: Windows PowerShell
    event_id: 400,600
    ignore_older: 30m
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861

#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  # Place your HELK IP(s) here (keep the port).
  # If you only have one Kafka instance (default for HELK) then remove the 2nd IP that has port 9093
  hosts: ["192.168.0.3:9092"]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  max_retries: 2
  max_message_bytes: 1000000

**Comment by tee2015** [comment]
Do U have data in the "logs" or in the "logs-endpoints-*" ?

**Comment by OmarSalimAhmed** [comment]
> Do U have data in the "logs" or in the "logs-endpoints-*" ?

No Data at All

Rebuilding the install now since it was new anyway, facing new errors with the installation actually.

Retrying the setup and will revert if the issue persists

**Comment by tee2015** [comment]
Did U remove the images and the containers of the old setup ? Do that by running helk_remove-container.sh
After that helk_install.sh

**Comment by neu5ron** [comment]
winlogbeat should not be the issue, let me check if it is something else. also thanks @tee2015 for some of the recommendations

**Comment by neu5ron** [comment]
ok I fixed in https://github.com/Cyb3rWard0g/HELK/pull/373
thanks for everybody's help!

let me know if any other issues. But I tested with latest winlogbeat (7.4.2) and on Sysmon, Security, and Application logs.

**Comment by neu5ron** [comment]
there was an odd one-off where windows logs were coming in via the wrong channel name / casing. I implemented this fix but my syntax was off. Anyways, it should be fixed now

**Comment by OmarSalimAhmed** [comment]
> there was an odd one-off where windows logs were coming in via the wrong channel name / casing. I implemented this fix but my syntax was off. Anyways, it should be fixed now.
> 
> Thanks for everyone's patience and help, and I apologize for the issue!

I cloned the git fresh on a new VM and it works smoothly, no errors so far.
Tried with logs forwarded centrally from a WEF and from individual PCs

Thank you

**Comment by squ1ddy** [comment]
@neu5ron I just downloaded and retested everything is working now (screenshots below). Thank you very much for getting this fixed.

If you have the time / inclination I would like to understand a bit about your troubleshooting process so I might be able to help in future?

![image](https://user-images.githubusercontent.com/57396486/68518679-2b905d80-02e1-11ea-9c9a-3ed3ed7e1439.png)

![image](https://user-images.githubusercontent.com/57396486/68518870-0819e280-02e2-11ea-8ed4-324e21b075b5.png)

I'm going to close the issue (not sure if this if for me to do?) please correct me if I'm wrong.

Thanks again.

**Comment by neu5ron** [comment]
Hey @squ1ddy thanks for asking actually :)
So basically I checked running containers using `docker ps` - and saw that `helk-logstash` was continually restarting (aka had a short uptime). Then I checked the logstash out put using  
`docker logs --follow --tail 5 helk-logstash`
Which came to conclusion that there was an issue in one of the configurations.

**Comment by squ1ddy** [comment]
Thanks @neu5ron  appreciate that. Looking forward to contributing.
