### ISSUE TITLE
ngix ssl error

### ISSUE THREAD

**Issue by Fedora-Man** [Cyb3rWard0g/HELK#374]
Suddenly I got error (Bad Gateway) while connecting to Kibana through the browser!

nginx log is showing:

```
> ==> /var/log/nginx/error.log <==
> 2019/11/05 07:31:29 [crit] 83#83: *3556 SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 172.16.1.1, server: 0.0.0.0:443
```

Any hint?

**Comment by neu5ron** [comment]
What browser and browser version are you using?

I am wondering if it may be due to NGINX config that denies certain insecure negotiation's like RC4 and such

**Comment by Fedora-Man** [comment]
I get the same error on both Chrome (Version 78.0.3904.70) and Firefox (7.0)

**Comment by neu5ron** [comment]
what information does your browser show? are you going to Kibana via a domain or direct IP?

This is usually indicative of a browser not trusting SSL/SNI or browser using incorrect ciphers (which in this case is probably not the case with the versions of browsers you are using)

**Comment by Fedora-Man** [comment]
The browser show:
**502 Bad Gateway**

And I am using the IP address.

**Comment by neu5ron** [comment]
hey sorry on the late reply - anything different on this?

**Comment by Fedora-Man** [comment]
No the same issue!

**Comment by neu5ron** [comment]
can you try to update HELK?
