### ISSUE TITLE
HELK and German Windows 10?

### ISSUE THREAD

**Issue by ystrela** [Cyb3rWard0g/HELK#379]
#### Describe the problem
Hey, I followed exactly everything ippsec does in this video: https://www.youtube.com/watch?v=C2cgvpN44is (only difference is that I use winlogbeat 7.1, which is the same version as elastic on my helk stack)

My windows machine is sending sysmon data to my helk machine on the correct port. Now, I don't have any sysmon logs in my kibana. **I think this is due to that my windows machine is in German.**  Can someone confirm if this is true?

#### Provide the output of the following commands

Get operating system and version
for linux (except Mac) use:  
`cat /etc/os-release`  
for Mac/OSX use:  
`sw_vers`  
Get disk space, memory, processor cores, and docker storage  
`echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN`  
Get output of the HELK docker containers:  
`docker ps --filter "name=helk"`

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN

Docker Space:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        94G   28G   62G  32% /

Memory:
              total        used        free      shared  buff/cache   available
Mem:              7           6           0           0           1           1
Swap:             3           0           3

Cores:
4

sudo docker ps --filter "name=helk
"
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
4e33c5d2eca0        confluentinc/cp-ksql-server:5.1.3                     "/etc/confluent/dock…"   8 days ago          Up 7 minutes        0.0.0.0:8088->8088/tcp                                     helk-ksql-server
0eeb7810b4b0        cyb3rward0g/helk-kafka-broker:2.2.0                   "./kafka-entrypoint.…"   8 days ago          Up 7 minutes        0.0.0.0:9092->9092/tcp                                     helk-kafka-broker
447c6e3e5177        cyb3rward0g/helk-zookeeper:2.2.0                      "./zookeeper-entrypo…"   8 days ago          Up 7 minutes        2181/tcp, 2888/tcp, 3888/tcp                               helk-zookeeper
6f00f1005136        docker_helk-elastalert                                "./elastalert-entryp…"   8 days ago          Up 7 minutes                                                                   helk-elastalert
bffbb36761ba        cyb3rward0g/helk-nginx:0.0.7                          "/opt/helk/scripts/n…"   8 days ago          Up 7 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                   helk-nginx
2b2b75ffcefd        docker.elastic.co/logstash/logstash:7.1.0             "/usr/share/logstash…"   8 days ago          Up 7 minutes        0.0.0.0:5044->5044/tcp, 0.0.0.0:8531->8531/tcp, 9600/tcp   helk-logstash
539b3fdf0da9        docker.elastic.co/kibana/kibana:7.1.0                 "/usr/share/kibana/s…"   8 days ago          Up 7 minutes        5601/tcp                                                   helk-kibana
5cf17597fddc        docker.elastic.co/elasticsearch/elasticsearch:7.1.0   "/usr/share/elastics…"   8 days ago          Up 7 minutes        9200/tcp, 9300/tcp                                         helk-elasticsearch

```

#### Provide the HELK installation logs located at /var/log/helk-install.log if you are having install errors

```
Place the output here
```

#### What version of HELK are you using

just provide the date you cloned the HELK repo:
```
November 10, 2019
```

##### Any additionally code or log context you would like to provide

```
Place the output here
```

#### Any additional context or input you have

pictures, comments, etc.

**Comment by Cyb3rWard0g** [comment]
Hey @ystrela , I am tracking a potential similar issue here: https://github.com/Cyb3rWard0g/HELK/issues/380 . Can you please confirm the Winlogbeat version you are using and can you share your WInlogbeat config? 

Also, can you provide an event sample that hits Kafka? I would like to know if the field names in German got something to do? I have never dealt with German field names, so I would like to have a sample to make sure it is that and not other parts in the data pipeline. 

Thank you in advance!

**Comment by Cyb3rWard0g** [comment]
might be related too (winlogbeat 7.4.0) https://github.com/Cyb3rWard0g/HELK/issues/364

**Comment by ystrela** [comment]
Hey @Cyb3rWard0g, 
Here is the winlogbeat config. I am running 7.1.0, but had the same problem with 7.4.2.
I tried 7.4.2 first, saw it didnt work, and uninstalled the 7.4.2 service and installed the 7.1.0 service. I am not sure if this screwed something up in the first place.

`# Winlogbeat 6, 7, and 8 are currently supported!
# You can download the latest stable version of winlogbeat here:
# https://www.elastic.co/downloads/beats/winlogbeat

# For simplicity/brevity we have only included only the enabled options necessary for sending windows logs to HELK.
# Please visit the Elastic documentation for the complete details of each option and full reference config:
# https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-reference-yml.html

#======================= Winlogbeat specific options ==========================
winlogbeat.event_logs:
  - name: Application
    ignore_older: 30m
  - name: Security
    ignore_older: 30m
  - name: System
    ignore_older: 30m
  - name: Microsoft-windows-sysmon/operational
    ignore_older: 30m
  - name: Microsoft-windows-PowerShell/Operational
    ignore_older: 30m
    event_id: 4103, 4104
  - name: Windows PowerShell
    event_id: 400,600
    ignore_older: 30m
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861

#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  # Place your HELK IP(s) here (keep the port).
  # If you only have one Kafka instance (default for HELK) then remove the 2nd IP that has port 9093
  hosts: ["192.168.56.102:9092"]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  max_retries: 2
max_message_bytes: 1000000`

Im not experienced at all with kafka, where/how can I find a log entry of interest for you?

I tried the following inside the kafka container:
`
bin/kafka-console-consumer.sh --bootstrap-server helk-zookeeper:2181 -topic winlogbeat 
-> no results at all `

`
bin/kafka-console-consumer.sh --bootstrap-server helk-kafka-broker:9092 -topic winlogbeat --from-beginning
[2019-11-29 22:46:04,706] WARN [Consumer clientId=consumer-1, groupId=console-consumer-70196] Error while fetching metadata with correlation id 2 : {winlogbeat=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)
[2019-11-29 22:46:04,809] WARN [Consumer clientId=consumer-1, groupId=console-consumer-70196] Error while fetching metadata with correlation id 3 : {winlogbeat=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)
[2019-11-29 22:46:04,918] WARN [Consumer clientId=consumer-1, groupId=console-consumer-70196] Error while fetching metadata with correlation id 4 : {winlogbeat=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)
[2019-11-29 22:46:05,020] WARN [Consumer clientId=consumer-1, groupId=console-consumer-70196] Error while fetching metadata with correlation id 5 : {winlogbeat=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)
[2019-11-29 22:46:05,122] WARN [Consumer clientId=consumer-1, groupId=console-consumer-70196] Error while fetching metadata with correlation id 6 : {winlogbeat=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)
`

**Comment by ystrela** [comment]
Maybe one more addition: 
Here are my elasticsearch indices. I have some information in my kibana but nothing related to winlogbeat I guess. The logs-endpoint-winevent-additional-* indices are not from winlogbeat right?

`
curl localhost:9200/_cat/indices
yellow open elastalert_status_status                     ggAgjyFhSRGpwgRJKe0_xw 1 1 115461     0  29.7mb  29.7mb
yellow open elastalert_status_past                       Zj6CiUWNRKONysrgtSR_ZQ 1 1      0     0    283b    283b
yellow open mitre-attack-2019.11.10                      uXBFg-ZcRZiX2T6v8bf6EQ 1 1   8624     0  32.7mb  32.7mb
green  open .monitoring-logstash-7-2019.11.18            jJ939mxjTDKG89qUc-Mb0Q 1 0  43888     0   9.1mb   9.1mb
yellow open elastalert_status_error                      1MzUZlvESXqf7gfpRy9o4A 1 1     40     0  57.6kb  57.6kb
yellow open mitre-attack-2019.11.17                      T_VVBJ-ST6G7mnYY4uTNKQ 1 1  17248     0  65.5mb  65.5mb
green  open .monitoring-es-7-2019.11.10                  hFY7MJh2S3KplVfppXiInw 1 0  11341 12409   5.6mb   5.6mb
green  open .monitoring-kibana-7-2019.11.17              C5rLGUbnS3eiAJ5fMRjgGQ 1 0    928     0 376.5kb 376.5kb
green  open .monitoring-kibana-7-2019.11.18              S5wj0NBLRkC4-09bjlOp0A 1 0    157     0    85kb    85kb
green  open .kibana_1                                    KBmL7hkVR0myGvNPKTL-qA 1 0    271    12 180.2kb 180.2kb
green  open logs-endpoint-winevent-additional-2019.11.10 39oAGkmiQzmLQmq4YOtG3Q 1 0   8624     0  28.6mb  28.6mb
green  open .monitoring-es-7-2019.11.18                  wk1VOBBBSC6NntIn81-Hfg 1 0   4444  4356     3mb     3mb
green  open .monitoring-kibana-7-2019.11.29              rKJXTnTaRJKDqX0KITI8uw 1 0    233     0 164.2kb 164.2kb
green  open .monitoring-logstash-7-2019.11.10            kVWUaigtT5KM2sE69ERlLg 1 0 220609     0  64.3mb  64.3mb
green  open .monitoring-logstash-7-2019.11.17            57WS8NgIRAabnV-i6P66hg 1 0 289538     0  81.9mb  81.9mb
yellow open elastalert_status_silence                    BM52OuxLQR2ydOMqpIWdvA 1 1      0     0    283b    283b
yellow open mitre-attack-2019.11.18                      Dh0HOHKvS9Kwv5uc6jDmIQ 1 1   8624     0  33.8mb  33.8mb
green  open .kibana_task_manager                         RoTfQ6m1TiaTQ62lbMh6Dg 1 0      2     0  46.1kb  46.1kb
green  open logs-endpoint-winevent-additional-2019.11.17 J939sA5hSeOK3cQUWN9FsQ 1 0   8624     0  28.4mb  28.4mb
green  open .monitoring-es-7-2019.11.29                  sUvUkkrYQnOZy0KUuJlXaw 1 0   6997  7701   5.1mb   5.1mb
yellow open elastalert_status                            WDQ2FHrERpiYRVTPDhVuCw 1 1      0     0    283b    283b
green  open .monitoring-kibana-7-2019.11.10              6b8WdrgYQc6nnIIPi7ndRg 1 0    703     0 209.1kb 209.1kb
green  open logs-endpoint-winevent-additional-2019.11.18 V03BNvh5TNS65ewra5n8Rw 1 0   8624     0  29.2mb  29.2mb
green  open .monitoring-es-7-2019.11.17                  W6_Q-sUsQl6Gg72ZHLg6qw 1 0  19980  8424  10.2mb  10.2mb
`

**Comment by Cyb3rWard0g** [comment]
Can you share your helk-kafka-broker logs please? `docker logs helk-kafka-broker`. I can see what `winlogbeat` topic was not created in your logs.

Also, can you create an index pattern for `logs-endpoint-winevent-additional`? you can do it via Kibana with management > kibana index patterns > create index pattern> logs-endpoint-winevent-additional-* and see what you get in there?

**Comment by ystrela** [comment]
Hey, I found the error by looking at the kafka logs with the command you provided. It said that it could not reach 10.0.2.15, which was the IP of my helk stack initially. See below for more details.

This is what happened: 
1. I installed HELK in a VM using the NAT network type with an IP of 10.0.2.15 initially.
2. After successful installation, I changed the network type to virtualhost only adapter and changed the IP of the HELK VM to 172.x.x.102
3. I configured winlogbeat on my windows 10 machine with IP 172.x.x.101 to send the logs to the HELK machine 172.x.x.102.
4. Now the problem was: I could see tcpdump showing the logs are received by the HELK VM, however they were not forwarded to kafka because it was initially installed with the IP: 10.0.2.15.
This means it is not possible to change the IP after HELK installation. (There probably is a way, but none that I know of. )

I fixed the problem by completely deleting helk from docker and reinstalling it, this time using NAT NETWORK as network type to avoid changing IP addresses after installation. I noticed that you need an active Internet connection to install HELK in the first place to resolve dns names. Is this correct/intended? 

Lastly, to answer the question regarding German windows10 logging, the logs are still send in english from my german windows 10 machine. 
Example Log Entry from Kibana:
´´´
Process Create:
RuleName: technique_id=T1086,technique_name=PowerShell
UtcTime: 2019-12-08 14:05:05.101
ProcessGuid: {7609d79a-0311-5ded-0000-00108ee92900}
ProcessId: 4424
Image: C:\Windows\System32\PING.EXE
FileVersion: 10.0.17763.1 (WinBuild.160101.0800)
Description: TCP/IP Ping Command
Product: Microsoft® Windows® Operating System
Company: Microsoft Corporation
OriginalFileName: ping.exe
CommandLine: "C:\Windows\system32\PING.EXE" 10.0.1.30
CurrentDirectory: C:\Users\d3ku\
User: DESKTOP-5NU0M0C\d3ku
LogonGuid: {7609d79a-ff3d-5dec-0000-00205ea90300}
LogonId: 0x3A95E
TerminalSessionId: 1
IntegrityLevel: Medium
Hashes: SHA1=8757646428A176F76E6F38458A25902A8FEBA9C0,MD5=56633150D77AE242D07727B0564430BB,SHA256=741AD992403C78A8A7DBD97C74FDA06594A247E9E2FA05A40BB6945403A90056,IMPHASH=8C3BE1286CDAD6AC1136D0BB6C83FF41
ParentProcessGuid: {7609d79a-01b3-5ded-0000-00107eab2400}
ParentProcessId: 2760
ParentImage: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
ParentCommandLine: "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
´´´

Thanks a lot for your help, if you have any more questions, I will gladly answer them, if not you can close this issue. :)

PS: (I noticed the log command was in the install documentation afterwards, should have RTFM, right? :D )

**Comment by Cyb3rWard0g** [comment]
Awesome thank you very much for providing all those details @ystrela
