### ISSUE TITLE
Winlog events not displaying in Kibana

### ISSUE THREAD

**Issue by premum** [Cyb3rWard0g/HELK#380]
Hi,

I have configured HELK in Debian 10 and all the necessary docker services are running fine.
I have joined a Windows Server 2012 R2 using Winlogbeat 7.4.2 .
I am able to see the logs coming from Windows machine in Kafka, but the index patterns in Kibana are not created yet.
Loading the kibana page keeps on showing following error.
    No matching indices found: No indices match pattern "logs-endpoint-*"
    Discover: Could not locate that index-pattern-field (id: @timestamp)

Only the elastalert indices are created so far.
What could be the issue., how to fix it?
I have used the sample winlogbeat.yml given as part of the HELK project in my Windows PC.

----------------------------------------------------------------
Following are the output references:
root@demo-siem:/home/prem/helk# echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN
Docker Space:
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       246G   17G  220G   7% /

Memory:
              total        used        free      shared  buff/cache   available
Mem:             31          19           6           0           5          10
Swap:             0           0           0

Cores:
8
--------------------------------------------------------------
oot@demo-siem:/home/prem/helk#  docker ps --filter "name=helk"
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
9130ed210ae6        confluentinc/cp-ksql-cli:5.1.3                        "/bin/sh"                11 days ago         Up 24 minutes                                                                  helk-ksql-cli
a7d6ecf9d03e        confluentinc/cp-ksql-server:5.1.3                     "/etc/confluent/dock…"   11 days ago         Up 24 minutes       0.0.0.0:8088->8088/tcp                                     helk-ksql-server
6c49fe245e51        cyb3rward0g/helk-spark-worker:2.4.3                   "./spark-worker-entr…"   11 days ago         Up 24 minutes                                                                  helk-spark-worker
a58876efabcb        cyb3rward0g/helk-kafka-broker:2.2.0                   "./kafka-entrypoint.…"   11 days ago         Up 24 minutes       0.0.0.0:9092->9092/tcp                                     helk-kafka-broker
ae4933c5463f        cyb3rward0g/helk-zookeeper:2.2.0                      "./zookeeper-entrypo…"   11 days ago         Up 24 minutes       2181/tcp, 2888/tcp, 3888/tcp                               helk-zookeeper
ba277691fc5d        cyb3rward0g/helk-spark-master:2.4.3                   "./spark-master-entr…"   11 days ago         Up 24 minutes       7077/tcp, 0.0.0.0:8080->8080/tcp                           helk-spark-master
c8bd31a1eadb        docker_helk-elastalert                                "./elastalert-entryp…"   11 days ago         Up 24 minutes                                                                  helk-elastalert
7baeb30df386        docker_helk-jupyter                                   "/opt/jupyter/script…"   11 days ago         Up 24 minutes       8000/tcp, 8888/tcp                                         helk-jupyter
70636edf578a        docker.elastic.co/logstash/logstash:7.1.0             "/usr/share/logstash…"   11 days ago         Up 24 minutes       0.0.0.0:5044->5044/tcp, 0.0.0.0:8531->8531/tcp, 9600/tcp   helk-logstash
6702ffa76f8e        cyb3rward0g/helk-nginx:0.0.7                          "/opt/helk/scripts/n…"   11 days ago         Up 24 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                   helk-nginx
af3c2952a987        docker.elastic.co/kibana/kibana:7.1.0                 "/usr/share/kibana/s…"   11 days ago         Up 24 minutes       5601/tcp                                                   helk-kibana
bf312f31b150        docker.elastic.co/elasticsearch/elasticsearch:7.1.0   "/usr/share/elastics…"   11 days ago         Up 24 minutes       9200/tcp, 9300/tcp                                         helk-elasticsearch

**Comment by Cyb3rWard0g** [comment]
Hey @premum , I cannot replicate the issues that you are having. I created the following AWS cloud formation templates to deploy  a HELK stack with a Windows box and it is working fine. 

CFN Files: https://github.com/hunters-forge/Blacksmith/tree/master/aws/HELK
HELK installation: https://github.com/hunters-forge/Blacksmith/blob/master/aws/HELK/cfn-templates/helk-server-template.json#L148-L159
Winlogbeat installation (7.4.0): https://github.com/hunters-forge/Blacksmith/blob/master/aws/HELK/cfn-files/scripts/default/Install-Winlogbeat.ps1#L12 

![image](https://user-images.githubusercontent.com/9653181/69696572-09068e80-10ae-11ea-8d58-663a7f163fde.png)

I am using Winlogbeat 7.4.0 but it doesnt look like there were major changes from 7.4.0 to 7.4.2 . Can you share your Winlogbeat config? This is mine: https://github.com/hunters-forge/Blacksmith/blob/master/aws/HELK/cfn-files/configs/winlogbeat.yml

**Comment by Cyb3rWard0g** [comment]
might be related https://github.com/Cyb3rWard0g/HELK/issues/364

**Comment by premum** [comment]
Hi

I replaced winlogbeat 7.4.2 with 7.4.0 and used exactly the same winlogbeat config file you have shared.., still no index created.

I am able to see the data coming to kafka using "bin/kafka-console-consumer.sh" under "winlogbeat" topic. What settings might be wrong.?
I have been trying to set this up for more than 2 weeks now..but unfortunately struck with this index creation error.
Does HELK takes input from linux machines., can I test it with filebeat or metricbeat from a linux client.?

**Comment by premum** [comment]
Sample log received in kafka:
{"@timestamp":"2019-11-27T08:07:56.654Z","@metadata":{"beat":"winlogbeat","type":"_doc","version":"7.4.0","topic":"winlogbeat"},"winlog":{"version":5,"opcode":"Info","process":{"pid":2836,"thread":{"id":1732}},"channel":"Microsoft-Windows-Sysmon/Operational","event_id":1,"record_id":7712,"task":"Process Create (rule: ProcessCreate)","provider_guid":"{5770385F-C22A-43E0-BF4C-06F5698FFBD9}","api":"wineventlog","provider_name":"Microsoft-Windows-Sysmon","user":{"identifier":"S-1-5-18","name":"SYSTEM","domain":"NT AUTHORITY","type":"User"},"event_data":{"IntegrityLevel":"High","CurrentDirectory":"C:\\Windows\\system32\\","ProcessGuid":"{03850C27-2EDC-5DDE-0000-0010CA204200}","User":"WIN-P6RLVADJKPL\\Administrator","LogonGuid":"{03850C27-2E9A-5DDE-0000-002010D34000}","ParentCommandLine":"winlogon.exe","OriginalFileName":"scrnsave","ParentProcessId":"1132","Company":"Microsoft Corporation","TerminalSessionId":"2","ParentImage":"C:\\Windows\\System32\\winlogon.exe","Product":"Microsoft® Windows® Operating System","Description":"Blank Screen Saver","LogonId":"0x40d310","Hashes":"SHA1=6E34F71EBA01846B92F12B6BCF1BAF1D46F21375","Image":"C:\\Windows\\System32\\scrnsave.scr","CommandLine":"C:\\Windows\\system32\\scrnsave.scr /s","UtcTime":"2019-11-27 08:07:56.654","ParentProcessGuid":"{03850C27-2DF1-5DDE-0000-001038894000}","ProcessId":"1312","FileVersion":"6.3.9600.16384 (winblue_rtm.130821-1623)"},"computer_name":"WIN-P6RLVADJKPL"},"event":{"kind":"event","code":1,"action":"Process Create (rule: ProcessCreate)","created":"2019-11-27T08:07:57.719Z"},"log":{"level":"information"},"message":"Process Create:\nRuleName: \nUtcTime: 2019-11-27 08:07:56.654\nProcessGuid: {03850C27-2EDC-5DDE-0000-0010CA204200}\nProcessId: 1312\nImage: C:\\Windows\\System32\\scrnsave.scr\nFileVersion: 6.3.9600.16384 (winblue_rtm.130821-1623)\nDescription: Blank Screen Saver\nProduct: Microsoft® Windows® Operating System\nCompany: Microsoft Corporation\nOriginalFileName: scrnsave\nCommandLine: C:\\Windows\\system32\\scrnsave.scr /s\nCurrentDirectory: C:\\Windows\\system32\\\nUser: WIN-P6RLVADJKPL\\Administrator\nLogonGuid: {03850C27-2E9A-5DDE-0000-002010D34000}\nLogonId: 0x40D310\nTerminalSessionId: 2\nIntegrityLevel: High\nHashes: SHA1=6E34F71EBA01846B92F12B6BCF1BAF1D46F21375\nParentProcessGuid: {03850C27-2DF1-5DDE-0000-001038894000}\nParentProcessId: 1132\nParentImage: C:\\Windows\\System32\\winlogon.exe\nParentCommandLine: winlogon.exe","ecs":{"version":"1.1.0"},"host":{"name":"WIN-P6RLVADJKPL"},"agent":{"type":"winlogbeat","ephemeral_id":"4a821028-b61d-4e37-a4bf-fe396878f5ea","hostname":"WIN-P6RLVADJKPL","id":"5f74632e-eddf-4acd-9630-b13408ffadda","version":"7.4.0"}}

**Comment by Cyb3rWard0g** [comment]
can you change the time window to one year and refresh the web page. can you also share the logs from your kafka broker? latest logs.  with no errors in Logstash, it does not seem to be pipeline. Also, with @neu5ron pipeline configs to send everything to an index, it does not seem to be a bad filter in the pipeline. mmm. Any ideas @neu5ron whenever you have a chance? Can you test HELK with a Windows box sending logs over? Please and thank you!

**Comment by ConfusedOldMan** [comment]
I had the same problem when I tried to change my IP by issuing the two commands here: https://github.com/Cyb3rWard0g/HELK/wiki/Update-Kafka-Broker-IP . Used fresh ubuntu 18.04.3 and windows 10 enterprise images with recommended winlog config. Winlogbeat.exe -e showed successful connection and published records to kafka, guessing the issue is between kafka and ELK, and something isn't getting updated with just those two commands. 
I removed the containers and did a fresh install and I now see sysmon and endpoint logs.

**Comment by Cyb3rWard0g** [comment]
Hey @ConfusedOldMan , if you got a `successful connection` when publishing records to Kafka, after updating your kafka IP, then the `two commands` worked properly. Data not showing seems to be either a delay in Logstash or maybe logstash might be showing some error messages? I cannot replicate the issue on my end.
