### ISSUE TITLE
mitre-attack index question

### ISSUE THREAD

**Issue by omrirefaeli** [Cyb3rWard0g/HELK#381]
Hi ☺
just a small question, is the built-in index of mitre-attack is meant to log actual logs coming from remote hosts or to map the mitre attack framework tecniques to make it convenient on Kibana.
If the answer to this is the first option I mentioned, is there a specific data source that I need to feed Helk with?
thanks a lot, keep up the good work!

**Comment by Cyb3rWard0g** [comment]
Hey @omrirefaeli , thank you for your question and I appreciate the feedback :) . The mitre-attack index is just to show the data available in the ATT&CK's public TAXII server. It is not yet built to tag events or anything like that. That is something that is coming soon with the development of the project OSSEM: https://github.com/hunters-forge/OSSEM
