### ISSUE TITLE
Minor typo in helk_install.sh

### ISSUE THREAD

**Issue by yaap7** [Cyb3rWard0g/HELK#382]
I'm a huge fan of your work!
It helps docker-noobs like me to use such a great tool.

Thanks a lot for the effort your put in it!

#### Minor typo in helk_install.sh

I guess there is an incorrect command in `helk_install.sh` where the configuration file is at the end of the line.

This is what is in the install script:

``` bash
echo " [+] sudo docker-compose stop $COMPOSE_CONFIG"
```

and I had issues using it, so I think the correct command should be as follow:

``` bash
echo " [+] sudo docker-compose -f $COMPOSE_CONFIG stop"
```

So here is the modification I suggest:

``` diff
$ git diff docker/helk_install.sh
diff --git a/docker/helk_install.sh b/docker/helk_install.sh
index 95ef2bf..cd6d0f3 100755
--- a/docker/helk_install.sh
+++ b/docker/helk_install.sh
@@ -513,7 +513,7 @@ show_final_information(){
     echo "IT IS HUNTING SEASON!!!!!"
     echo " "
     echo "You can stop all the HELK docker containers by running the following command:"
-    echo " [+] sudo docker-compose stop $COMPOSE_CONFIG"
+    echo " [+] sudo docker-compose -f $COMPOSE_CONFIG stop"
     echo " "
 }
 ```

**Comment by Cyb3rWard0g** [comment]
Thank you @yaap7 ! I will add it for the next update. I appreciate it.
