### ISSUE TITLE
unable to pass Step 9/18 of helk installation in ubuntu 18.04

### ISSUE THREAD

**Issue by hisanmehmood** [Cyb3rWard0g/HELK#384]
i am trying to install HELK on freshly installed Ubuntu 18.04 but unable to pass through Step 9/18.

i have tried many many times but same issue

Error Message:
""
Installed /usr/local/lib/python3.6/dist-packages/keyring-19.3.0-py3.6.egg
Searching for secretstorage
Reading https://pypi.python.org/simple/secretstorage/
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/secretstorage/: [Errno 99] Cannot assign requested address -- Some packages may not be found!
Couldn't find index page for 'secretstorage' (maybe misspelled?)
No local packages or working download links found for secretstorage
error: Could not find suitable distribution for Requirement.parse('secretstorage')
Service 'helk-elastalert' failed to build: The command '/bin/sh -c apt-get update -qq && apt-get install -qqy --no-install-recommends   libmagic-dev   build-essential   python3-setuptools   git   python3-pip   python3-dev   python3-setuptools   tzdata   && apt-get -qy clean   autoremove   && rm -rf /var/lib/apt/lists/*   && git clone https://github.com/Yelp/elastalert.git ${ESALERT_HOME}   && bash -c 'mkdir -pv /etc/elastalert/rules'   && cd ${ESALERT_HOME}   && sudo pip3 install --upgrade pip   && pip3 install urllib3   && pip3 install -r requirements.txt   && python3 setup.py install   && git clone https://github.com/Cyb3rWard0g/sigma.git ${ESALERT_SIGMA_HOME}   && pip3 install -r ${ESALERT_SIGMA_HOME}/tools/requirements.txt' returned a non-zero code: 1
""

i installed secretstorage manually with 'pip3 install secretstorage', but still same issue

**Comment by Cyb3rWard0g** [comment]
can you provide the whole log. I cannot see where secretstorage is referenced or if it is a dependency of a specific package. secretstorage is not specified in Sigma or Elastlaert as far as I can tell (requirements.txt file). Also, can you provide more information about your build? What build option are you using? Thank you in advance!

**Comment by hisanmehmood** [comment]
i am using option 2

[helk-install.log](https://github.com/Cyb3rWard0g/HELK/files/3920416/helk-install.log)

**Comment by neu5ron** [comment]
@hisanmehmood 
#### Provide the output of the following commands

Get operating system and version
for linux (except Mac) use:  
`cat /etc/os-release`  
for Mac/OSX use:  
`sw_vers`  
Get disk space, memory, processor cores, and docker storage  
`echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN`  
Get output of the HELK docker containers:  
`docker ps --filter "name=helk"`

```
Place all output, from the above commands, here
```

#### Provide the HELK installation logs located at /var/log/helk-install.log if you are having install errors

```
Place the output here
```

#### What version of HELK are you using

just provide the date you cloned the HELK repo:
```
Place the date here
```

#### What version of Winlogbeat are you using if you are using Windows/WEF logs

just provide the date you cloned the HELK repo:
```
Place the version here
```

##### What steps did you take trying to fix the issue

##### How could we replicate the issue

##### Any additionally code or log context you would like to provide

```
Place the output here
```

#### Any additional context or input you have

pictures, comments, etc.
