### ISSUE TITLE
unable to differenciate between multiple hosts

### ISSUE THREAD

**Issue by hisanmehmood** [Cyb3rWard0g/HELK#385]
i want to import logs from multiple resources i.e multiple windows and linux systems
but unable to see host(s) identity, is there any way to identify between multiple hosts??

also i have used winlogbeat configuration file from HELK repo

![source ip](https://user-images.githubusercontent.com/33222670/70860571-2019fd00-1f45-11ea-9874-f22a346b83f3.JPG)

**Comment by neu5ron** [comment]
maybe I am missing some information, but this index you are in is just the status of the rules running..
logs themselves are in `logs-*` and rule fires from elastalert are in `elastalert_status`

**Comment by Cyb3rWard0g** [comment]
Let us know if you have any other issues @hisanmehmood
