### ISSUE TITLE
ELK to Helk?  Straight from your blog...

### ISSUE THREAD

**Issue by mathurin68** [Cyb3rWard0g/HELK#40]
Awww I used your blog awhile ago to build ELK, complete with reverse proxy.  How bout some steps to go from ELK to HELK?  Awesome work dude, your one of the few I have set to receive twitter notifications!!

Signed.  

Lazy

**Comment by Cyb3rWard0g** [comment]
Thank you very much for the feedback @mathurin68 👍 It means a lot. I am actually almost done with a blog post introducing the HELK and what I wish I had with my first ELK :) It will talk about a few of the features that make the HELK an upgrade from a regular ELK. I will be hopefully posting that this week. I  was busy with several projects that I could not release a few blog posts that I have there sitting and they are all about HELK ;) Thank you again

**Comment by Cyb3rWard0g** [comment]
Closing this issue since there is nothing to fix or update. Thank you for the feedback 👍
