### ISSUE TITLE
Scala version not existing

### ISSUE THREAD

**Issue by troplolBE** [Cyb3rWard0g/HELK#400]
#### Describe the problem
In the newest version of the Dockerfile in the helk-kafka-base directory, a variable called SCALA_VERSION is set to 2.13.1 to download Kafka. The problem is that there is no version of Kafka corresponding to kafka-2.13.1-2.4.0. The version available is kafka-2.13-2.4.0.

This results in not downloading the latest version of Kafka and scala.

To resolve this you just need to change the SCALA_VERSION to 2.13.

![image](https://user-images.githubusercontent.com/12971225/72252080-04b31800-35ff-11ea-8754-abef91d8c571.png)

#### What version of HELK are you using

just provide the date you cloned the HELK repo:
```
Cloned 13 January 2020
```

##### Any additional code or log context you would like to provide

```
Place the output here
```

**Comment by neu5ron** [comment]
thanks for report @troplolBE !
