### ISSUE TITLE
Kafka container not up to date

### ISSUE THREAD

**Issue by troplolBE** [Cyb3rWard0g/HELK#404]
#### Describe the problem
The helk-kafka-base container is not being rebuilt but only downloaded from the docker hub. This prevents the download of the newest version of Kafka. I may be wrong and unable to use docker properly but I did a fresh installation twice (Centos 7 and Ubuntu 18.04) and on both installations, the Kafka version was still kafka-2.12-2.2.0.

I haven't managed to fix the issue by changing the docker-compose or the Dockerfile files but I think that it is fixable by updating the image on the Docker Hub.

Content of /libs dir in halk-kafka-broker container:
![image](https://user-images.githubusercontent.com/12971225/72344085-b2422c00-36d0-11ea-9b43-d270b7a812b1.png)

Content of /helk-kafka-base/Dockerfile:
![image](https://user-images.githubusercontent.com/12971225/72344227-fdf4d580-36d0-11ea-90fc-8853a958f500.png)

#### What version of HELK are you using

just provide the date you cloned the HELK repo:
```
Cloned on January 14 2020
```

##### What steps did you take trying to fix the issue
I triad and am still trying to change the Dockerfile files to make Docker build the helk-kafka-base image localy and not remotely.

##### How could we replicate the issue
Simply by installing HELK on a machine.

**Comment by neu5ron** [comment]
thanks for posting this, will have an update tomorrow (EST timezone).

**Comment by neu5ron** [comment]
this should be fixed now, please confirm / let me know otherwise

**Comment by troplolBE** [comment]
Hi @neu5ron ,

Thank you for your quick response and action time. The new container is now downloaded properly and the latest version of kafka is now downloaded.
