### ISSUE TITLE
ElastAlert rule test passed but writing status error log

### ISSUE THREAD

**Issue by tgocoh** [Cyb3rWard0g/HELK#408]
Installed HELK with Elk stack 7.5 on Ubuntu 18.04. So, Many error logs written indexed by elastalert error status. I checked sample rule from it but this rule working fine when test with elastalert-test-rule tool.   
![image](https://user-images.githubusercontent.com/45187522/72420852-64095780-37ba-11ea-9f8e-7bcd85c49f29.png)

![image](https://user-images.githubusercontent.com/45187522/72420797-50f68780-37ba-11ea-96e1-a4c6abe91ea6.png)

**Comment by neu5ron** [comment]
can you send the output of the following command, note it must be run with in the HELK directory.
`cd HELK && cat .git/refs/heads/master`

**Comment by neu5ron** [comment]
this should have been fixed, atleast a very similar issue, yesterday/today, so it may be worth updating.

**Comment by tgocoh** [comment]
How I update without delete elasticsearch logs and configs and only reinstall elastalert? This patch is related other applications?

**Comment by neu5ron** [comment]
you can run the `helk_update.sh` script
