### ISSUE TITLE
Remove script not fully functionnal

### ISSUE THREAD

**Issue by troplolBE** [Cyb3rWard0g/HELK#411]
#### Describe the problem
I install and remove HELK a lot for testing purposes and remarked that the `helk_remove_containers` script only removes the containers but not all the rest that the installation script creates. I changed the script a little bit and want to propose it to everybody.

You can find new code here:
https://hastebin.com/obuxozekop.bash
or in the pull request #410 

Please let me know if this is useful or not.

**Comment by neu5ron** [comment]
nice! we need to add a check to perform `docker volume prune` on the es_data module - is that something can be done?

**Comment by troplolBE** [comment]
Hey @neu5ron 

I will work on that tomorrow. (Belgium time) Can you explain me what that command does ?

**Comment by troplolBE** [comment]
Hey @neu5ron 

I made a ne version with the prune command if chosen for.
here is the code on pastebin: https://pastebin.com/yQqwk7j8

I haven't changed it in the PR yet, please let me know if this is what you had in mind.

**Comment by neu5ron** [comment]
yup thats it, awesome!

**Comment by troplolBE** [comment]
Do you want me to adapt this in my pull request ?

**Comment by neu5ron** [comment]
yeah that would be great, just add the command to be specific using `docker volume rm docker_esdata`

**Comment by troplolBE** [comment]
After some investigation, I think that there is no need to integrate that command. The `-v` option in the `docker-compose down -f $FILE down --rmi all -v` command already deletes the volume `docker_esdata`.

![image](https://user-images.githubusercontent.com/12971225/72785443-8de3d380-3c2b-11ea-8843-b57ea3da6010.png)

**Comment by troplolBE** [comment]
![image](https://user-images.githubusercontent.com/12971225/72786499-051a6700-3c2e-11ea-89d6-17f7667d98a1.png)

**Comment by neu5ron** [comment]
merged.. in https://github.com/Cyb3rWard0g/HELK/pull/415
