### ISSUE TITLE
Error Code 127

### ISSUE THREAD

**Issue by gatorcc** [Cyb3rWard0g/HELK#42]
When attempting install on a fresh Ubuntu 16.04 LTS build I am seeing this error

![image](https://user-images.githubusercontent.com/38140959/38437128-832738dc-39a4-11e8-8005-88da68859652.png)

Any help would be appreciated

**Comment by Cyb3rWard0g** [comment]
Hey @gatorcc !! Can you provide your Installation logs. They are locally in the /var/log folder. Please submit the helk-install.log file. Thank you! Happy to help troubleshoot this error!
/var/log/helk-install.log

**Comment by Cyb3rWard0g** [comment]
Hey @gatorcc , I tested it again and I believe the way how the script from docker changed. I updated it in this latest commit https://github.com/Cyb3rWard0g/HELK/commit/6054e2be9abf4f1b1826a44b03583199d80e1bbb . I tested the build and it is working fine now. Let me know if you still have issues with it. Thank you

**Comment by gatorcc** [comment]
Looks like a certificate issue more than a docker issue
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libcurl3-gnutls
The following NEW packages will be installed:
  curl
The following packages will be upgraded:
  libcurl3-gnutls
1 upgraded, 1 newly installed, 0 to remove and 86 not upgraded.
Need to get 323 kB of archives.
After this operation, 339 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libcurl3-gnutls amd64 7.47.0-1ubuntu2.7 [185 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 curl amd64 7.47.0-1ubuntu2.7 [138 kB]
Fetched 323 kB in 0s (1,038 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 177161 files and directories currently installed.)

Preparing to unpack .../libcurl3-gnutls_7.47.0-1ubuntu2.7_amd64.deb ...

Unpacking libcurl3-gnutls:amd64 (7.47.0-1ubuntu2.7) over (7.47.0-1ubuntu2.6) ...

Selecting previously unselected package curl.

Preparing to unpack .../curl_7.47.0-1ubuntu2.7_amd64.deb ...

Unpacking curl (7.47.0-1ubuntu2.7) ...

Processing triggers for libc-bin (2.23-0ubuntu10) ...

Processing triggers for man-db (2.7.5-1) ...

Setting up libcurl3-gnutls:amd64 (7.47.0-1ubuntu2.7) ...

Setting up curl (7.47.0-1ubuntu2.7) ...

Processing triggers for libc-bin (2.23-0ubuntu10) ...

curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
chmod: cannot access 'scripts/get-docker.sh': No such file or directory
./helk_install.sh: line 156: scripts/get-docker.sh: No such file or directory
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
chmod: cannot access 'scripts/get-docker.sh': No such file or directory
./helk_install.sh: line 156: scripts/get-docker.sh: No such file or directory
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
chmod: cannot access 'scripts/get-docker.sh': No such file or directory
./helk_install.sh: line 156: scripts/get-docker.sh: No such file or directory
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
chmod: cannot access 'scripts/get-docker.sh': No such file or directory
./helk_install.sh: line 156: scripts/get-docker.sh: No such file or directory
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
chmod: cannot access 'scripts/get-docker.sh': No such file or directory
./helk_install.sh: line 156: scripts/get-docker.sh: No such file or directory
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
chmod: cannot access 'scripts/get-docker.sh': No such file or directory
./helk_install.sh: line 156: scripts/get-docker.sh: No such file or directory
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
chmod: cannot access 'scripts/get-docker.sh': No such file or directory
./helk_install.sh: line 156: scripts/get-docker.sh: No such file or directory
curl: (22) The requested URL returned error: 401 Authorization Required
chmod: cannot access 'get-docker.sh': No such file or directory
./helk_install.sh: line 75: ./get-docker.sh: No such file or directory

**Comment by Cyb3rWard0g** [comment]
Are those logs from before the last commit??

**Comment by gatorcc** [comment]
After.  I deleted the old install and re-downloaded then tried the install again.

**Comment by Cyb3rWard0g** [comment]
mmm did you try to add the --insecure flag to the curl command that starts the install_docker function?

**Comment by gatorcc** [comment]
I got a different error
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: 0.9 (Alpha)          **
** HELK ELK version: 6.2.3                  **
** License: BSD 3-Clause                    **
**********************************************
 
[HELK-INSTALLATION-INFO] Obtaining current host IP..
[HELK-INSTALLATION-INFO] Set HELK IP. Default value is your current IP: 192.168.136.135
[HELK-INSTALLATION-INFO] HELK IP set to 192.168.136.135
[HELK-INSTALLATION-INFO] HELK identified Linux as the system kernel
[HELK-INSTALLATION-INFO] Checking distribution list and version
[HELK-INSTALLATION-INFO] You're using ubuntu version xenial
[HELK-INSTALLATION-INFO] Docker is not installed
[HELK-INSTALLATION-INFO] Checking if curl is installed first
[HELK-INSTALLATION-INFO] curl is already installed
[HELK-INSTALLATION-INFO] Installing docker via convenience script..
[HELK-INSTALLATION-INFO] Docker-compose is not installed
[HELK-INSTALLATION-INFO] Checking if curl is installed first
[HELK-INSTALLATION-INFO] curl is already installed
[HELK-INSTALLATION-INFO] Installing docker-compose..
 * ERROR: Could not install docker-compose (Error Code: 1).
phil@ubuntu:~/HELK$ 

Here is the log for this error

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
gpg: no valid OpenPGP data found.
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

	curl performs SSL certificate verification by default, using a "bundle"
	 of Certificate Authority (CA) public keys (CA certs). If the default
	 bundle file isn't adequate, you can specify an alternate file
	 using the --cacert option.
	If this HTTPS server uses a certificate signed by a CA represented in
	 the bundle, the certificate verification probably failed due to a
	 problem with the certificate (it might be expired, or the name might
	 not match the domain name in the URL).
	If you'd like to turn off curl's verification of the certificate, use
	 the -k (or --insecure) option.
	curl: (6) Could not resolve host: get-docker.sh
	# Executing docker install script, commit: 8e87f31
	+ sh -c apt-get update -qq >/dev/null
	+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
	+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
	+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial edge" > /etc/apt/sources.list.d/docker.list
	+ [ ubuntu = debian ]
	+ sh -c apt-get update -qq >/dev/null
	+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
	+ sh -c docker version
	Client:
	 Version:	18.03.0-ce
	 API version:	1.37
	 Go version:	go1.9.4
	 Git commit:	0520e24
	 Built:	Wed Mar 21 23:10:01 2018
	 OS/Arch:	linux/amd64
	 Experimental:	false
	 Orchestrator:	swarm

	Server:
	 Engine:
	  Version:	18.03.0-ce
	  API version:	1.37 (minimum version 1.12)
	  Go version:	go1.9.4
	  Git commit:	0520e24
	  Built:	Wed Mar 21 23:08:31 2018
	  OS/Arch:	linux/amd64
	  Experimental:	false
	If you would like to use Docker as a non-root user, you should now consider
	adding your user to the "docker" group with something like:

	  sudo usermod -aG docker your-user

	Remember that you will have to log out and back in for this to take effect!

	WARNING: Adding a user to the "docker" group will grant the ability to run
		 containers which can be used to obtain root privileges on the
		 docker host.
		 Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
		 for more information.
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
		                         Dload  Upload   Total   Spent    Left  Speed

	  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
	100   617    0   617    0     0    471      0 --:--:--  0:00:01 --:--:--   472

	  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
	curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
	More details here: http://curl.haxx.se/docs/sslcerts.html

	curl performs SSL certificate verification by default, using a "bundle"
	 of Certificate Authority (CA) public keys (CA certs). If the default
	 bundle file isn't adequate, you can specify an alternate file
	 using the --cacert option.
	If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use

 the -k (or --insecure) option.

**Comment by Cyb3rWard0g** [comment]
I dont know why it would be doing all those certificate issues in your box. Can you curl another application to try and see it is your box and not the script itself. Let me know

**Comment by gatorcc** [comment]
Going to spin up a new vm on my home network to give it a try.

**Comment by Cyb3rWard0g** [comment]
thank you @gatorcc ! Let me know. Thank you

**Comment by Cyb3rWard0g** [comment]
Hey @gatorcc ! let me know if you still have issues with curl. I have tested the deployment of the HELK in several boxes and I am not getting those errors. I can reopen this issue if you think it is still the HELK and not a network issue in your environment (proxy?)

**Comment by jai6684** [comment]
Hi @Cyb3rWard0g ,

I tried on a fresh installation of ubuntu, again same problem occurs,

jay@jay-Virtual-Machine:~$ git clone https://github.com/Cyb3rWard0g/ATTACK-Python-Client
Cloning into 'ATTACK-Python-Client'...
remote: Counting objects: 144, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 144 (delta 49), reused 127 (delta 36), pack-reused 0
Receiving objects: 100% (144/144), 8.72 MiB | 4.14 MiB/s, done.
Resolving deltas: 100% (49/49), done.
jay@jay-Virtual-Machine:~$ cd ATTACK-Python-Client/integrations/helk_cti/
jay@jay-Virtual-Machine:~/ATTACK-Python-Client/integrations/helk_cti$ sudo ./install-helk-cti.sh
 
************************************************
**           HELK CTI Integration             **
**                                            **
** Author: Roberto Rodriguez (@Cyb3rWard0g)   **
** Author: Jose Luis Rodriguez (@Cyb3rPandaH) **
** HELK CTI version: 0.1.0 (BETA)             **
** HELK ELK version: 6.3.0                    **
** License: BSD 3-Clause                      **
************************************************
 
[HELK-CTI-INSTALLATION-INFO] Obtaining current host IP..
[HELK-CTI-INSTALLATION-INFO] HELK IP set to 0
[HELK-CTI-INSTALLATION-INFO] HELK identified Linux as the system kernel
[HELK-CTI-INSTALLATION-INFO] Checking distribution list and version
[HELK-CTI-INSTALLATION-INFO] You're using ubuntu version bionic
[HELK-CTI-INSTALLATION-INFO] Docker is not installed
[HELK-CTI-INSTALLATION-INFO] Checking if curl is installed first
[HELK-CTI-INSTALLATION-INFO] curl is not installed
[HELK-CTI-INSTALLATION-INFO] Installing curl before installing docker..
[HELK-CTI-INSTALLATION-INFO] Installing docker via convenience script..
[HELK-CTI-INSTALLATION-INFO] Docker-compose is not installed
[HELK-CTI-INSTALLATION-INFO] Checking if curl is installed first
[HELK-CTI-INSTALLATION-INFO] curl is already installed
[HELK-CTI-INSTALLATION-INFO] Installing docker-compose..
[HELK-CTI-INSTALLATION-INFO] Dockerizing HELK..
[HELK-CTI-INSTALLATION-INFO] Building & running HELK via docker-compose
*** ERROR: Could not run HELK via docker-compose (Error Code: 1).**
jay@jay-Virtual-Machine:~/ATTACK-Python-Client/integrations/helk_cti$ ^C

Kindly help me,

**Comment by Cyb3rWard0g** [comment]
Hey @jai6684. Can you provide the HELK's Log File?? should be /var/log/helk-install.log

**Comment by rzietlow** [comment]
I got this error on a fresh ubuntu install as well (16.04)


root@helk:~/HELK# ./helk_install.sh

**********************************************
**          HELK - THE HUNTING ELK          **
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: 0.9 (Alpha)          **
** HELK ELK version: 6.3.0                  **
** License: BSD 3-Clause                    **
**********************************************

[HELK-INSTALLATION-INFO] HELK being hosted on a Linux box
[HELK-INSTALLATION-INFO] Available Memory: 15
[HELK-INSTALLATION-INFO] Available Disk: 71
[HELK-INSTALLATION-INFO] Obtaining current host IP..
[HELK-INSTALLATION-INFO] Set HELK IP. Default value is your current IP: 10.16.1.17
[HELK-INSTALLATION-INFO] HELK IP set to 10.16.1.17
[HELK-INSTALLATION-INFO] HELK identified Linux as the system kernel
[HELK-INSTALLATION-INFO] Checking distribution list and version
[HELK-INSTALLATION-INFO] You're using ubuntu version xenial
[HELK-INSTALLATION-INFO] Docker already installed
[HELK-INSTALLATION-INFO] Docker-compose is not installed
[HELK-INSTALLATION-INFO] Checking if curl is installed first
[HELK-INSTALLATION-INFO] curl is already installed
[HELK-INSTALLATION-INFO] Installing docker-compose..
[HELK-INSTALLATION-INFO] Dockerizing HELK..
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 262144
[HELK-INSTALLATION-INFO] Setting KAFKA ADVERTISED_LISTENER value...
[HELK-INSTALLATION-INFO] Setting ES_JAVA_OPTS value...
[HELK-INSTALLATION-INFO] Building & running HELK via docker-compose
 * ERROR: Could not run HELK via docker-compose (Error Code: 127).

root@helk:~/HELK# tail /var/log/helk-install.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1163      0 --:--:-- --:--:-- --:--:--  1164
100 8288k  100 8288k    0     0  2301k      0  0:00:03  0:00:03 --:--:-- 2997k
./helk_install.sh: line 80: docker-compose: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1054      0 --:--:-- --:--:-- --:--:--  1054
100 8288k  100 8288k    0     0  2343k      0  0:00:03  0:00:03 --:--:-- 3057k
./helk_install.sh: line 80: docker-compose: command not found


line 80 is as follows:
  docker-compose up --build -d >> $LOGFILE 2>&

When I try to run that I get a path error


root@helk:~/HELK# docker-compose up
Command 'docker-compose' is available in '/usr/local/bin/docker-compose'
The command could not be located because '/usr/local/bin' is not included in the PATH environment variable.
docker-compose: command not found

root@helk:~/HELK# ls -l /usr/local/bin/docker-compose
-rwxr-xr-x 1 root root 8486976 Jul  6 18:26 /usr/local/bin/docker-compose
root@helk:~/HELK# echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/snap/bin:/opt/puppetlabs/bin
root@helk:~/HELK# id
uid=0(root) gid=0(root) groups=0(root)
root@helk:~/HELK#

**Comment by Cyb3rWard0g** [comment]
your image has Docker already installed. Run the script on a fresh image without Docker. 

```
[HELK-INSTALLATION-INFO] Docker already installed
```

**Comment by rzietlow** [comment]
right, but, it crossed itself out, the issue appears to be that docker-compose isn't in my path (on the default install) which is why I'm getting error code 127. 

root@helk:~/HELK# docker-compose up
Command 'docker-compose' is available in '/usr/local/bin/docker-compose'
The command could not be located because '/usr/local/bin' is not included in the PATH environment variable.
docker-compose: command not found

**Comment by Cyb3rWard0g** [comment]
ok so did you add that to your PATH?? Did it work after that?

**Comment by rzietlow** [comment]
yes I added it to my path and after that it worked correctly. 

root@helk:~/HELK# export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/snap/bin:/opt/puppetlabs/bin:/usr/local/bin
root@helk:~/HELK# ./helk_install.sh

**********************************************
**          HELK - THE HUNTING ELK          **
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: 0.9 (Alpha)          **
** HELK ELK version: 6.3.0                  **
** License: BSD 3-Clause                    **
**********************************************

[HELK-INSTALLATION-INFO] HELK being hosted on a Linux box
[HELK-INSTALLATION-INFO] Available Memory: 15
[HELK-INSTALLATION-INFO] Available Disk: 66
[HELK-INSTALLATION-INFO] Obtaining current host IP..
[HELK-INSTALLATION-INFO] Set HELK IP. Default value is your current IP: 10.16.1.17
[HELK-INSTALLATION-INFO] HELK IP set to 10.16.1.17
[HELK-INSTALLATION-INFO] HELK identified Linux as the system kernel
[HELK-INSTALLATION-INFO] Checking distribution list and version
[HELK-INSTALLATION-INFO] You're using ubuntu version xenial
[HELK-INSTALLATION-INFO] Docker already installed
[HELK-INSTALLATION-INFO] Docker-compose already installed
[HELK-INSTALLATION-INFO] Dockerizing HELK..
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 262144
[HELK-INSTALLATION-INFO] Setting KAFKA ADVERTISED_LISTENER value...
[HELK-INSTALLATION-INFO] Setting ES_JAVA_OPTS value...
[HELK-INSTALLATION-INFO] Building & running HELK via docker-compose
[HELK-INSTALLATION-INFO] Waiting for HELK services and Jupyter Server to start..


***********************************************************************************
** [HELK-INSTALLATION-INFO] YOUR HELK IS READY                                   **
** [HELK-INSTALLATION-INFO] USE THE FOLLOWING SETTINGS TO INTERACT WITH THE HELK **
***********************************************************************************

**Comment by Cyb3rWard0g** [comment]
Nice thank you for the updates 👍
