### ISSUE TITLE
Looking for Jupyterhub support

### ISSUE THREAD

**Issue by nguyenl95** [Cyb3rWard0g/HELK#429]
#### Describe the problem
As title, I was looking for Jupyterhub support on HELK. I can see that you guys already worked on Jupyterhub [ref](https://github.com/Cyb3rWard0g/HELK/blob/v0.1.7-alpha03042019/docker/helk-jupyter/jupyterhub/jupyterhub_config.py), but I couldn't find anything left on the master branch.

Goal: I prefer to use Jupyterhub rather than JupyterLab and it'd be nice if we could add Nginx docker as separate proxy for Jupyterhub too [ref](https://jupyterhub.readthedocs.io/en/stable/reference/separate-proxy.html).

**Comment by Cyb3rWard0g** [comment]
Hey @nguyenl95 ! Thank you for the recommendation. Yes I worked on a jupyterhub integration before, but I figured providing a basic Jupyter notebook/lab server was easier than providing the capability to add users and spawn several servers under one docker image or multiple docker images. If you have deployed Jupyter Hub before and would like to help us with that, it would be awesome!!

**Comment by nguyenl95** [comment]
@Cyb3rWard0g Can you share your Dockerfile cyb3rward0g/jupyter-hunter:0.0.8? That'd be very helpful for me to see the difference between Jupyter minimal build and yours. Appreciate!

**Comment by Cyb3rWard0g** [comment]
Hey @nguyenl95 ! Yes! I have all the docker images that build notebooks servers here: https://github.com/hunters-forge/notebooks-forge/tree/master/docker . The Jupyter-Hunter specifically is this one: https://github.com/hunters-forge/notebooks-forge/blob/master/docker/jupyter-hunt/Dockerfile . if you are looking for a minimal notebook server you can use this one: https://github.com/hunters-forge/notebooks-forge/blob/master/docker/jupyter-base/Dockerfile

**Comment by Cyb3rWard0g** [comment]
I will close this issue since there is nothing to fix and the JupyterHub integration is not in the main to-do list at the moment. Thank you for the suggestions @nguyenl95 . I hope one day we can deploy that as well or make it easy to add on the fly or with a wiki document ;)
