### ISSUE TITLE
Elastic Issue not starting properlly (last version installed including old versions) all the same issue however this never occured before any Ideas? thanks

### ISSUE THREAD

**Issue by tee2015** [Cyb3rWard0g/HELK#430]
.e.b.ElasticsearchUncaughtExceptionHandler] [helk-1] uncaught exception in thread [main]

2020-02-11T12:20:09.289289385Z org.elasticsearch.bootstrap.StartupException: ElasticsearchException[java.io.IOException: failed to read [id:12, file:/usr/share/elasticsearch/data/nodes/0/_state/node-12.st]]; nested: IOException[failed to read [id:12, file:/usr/share/elasticsearch/data/nodes/0/_state/node-12.st]]; nested: XContentParseException[[-1:36] [node_meta_data] unknown field [node_version], parser not found];

**Comment by troplolBE** [comment]
Hi @tee2015 

Could you provide us more information about system, install version/date, etc? Without this information we will not be able to help you properly.

**Comment by tee2015** [comment]
Ubuntu 19.0 docker env

**Comment by Cyb3rWard0g** [comment]
I believe the issue with Logstash permissions over its config files is not allowing HELK to finish since it waits for Logstash docker service to run properly. However, it restarts constantly. as shown in this latest issue from a different project leveraging HELK https://github.com/hunters-forge/Blacksmith/issues/4

**Comment by Cyb3rWard0g** [comment]
@tee2015 would you mind trying again after the latest update? Thank you in advance!

**Comment by Cyb3rWard0g** [comment]
This I assume is the same issue as https://github.com/Cyb3rWard0g/HELK/issues/423 . You can read more about it in the comments. Read the latest ones to know how I found out about the issue. thank you in advance!

**Comment by tee2015** [comment]
thanks @Cyb3rWard0g on a fresh setup all is good i am running the latest release
