### ISSUE TITLE
Ingest .csv file

### ISSUE THREAD

**Issue by jpark952** [Cyb3rWard0g/HELK#431]
Apologies for the newbie question.

I want to be able take a .CSV from an external system and bring it over to my machine running HELK and ingest it so i can search through it in kibana.

What would be the best way of doing this?

**Comment by Cyb3rWard0g** [comment]
Hey @jpark952 !

You will have to do the following:
- Move your CSV file to your HELK server (i.e. using SCP command)
- Create another logstash input config like this to have Logstash read the CSV file from a local directory: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/0003-attack-input.conf
- Create another logstash filter config to set the column names https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/1216-attack-filter.conf
- An a logstash output config like this one for example to send the data to an ES index: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9956-attack-output.conf
- Once you do that and the index populates you will have to create the index patter view from the Kibana console.https://www.elastic.co/guide/en/kibana/current/tutorial-define-index.html

I hope that helps

**Comment by neu5ron** [comment]
no response, closing
