### ISSUE TITLE
Cannot Add a new Pipeline config to Helk getting data ingested from Filebeat 

### ISSUE THREAD

**Issue by tee2015** [Cyb3rWard0g/HELK#433]
#### Describe the problem
Creating a new Pipeline file 
---------------------------------
![image](https://user-images.githubusercontent.com/14360476/74998363-a9513100-54ac-11ea-9bea-38bea98826de.png)

Edited the file 9998 catch all output:
---------------------------------------
![image](https://user-images.githubusercontent.com/14360476/74998399-bec65b00-54ac-11ea-863f-a2037980241a.png)

Created a new output template:
-----------------------------------
![image](https://user-images.githubusercontent.com/14360476/74998419-cbe34a00-54ac-11ea-9375-0aeb67fabbad.png)

Error on Logstash:
-------------------------------
![image](https://user-images.githubusercontent.com/14360476/74998338-98082480-54ac-11ea-8576-20d9b88f8557.png)

#### Provide the output of the following commands

Get operating system and version
for linux (except Mac) use:  
`cat /etc/os-release`  

![image](https://user-images.githubusercontent.com/14360476/74998483-f0d7bd00-54ac-11ea-8be4-555a38bc3d4a.png)

Get output of the HELK docker containers:  
`docker ps --filter "name=helk"`
![image](https://user-images.githubusercontent.com/14360476/74998573-372d1c00-54ad-11ea-879c-01b47c5b0ac1.png)

```
Place all output, from the above commands, here
```

#### Provide the HELK installation logs located at /var/log/helk-install.log if you are having install errors

```
Place the output here
```

#### What version of HELK are you using

run the command from within the HELK root directory `cat .git/refs/heads/master`  
and include what date you cloned the HELK repo
```
Latest version run from Master folder
```

#### What version of Winlogbeat are you using if you are using Windows/WEF logs

Logstash

**Comment by tee2015** [comment]
Fixed the Suricata template issue npw I can see the template on Elastic uploaded however cannot get the index on Kibana yet
![image](https://user-images.githubusercontent.com/14360476/75086418-ffdf6d80-5587-11ea-931a-241ca4e1674c.png)

**Comment by tee2015** [comment]
should we define the new introduced input / output config files on logstash somewhere ?

**Comment by Cyb3rWard0g** [comment]
sorry for the late response. so when you go to Kibana and try to create the index pattern, it does not show up?

**Comment by Cyb3rWard0g** [comment]
Feel free to reopen this issue or create another one if you still have questions. Thank you @tee2015 !
