### ISSUE TITLE
Missing Kafka.out for Winlogbeat.yaml file?

### ISSUE THREAD

**Issue by bdorr1105** [Cyb3rWard0g/HELK#434]
I can not find the output for the kafka config. Thanks. 

Note - Page 404 not found

https://github.com/Cyb3rWard0g/HELK/blob/master/winlogbeat/winlogbeat.yml

**Comment by troplolBE** [comment]
Th file was moved to this place:

https://github.com/Cyb3rWard0g/HELK/blob/master/configs/winlogbeat/winlogbeat.yml

**Comment by Cyb3rWard0g** [comment]
Thank you @troplolBE . feel free to open another issue if you have any further questions @bdorr1105 . Thank you!
