### ISSUE TITLE
create a new config into Logstash

### ISSUE THREAD

**Issue by santi10** [Cyb3rWard0g/HELK#436]
Hi, I'm creating a new config pile type within pipeline. I haven't permission for change or create a new file. Do you known the "su -" password, please?

Thanks

**Comment by Cyb3rWard0g** [comment]
Hey @santi10 , the pipeline is mounted from your host. Let's say you deployed HELK on an Ubuntu box. The folder helk-logstash/pipeline is mounted on /usr/share/logstash/pipeline. I assume that you are trying to update the pipeline inside of the docker container in the `/usr/share/logstash/pipeline/` folder right? You have to do it in the local pipeline folder outside of the docker container. Let me know if this makes sense and if you are able to update your pipeline files. Thank you!
