### ISSUE TITLE
HELK and filebeat on linux

### ISSUE THREAD

**Issue by geekon75** [Cyb3rWard0g/HELK#439]
Hello,

Willl current version of HELK (v0.1.7-alpha03042019) be working properly
with Filebeat (linux) and Linux's logs?
I try to make a connection like that:

[linux->osquery->filebeat]->[kafka->logstash-> ... ]

To be honest I do not have in Kibana similar data like from Windows' Winlogbeat.
Does Kibana which comes with Helk display messages sent from Linux?

Regards

Greg

**Comment by Cyb3rWard0g** [comment]
Hey @geekon75 , there is beats Input in the project https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/0004-beats-input.conf and if you send it there it will be caught by https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9998-catch_all-output.conf  You will just have to create the index pattern in Kibana. You will see events in the `index-me` index
