### ISSUE TITLE
Feature Request: Add port forwarding to ElasticSearch container

### ISSUE THREAD

**Issue by TomerG711** [Cyb3rWard0g/HELK#443]
We want to connect the HELK's ES with other systems that we wrote, se we could use the data collected by HELK.
However, currently the ES container is accessible only within the docker.
It shouldn't be difficult to support this, only to add port forwarding parameter when running the container, with -p 9200:9200.
As for today, we need to add this manually by changing iptables on the server where the HELK's docker is running.
Is it possible to add the port forwarding to the creation of the ES container?

**Comment by Cyb3rWard0g** [comment]
Hey @TomerG711 , sorry for the late response. I believe you can do that by simply modifying the Docker compose file right? Adding something similar to this: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-kibana-analysis-basic.yml#L56

**Comment by TomerG711** [comment]
PR: https://github.com/Cyb3rWard0g/HELK/pull/450

**Comment by TomerG711** [comment]
@Cyb3rWard0g Can you please review the PR?

**Comment by troplolBE** [comment]
Hey @TomerG711 

Thanks you for submitting your issue and for your PR #450 . We are planning on adding this feature in one of the future releases of the project but at the moment we don't want to force everyone to have port forwarding by default.

**Comment by Cyb3rWard0g** [comment]
Closing this issue following this response https://github.com/Cyb3rWard0g/HELK/pull/450
