### ISSUE TITLE
General Question on Evolution

### ISSUE THREAD

**Issue by securigeek** [Cyb3rWard0g/HELK#444]
Hello Roberto and Spectre,
Thanks for the wonderful work and effort behind HELK. I have 2 questions regarding the project:
1) I have been following HELK since few months now and the status has ever since stayed on ALPHA, when do you plan the next step to get to BETA or Production . 
2) Initially since there was no inbuilt SIEM capabilities on ELK so indeed HELK seemed like a perfect architecture. How does HELK now compares to ELK 7.6 with open source SIEM and detection signals inside? 
Thanks in advance.
Kind Regards,
Securigeek

**Comment by neu5ron** [comment]
Hello,

1) HELK may be in Beta this year - lots of work to do, but even tho its alpha we still try to make as stable as possible.
2) SIEM requires ECS which we dont use. We use OSSEM. Signals is not as verbose as SIGMA which HELK has.

btw, its not a Spectre OPs project :)

**Comment by securigeek** [comment]
Hello,
Thank you for your response. Just 1 last question, can we not covert sigma to signals since SIGMA has sigma convertor to convert it to ECS.

**Comment by neu5ron** [comment]
I assume you can still use signals without ECS - but i imagine the prebuilt stuff may not work. SOC Prime added signals in SIGMA, you can test it that way until we merge the latest sigma into HELK

**Comment by securigeek** [comment]
Thanks a million. I appreciate your response.
