### ISSUE TITLE
Help starting elastic search and logstash

### ISSUE THREAD

**Issue by elcrazywolf** [Cyb3rWard0g/HELK#445]
#### **Describe the problem**

I am a total newbie in both linux and threat hunting. I want to use HELK as part of my bachelor thesis but I don't know how to start elasticsearch and logstash. Managed to interact only with kibana so far using firefox. So I succesfully installed HELK using the instructions provided. Can someone tell me how to open elasticsearch and logstash in order to start learning things? If not, can you provide links where I can read and learn things about this question to solve it myself? My ggogling didn't provide me with much help.

NOTE: I am using VM (virtualbox) with UBUNTU installed on a windows 10 host and I haven't downloaded Winlogbeat, SysV, or anything else.

#### **Provide the output of the following commands**

Get operating system and version
for linux (except Mac) use:  
`cat /etc/os-release`  

Get disk space, memory, processor cores, and docker storage  
`echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN`  

Get output of the HELK docker containers:  
`docker ps --filter "name=helk"`

```
Place all output, from the above commands, here

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Docker Space:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       196G   14G  173G   8% /

Memory:
              total        used        free      shared  buff/cache   available
Mem:              6           5           0           0           0           0
Swap:             1           0           1

Cores:
4

CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                              NAMES
bbe09d23de80        confluentinc/cp-ksql-server:5.1.3                     "/etc/confluent/dock…"   45 hours ago        Up 5 minutes        0.0.0.0:8088->8088/tcp                                                             helk-ksql-server
26d90bb015da        otrf/helk-kafka-broker:2.3.0                          "./kafka-entrypoint.…"   45 hours ago        Up 5 minutes        0.0.0.0:9092->9092/tcp                                                             helk-kafka-broker
1fbd1a498cb4        otrf/helk-elastalert:0.2.6                            "./elastalert-entryp…"   45 hours ago        Up 5 minutes                                                                                           helk-elastalert
37a96f97a533        otrf/helk-zookeeper:2.3.0                             "./zookeeper-entrypo…"   45 hours ago        Up 5 minutes        2181/tcp, 2888/tcp, 3888/tcp                                                       helk-zookeeper
29505de52d0e        otrf/helk-logstash:7.5.2.2                            "/usr/share/logstash…"   46 hours ago        Up 5 minutes        0.0.0.0:3515->3515/tcp, 0.0.0.0:5044->5044/tcp, 0.0.0.0:8531->8531/tcp, 9600/tcp   helk-logstash
c484cb516c0e        otrf/helk-nginx:0.0.8                                 "/opt/helk/scripts/n…"   46 hours ago        Up 5 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                           helk-nginx
2d531823a3c5        docker.elastic.co/kibana/kibana:7.5.2                 "/usr/share/kibana/s…"   46 hours ago        Up 5 minutes        5601/tcp                                                                           helk-kibana
90326e5e47a2        docker.elastic.co/elasticsearch/elasticsearch:7.5.2   "/usr/share/elastics…"   46 hours ago        Up 5 minutes        9200/tcp, 9300/tcp                                                                 helk-elasticsearch
```

#### What version of HELK are you using

run the command from within the HELK root directory `cat .git/refs/heads/master`  
and include what date you cloned the HELK repo
```
Place the date here

30/03/2020
e819bc892a1fe3830f62ec4d33eeaa7f43eb2c51

```

#### What version of Winlogbeat are you using if you are using Windows/WEF logs

```
Place the version here
NOT INSTALLED YET!
```

##### What steps did you take trying to fix the issue
Googling but nothing found helpful

#### Any additional context or input you have

Please bear with my newbiness!

**Comment by elcrazywolf** [comment]
Problem was that although installation was successful (according to the message in the end of installation), elasticsearch was never really installed. I installed it manually

**Comment by Cyb3rWard0g** [comment]
Hey @elcrazywolf , thank you for the details and all the information. Would you mind sharing how you installed the HELK? what do you mean with Elasticsearch not being installed. It downloads the official Elasticsearch Docker container as a service and connects with the other docker services.

**Comment by elcrazywolf** [comment]
I tried installing HELK in an ubuntu virtual machine and allocated RAM enough to install HELK but also too much for my host pc to handle. So host PC crashed stopping the installation again and again until I could find RAM percentage I could allocate to VM so that both my pc didn't crash and the installation could proceed. So the result was an installation stopping 3-4 times (beggining each time at the stop point of previous install) and one final installation which actually showed up the finishing message (installation completed). Meaning that probably if for some reason installation stops and then continues, some things like elasticsearch won't install at all (searching elasticservice and dockers showed up nothing until I installed it manually).

**Comment by Cyb3rWard0g** [comment]
Would you mind sharing what option you tried? We have some steps here in the Wiki and when you run the install script it asks you to specify the install option : https://github.com/Cyb3rWard0g/HELK/wiki/Installation . I can see you had 6GB of memory and 5GB used. Do you have anything else installed in your Ubuntu box?

**Comment by neu5ron** [comment]
no response from issue opener. closing
