### ISSUE TITLE
General Question Update to 7.6

### ISSUE THREAD

**Issue by Mangolinux** [Cyb3rWard0g/HELK#456]
How do I update HELK to Elastic version 7.6?

**Comment by troplolBE** [comment]
Hey @Mangolinux ! Thanks for this question. You have 2 ways to upgrade to elastic 7.6.

1. You can wait the next update of HELK which supports Elastics latest version.
2. You can change the version in docker downloads in the Dockerfile files.

https://github.com/Cyb3rWard0g/HELK/blob/9a74d4426b734f2f3cd292345c37f3315af6628a/docker/helk-kibana/Dockerfile#L9

https://github.com/Cyb3rWard0g/HELK/blob/9a74d4426b734f2f3cd292345c37f3315af6628a/docker/helk-logstash/Dockerfile#L9

https://github.com/Cyb3rWard0g/HELK/blob/9a74d4426b734f2f3cd292345c37f3315af6628a/docker/helk-elasticsearch/Dockerfile#L9

I personally recommend you to wait for the next update but you can try to upgrade by yourself with the second option.

Hope this comment helped you ! If you have any further questions, be sure to comment or open a new issue ;)

**Comment by Mangolinux** [comment]
Thanks @troplolBE, any ETA on option one?

**Comment by troplolBE** [comment]
Hey @Mangolinux ! I don't have any date for the moment but it should not be too long anymore.

**Comment by neu5ron** [comment]
its updated to 7.6.2
