### ISSUE TITLE
Errors missing in docker logs command

### ISSUE THREAD

**Issue by troplolBE** [Cyb3rWard0g/HELK#457]
### Describe the problem
I ran tried installing the version 2 of HELK and wanted to check the output of `docker logs helk-elastalert` so I had it open in a shell. After the installation of the HELK I saw that when I executed `docker logs helk-elastalert` some errors are missing.
### Provide the output of the following commands
```
Centos 7
```

### What version of HELK are you using

Fork of @devdua , branch sigma-pull-fix

#### What steps did you take trying to fix the issue
```
None
```

#### How could we replicate the issue
```
Try install
```

### Any additional context or input you have

Output of `docker logs -f helk-elastalert` during install:

![image](https://user-images.githubusercontent.com/12971225/80699199-df79e500-8adb-11ea-944f-294056301a3f.png)

Output of  `docker logs helk-elastalert` after install:

![image](https://user-images.githubusercontent.com/12971225/80699266-f7516900-8adb-11ea-9342-5907b6895994.png)

**Comment by troplolBE** [comment]
There are a total of 233 error lines missing in the second version. All of them are python errors except for the last one on the 2 screens above.

**Comment by neu5ron** [comment]
that mapping error is a non issue - its an ordering thing in elasticsearch templates - i cant supress the error.
reopen if you need.
