### ISSUE TITLE
Kafka Zeek logs to SIEM 

### ISSUE THREAD

**Issue by Mangolinux** [Cyb3rWard0g/HELK#458]
#### Describe the problem
SIEM is not seeing my Zeek logs
#### Provide the output of the following commands

Get operating system and version
for linux (except Mac) use:  
`cat /etc/os-release`  
for Mac/OSX use:  
`sw_vers`  
Get disk space, memory, processor cores, and docker storage  
`echo -e "\nDocker Space:" && df -h /var/lib/docker; echo -e "\nMemory:" && free -g; echo -e "\nCores:" && getconf _NPROCESSORS_ONLN`  
Get output of the HELK docker containers:  
`docker ps --filter "name=helk"`

```
Place all output, from the above commands, here
```
HELK server
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
###
Docker Space:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        49G   37G  9.5G  80% /

Memory:
              total        used        free      shared  buff/cache   available
Mem:              8           7           0           0           1           1
Swap:             3           0           3

Cores:
4
###
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                              NAMES
e8ba5fd2f71b        confluentinc/cp-ksql-server:5.1.3                     "/etc/confluent/dock…"   2 months ago        Up 2 days           0.0.0.0:8088->8088/tcp                                                             helk-ksql-server
1c70f613e024        otrf/helk-spark-worker:2.4.4                          "./spark-worker-entr…"   2 months ago        Up 2 days                                                                                              helk-spark-worker
1e0b580d8c62        otrf/helk-kafka-broker:2.3.0                          "./kafka-entrypoint.…"   2 months ago        Up 2 days           0.0.0.0:9092->9092/tcp                                                             helk-kafka-broker
042f0025242b        docker_helk-jupyter                                   "/opt/jupyter/script…"   2 months ago        Up 2 days           8000/tcp, 8888/tcp                                                                 helk-jupyter
695d359d5518        otrf/helk-zookeeper:2.3.0                             "./zookeeper-entrypo…"   2 months ago        Up 2 days           2181/tcp, 2888/tcp, 3888/tcp                                                       helk-zookeeper
18cbc17c865a        otrf/helk-spark-master:2.4.4                          "./spark-master-entr…"   2 months ago        Up 2 days           7077/tcp, 0.0.0.0:8080->8080/tcp                                                   helk-spark-master
265246c4cc32        otrf/helk-elastalert:0.2.6                            "./elastalert-entryp…"   2 months ago        Up 2 days                                                                                              helk-elastalert
9c7ac3c8e304        otrf/helk-nginx:0.0.8                                 "/opt/helk/scripts/n…"   2 months ago        Up 2 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                           helk-nginx
79903a76db00        otrf/helk-logstash:7.5.2.2                            "/usr/share/logstash…"   2 months ago        Up 2 days           0.0.0.0:3515->3515/tcp, 0.0.0.0:5044->5044/tcp, 0.0.0.0:8531->8531/tcp, 9600/tcp   helk-logstash
73dae679206e        docker.elastic.co/kibana/kibana:7.5.2                 "/usr/share/kibana/s…"   2 months ago        Up 2 days           5601/tcp                                                                           helk-kibana
a758dc5be82f        docker.elastic.co/elasticsearch/elasticsearch:7.5.2   "/usr/share/elastics…"   2 months ago        Up 2 days           9200/tcp, 9300/tcp                                                                 helk-elasticsearch
#### Provide the HELK installation logs located at /var/log/helk-install.log if you are having install errors

```
Place the output here
```

#### What version of HELK are you using

run the command from within the HELK root directory `cat .git/refs/heads/master`  
and include what date you cloned the HELK repo
```
Place the date here
```
e819bc892a1fe3830f62ec4d33eeaa7f43eb2c51  29Feb2020
#### What version of Winlogbeat are you using if you are using Windows/WEF logs

```
Place the version here
```

##### What steps did you take trying to fix the issue
I don't know the Elastisearch password
##### Any additionally code or log context you would like to provide

```
Place the output here
filebeat.service - Filebeat sends log files to Logstash or directly to Elasticsearch.
   Loaded: loaded (/usr/lib/systemd/system/filebeat.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-05-01 20:44:47 EDT; 25min ago
     Docs: https://www.elastic.co/products/beats/filebeat
 Main PID: 8571 (filebeat)
    Tasks: 8 (limit: 11491)
   Memory: 36.5M
   CGroup: /system.slice/filebeat.service
           └─8571 /usr/share/filebeat/bin/filebeat -e -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/lo>

May 01 21:08:52 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:08:52.141-0400        INFO        [publisher]        pipeline/retry.go:175          done
May 01 21:08:57 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:08:57.985-0400        INFO        log/harvester.go:297        Harvester started for file: /opt/zeek/logs/current/dhcp.log
May 01 21:09:17 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:09:17.887-0400        INFO        [monitoring]        log/log.go:145        Non-zero metrics in the last 30s        {"monitori>
May 01 21:09:42 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:09:42.477-0400        ERROR        pipeline/output.go:100        Failed to connect to backoff(elasticsearch(http://192.168.16.>
May 01 21:09:42 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:09:42.477-0400        INFO        pipeline/output.go:93        Attempting to reconnect to backoff(elasticsearch(http://192.168>
May 01 21:09:42 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:09:42.478-0400        INFO        [publisher]        pipeline/retry.go:196        retryer: send unwait-signal to consumer
May 01 21:09:42 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:09:42.478-0400        INFO        [publisher]        pipeline/retry.go:198          done
May 01 21:09:42 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:09:42.478-0400        INFO        [publisher]        pipeline/retry.go:173        retryer: send wait signal to consumer
May 01 21:09:42 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:09:42.478-0400        INFO        [publisher]        pipeline/retry.go:175          done
May 01 21:09:47 Cent-Bro.hamcllc filebeat[8571]: 2020-05-01T21:09:47.887-0400        INFO        [monitoring]        log/log.go:145        Non-zero metrics in the last 30s        {"monitori>
lines 1-20/20 (END)
```

#### Any additional context or input you have

pictures, comments, etc.
I am using Filebeats version 7.6.2 on my Zeek server, with output.kafka configured I can see zeek logs under indexme-* but when I try to configure output.elasticsearch I get failed to connect errors

**Comment by Mangolinux** [comment]
I did a basic install option 4

**Comment by troplolBE** [comment]
Hey @Mangolinux ! Are you tring to use the SIEM of the ELK Stack ? Can ou please provide us the output.elasticsearch you are trying to use ?

**Comment by neu5ron** [comment]
zeek parsing is coming soon and will be under `logs-network-zeek`. However, if you desire to use the SIEM portion, I suggest using an Elastic Common Schema supported stack. The siem does not function without ECS, HELK uses a different schema (OSSEM) that has broader support  and allows HELK to move at its own pace.
