### ISSUE TITLE
Not able to create index related to winlogbeat [just making sure that's needed]

### ISSUE THREAD

**Issue by dimpol** [Cyb3rWard0g/HELK#46]
Hi @Cyb3rWard0g 
Thanks a lot for the time used to implement such a great project.

I am using the latest HELK image.
What i see on the index patterns is the below:
![screenshot from 2018-04-22 14 11 35](https://user-images.githubusercontent.com/4255178/39099946-386e697a-468b-11e8-942d-1ea1c7f11570.png)

Do i still have to do what your winlogbeat manual describes as: "You will be able to substitute logstatsh-* for winlogbeat-* and set the field name to Timestamp as shown in figure 33 below. Click on the create option at the bottom to continue." ?

Thanks and sorry for the noobish question

**Comment by Cyb3rWard0g** [comment]
Hey @dimpol !! The HELK already defined the indices for you. You do not need to create a winlogbeat one anymore. Let me know if you can click on the Discover option on the left and see your event logs

**Comment by dimpol** [comment]
Yeap everything is working as expected !
Thanks a lot for the clarification and this little beast you created !
Closing the noobish post...
