### ISSUE TITLE
 set_elasticsearch_password command not found

### ISSUE THREAD

**Issue by eatyourpeas747** [Cyb3rWard0g/HELK#464]
#### Describe the problem
when running ./help_install.sh I get the following:

./helk_install.sh: line 580: set_elasticsearch_password: command not found

I do not see the command to actually run it.  It seems to be missing from the sh file.

**Comment by neu5ron** [comment]
which install option are you using?

**Comment by xiaodupi-zyq** [comment]
I used option 2 to install, and also encountered this problem

**Comment by xiaodupi-zyq** [comment]
> which install option are you using?

I used option 2 to install, and also encountered this problem

**Comment by neu5ron** [comment]
@xiaodupi-zyq can you run this command from within the HELK directory `cat .git/refs/heads/master`

**Comment by neu5ron** [comment]
can you try latest repo now?

**Comment by xiaodupi-zyq** [comment]
> @xiaodupi-zyq can you run this command from within the HELK directory `cat .git/refs/heads/master`

no I can not. No such file and directory

**Comment by neu5ron** [comment]
can you try the latest repo, remove HELK directory and rerun git clone and then `helk_install.sh`

**Comment by xiaodupi-zyq** [comment]
> can you try the latest repo, remove HELK directory and rerun git clone and then `helk_install.sh`

I fix it

**Comment by neu5ron** [comment]
glad to hear! reach out if you have any comments, suggestions, etc.

going to close the issue
