### ISSUE TITLE
ubuntu 18 docker via snap

### ISSUE THREAD

**Issue by neu5ron** [Cyb3rWard0g/HELK#467]
certain Ubuntu 18+ builds come with docker install via `snap` and thus systemctl won't work.
to remove the snap version the commands are along the lines of:
```
sudo snap list
sudo snap remove docker
```

**Comment by devdua** [comment]
If snap is not preferable, then it has to be removed as an installation alternative in the `helk_install.sh` script - https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_install.sh#L265 (lines 265 - 274)

This was originally contributed by me as PR #51

**Comment by rfoster55** [comment]
Thanks for pointing this out as I was having trouble managing containers with apt-installed docker-compose while snap docker was still present!
