### ISSUE TITLE
Add ability to make silent installation for  helk_install.sh

### ISSUE THREAD

**Issue by Alex-0293** [Cyb3rWard0g/HELK#470]
#### Describe the problem
Good day!
I`m deploying virtual environment with HELK via powershell. 
I have no ability to interact with script.
Would you be so kind, to add helk_install.sh parameters for silent installation.
Thank you!

**Comment by troplolBE** [comment]
Hi @Alex-0293 ! Why do you want silent installation ? It is useful to see where the install script fails to help us fix potential issues or just for you to know what minimum requirements you don't have.

Please explain a bit more why you think this should be added in the install script 😉

**Comment by Alex-0293** [comment]
> 
> 
> Hi @Alex-0293 ! Why do you want silent installation ? It is useful to see where the install script fails to help us fix potential issues or just for you to know what minimum requirements you don't have.
> 
> Please explain a bit more why you think this should be added in the install script 😉

Good day, troplolBE!
I`m build project with HELK in virtual machines. I want to deploy them with powershell script. 
It`s done, but i have one interactive thing.

**Comment by Cyb3rWard0g** [comment]
You can do it via the CLI. Does that help? https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_install.sh#L605-L616
