### ISSUE TITLE
ERROR: Could not run HELK via docker-compose file helk-kibana-analysis-alert-basic.yml (Errror code:1)

### ISSUE THREAD

**Issue by spexboy** [Cyb3rWard0g/HELK#471]
#### Describe the problem

Unable to complete the installation on Ubuntu 18.04, please find the error details below,

![image](https://user-images.githubusercontent.com/13061021/84226667-0de9d780-ab00-11ea-890a-9453299dd5d5.png)

tail -f /var/log/helk-install.log
![image](https://user-images.githubusercontent.com/13061021/84226779-599c8100-ab00-11ea-8902-1cce7ba8adf8.png)

**Comment by Cyb3rWard0g** [comment]
Hey @spexboy , are you running the update script? https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_update.sh

because there is the only place where I see those commands https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk_update.sh#L145

`mv helk-nxing/htpasswd.users`

**Comment by Cyb3rWard0g** [comment]
Hey @spexboy , would you mind trying to install it one more time? Sorry for the inconvenience.

**Comment by spexboy** [comment]
Hi,

Thanks for Responding.

Tried to reinstall again, but still facing the issue.

Please find the screenshot below,
mv helk-nginx/htpasswd.users helk-nginx/htpasswd.users_backup >>$LOGFILE 2>&1 

![image](https://user-images.githubusercontent.com/13061021/84608319-84efe900-aecf-11ea-8877-871fa0eaeba4.png)


tail -f /var/log/helk-install.log

![image](https://user-images.githubusercontent.com/13061021/84608417-f9c32300-aecf-11ea-9456-199292cb4305.png)


Thanks & Regards,
Sathish

**Comment by Cyb3rWard0g** [comment]
The first image has nothing to do with the file not being available. that is because $LOGFILE needs to be defined and it is defined in the script. If you run it outside of the script, it would fail. Can you do a clean install please?

**Comment by spexboy** [comment]
after clean install, i am getting below error.

![image](https://user-images.githubusercontent.com/13061021/84625766-8a662700-af01-11ea-97ff-87914467468a.png)

My wget result show below,
![image](https://user-images.githubusercontent.com/13061021/84625905-ca2d0e80-af01-11ea-8564-436e18d49606.png)

Thanks,
Sathish

**Comment by Cyb3rWard0g** [comment]
That looks like a local certificates issue? Maybe?

can you try running:
```
sudo apt-get install ca-certificates
```

And try it again? please. thank you!

**Comment by spexboy** [comment]
Issue resolved.

Thank you so much for your support.
