### ISSUE TITLE
winlogbeat.yml link is broken

### ISSUE THREAD

**Issue by martclau** [Cyb3rWard0g/HELK#472]
The link on https://thehelk.com/installation.html to https://github.com/Cyb3rWard0g/HELK/blob/master/winlogbeat/winlogbeat.yml is broken.

**Comment by Cyb3rWard0g** [comment]
Thank you @martclau! I will fix the in a commit in a few mins.

**Comment by Cyb3rWard0g** [comment]
This link works just in case: https://github.com/Cyb3rWard0g/HELK/blob/master/configs/winlogbeat/winlogbeat.yml
