### ISSUE TITLE
ERROR: how to connection log from windows (client) to HELK in ubuntu ?

### ISSUE THREAD

**Issue by nugnugrawk** [Cyb3rWard0g/HELK#474]
how to connection log windows (client) to HELK in ubuntu ?

**Comment by Cyb3rWard0g** [comment]
Hey @nugnugrawk ! Would you mind providing more details about this?

Do you mean a client/ log shipper on a Windows box to send logs to HELK installed in an Ubuntu box?

**Comment by nugnugrawk** [comment]
yes, i want
 client/ log shipper on a Windows box to send logs to HELK installed in an Ubuntu box

**Comment by Cyb3rWard0g** [comment]
You can simply install Winlogbeat by following these official instructions:https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-getting-started.html

You can use the following winlogbeat config to send logs to kafka (front pipe)

https://github.com/Cyb3rWard0g/HELK/blob/master/configs/winlogbeat/winlogbeat.yml

Just update your HELK Ubuntu IP address and only use the `9092` port ("<HELK-IP>:9092")

That should do it
