### ISSUE TITLE
ERROR: helk-logstash 

### ISSUE THREAD

**Issue by nugnugrawk** [Cyb3rWard0g/HELK#475]
![error-helk-logstash](https://user-images.githubusercontent.com/19874624/85395749-d1e05900-b57a-11ea-8f78-751e97932c45.png)

how to solve this problem ? thank you.

**Comment by Cyb3rWard0g** [comment]
do you have anything else running in that box? any other applications?

**Comment by nugnugrawk** [comment]
![image](https://user-images.githubusercontent.com/19874624/85835557-73f08300-b7bf-11ea-8fc7-8808dad6eb2f.png)
now problem like this, 

what should i do?

Previously, i run Kibana but there was a problem "Kibana server is not ready yet"

![image](https://user-images.githubusercontent.com/19874624/85835838-efeacb00-b7bf-11ea-90db-ac098149c41a.png)

why this problem ?

**Comment by Cyb3rWard0g** [comment]
Can you restart Kibana? `docker restart helk-kibana`?

**Comment by nugnugrawk** [comment]
![Screenshot_20200630-113223_1](https://user-images.githubusercontent.com/19874624/86083926-b8349980-bac5-11ea-9ebf-27724336eb88.jpg)
how to solve this problem after try restart kibana ?

**Comment by nugnugrawk** [comment]
![Screenshot_20200630-141211_1](https://user-images.githubusercontent.com/19874624/86095652-7400c380-badc-11ea-8275-8670153e5208.jpg)
after restart kibana, i have a this problem, how to fix ?

**Comment by Cyb3rWard0g** [comment]
mmmm I cannot replicate that issue. can you send logs from kibana and Elasticsearch?

Reference: https://thehelk.com/installation.html#monitor-helk-installation-logs-always

**Comment by Cyb3rWard0g** [comment]
Hey @nugnugrawk ! Feel free to re-open this issue if you still need assistance deploying HELK. I could not replicate your issue. Try the latest version of it too. Thank you!
