### ISSUE TITLE
helk_install.sh: line 373: docker-compose: command not found

### ISSUE THREAD

**Issue by spexboy** [Cyb3rWard0g/HELK#478]
Unable to install HELK in Centos 7.7.x

Please find the screenshot below,

![image](https://user-images.githubusercontent.com/13061021/86113186-8da70880-bae6-11ea-9284-d8c7431fa781.png)

Centos Linux release 7.7.1908

Kindly help. Thank you.

pictures, comments, etc.

**Comment by Cyb3rWard0g** [comment]
Can you provide the version of your docker and docker-compose? I have seen this before and it is because of an old version installed. Let me know please thank you!

**Comment by Cyb3rWard0g** [comment]
I see you got it to work since you opened another issue with another question related to logs ingestion which means that your HELK should be up and running. Feel free to re-open it if it is necessary. Thank you!

**Comment by Cyb3rWard0g** [comment]
https://github.com/Cyb3rWard0g/HELK/issues/479
