### ISSUE TITLE
Unable to push the logs in HELK Ubuntu

### ISSUE THREAD

**Issue by spexboy** [Cyb3rWard0g/HELK#479]
Unable to push the logs Winlogbeat from HELK-Ubuntu 18.04

Ubuntu is running on VMware, so i can able to send winlogbeat logs from Host(Windows - Vmware Installed)  to Guest(HELK).

But apart from this i unable to send logs from any other machine winlogbeat to HELK.

Windows Screenshot - which logs are not reaching HELK, i dont know where it getting blocked.

![image](https://user-images.githubusercontent.com/13061021/86779076-c14ed900-c078-11ea-9699-48808668a3ee.png)

All are in same network lan and no firewall is blocking. but still i dont have idea where it is getting blocked.

Requesting you to kindly help on this,

Thanks,
Sathish

**Comment by Cyb3rWard0g** [comment]
can you share your winlogbeat config please? Also can you ping your Ub untu box from your WIndows box?

**Comment by Cyb3rWard0g** [comment]
You will need something like this connect a Windows box with Winlogbeat installed:
```winlogbeat.event_logs:
  - name: Application
    ignore_older: 30m
  - name: Security
    ignore_older: 30m
  - name: System
    ignore_older: 30m
  - name: Microsoft-windows-sysmon/operational
    ignore_older: 30m
  - name: Microsoft-windows-PowerShell/Operational
    ignore_older: 30m
    event_id: 4103, 4104
  - name: Windows PowerShell
    event_id: 400,600
    ignore_older: 30m
  - name: Microsoft-Windows-WMI-Activity/Operational
    event_id: 5857,5858,5859,5860,5861

#----------------------------- Kafka output --------------------------------
output.kafka:
  # initial brokers for reading cluster metadata
  # Place your HELK IP(s) here (keep the port).
  # If you only have one Kafka instance (default for HELK) then remove the 2nd IP that has port 9093
  hosts: ["<HELK-IP>:9092","<HELK-IP>:9093"]
  topic: "winlogbeat"
  ############################# HELK Optimizing Latency ######################
  max_retries: 2
  max_message_bytes: 1000000
```

**Comment by Cyb3rWard0g** [comment]
Let me know if you still have additional questions about this issue. Feel free to re-open or create a new issue. I could not replicate this.
