### ISSUE TITLE
SSL certificate error 

### ISSUE THREAD

**Issue by htoochonaung** [Cyb3rWard0g/HELK#480]
I got issues while setup filebeat in client machine.
when i run sudo metricbeat setup -e
i got this .

![1056889](https://user-images.githubusercontent.com/46007529/87006961-80290700-c1e7-11ea-8019-8e4fa81e53c4.jpg)

**Comment by Cyb3rWard0g** [comment]
Hey @htoochonaung , isnt that an EC2 instance issue? I dont think that has to do with HELK itself right>

**Comment by htoochonaung** [comment]
hmm. I can't get ssl certificate from HELK  even i add HELK.crt from nginx server to client's instance .
what should i do?

**Comment by Cyb3rWard0g** [comment]
Hey @htoochonaung , let me know if you were able to figure it out. I believe it had to do with your EC2 instance connection rather than HELK itself. Feel free to re-open this issue if you still have additional questions.
