### ISSUE TITLE
Predefined Algorithms in HELK

### ISSUE THREAD

**Issue by srinivas946** [Cyb3rWard0g/HELK#482]
Using Apache Spark and Graphframes we can achieve best results in Hunting, but when i download helk and open jupyter notebook, i haven't found any predefined algorithms related to apache spark. There is no path "training/jupyter_notebooks/getting_started/ folder" as per the documentation "https://github.com/Cyb3rWard0g/HELK/wiki/Spark"

**Comment by Cyb3rWard0g** [comment]
Hey @srinivas946 ! Thank you for the feedback. I believe you can see them in the notebook folder? https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-jupyter/Dockerfile#L28-L29 Let me know if you see that folder when you open the Jupyter Notebook server. I will update the documentation. I have not ported Apache Spark and Jupyter docs to the new docs site: https://thehelk.com/intro.html

**Comment by Cyb3rWard0g** [comment]
let me know if you were able to find the notebooks. 

You will see the following folder tree:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/9653181/90547217-2528ef00-e159-11ea-8a64-561e8e1e09c7.png">

Enter tutorials and you will find this notebook

<img width="962" alt="image" src="https://user-images.githubusercontent.com/9653181/90547177-16423c80-e159-11ea-9cf5-1bf00e378e56.png">

**Comment by Cyb3rWard0g** [comment]
I just tested with current master.
