### ISSUE TITLE
Error Installation 

### ISSUE THREAD

**Issue by hakavod** [Cyb3rWard0g/HELK#485]
Hello dear, could someone please support me, I am installing Helk in a clean installation and the following error is displayed.
![Error_Installation](https://user-images.githubusercontent.com/45045004/87328071-917d5680-c4fa-11ea-96fd-1dfcd02644e1.jpg)

**Comment by Cyb3rWard0g** [comment]
Hey @hakavod ! Would you mind providing some logs? https://thehelk.com/installation.html#monitor-helk-installation-logs-always . First it would be good to check the helk-install logs as shown in the link that I just shared. Let me know! Thank you!

**Comment by Cyb3rWard0g** [comment]
That looks like a docker-compose version or already installed via a different way. Can you remove docker or docker-compose before installing HELK. it installs all that for you. Let me know. Thank you!
