### ISSUE TITLE
Unable to Install the Helk in Centos

### ISSUE THREAD

**Issue by satspex** [Cyb3rWard0g/HELK#486]
Hi,

I unable to complete the install the HELK in centos 7.7

![image](https://user-images.githubusercontent.com/68596361/88056583-6dff7f00-cb7e-11ea-9bab-8c9ad84963ff.png)

Thank you in advance.

**Comment by Cyb3rWard0g** [comment]
Hey @satspex ! mmmm can you try to remove docker if it is already installed before running the helk_install script? Maybe there is a docker-compose version or docker already installed.

**Comment by Cyb3rWard0g** [comment]
I tried it tonight and I got the same issue. I looked at the logs 

```
[HELK-FIREWALL] The new service has succesfully installed on your firewall. HELK should run properly...
Creating network "docker_helk" with driver "bridge"
Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-6c6aa2a0979c -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
^C
```

I restarted the docker service as shown below and it worked. I have seen that in a few places after Googling.

```
[root@CENTOS10 docker]# systemctl restart docker
[root@CENTOS10 docker]# ./helk_install.sh 
```

```
[root@CENTOS10 docker]# tail -f /var/log/helk-install.log 
  protocols: 
  source-ports: 
  modules: 
  destination: 
[HELK-FIREWALL] The new service has succesfully installed on your firewall. HELK should run properly...
Creating network "docker_helk" with driver "bridge"
Creating volume "docker_esdata" with local driver
Pulling helk-elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:7.6.2)...
7.6.2: Pulling from elasticsearch/elasticsearch
```
I am adding the docker service restart just in case after the firewall setup.

**Comment by neu5ron** [comment]
fixed
