### ISSUE TITLE
helk-elasticsearch connection

### ISSUE THREAD

**Issue by rocket-ops** [Cyb3rWard0g/HELK#487]
#### Describe the problem

I am trying to follow this blog post, 

https://medium.com/threat-hunters-forge/jupyter-notebooks-from-sigma-rules-%EF%B8%8F-to-query-elasticsearch-31a74cc59b991

I believe everything is up and running as it should be.  I can connect to the the Jupyter Notebooks using my <ip address> and the additional items specified. 

However, when trying to initialize the Elasticsearch client, I can't connect to per the instructions:

http://helk-elasticsearch:9200, I also tried to connect utilizing the server ip:9200 but it will not connect. 

My apologies if this is wrong place to post this question.

**Comment by Cyb3rWard0g** [comment]
Hey @rocket-ops ! Let me take a look at it.

**Comment by Cyb3rWard0g** [comment]
I just tested the current master with option 4 and it works with (for example) tutorials/07-pyspark-sparkSQL_tables, but it uses PySPark

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/9653181/90547917-2dcdf500-e15a-11ea-81f4-48e1555eaea0.png">


I also tested the following steps from the blog post and it worked too. HELK automatically for testing the pipeline provides Sysmon Event ID 3 after a fresh deployment so I just used that

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/9653181/90548154-8a311480-e15a-11ea-98dc-f8c156b5161b.png">

Feel free to re-open this issue for further questions. Thank you for using the tool!
