### ISSUE TITLE
Elastic license

### ISSUE THREAD

**Issue by ankhazam** [Cyb3rWard0g/HELK#488]
Could you please describe why does HELK need Elastic basic (Elasitc) tier and the OSS (Apache 2.0) licensed core is not sufficient?

I have only found that you use monitoring:
https://github.com/Cyb3rWard0g/HELK/blob/220baae6b17617300f6f87b4c21f193d66ad52b6/docker/helk-elasticsearch/config/elasticsearch.yml#L101

**Comment by webhead404** [comment]
@ankhazam it is so if users want to, they can upgrade directly to platinum trial. Elastic greenlit this project to use the Basic license a long time ago.
