### ISSUE TITLE
New release install over previous install : java.lang.IllegalStateException: failed to obtain node locks

### ISSUE THREAD

**Issue by 1332530** [Cyb3rWard0g/HELK#49]
Following a succesful build, an attempt was made to upgrade to HELK 6.2.4-050318. The following steps were taken:

1. Bring down the environment with docker-compose down.
2. Delete the HELK directory.
3. Clone the repo for the new release.
4. Run install script.

The build is successful.
Compose spins up the environement.

Following issues noted:

1. The Kibana URL is not accessible. ''Connection refused''.
2. The Kibana enterypoint.sh script fails the curl check on the local URL.
3. The Elasticsearch container keeps restarting every 3 seconds.
4. The Elasticsearch docker logs display ''java.lang.IllegalStateException: failed to obtain node locks''.

After searching the web, it would appear that the issue was caused by orphaned java processes.

Resolutuion:

Kill all java processes: killall -9 java
Removed and cloned repo.
Ran install script.

Build successful.

**Comment by offsecn00b** [comment]
I get an initial error > "Invalid published port: 4040-4050" which comse from the docker compose file. This can be fixed manually by changing to 4040-4050:4040-4050

However I cannot solve the ES java error above.

I could not resolve this issue. I did a full docker system prune -a
Followed by a full git clone + helk_install.sh

**Comment by Cyb3rWard0g** [comment]
@1332530 thank you for providing a few steps to get rid of an old HELK build. @offsecn00b since I use HELK for testing purposes I always have a snapshot of a clean ubuntu install. I just revert it to a clean state and it works. The java error as @1332530 stated, it is about an old HELK ES node still there.
