### ISSUE TITLE
Can't connect winlogbeat to ELK 

### ISSUE THREAD

**Issue by nugnugrawk** [Cyb3rWard0g/HELK#491]
i have try this tutorial : https://cyberwardog.blogspot.com/2017/02/setting-up-pentesting-i-mean-threat_87.html

but after finisihed try tutorial, i can't connect winlogbeat to server ELK,  even though the configuration is running smoothly, why ? 

Thank you!

**Comment by Cyb3rWard0g** [comment]
Hey @nugnugrawk !

That blog post makes Winlogbeat to point to Logstash. We recommend to use Win -> Kafka.  The WInlogbeat script should be something like this: https://github.com/Cyb3rWard0g/HELK/blob/master/configs/winlogbeat/winlogbeat.yml

**Comment by nugnugrawk** [comment]
So I have to install Kafka first on ELK? and then use config win -> kafka on client windows ?

**Comment by Cyb3rWard0g** [comment]
HELK comes with Kafka set up already. Are you building ELK manually? or deploying HELK via docker?

**Comment by nugnugrawk** [comment]
ELK manually, I followed the instructions https://cyberwardog.blogspot.com/2017/02/setting-up-pentesting-i-mean-threat_98.html

**Comment by Cyb3rWard0g** [comment]
Got it. Unfortunately we only support HELK deployments. Manual installs are out of the scope. thats why we provide docker containers. is it possible to deploy it with HELK?

**Comment by nugnugrawk** [comment]
is there a tutorial that explains the steps start to finish pushing log windows (client) to helk (server) ?

**Comment by Cyb3rWard0g** [comment]
This is the HELK installation instructions: https://thehelk.com/installation.html

For WIndows with WInlogbeat is the same steps you follow to install Winlogbeat but you need to use the config I shared above: https://github.com/Cyb3rWard0g/HELK/blob/master/configs/winlogbeat/winlogbeat.yml . You just need to update the HELK IP in the config.

**Comment by nugnugrawk** [comment]
for install winlogbeat use this  https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-installation.html ?

**Comment by Cyb3rWard0g** [comment]
Yeah that works. Make sure you have the right version aligned with HELK's ELK stack.

**Comment by Cyb3rWard0g** [comment]
Currently as 2020/08/11 we are at Elastic stack version 7.6.2.

**Comment by Cyb3rWard0g** [comment]
Feel free to re-open the issue or create another one if you have any further questions. Thank you!
