### ISSUE TITLE
nginx kibana dashboard

### ISSUE THREAD

**Issue by nugnugrawk** [Cyb3rWard0g/HELK#494]
i have the problem "502 bad gateway" after shutdown PC, why ? thanks.
![image](https://user-images.githubusercontent.com/19874624/90604052-7521b780-e226-11ea-87da-f169a040ea5a.png)

**Comment by Cyb3rWard0g** [comment]
I would also restart Kibana or Nginx.

```
sudo docker restart helk-kibana
sudo docker restart helk-nginx
```
