### ISSUE TITLE
question: docker data retention?

### ISSUE THREAD

**Issue by h4sh5** [Cyb3rWard0g/HELK#497]
where does the data go outside of docker? If they are all in a docker volume somewhere, does the volume get destroyed when:

- `docker ps -qa | xargs docker kill` (kill all docker instances)
- `docker ps -qa | xargs docker rm` (remove all docker instance)
- `docker-compose -f someconfig.yml stop` (the usual stop sequence)

And how can I export / move the data out in that case?

**Comment by neu5ron** [comment]
the only persistent docker data is the elasticsearch database.

are you referring to something else perhaps?

**Comment by h4sh5** [comment]
I got it - it's in the volumes.
