### ISSUE TITLE
Elasticsearch cluster in Production mode with TLS enabled

### ISSUE THREAD

**Issue by doludizgin** [Cyb3rWard0g/HELK#500]
Hi,

i am trying to build HELK with an elastic cluster with TLS enabled  to use basic license in prodcution mode.

I rebuilded the compose file and i can get the cluster online in production mode only kibana isnt finding the cluster can you pinpoint me further ?

https://pastebin.com/SWiec39w

**Comment by zorteran** [comment]
I assume that you didn't provide `elasticsearch.username` and `elasticsearch.password` and/or `elasticsearch.ssl.certificateAuthorities` in `kibana.yml`
https://www.elastic.co/guide/en/kibana/current/settings.html
