### ISSUE TITLE
how to setting ELK rules detection in HELK ?

### ISSUE THREAD

**Issue by nugnugrawk** [Cyb3rWard0g/HELK#501]
I have problem to add log to SIEM for ELK rules detection, thank you

**Comment by neu5ron** [comment]
SIEM as in the Elastic SIEM Kibana app?

**Comment by nugnugrawk** [comment]
SIEM Kibana app

**Comment by nugnugrawk** [comment]
Yes

**Comment by nugnugrawk** [comment]
how to implementation sigma rules after installation HELK on ubuntu ? thank you

**Comment by Cyb3rWard0g** [comment]
We do not support that app at the moment.
