### ISSUE TITLE
use helk with an external elk ?

### ISSUE THREAD

**Issue by badroum** [Cyb3rWard0g/HELK#515]
hello I would have liked to know if HELK could be easily plugged to an external ELK.

**Comment by Cyb3rWard0g** [comment]
Hey @badroum ! Can you provide more information to your question? Do you mean push events to an external ELK? Like HELK-KAFKA -> HELK-LOGSTASH -> EXTERNAL-LOGSTASH?

**Comment by erezhazan1** [comment]
Hey!
I'm not sure what exactly is the meaning of his question, but I got a similar one.
Is it possible to push events from logstash to a different ELK setup?
Meaning Winlogbeat --> kafka --> logstash --> add another output to a different ELK setup.

To be more specific:

output {
  lumberjack {
    hosts => xxxx
    port => 5006
    ssl_certificate => "/usr/share/logstash/keys/TrustExternalCARoot.crt"
    codec => "json_lines"
  }
}

the external ELK setup is a SAAS setup.

**Comment by Cyb3rWard0g** [comment]
Oh yeah for sure. That's possible. . Following this syntax https://www.elastic.co/guide/en/logstash/current/plugins-outputs-lumberjack.html

**Comment by badroum** [comment]
Hello,
Sorry for the late response.
The purpose of my question is twofold, as I already have an ELK cluster on other VMs, I would like to use them already present on it with HELK.
Then, to know if HELK is compatible with open distro.
