### ISSUE TITLE
Use an ELK or opendistro cluster

### ISSUE THREAD

**Issue by badroum** [Cyb3rWard0g/HELK#522]
#### Describe the problem

Hello,
Sorry to open a second exit, but I didn't get an answer when the first one closed.
The purpose of my question is twofold, as I already have an ELK cluster on other VMs, I would like to use them already present on it with HELK.
Then, to know if HELK is compatible with open distro.

Several solutions can be envisaged but the one that interests me would be the following architecture

Logstash => Elasticsearch <=kibana
                                ^
                            HELK(with out elasticsearch)

**Comment by priamai** [comment]
On a related question could we add an option to run OpenElasticSearch instead of the current ElasticSearch?

**Comment by priamai** [comment]
By the way I am attempting to replace the vanilla ES with the Open Distro ES, will see if that works and keep an update log here.

**Comment by badroum** [comment]
Thanks for your feedback, how are you progressing with the integration of opendistro?

**Comment by priamai** [comment]
Got a HDD failure (bad sectors) on my server machine, waiting for replacement on Monday. Will update later.
Cheers!

**Comment by Cyb3rWard0g** [comment]
Hello @badroum @priamai . I have not worked on opendistro  ES, and I do not think I would be able to get to it. Is this something that is still under development? or we can close this issue? Thank you all!

**Comment by badroum** [comment]
Hi @Cyb3rWard0g  I'm still debugging on this installation, considering the latest news about ELK, I think it's not useless to have an idea about the integration with opendistro.
I'll let you know as soon as I've implemented this modification.

**Comment by priamai** [comment]
Hi there,
quick feedback on this I dropped the task for two reasons (1) as you mentioned after the skirmish AWS vs Elastic they have decided to split (2) there was quite a lot of things to fix to make it work.
Personally I would not use OpenDistro anymore.
Cheers.

**Comment by neu5ron** [comment]
this is going to become near impossible to maintain the two together, I have spent a lot of time following everything with elastic and opendistro and things in general around ELK.
as of right now I still have no great answer on what to do - 
I think the best solution is HELK without Kibana and possibly without Elasticsearch.
can still branch the elastic elaticsearch of HELK but make the main repo have ability to use all the things that differentiate HELK from every other commodity ELK and Elastic build (logstash, sigma, kafka, ksql, jupyter, etc..)

closing this, I imagine things in the future will be worked around this....
