### ISSUE TITLE
elastic 7.10.1 support 

### ISSUE THREAD

**Issue by d3b4g** [Cyb3rWard0g/HELK#535]
After upgrading my HELK installation elasticsearch and kibana images to 7.10.1 I get the below warning and logs are not sent to kibana. Any way to troubleshoot this issue? 
`[HELK-LOGSTASH-DOCKER-INSTALLATION-WARNING] Retrying uploading data for Kibana experience`

Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:

error:
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.

**Comment by priamai** [comment]
Looking into it....

**Comment by priamai** [comment]
@d3b4g alright this is related to the new version of JDK used in ES and Kibana as described here: https://github.com/elastic/elasticsearch/issues/51361
I will create a branch and attempt to change the docker config files to accomodate for that.
Cheers.

**Comment by d3b4g** [comment]
Great. Thank you @priamai

**Comment by priamai** [comment]
Hi @d3b4g:
this patch is very simple:
```

################################################################

## GC configuration
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
8-13:-XX:+UseConcMarkSweepGC
8-13:-XX:CMSInitiatingOccupancyFraction=75
8-13:-XX:+UseCMSInitiatingOccupancyOnly

## G1GC Configuration
# NOTE: G1GC is only supported on JDK version 10 or later.

```
Then change the args in the docker files.
We should add to the install menu.

**Comment by neu5ron** [comment]
using newer jvm.options,
let me know if issue persists
