### ISSUE TITLE
Is there any way to edit max_query_size

### ISSUE THREAD

**Issue by aniketpant1** [Cyb3rWard0g/HELK#537]
In helk_elastalert there is a directory called rules there are 800 something rules i have to add max_query_size parameter is there any option to add the above parameter

**Comment by Cyb3rWard0g** [comment]
Hello @aniketpant1 , the rules are created automatically from SIGMA to elastalert. I do not know if it can be added when the rule is translated. I believe that would be a question to the SIGMA project. I do not know if that's what you mean (Adding the property to every single rule right?)

**Comment by aniketpant1** [comment]
Yes but now i have stop using elastalert but i am going to restart this...
