### ISSUE TITLE
Install in Azure Error 255

### ISSUE THREAD

**Issue by hackjalstead** [Cyb3rWard0g/HELK#538]
I'm trying to install in a Azure cloud instance w/ x4 processors, 16gb RAM, 1TB SSD but keep getting error coded when running the ./helk_install.sh script - 

 * ERROR: Could not run HELK via docker-compose file helk-kibana-analysis-basic.yml (Error Code: 255).

The issue remains with Ubuntu 16 & 18 with updates applied to the OS & python libraries + tried with various partitioning schemas on the SSD + I have disabled network security groups in Azure too.
 
It always fails at the same spot - 

[HELK-INSTALLATION-INFO] Docker not installed via snap
[HELK-INSTALLATION-INFO] Assesing if Docker is running..
[HELK-INSTALLATION-INFO] Docker is running
[HELK-INSTALLATION-INFO] Making sure you assigned enough disk space to the current Docker base directory
[HELK-INSTALLATION-INFO] Available Docker Disk: 26 GBs
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 4120294
[HELK-INSTALLATION-INFO] Setting local vm.swappiness variable to 25
[HELK-INSTALLATION-INFO] Building & running HELK from helk-kibana-analysis-basic.yml file..
 * ERROR: Could not run HELK via docker-compose file helk-kibana-analysis-basic.yml (Error Code: 255).

The output of /var/log/helk-install.log -

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:09 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   651  100   651    0     0   9573      0 --:--:-- --:--:-- --:--:--  9573
100 12.2M  100 12.2M    0     0   9.7M      0  0:00:01  0:00:01 --:--:-- 17.7M
[4784] Error loading Python lib '/tmp/_MEIxECDGj/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIxECDGj/libpython3.9.so.1.0)
Adding password for user helk
[2315] Error loading Python lib '/tmp/_MEIV7LEwt/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIV7LEwt/libpython3.9.so.1.0)
Adding password for user helk
[2272] Error loading Python lib '/tmp/_MEIXUGFXT/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIXUGFXT/libpython3.9.so.1.0)
Adding password for user helk
[2571] Error loading Python lib '/tmp/_MEILkc1Vv/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEILkc1Vv/libpython3.9.so.1.0)
Adding password for user helk
[8071] Error loading Python lib '/tmp/_MEIrK1GlV/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIrK1GlV/libpython3.9.so.1.0)

**Comment by null-default** [comment]
It looks like `docker-compose` v1.28.0 requires `glibc` v2.28 or higher, which does not come standard on all systems. I simply installed an older version of `docker-compose` (v1.26.0), and it worked. For reference, my system (CentOS 7) is running `glibc` v2.17.

**Comment by hackjalstead** [comment]
yes, that's got it working, thank you. 
Commands to follow below incase anyone else encounters this problem - 

First Uninstall Docker Compose -
sudo rm /usr/local/bin/docker-compose
sudo apt-get remove docker-compose
sudo apt-get autoremove

Install docker v1.26.0 & change execute permissions -
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

Running the helk install will now work
