### ISSUE TITLE
event_id:4624 from security logs reports a grokparse failure

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#54]
forwarding data from WEC via winlogbeat. and get a grok error on this event_ID in kibana

json outbut from kibana, i cant not spot the error :(

{
  "_index": "logs-endpoint-winevent-security-2018.05.17",
  "_type": "doc",
  "_id": "1580881363",
  "_version": 1,
  "_score": null,
  "_source": {
    "opcode": "Info",
    "@timestamp": "2018-05-17T10:25:47.956Z",
    "user_domain": "XXXXX",
    "type": "wineventlog",
    "message": "An account was successfully logged on.\n\nSubject:\n\tSecurity ID:\t\tS-1-0-0\n\tAccount Name:\t\t-\n\tAccount Domain:\t\t-\n\tLogon ID:\t\t0x0\n\nLogon Information:\n\tLogon Type:\t\t3\n\tRestricted Admin Mode:\t-\n\tVirtual Account:\t\tNo\n\tElevated Token:\t\tNo\n\nImpersonation Level:\t\tIdentification\n\nNew Logon:\n\tSecurity ID:\t\tS-1-5-21-2007484102-1456041316-233718849-37790\n\tAccount Name:\t\tSRVP00002$\n\tAccount Domain:\t\tDAC.LOCAL\n\tLogon ID:\t\t0x665F7DB\n\tLinked Logon ID:\t\t0x0\n\tNetwork Account Name:\t-\n\tNetwork Account Domain:\t-\n\tLogon GUID:\t\t{A6BD0686-17D4-384B-DA6D-5A81CDF698F5}\n\nProcess Information:\n\tProcess ID:\t\t0x0\n\tProcess Name:\t\t-\n\nNetwork Information:\n\tWorkstation Name:\t-\n\tSource Network Address:\t10.200.28.241\n\tSource Port:\t\t62536\n\nDetailed Authentication Information:\n\tLogon Process:\t\tKerberos\n\tAuthentication Package:\tKerberos\n\tTransited Services:\t-\n\tPackage Name (NTLM only):\t-\n\tKey Length:\t\t0\n\nThis event is generated when a logon session is created. It is generated on the computer that was accessed.\n\nThe subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.\n\nThe logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).\n\nThe New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.\n\nThe network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.\n\nThe impersonation level field indicates the extent to which a process in the logon session can impersonate.\n\nThe authentication information fields provide detailed information about this specific logon request.\n\t- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.\n\t- Transited services indicate which intermediate services have participated in this logon request.\n\t- Package name indicates which sub-protocol was used among the NTLM protocols.\n\t- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.",
    "event_data": {},
    "level": "Information",
    "user_sid": "XXXXXXXXXXXXXXXXXXXXXXXX",
    "source_name": "Microsoft-Windows-Security-Auditing",
    "logon_type": "3",
    "logon_restricted_adminmode": "-",
    "user_networkaccount_domain": "-",
    "host_src_name": "-",
    "ip_src": "XXX.XXX.XXX.XXX",
    "logon_key_length": "0",
    "@version": "1",
    "user_reporter_domain": "-",
    "user_logon_linkedid": "0x0",
    "logon_authentication_package": "Kerberos",
    "provider_guid": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "thread_id": 15204,
    "port_src_number": 62536,
    "process_id": 0,
    "version": 2,
    "logon_elevated_token": "%%1843",
    "task": "Logon",
    "keywords": [
      "Audit Success"
    ],
    "log_name": "Security",
    "user_reporter_name": "-",
    "logon_package_name": "-",
    "logon_virtual_account": "%%1843",
    "logon_process_name": "Kerberos",
    "activity_id": "{DC3C281D-ED96-0000-2128-3CDC96EDD301}",
    "user_networkaccount_name": "-",
    "logon_transmitted_services": "-",
    "reporter_logon_id": "0x0",
    "process_path": "-",
    "user_logon_guid": "XXXXXXXXXXXXXXXXXXXXXXXXX5",
    "user_reporter_sid": "S-1-0-0",
    "event_id": 4624,
    "tags": [
      "_grokparsefailure",
      "_parsefailure"
    ],
    "impersonation_level": "%%1832",
    "user_logon_id": 107345883,
    "user_name": "SRVP00002$",
    "beat": {
      "name": "SRVPXXX",
      "version": "6.0.0",
      "hostname": "SRXXXXXXXXX"
    },
    "host_name": "srvpXXXXXXXXX",
    "record_number": "35697580"
  },
  "fields": {
    "@timestamp": [
      "2018-05-17T10:25:47.956Z"
    ]
  },
  "sort": [
    1526552747956
  ]
}

**Comment by ssi0202** [comment]
seem to be related to the logon type 3, logon type 5 is ok

**Comment by Cyb3rWard0g** [comment]
Interesting. I will take a look at it. thank you

**Comment by Cyb3rWard0g** [comment]
Ok I know what the problem is:

**4624 Logon Type 3: Process Name = "-"**

![image](https://user-images.githubusercontent.com/9653181/41238501-0e182b5c-6d64-11e8-9c94-d418d03ebbd2.png)

The Grok filter is the following: https://github.com/Cyb3rWard0g/HELK/blob/master/helk-logstash/pipeline/12-winevent-security-filter.conf#L8

```
if [log_name] == "Security"{
    if [event_data][ProcessName] {
      grok {
        match => {
          "[event_data][ProcessName]" => ".*\\%{GREEDYDATA:process_name}"
        }
        tag_on_failure => [ "_grokparsefailure", "_parsefailure" ]
      }
    }
```

Therefore, **-** will fail once it tries to go through the filter.

**4624  Logon Type 5: It usually has a ProcessName**

![image](https://user-images.githubusercontent.com/9653181/41238632-68f04726-6d64-11e8-9889-05a250c2ccb8.png)

I will have to add another conditional to skip those

**Comment by neu5ron** [comment]
this shouod be fixed with latest pipeline update as we remove “-“ values and so ProcessName wouldn’t exist if blank and therefore would NOT hit this grok filter and cause an error.
close meh :)

**Comment by Cyb3rWard0g** [comment]
yes I agreed. Thank you brother!!!
