### ISSUE TITLE
500 Server Error from NGINX Proxy

### ISSUE THREAD

**Issue by srlucken** [Cyb3rWard0g/HELK#545]
#### Describe the problem
When attempting to access the Kibana URL, after entering the credentials, I would receive a "500 server error" from NGINX

##### What steps did you take trying to fix the issue
The root of this issue was caused by nginx getting a permission denied message when attempting to read /etc/nginx/htpasswd.users. This caused NGINX to be unable to authenticate the user. I added an extra line to the helk-nginx/Dockerfile to resolve the issue "RUN chmod 644 /etc/nginx/htpasswd.users" then restarted the container. I can now successfully authenticate to Kibana.

##### How could we replicate the issue
As a non-root user I followed the exact steps from the installation documentation.
git clone https://github.com/Cyb3rWard0g/HELK.git
cd HELK/docker/
sudo ./helk_install.sh
**Installed using option 4**
The installation completed successfully, but I was unable to authenticate to Kibana.

**Comment by neu5ron** [comment]
thanks @srlucken 
was this an ubuntu or centos build?

**Comment by srlucken** [comment]
This was an Ubuntu 18.04LTS build.

Thank you for your time on this project, it's really great.
