### ISSUE TITLE
Logstash test config in HELK?

### ISSUE THREAD

**Issue by tmrgbox** [Cyb3rWard0g/HELK#551]
Hi,
How do i test my logstash config? there's an option for debugging with the following command:
sudo bin/logstash --config.test_and_exit -f <path_to_config_file>

What is the equivalent in HELK?

Thanks in advance

**Comment by neu5ron** [comment]
@tmrgbox `docker exec helk-logstash logstash --config.test_and_exist -f <path_to_config_file>`
