### ISSUE TITLE
Changing IP address of HELK

### ISSUE THREAD

**Issue by Khalid155** [Cyb3rWard0g/HELK#555]
Hi, 

We have installed helk a while ago and it is working just fine,, 
when we changed the IP addresses, the kafka broker stoped listening for incoming events. 

i have seen thread (https://github.com/Cyb3rWard0g/HELK/issues/127) but I think it is outdated 

PS: yes, we have changed the winlogbeat config to have the new address, and yes there are no network issue. 
 
your support is highly appreciated.

**Comment by neu5ron** [comment]
@Khalid155 the details outlined in #127 should still work.
can also try to use `helk_update.sh`
let me know.

**Comment by neu5ron** [comment]
closing, no reponse
