### ISSUE TITLE
ECS version

### ISSUE THREAD

**Issue by aminemirat** [Cyb3rWard0g/HELK#558]
Hi there
 I hope this message finds you well, first thank you for this great project, so what is the version of ECS that this project use? 
thanks

**Comment by neu5ron** [comment]
it does not use ECS. HELK uses a schema it built years before ECS unfortunately.

**Comment by aminemirat** [comment]
hi
could you tell me the name of the schema that HELK use ?
thanks

**Comment by neu5ron** [comment]
@aminemirat https://github.com/OTRF/OSSEM
let me know if you have any other questions.
