### ISSUE TITLE
Could not build HELK via docker-compose on Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by mrtadeo** [Cyb3rWard0g/HELK#58]
Hello

Getting errors during installation on Ubuntu 16.04.4 LTS Server:

```
**********************************************
**          HELK - THE HUNTING ELK          **
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: 0.9 (Alpha)          **
** HELK ELK version: 6.2.4                  **
** License: BSD 3-Clause                    **
**********************************************

[HELK-INSTALLATION-INFO] HELK being hosted on a Linux box
[HELK-INSTALLATION-INFO] Available Memory: 14
[HELK-INSTALLATION-INFO] Available Disk: 95
[HELK-INSTALLATION-INFO] Obtaining current host IP..
[HELK-INSTALLATION-INFO] Set HELK IP. Default value is your current IP: x.x.x.x
[HELK-INSTALLATION-INFO] HELK IP set to x.x.x.x
[HELK-INSTALLATION-INFO] HELK identified Linux as the system kernel
[HELK-INSTALLATION-INFO] Checking distribution list and version
[HELK-INSTALLATION-INFO] You're using ubuntu version xenial
[HELK-INSTALLATION-INFO] Docker already installed
[HELK-INSTALLATION-INFO] Docker-compose already installed
[HELK-INSTALLATION-INFO] Dockerizing HELK..
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 262144
[HELK-INSTALLATION-INFO] Setting KAFKA ADVERTISED_LISTENER value...
[HELK-INSTALLATION-INFO] Setting ES_JAVA_OPTS value...
[HELK-INSTALLATION-INFO] Building HELK via docker-compose
 * ERROR: Could not build HELK via docker-compose (Error Code: 1).
get more details in /var/log/helk-install.log locally
```

```
Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

If I remove "Version" then getting following errors:
```
The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for volumes: 'esdata'
Unsupported config option for networks: 'helk'
Unsupported config option for services: 'helk-elasticsearch'
```
Please advise.

Thanks in advance
TK

**Comment by devdua** [comment]
Hi @mrtadeo what version of docker and docker-compose are you using?

**Comment by mrtadeo** [comment]
Hi @devdua  

Docker version 1.13.1, build 092cba3 and docker-compose version 1.8.0, build unknown.

Thanks
tadeo

**Comment by Cyb3rWard0g** [comment]
Hey @mrtadeo ! I see that you had docker already installed. would you mind testing it in a fresh ubuntu install and let the script install docker for you? I would like to see the difference and I would assume it is because last time I ran it I got this docker client version:
```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:16:33 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm
..
```
can you run:
```
sudo docker version
```
Let me know. Thank you. I will have to add a Docker supported versions list. Something like the following from the Docker site:
```
Compose file format | Docker Engine release
-- | --
3.6 | 18.02.0+
3.5 | 17.12.0+
3.4 | 17.09.0+
3.3 | 17.06.0+
3.2 | 17.04.0+
3.1 | 1.13.1+
3.0 | 1.13.0+
```
I assume that my config is being picked up as a 3.6 version then. that must be why. Let me know. Thank you!

**Comment by mrtadeo** [comment]
Hey @Cyb3rWard0g 

I removed the docker and the installation now is moving forward.

Now stopping on pulling helk-elasticksearch, but it just a matter of a proxy thingy I guess.
```
Pulling helk-elasticsearch (cyb3rward0g/helk-elasticsearch:6.2.4)...
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Thanks!
T.

**Comment by Cyb3rWard0g** [comment]
Nice @mrtadeo ! yeah it was deff the docker version then. Yeah let me know if the connection to docker hub works. It must be a proxy thing yeah. Let me know before closing this issue. I will add a version table for the Wiki. Thank you. Also. can you send the initial part of your HELK install logs where it tells you what version of Docker is installed during the build?

**Comment by mrtadeo** [comment]
Installed successfully! 

Sorry, but I removed the old log and the new one does not says which version it is, but the version mentioned earlier was installed by the install script.

Thank you!

**Comment by mrtadeo** [comment]
I was happy to early. HELK is installed, but the UI is not available. 

Getting: `HTTP Error 404. The requested resource is not found.`

```
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                                            NAMES
ca3d6c1213b0        cyb3rward0g/helk-jupyter:0.32.1        "./jupyter-entrypo..."   3 days ago          Up 29 minutes       0.0.0.0:4040->4040/tcp, 0.0.0.0:8880->8880/tcp   helk-jupyter
0f9207fc90af        cyb3rward0g/helk-nginx:0.0.2           "./nginx-entrypoin..."   3 days ago          Up 29 minutes       0.0.0.0:80->80/tcp                               helk-nginx
006e98328b90        cyb3rward0g/helk-kafka-broker:1.1.0    "./kafka-entrypoin..."   3 days ago          Up 29 minutes       0.0.0.0:9093->9093/tcp                           helk-kafka-broker2
2e14b57a5268        cyb3rward0g/helk-spark-worker:2.3.0    "./spark-worker-en..."   3 days ago          Up 29 minutes       0.0.0.0:8081->8081/tcp                           helk-spark-worker
3b540ea3dfe6        cyb3rward0g/helk-spark-worker:2.3.0    "./spark-worker-en..."   3 days ago          Up 29 minutes       0.0.0.0:8082->8082/tcp                           helk-spark-worker2
5589c1f4efdb        cyb3rward0g/helk-kafka-broker:1.1.0    "./kafka-entrypoin..."   3 days ago          Up 29 minutes       0.0.0.0:9092->9092/tcp                           helk-kafka-broker
2a0694566542        cyb3rward0g/helk-zookeeper:3.4.10      "./zookeeper-entry..."   3 days ago          Up 29 minutes       2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp       helk-zookeeper
24d44795dc62        cyb3rward0g/helk-kibana:6.2.4          "./kibana-entrypoi..."   3 days ago          Up 29 minutes       5601/tcp                                         helk-kibana
e2bcf298054c        cyb3rward0g/helk-spark-master:2.3.0    "./spark-master-en..."   3 days ago          Up 29 minutes       0.0.0.0:7077->7077/tcp, 0.0.0.0:8080->8080/tcp   helk-spark-master
664de7418948        cyb3rward0g/helk-logstash:6.2.4        "/usr/local/bin/do..."   3 days ago          Up 29 minutes       5044/tcp, 9600/tcp                               helk-logstash
cc3c46bc08a5        cyb3rward0g/helk-elasticsearch:6.2.4   "/usr/local/bin/do..."   3 days ago          Up 29 minutes       9200/tcp, 9300/tcp                               helk-elasticsearch
```

**Comment by jai6684** [comment]
I am receiving the same error, this is my docker version, i am installing on a new installation of ubuntu.

Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:23 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by mrtadeo** [comment]
Hi All, I am still having problems with the installation as per post above. Any ideas?

Thanks
T.

**Comment by jespersj** [comment]
As you mention this is probably because of a proxy blocking the access. On my Centos 7 I've had luck with editing /usr/lib/systemd/system/docker.service and adding the proxy info in the [Service] section
Environment="HTTP_PROXY=http://YOURPROXYHERE:1234/ HTTPS_PROXY=http://YOURPROXYHERE:1234/"

Then I could pulll docker images.

I found the recipe here "https://stackoverflow.com/questions/53477114/using-proxy-on-docker-compose-in-server"

**Comment by Cyb3rWard0g** [comment]
Niceee thank you @jespersj

**Comment by unfo** [comment]
Necroing this thread, but FWIW: **do not install docker-compose** - it will give you an incompatible version. Just installing docker's reqs will provide you with the compatible version.

via Docker's own manual:
```
sudo apt-get install docker-ce docker-ce-cli containerd.io
```
That is sufficient!

I had this exact problem and with the same 18.x docker version etc, but I had foolishly installed `docker-compose` thinking I need that as well.

```
$ docker-compose --version
docker-compose version 1.8.0, build unknown
```

Once I uninstalled that package, the install moves forward, this is probably why @Cyb3rWard0g your _fresh_ install went through.
