### ISSUE TITLE
install elasticsearch curator to auto limit days to keep

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#59]
not an issue as such  but i would be nice to be able to limit the days to keep log data or am i missing something?

**Comment by Cyb3rWard0g** [comment]
Yes I agree with you. I will look into it. That was something that I remember willing to do, but it is still in the backlog. I will close this issue when I get to it. Thank you @ssi0202 !

**Comment by ssi0202** [comment]
hey anyone found a good curator image/container seems like this might fit the use case

https://github.com/stefanprodan/es-curator-cron

**Comment by ssi0202** [comment]
does the elasticsearch expose any ports to the outside in the current build ? would it break anything if i exposed ports to the outside in the docker file to get a entrypoint for a curator instance?

**Comment by neu5ron** [comment]
@ssi0202 if you want to expose the elasticsearch node (if it isn't already) then 
# To set to listen on localhost and external IP set the following in your elasticsearch.yml:
network.host: [ "$EXTERNAL_IP", "127.0.0.1" ]
network.publish_host: $EXTERNAL_IP

**Comment by neu5ron** [comment]
you may have to NAT with docker though -- because https://github.com/Cyb3rWard0g/HELK/blob/2d51dae636c4e09d113a912983d950bbe686a7f9/docker/helk-elasticsearch/elasticsearch.yml#L57
looks like it defaults listens on 0.0.0.0

**Comment by neu5ron** [comment]
after running curator in production the last few months with @torycmos -- curator is basically a blank slate and has a lot of buttons/knobs.
as an open source project I don't believe we want to get into adding it. Although, I completely agree there is a positive aspect to adding it and @Cyb3rWard0g and I always much appreciate the suggestions that you @ssi0202 have -- I believe the negative aspect outweighs this.

Example: positive for those who won't think about removing old data before the disk fills up
but negative for those who will end up doing their own curation.

I say we just add to documentation as a critical note such as "make sure to delete old data so your hard drive/storage does not fill up." -- we could then add an example.

thoughts/feedback welcome

**Comment by ssi0202** [comment]
hi sorry for the late reply. I see your point, I'll take a stab at it my self or see if i can't bribe one of the dev's with cake to add it.
by the way when you run this in production what sysmon configs are you using, and how much data do you end up collection from each host in a 24 hour period?

**Comment by neu5ron** [comment]
Moving this to a FAQ/Best-practices section. and closing this. 


hard to determine how much data per host due to variables of user usage or GPO configurations and environment, but I usually see about 3-5 events per second per host with no filtering.
