### ISSUE TITLE
docker container mem limit 

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#60]
hi i've tried to raise the limit for mem on the containers but nothing works  do i have to fix it in the docker compose.yml file to 

CONTAINER ID        NAME                 CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
0c0f3698ae97        helk-spark-worker2   0.09%               89.47MiB / 983.3MiB   9.10%               14.9kB / 16.2kB     603MB / 26.4MB      27
451397e84543        helk-spark-worker    0.10%               38.79MiB / 983.3MiB   3.94%               13.6kB / 18.1kB     356MB / 26.7MB      27
9a59a4919c83        helk-kafka-broker2   7.47%               533.1MiB / 983.3MiB   54.21%              7.37MB / 7.04MB     2.21GB / 41.6MB     73
05e189e07f3f        helk-kafka-broker    1.59%               501MiB / 983.3MiB     50.95%              6.89MB / 208kB      2.26GB / 37.6MB     71
8607ccf98c6e        helk-jupyter         0.00%               68KiB / 983.3MiB      0.01%               9.51kB / 0B         189MB / 7.39MB      1
fa59aac38e36        helk-nginx           0.02%               3.324MiB / 983.3MiB   0.34%               48.1kB / 40.1kB     328MB / 21.4MB      7
daf2399a476c        helk-zookeeper       0.14%               24.29MiB / 983.3MiB   2.47%               89kB / 93.9kB       148MB / 13.8MB      28
ef6c1d43cf8c        helk-spark-master    0.11%               73.64MiB / 983.3MiB   7.49%               41.8kB / 7.76kB     419MB / 22.5MB      37
144720494d8a        helk-logstash        106.50%             1.144GiB / 983.3MiB   119.10%             14.6kB / 3.3kB      1.29GB / 53.1MB     36
dcf41cb7edd5        helk-kibana          1.62%               275.9MiB / 983.3MiB   28.06%              476kB / 329kB       486MB / 31.3MB      12
954c7d1aba59        helk-elasticsearch   1.20%               5.575GiB / 983.3MiB   580.56%             311kB / 459kB       980MB / 14.6MB      76

**Comment by Cyb3rWard0g** [comment]
Hey @ssi0202 , Niceee yes let me know if that works and I will review the PR. For now, I dont set a limit to ELK yet. I allocate as much space as I can for when I deploy HELK and then I tear it down when I am done. I have not set up curator yet. Let me know how that works for you. There was an initiative by Jordan Potti (contributor) to do that, but I forgot what happened with it. You can set specific resources. Check the link I shared earlier. https://docs.docker.com/compose/compose-file/#resources . Let me know if that helps. Thank you again @ssi0202

**Comment by Cyb3rWard0g** [comment]
This is possible with mem_limit is possible but with docker-compose versions prior to 3. After version 3, it can be done via the resources feature of Deploy. However, it is ignored when the build is not run in docker swarm. The docker deployment of the HELK is only supporting local builds with docker-compose at the moment. Thank you for the suggestion though. Nothing to fix here unless you want to help us with a swarm config that could be integrated with the HELK.
