### ISSUE TITLE
logstash config IOC additions

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#62]
hi 

im trying to add what syspanda.com have made to tag IOC within the systemon conf file. as there is a renaming of the fields in there i can't get the exact code from syspanda.com to work

could you help me along then i'll complete the task and add a pull request once i have tested it as working

here is the relevant post from syspanda

https://www.syspanda.com/index.php/2018/05/04/labeling-endpoint-actions-logstash-threat-hunting/

here is the code from 11-winevent-sysmon-filter.conf in question

    if [event_id] == 1 {
      mutate {
        add_field => { "action" => "processcreate" }
        rename => {
          "[event_data][CommandLine]" => "process_command_line"
          "[event_data][CurrentDirectory]" => "process_current_directory"
          "[event_data][ParentImage]" => "process_parent_path"
          "[event_data][ParentCommandLine]" => "process_parent_command_line"
          "[event_data][IntegrityLevel]" => "process_integrity_level"
          "[event_data][LogonGuid]" => "user_logon_guid"
          "[event_data][ParentProcessGuid]" => "process_parent_guid"
          "[event_data][ParentProcessId]" => "process_parent_id"
          "[event_data][TerminalSessionId]" => "user_terminal_session_id"
          "[event_data][FileVersion]" => "file_version"
          "[event_data][Description]" => "file_description"
          "[event_data][Product]" => "file_product"
          "[event_data][Company]" => "file_company"
        }
        gsub => ["process_parent_guid","[{}]",""]
        gsub => ["user_logon_guid","[{}]",""]
      }
    }

### IOC ###
  if [event_id] == 1 {
  and ( ([event_data][process_parent_path] =~ /(?i)(OUTLOOK.EXE)/ ) or (##if i put it after the renaming do i have to use [process_parent_path] or can i just use [parentImage] still?###)
    ([event_data][ParentImage] =~ /(?i)(OUTLOOK.EXE)/ 
  and ([event_data][Image] =~ /(?i)(iexplore.exe|chrome.exe|firefox.exe|edge.exe)/ ) )
  {
   mutate { 
   add_field => { "IOC" => "Browser Launched From Outlook Sysmon 1" } }}
    }

 
How do i add this mutate statement into the existing event_id:1 filter ? this must be possible to do in an elegant way

**Comment by Cyb3rWard0g** [comment]
Nice thank you for sharing this @ssi0202 . I like it!!
