### ISSUE TITLE
helk_install.sh wont install with more than 1tb drive on 16.04

### ISSUE THREAD

**Issue by FlemmingRiis** [Cyb3rWard0g/HELK#67]
** HELK ELK version: 6.2.4                  **
** License: BSD 3-Clause                    **
**********************************************

[HELK-INSTALLATION-INFO] HELK being hosted on a Linux box
[HELK-INSTALLATION-ERROR] YOU DO NOT HAVE ENOUGH AVAILABLE MEMORY OR DISK SPACE
[HELK-INSTALLATION-ERROR] Available Memory: 61
[HELK-INSTALLATION-ERROR] Available Disk: 2

The script sees 1.9 vs 1900gb and wont continue install , resized for workaround insted of modifying script (so mostly info)

helk@helk:~/HELK$ df -h | awk '$NF=="/"{printf "%.f\t\t", $4}'

2               

helk@helk:~/HELK$ df -h

Filesystem                            Size  Used Avail Use% Mounted on
udev                                   32G     0   32G   0% /dev
tmpfs                                 6.3G  8.6M  6.3G   1% /run
/dev/mapper/atlas--helk--01--vg-root  1.9T  1.8G  1.8T   1% /
tmpfs                                  32G     0   32G   0% /dev/shm
tmpfs                                 5.0M     0  5.0M   0% /run/lock
tmpfs                                  32G     0   32G   0% /sys/fs/cgroup
/dev/sda1                             472M   58M  390M  13% /boot
tmpfs                                 6.3G     0  6.3G   0% /run/user/1000

**Comment by Cyb3rWard0g** [comment]
@FlemmingRiis Thank you very much for sharing this. I had not tested it with 1TB which makes sense why it sees 2. I will have to add another conditional to the script. Sorry for the late response. I was traveling and in a conference. I will get that taken care of in the next couple of days.

**Comment by FlemmingRiis** [comment]
My pleasure , and again thank you for sharing and taking the time to do all the work

Den 10. jun. 2018 kl. 08.44 skrev Roberto Rodriguez <notifications@github.com<mailto:notifications@github.com>>:


@FlemmingRiis<https://github.com/FlemmingRiis> Thank you very much for sharing this. I had not tested it with 1TB which makes sense why it sees 2. I will have to add another conditional to the script. Sorry for the late response. I was traveling and in a conference. I will get that taken care of in the next couple of days.

**Comment by Cyb3rWard0g** [comment]
@FlemmingRiis . I now use **df -m** instead of the human readable format. This allows me now to transform everything to MBs and then do the calculation that way. Thank you!
