### ISSUE TITLE
Docker-Compose Fails with error: ERROR: for helk-elasticsearch  Cannot create container for service helk-elasticsearch: b'Drive has not been shared'

### ISSUE THREAD

**Issue by 1332530** [Cyb3rWard0g/HELK#79]
**Describe the problem**
When running an instance of docker-compose up, the operation fails with a terminating error when trying to bring up the first container; helk-elasticsearch.

**What steps did you take trying to fix the issue?**
Attempted to comment out the compose instruction setting the volume:
- esdata:/usr/share/elasticsearch/data

**How could we replicate the issue?**
Fresh build on Windows 10.
Simply set location to HELK directory and run docker-compose up.

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**
Currently unable to provide logs seeing as this is a non-standard usage Windows build.

**What version of HELK are you using?**
HELK 6.2.4-050318

**What OS are you using to host the HELK?**
Windows 10, build 14393.

**Any additional context?**
PS C:\Users\bruce.lavoie\git\DFIR\ThreatHunting\HELK> docker-compose up
Creating helk-elasticsearch ... error

ERROR: for helk-elasticsearch  Cannot create container for service helk-elasticsearch: b'Drive has not been shared'

ERROR: for helk-elasticsearch  Cannot create container for service helk-elasticsearch: b'Drive has not been shared'
ERROR: Encountered errors while bringing up the project.

![helk-fail](https://user-images.githubusercontent.com/17053920/41471217-035a46ee-7081-11e8-9e2f-3c514491b80b.PNG)

**Comment by Cyb3rWard0g** [comment]
Try the following:
https://github.com/docker/compose/issues/4303
```
On Command Line: "set COMPOSE_CONVERT_WINDOWS_PATHS=1";
Restart Docker for Windows;
Go to Docker for Windows settings > Shared Drives > Reset credentials > select drive > Apply;
Reopen Command Line;
Kill the Containers;
Rerun the Containers.
```
Also make sure the shares are configured properly:

https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/

It is hard to test it in a different environment than the one recommended by the project. let me know if the things above helped. Thank you @1332530

**Comment by Cyb3rWard0g** [comment]
Hey @1332530 !! It has been a while and I have not heard from you and your testing in a WIndows box. It looks like a Docker issues to me. I will close this issue since the HELK is intended to be deployed in a Linux box according to our Wiki and development steps. Feel free to open an issue if you have any issues with HELK in Linux environments. Thank you!
