### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by xtremebeing** [Cyb3rWard0g/HELK#8]
from the log file:
Package openjdk-8-jre-headless is a virtual package provided by:
  oracle-java9-installer 9.0.1-1~webupd8~0
  oracle-java8-installer 8u151-1~webupd8~0

E: Package 'openjdk-8-jre-headless' has no installation candidate

**Comment by Cyb3rWard0g** [comment]
Hello @xtremebeing, Do you still have this issue? What OS are using to host the HELK, and can you try the new version??. Option 3 when you run the main helk_install.sh script. Let me know.

**Comment by Cyb3rWard0g** [comment]
@xtremebeing let me know if you still have this issue?

**Comment by xtremebeing** [comment]
sorry, I just noticed my VM is Ubuntu 14.04.5 LTS

**Comment by Cyb3rWard0g** [comment]
@xtremebeing np. This actually helps to be more specific in what versions of Ubuntu too (Xenial). Run the script again and let me know if that works.
