### ISSUE TITLE
Adding Beats outside of Winlogbeat

### ISSUE THREAD

**Issue by TDominiqueWilliams** [Cyb3rWard0g/HELK#80]
I am looking to try to extend HELK out by having filebeat, packetbeat, and metricbeat. Is it best to configure the new beats like your winlogbeat and point them to Kafka or should I do the traditional method by pointing them to elasticsearch?

**Comment by Cyb3rWard0g** [comment]
Niceee!! I would recommend to point them to Kafka. However, you will just have to add a topic for each data set. What data are you going to be using it with?? Filebeat pulling what type of logs?

**Comment by TDominiqueWilliams** [comment]
Okay sounds good. For now I am testing filebeat against the basic logs of ubuntu. The goal would be to have an external machine with bro logs on it to send back to HELK.

**Comment by Cyb3rWard0g** [comment]
Let me know how this is going for you @TDominiqueWilliams 👍 Would love to hear about what I can be doing to add some filters or anything to the build 👍

**Comment by Cyb3rWard0g** [comment]
Hows everything going @TDominiqueWilliams ??? I hope everything is well. 👍

**Comment by Cyb3rWard0g** [comment]
@TDominiqueWilliams closing this issue since there is nothing to fix. If you get to figure out Filebeat for Ubuntu logs, let me know and a PR will help to update the logstash pipeline. Thank you in advance!
