### ISSUE TITLE
Could not run HELK via docker-compose (Error Code: 1)

### ISSUE THREAD

**Issue by mrtadeo** [Cyb3rWard0g/HELK#82]
Hello, I tried with new installation and I got the following error:

```
* ERROR: Could not run HELK via docker-compose (Error Code: 1).

Pulling helk-jupyter (cyb3rward0g/helk-jupyter:0.32.1)...
0.32.1: Pulling from cyb3rward0g/helk-jupyter
unauthorized: authentication required
```
The OS is Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64).

Any ideas?

Thanks in advance
T.

**Comment by Cyb3rWard0g** [comment]
Hey @mrtadeo ! That is usually with a proxy issue or caused by the host clock. Those have been a few issues that I have seen in other projects. Let me know if you can try to build it again in a fresh image. Thank you!

**Comment by mrtadeo** [comment]
Hey @Cyb3rWard0g 

I sync with ntp server and it works now. 

Thanks!
T.

**Comment by Cyb3rWard0g** [comment]
awesome thank you very much 👍
