### ISSUE TITLE
Spark Setup

### ISSUE THREAD

**Issue by cgoss** [Cyb3rWard0g/HELK#88]
How do you get spark setup. I'm trying to deploy on hortonworks but am not clear on the spark setup.

**Comment by Cyb3rWard0g** [comment]
Hey @cgoss , 
I havee not tested the spark cluster in Hortonworks. I am not planning on providing support for that type of deployment. Im sorry. Let me know if you have any issues deploying it with Docker-Compose. Thats what I am covering so far. Thank you!
