### ISSUE TITLE
enrichments

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#92]
hi - its me again.

im doing enrichments in the logstash conf files. do you plan to do it this way also or do you have anything other i mind?

currently im doing going through this repo
https://github.com/HASecuritySolutions/Logstash

also check out his elastaleart cerebro and curator containers .-)

full disclosure its SANS course related, i have no affiliation with SANS other than that they make 
really good courses that i attend

to get ideas and incorporate them into the helk-logstash sections.

**Comment by Cyb3rWard0g** [comment]
HEy @ssi0202 !! Can you provide specific examples of enrichments that you believe can be added to the current pipeline?? Im focusing in Windows (security, sysmon & powershell) & OSQuery tables for now. Would love to hear your thoughts

**Comment by ssi0202** [comment]
im currently adding the dictionary section folder ( it works with logstash translate ) so i get er readable version of login type instead of a number.

and these 

https://github.com/HASecuritySolutions/Logstash/blob/master/configfiles/6302_windows_translations.conf

https://github.com/HASecuritySolutions/Logstash/blob/master/configfiles/6300_windows.conf

he also has alot of bro related stuff 

the windows conf file has as far as i can see a way to count the length of the command lines being logged something i would really like as long (ie base64 etc) encoded powershell is really really long. and my sandbox enabled mail filter tells me this is getting more and more commen. basically if i end up up with a realllly long powershell commandline input something most likely got passed my av etc. this was one of the take aways from taking the sans 508 - uninstall / get id of powershell2.0 - its still on by default on win10. log every command line input be it powershell with script logging or cmd. 

look for long input 500 chr+ and invokation of powershell hidden windows .net webshells etc. 

the logstash conf file for windows holds the code to do this, from what i can tell.

Also I enrich the event id 3, network data from sysmon with your network topography.

add client ip and server ip dmz ip identicationmand depending on what makes sense in your environment (add office location client/server/internal/eksternal) i have added to determine client to client traffic for instance and then put IOC tags in if its generated from psexec etc exe. 

I would really really like to know if a client is touching another client via psexec, powershell etc. - or a server or something in my DMZ starts tries to chat up one of my servers or the other servers in the DMZ. putting these "additions" into logstash makes this possible. also i added a tag to for all the my MS published public it's so i can filter them out. 

for some reason my office programs just have to talk to a MS  ip in hongkong from time to time.... and it makes for alot of noise. see below, but i guess they change them from time to time so not complete. ill most likely move them to the winlogbeat on the WEF server to get rid of them before it all goes into the HELK

https://www.microsoft.com/en-us/download/details.aspx?id=53602

anyways thank you and your crew so much for making the HELK. My use case currently is not so much as look for bad stuff, but more to quickly determine what did not happen. Given my job management etc mostly want to know what is not affected or what did not get compromised and the helk is a great way to do this. i certainly see the idea of threat hunting, but that is currently second priority. 

i need to know what did not happen.

absence of proof is not proof of absence - as one of my prof at uni used to say, and then we would work even harder to determine what did NOT happen, as this was just as important.

cheers.

**Comment by Cyb3rWard0g** [comment]
Thank you for the suggestiong @ssi0202 . @neu5ron is working on improving the Pipe from time to time. I see what SecurityMapper has done with his pipeline. I think that there are several ways to enrich a pipeline specially with host-events and we will keep an eye on the best way to enhance the pipeline configs for the community. I will close this issue since there is nothing to fix. Thank you man!

**Comment by neu5ron** [comment]
also the goal with the pipeline in the long run is to make much more modular than other's pipelines -- for example a single file to rule all CLI and Username fields for example
