### ISSUE TITLE
Can't connect to web

### ISSUE THREAD

**Issue by MgOmbodorj** [Cyb3rWard0g/HELK#94]
**Describe the problem**
I can't access to Kibana URL

**What steps did you take trying to fix the issue?**

Tried disable firewall

**How could we replicate the issue?**

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

Installation succesfully completed.

https://pastebin.com/82fcAb8m

**What version of HELK are you using?**
2.3.1
**What OS are you using to host the HELK?**
Ubuntu 16.04.5
**Any additional context?**
other log files, pictures, etc.

**Comment by hsvsocintern** [comment]
I am also having the same issue, after using the helk_install.sh script from a fresh install of Ubuntu 16.04.

**Comment by Cyb3rWard0g** [comment]
Hey @hsvsocintern and @MgOmbodorj can you try again?? I pushed a big commit https://github.com/Cyb3rWard0g/HELK/commit/634e24e3aa85308657d6192022025b2e5a0409f4

**Comment by Cyb3rWard0g** [comment]
https://github.com/Cyb3rWard0g/HELK/releases/tag/v0.1.2-alpha08032018

**Comment by hsvsocintern** [comment]
I re-ran the install script after the update and was able to access the web interface, Thanks!

**Comment by Cyb3rWard0g** [comment]
awesome thank you @hsvsocintern 👍
