### ISSUE TITLE
Kafka Issues?

### ISSUE THREAD

**Issue by hsvsocintern** [Cyb3rWard0g/HELK#96]
**Describe the problem**
After a fresh install of HELK, using the helk_install.sh script, with a windows with winlogbeat. I am not receiving data in Kibana using the "log-endpoint-winevent-sysmon" index. Error logs provided below.
**What steps did you take trying to fix the issue?**
I am a total ELK stack new comer, still trying to diagnose and understand the problem.

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**
N/A
**What version of HELK are you using?**
v0.1.2-alpha08062018 
**What OS are you using to host the HELK?**
Ubuntu 16.04
**Any additional context?**
Error Logs from "$docker logs --follow helk-logstash":
[2018-08-07T14:01:03,308][WARN ][org.apache.kafka.clients.NetworkClient] [Consumer clientId=logstash-0, groupId=logstash] Error while fetching metadata with correlation id 41 : {winlogbeat=UNKNOWN_TOPIC_OR_PARTITION}
[2018-08-07T14:01:03,412][WARN ][org.apache.kafka.clients.NetworkClient] [Consumer clientId=logstash-0, groupId=logstash] Error while fetching metadata with correlation id 42 : {winlogbeat=UNKNOWN_TOPIC_OR_PARTITION}
[2018-08-07T14:01:03,417][WARN ][org.apache.kafka.clients.consumer.internals.ConsumerCoordinator] [Consumer clientId=logstash-0, groupId=logstash] The following subscribed topics are not assigned to any members: [winlogbeat] 
[2018-08-07T14:01:02,536][ERROR][logstash.inputs.metrics  ] Failed to create monitoring event {:message=>"For path: http_address. Map keys: [:stats, :jvm]", :error=>"LogStash::Instrument::MetricStore::MetricNotFound"}

More logs:
[output.txt](https://github.com/Cyb3rWard0g/HELK/files/2266803/output.txt)

**Comment by Cyb3rWard0g** [comment]
Hey @hsvsocintern . Thank you for the details. Can you provide the logs from /var/log/helk_install.log?? That should be locally and the details of when the HELK was being built? How much memory did you allocate for the build? Also, can you share Kafka Brokers logs?? That will help me to figure out what happened. Most likely it was that the Kafka brokers did not create that specific topic while they were being initialized. it could happen and it has been usually due to resources assigned to the HELK

**Comment by hsvsocintern** [comment]
Yes, Thanks for your help with getting HELK up and running. I am using a Ubuntu 16.04 VM, with 15GB RAM, 175GB Storage, 4 core CPU @ 1.8 GHz. Attached is my results from docker-kafka-broker and docker-kafka-broker2. Along with my helk_install.log from /var/log/
[Kafka2.txt](https://github.com/Cyb3rWard0g/HELK/files/2268033/Kafka2.txt)
[Kafka.txt](https://github.com/Cyb3rWard0g/HELK/files/2268034/Kafka.txt)
[helk-install.log](https://github.com/Cyb3rWard0g/HELK/files/2268035/helk-install.log)

Once again, thanks for your help!

**Comment by Cyb3rWard0g** [comment]
I can see that both brokers failed to create the Kafka Topics:
```
[HELK-DOCKER-INSTALLATION-INFO] Creating Kafka winlogbeat Topic..
Error while executing topic command : Replication factor: 2 larger than available brokers: 0.
[HELK-DOCKER-INSTALLATION-INFO] Creating Kafka sysmontransformed Topic..
Error while executing topic command : Replication factor: 2 larger than available brokers: 1.
```

**Comment by Cyb3rWard0g** [comment]
do you think that you could run it again? the whole deployment and monitor for those two brokers. let me know if you still get the same errors. thank you @hsvsocintern

**Comment by hsvsocintern** [comment]
I re-ran the install script on a fresh system with 16GB RAM, 250GB Storage, 8 core CPU @ 1.8GHz. and I am getting the same error from the kafka-log. 
"[HELK-DOCKER-INSTALLATION-INFO] Creating Kafka winlogbeat Topic..
Error while executing topic command : Replication factor: 2 larger than available brokers: 0.
[HELK-DOCKER-INSTALLATION-INFO] Creating Kafka sysmontransformed Topic..
Error while executing topic command : Replication factor: 2 larger than available brokers: 1."
This might not be related to the issue, but I was looking at the server.properties file in the ../HELK/docker/helk-kafka-broker/ dir. and I noticed the advertised.listeners=PLAINTEXT://HELKIP:9032", is the expected value or should HELKIP be the actual IP address of the system? Thank you once again for all the help!

**Comment by Cyb3rWard0g** [comment]
ohhhh @hsvsocintern . How are you running the HELK installation? Are you using the helk_install.sh script? Also, does your system have an IP address? That value HELKIP gets adjusted via the helk_install.sh script. Sorry I have been busy with BlackHat these past couple of days.

**Comment by hsvsocintern** [comment]
Yes, I have been running the installation with a clean VM, doing:
"git clone https://Cyb3rWard0g/HELK"
"sudo ./helk_install.sh".
The system gets it's IP from DHCP, when the script displays the current IP, it is the correct value. 

I hope you're having a good time at BlackHat!
Thanks

**Comment by Cyb3rWard0g** [comment]
ok so I do the following:
first I edit the docker-compose file Kafka broker variable to the HOST IP:
```
# ****** Setting KAFKA ADVERTISED_LISTENER environment variable ***********
    sed -i "s/ADVERTISED_LISTENER=HOSTIP/ADVERTISED_LISTENER=$host_ip/g" docker-compose-elk-${license_choice}.yml

```
Then, in the Kafka broker entrypoint I update the kafka server.properties file:
```
sed -i "s/advertised\.listeners\=PLAINTEXT:\/\/HELKIP\:9092/advertised\.listeners\=PLAINTEXT\:\/\/${ADVERTISED_LISTENER}\:${KAFKA_BROKER_PORT}/g" ${KAFKA_HOME}/config/server.properties
```
when you check your server.properties file in /opt/helk/kafka/kafka_2.11-1.1.1//config/server.properties, you should have the advertised listener set up to your current HOST IP. Can you provide the server.properties files from your kafka brokers?? Thank you @hsvsocintern 👍

**Comment by neu5ron** [comment]
@hsvsocintern  I am going to close this unless the above did not fix for you.
