### ISSUE TITLE
Install Script Bound to Root

### ISSUE THREAD

**Issue by Amorik** [Cyb3rWard0g/HELK#99]
**Describe the problem**
The install script is bound to checking the available free space on /
This is not always the case as one can configured docker to alter its base directory by editing the /etc/docker/daemon.json file (created if not present)

Example config:
```
{
   "graph": "/opt/docker"
}
```

**What steps did you take trying to fix the issue?**
Edited line 31 from:
```
AVAILABLE_DISK=$(df -m | awk '$NF=="/"{printf "%.f\t\t", $4 / 1024}')  
```
to:
```
df -m $(docker info --format '{{.DockerRootDir}}') | awk '$1 ~ /\//{printf "%.f\t\t", $4 / 1024}'
```

The ```docker info --format '{{.DockerRootDir}}'``` will return the directory that docker is configured to store in (```/opt/docker```) and ```df``` will translate the folder to the disk it belongs on.  Since it should only return the header and the one disk its associated to (assuming its not possible to have multiple ...) the ```awk``` statement is adjusted to evaluate lines starting with ```/``` instead.

**How could we replicate the issue?**
This would often be an post docker install concern as the /etc/docker folder does not exist until after installation, and one must manual create the daemon.json file. It is my assumption that one could create it before hand, though i have not personal tried that ... yet anyways.

**If you are having issue during the installation stage, please provide the HELK installation logs located at /var/log/helk-install.log**

**What version of HELK are you using?**
v0.1.2-alpha08062018  b9daa4c

**What OS are you using to host the HELK?**
CentOS Linux release 7.5.1804 (Core)

**Any additional context?**
This fix requires docker to be installed before execution. Obviously this will not work as the install script is responsible for that as well. I would like to suggest that the install script be updated with an option to select an alternate root directory for docker, in which that disk would checked for capacity and docker settings adjusted to comply.

**Comment by Cyb3rWard0g** [comment]
Very interesting. Thank you very much for the information. your change by itself works in my Ubuntu box too. However, as you mentioned in your comments, the user will have to alter the docker base directory in order for the current script to fail. The helk_install script is provided to install docker and everything one needs to run HELK. the helk_install script is for those that just want to press a button with a fresh Ubuntu install. What I think I can do is have two checks (before and after docker is installed). The first check can be overall to check if the default base directory / has enough space to host the build. Then, the second one will be for those that have enough space already, but had docker installed already and altered the docker base directory.

**Comment by Cyb3rWard0g** [comment]
I will add the second check here:
```
# *********** Check if docker is installed ***************
        if [ -x "$(command -v docker)" ]; then
            echo "[HELK-INSTALLATION-INFO] Docker already installed"
            echo "[HELK-INSTALLATION-INFO] Making sure you assigned enough disk space to the current Docker base directory"
            AVAILABLE_DOCKER_DISK=$(df -m $(docker info --format '{{.DockerRootDir}}') | awk '$1 ~ /\//{printf "%.f\t\t", $4 / 1024}')    
            if [ "${AVAILABLE_DOCKER_DISK}" -ge "30" ]; then
                echo "[HELK-INSTALLATION-INFO] Available Docker Disk: $AVAILABLE_DOCKER_DISK"
            else
                echo "[HELK-INSTALLATION-ERROR] YOU DO NOT HAVE ENOUGH DOCKER DISK SPACE ASSIGNED"
                echo "[HELK-INSTALLATION-ERROR] Available Docker Disk: $AVAILABLE_DOCKER_DISK"
                echo "[HELK-INSTALLATION-ERROR] Check the requirements section in our installation Wiki"
                echo "[HELK-INSTALLATION-ERROR] Installation Wiki: https://github.com/Cyb3rWard0g/HELK/wiki/Installation"
                exit 1
            fi
```
This will be updated in the next release. Thank you very much @Amorik !! 👍
